### ISSUE TITLE
Gutenberg Block issue

### ISSUE THREAD

**Issue by swissky** [insideout10/wordlift-plugin#1004]
Please describe the issue here:

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.3.2
[ ] WordLift plugin version: 3.24.1
[ ] Step-by-step procedure on how to reproduce the issue:

There are several times the same block.
![Neue_Seite_erstellen_‹_Techgarage_Media_—_WordPress](https://user-images.githubusercontent.com/30409887/72956864-ae359e80-3da1-11ea-9809-21a40fcde66b.jpg)

**Comment by ziodave** [comment]
@swissky it'll be fixed with 3.24.2 which is going into QA as we speak. We shall publish it to wordpress.org by next week.

Cheers.

**Comment by ziodave** [comment]
@swissky 3.24.2 is online.

**Comment by swissky** [comment]
@ziodave thank you ;)
