### ISSUE TITLE
Content classification Categories Gutenberg

### ISSUE THREAD

**Issue by swissky** [insideout10/wordlift-plugin#1010]
Since some Updates, the Content classification Categories just showing entity﻿ when the tab "All" is active. 

![Beitrag_bearbeiten_‹_Techgarage_Media_—_WordPress](https://user-images.githubusercontent.com/30409887/73189924-7625b700-4125-11ea-9028-a9527b45d321.jpg)
![Beitrag_bearbeiten_‹_Techgarage_Media_—_WordPress](https://user-images.githubusercontent.com/30409887/73189935-7cb42e80-4125-11ea-9acc-ab44c74ce293.jpg)
![Beitrag_bearbeiten_‹_Techgarage_Media_—_WordPress](https://user-images.githubusercontent.com/30409887/73190143-d157a980-4125-11ea-9268-317b22b86dc1.jpg)

[ ] WordPress version: 5.3.2
[ ] WordLift plugin version:.3.24.3.1

**Comment by ziodave** [comment]
@swissky it's fixed (it was an issue on platform side). Can you confirm?

<img width="264" alt="image" src="https://user-images.githubusercontent.com/11438/73200137-7ed2b900-4136-11ea-9fcd-6fb189d29e05.png">

<img width="264" alt="image" src="https://user-images.githubusercontent.com/11438/73200146-82fed680-4136-11ea-863e-358dadfbd69c.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/11438/73200154-872af400-4136-11ea-8016-7ea8519eeca7.png">

<img width="259" alt="image" src="https://user-images.githubusercontent.com/11438/73200160-8b571180-4136-11ea-9f5a-b0ee501c5ea3.png">



Cheers.

**Comment by ziodave** [comment]
Closing, feel free to reopen.
