### ISSUE TITLE
sameAs validation

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1017]
Prevent people from inserting things that are not URLs and local dataset URLs into the sameAs field.

On WLP update, WLP should check whether the local dataset URI has been used for sameAs. If that's the case, a task would be displayed in Dashboard > WordLift > Tasks to cleanup the sameAs.

The cleanup is a task with a progress bar, which would process each item with a local dataset URI in the sameAs, remove it and save, pushing the updated data to the KG.

During normal operation, WLP will prevent using the local dataset URI in sameAs, i.e. when saving the sameAs, local dataset URI will be automatically filtered out.

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [It's still possible to add sameAs to the local dataset](https://trello.com/c/kH1HMd9F/29-its-still-possible-to-add-sameas-to-the-local-dataset)

**Comment by akshayraje** [comment]
Related #507
