### ISSUE TITLE
Adding https://schema.org/about in the WordLift widget

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#102]
Here the goal is to give the editor the possibility to select - _among the chosen entities_ - one _super_ entity that represents the subject matter of the post. 

This can be implemented with a star icon that the editor choses across all entities being annotated. 
Once this is done WordLift adds the for that entity the `https://schema.org/about`.   

The about property shall not be set on entity pages. The about property, for entity pages, shall always be the entity itself.

**Comment by cyberandy** [comment]
@mcolacino I've updated here the description.

**Comment by mcolacino** [comment]
@cyberandy we should close or update this issue, considering that we decided to include dbpedia categories on WL side, using them eventually as *about*.

**Comment by cyberandy** [comment]
One important update on this front. We receive the classification categories and these are dereferenciable as RDF resources following the DBpedia/Wikipedia URL encoding rules (e.g., Social sciences -> http://dbpedia.org/resource/Category:Social_sciences) - entities in other words. 

The list of all categories is in the file below: 
[topic.txt](https://github.com/insideout10/wordlift-plugin/files/88639/topic.txt)

**Comment by ziodave** [comment]
The referenced topic.txt is in the ML engine: https://github.com/redlink-gmbh/machinelinking-stanbol-enhancement-engine/blob/master/src/main/resources/topic.txt

Which in turn points to http://www.airpedia.org/topic.txt

In the JSON-LD response Redlink provide this information (english-only) with TopicAnnotations

**Comment by ziodave** [comment]
This issue is now related to #451 .
