### ISSUE TITLE
Clear out key when a duplicate web site is detected

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1020]
To avoid duplicated entities.

**Comment by ziodave** [comment]
I propose the following changes:

1. During the set-up screen, currently when the user enters the key, the key is only validated for its existence. In the future also the URL associated with the key is checked and a non valid key message is displayed ("The key is already used on another site, please contact us at hello@wordlift.io to move the key to another site.").
1. During normal operations, if the current web site URL isn't stored, WLP stores it in local configuration. At every load WLP checks whether the current URL differs from the stored URL. If it differs then the key is removed and an admin notice is displayed with the following message "Your web site URL has changed. To avoid data corruption, WordLift's key has been removed. Please provide a new key in WordLift Settings. If you believe this to be an error, please contact us at hello@wordlift.io". 'WordLift Settings' is linked to the settings screen.

**Comment by cyberandy** [comment]
makes sense to me!
