### ISSUE TITLE
Gutenberg/ Wordlift

### ISSUE THREAD

**Issue by swissky** [insideout10/wordlift-plugin#1038]
Hey, since WP 5.4 there is an issue with the WL Plugin inside an editor. 

See the Screenshots: First one is without Wordlift active. You see the Yoast Meta Box under the Page Content.
![Seite_bearbeiten_‹_Techgarage_Media_—_WordPress](https://user-images.githubusercontent.com/30409887/79040083-5b23f880-7be6-11ea-9782-c1b8381a2016.jpg)

Second image with WL active. You see both Meta Boxes inside the editor. Under the "closed boxes" i can edit the page still.
![Seite_bearbeiten_‹_Techgarage_Media_—_WordPress](https://user-images.githubusercontent.com/30409887/79040143-ab02bf80-7be6-11ea-99f8-e14cc780d94e.jpg)

**Comment by ziodave** [comment]
Hello @swissky,

Can you tell us the exact issue you're experiencing? We tested Yoast + WLP on WP 5.4 with no evident issue.

BR

see https://send.firefox.com/download/5f5f03c781f290b1/#0hZ8YZwvqTjGR9T-NTaS5A (link valid for 7 days)

**Comment by swissky** [comment]
Thank you @ziodave. That looks normal. On my sites it looks so
https://drive.google.com/file/d/1uxU0NzoKovUALVcURa7rHsp17uQdBv2_/view?usp=sharing

**Comment by ziodave** [comment]
Hello @swissky, can you contact us at support@wordlift.io so that we can take a closer look at this?
