### ISSUE TITLE
Problem when adding 2 Navigator Widgets in the same article

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#104]
Adding two navigator widgets in this article here (http://blog.insideout.io/it/2015/09/21/il-nuovo-catalogo-open-data/) generated a Javascript error (ˆsrc not definedˆ).

**Comment by ziodave** [comment]
While I cannot reproduce the issue, I can see that the navigator widget uses a fixed class which creates issues when placing 2+ navigators on the same page.

**Comment by ziodave** [comment]
I tried to reproduce it, but didn't manage to. However in the meanwhile I made a change which should fix this style issue when you load two or more navigators:
![pasted image at 2015_11_09 22_50](https://cloud.githubusercontent.com/assets/11438/11046272/23b3f936-8735-11e5-86f2-9a8123029506.png)

@cyberandy can you show me how to reproduce this issue?

**Comment by ziodave** [comment]
The error can be reproduced also here:

http://test.wordlift.it/2015/11/16/molenbeek-dove-il-problema-non-sono-i-terroristi-ma-la-disoccupazione/

It's not the original error, this is what is recorded in the console:

    Uncaught TypeError: Cannot read property 'add' of null (slick.min.js)
    b.initADA	@	slick.min.js?ver=4.3.1:18
    b.init	@	slick.min.js?ver=4.3.1:17
    c	@	slick.min.js?ver=4.3.1:17
    a.fn.slick	@	slick.min.js?ver=4.3.1:18
    (anonymous function)	@	(index):294
    j	@	jquery.js?ver=1.11.3:2
    k.fireWith	@	jquery.js?ver=1.11.3:2
    m.extend.ready	@	jquery.js?ver=1.11.3:2
    J	@	jquery.js?ver=1.11.3:2

Ad index:294 c'è la seguente linea di codice:

    $("#wl-navigator-widget").slick({

**Comment by ziodave** [comment]
Published on wordpress.org, 3.1.2
