### ISSUE TITLE
Allow the Navigator to lazyload 

### ISSUE THREAD

**Issue by claudiopome** [insideout10/wordlift-plugin#1060]
We need a way to add lazy loading to WordLift Navigator. 

Currently, even though the content is loaded async, Lighthouse is complaining about thumbnails from the navigator cards not being deferred. The lazyloading can't be handled by WP Rocket either, since the Navigator data is loaded on window load. https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwindowsreport.com%2Fedge-automatic-profile-switching-2%2F

<img width="893" alt="Screenshot 2020-05-28 at 17 46 06" src="https://user-images.githubusercontent.com/5725682/83163281-27a41b80-a10b-11ea-9724-691f60864d3c.png">

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lazy Loading Navigator and Faceted Search](https://trello.com/c/7GpTslyP/22-lazy-loading-navigator-and-faceted-search)
