### ISSUE TITLE
WordLift key is erased when plugin deactivated

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#108]
Currently the WordLift key is erased when plugin deactivated. This may "conflict" with the WordPress upgrade procedures as they deactivate all the plugins [1], making it required for a user to reset the WordLift key.

I would say not to erase the key when the plugin is deactivated. The key should be eventually erased when the plugin is uninstalled.

[1] https://codex.wordpress.org/Upgrading_WordPress_-_Extended_Instructions

**Comment by pieroit** [comment]
Hotfixed !
