### ISSUE TITLE
Setup screen fails when WPML 3.9 is installed

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1085]
/wp-admin/index.php?page=wl-setup

<img width="752" alt="image" src="https://user-images.githubusercontent.com/11438/85543835-b75dbc80-b61a-11ea-83a7-e37e36078526.png">

Setup screen doesn’t load, console errors:
ReferenceError: icl_ajxloaderimg_src is not defined scripts.js:265:24
TypeError: icl_popups is undefined scripts.js:77:5

scripts.js: /wp-content/plugins/sitepress-multilingual-cms/res/js/scripts.js?ver=3.9.3

### Workaround

Use WordLift > Settings

**Comment by akshayraje** [comment]
Code in `release\3.27.1`

**Comment by akshayraje** [comment]
Code in `release\3.27.1`
