### ISSUE TITLE
View Linked Data button disappeared

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#109]
![image](https://cloud.githubusercontent.com/assets/837037/10102409/87100f0c-639e-11e5-9988-655d62c2cd17.png)

We've lost the "_View Linked Data_" button in the UI. 
This can be seen now on blog.insideout.io and test.wordlift.it that are both running on Version 3.1.1-dev.

**Comment by mcolacino** [comment]
The dataset uri on that installation was not configured anymore. Now it's ok
