### ISSUE TITLE
Post title in the faceted search widget cannot be read

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#110]
![image](https://cloud.githubusercontent.com/assets/837037/10105576/b6c3c5de-63af-11e5-8254-7fccfffff059.png)

This can be seen in the example above on the post of WordLift 3.0.

Here is another example: http://blog.insideout.io/en/entity/mico/

**Comment by cyberandy** [comment]
![image](https://cloud.githubusercontent.com/assets/837037/10690498/ae6541d6-7982-11e5-95d0-e2712f6079cf.png)

by bringing the `line-height` to `0.9` the issue can be hot-fixed (we need here more structure in any case).

**Comment by mcolacino** [comment]
Fixed 3.0.14
