### ISSUE TITLE
Cut off FAQ markup on the suggested entities

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#1104]
Here the goal is to avoid having a duplicated FAQ Markup on the same page.
If we have two pages with those markups:
- Page A (FAQ + Article)
- Page B (FAQ + Thing)
If I'm editing on Page A and I get Page B suggested by the semantic analysis of the content, we need to ensure that we don't bring the FAQ markup of page B to avoid having a duplicate FAQ markup on Page A (that has already its FAQ Markup).

### Technical Task

In JSON-LD only print out the `FAQPage` markup if the `FAQPage` is related to the current post.

When the `FAQPage` isn't related to the current post, then

* if there are no other entity types, then do not print the entity data.
* if there are other entity types, print them (but to not print the FAQPage data).

**Comment by akshayraje** [comment]
The same issue also affects `HowTo`
