### ISSUE TITLE
Relationships of Relationships not expanded in Mappings

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1111]
Please describe the issue here:

Crreating an EventSeries:

* https://kalicube.pro/entity/takeitoffline/

Here are the subEvents:

* https://kalicube.pro/entity/takeitoffline-amsterdam-2019/
* https://kalicube.pro/entity/takeitoffline-brighton-2019/

It seems the relationships don't cascade. The two events return no errors, but the series has an error for location and date and warnings for performers. So, as it stands, using relationships is limited to one depth. It won't pull in the markup from a relationship within a relationship.

**Comment by akshayraje** [comment]
Code in `hotfix/1111-relationships-of-relationships`
