### ISSUE TITLE
Cancel button not working when trying to manually add an entity

### ISSUE THREAD

**Issue by claudiopome** [insideout10/wordlift-plugin#1117]
Issue spotted on the Scripbox website. 

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.4.2
[ ] WordLift plugin version: 3.26.3

[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Select any text to manually annotate an entity.
 - Step 2: Select Add _text that you want to annotate_
 - Step 3:  From the dropdown, click on create _text that you want to annotate_
 - Step 4:  Try going back hitting the **Cancel** button 

Here's a screencast

![Screen Cast 2020-08-03 at 11 03 39 AM](https://user-images.githubusercontent.com/5725682/89274144-d0f21b00-d640-11ea-80bd-a641f8428541.gif)

**Comment by akshayraje** [comment]
Code in `release/3.27.1`
