### ISSUE TITLE
Chord Widget rendering problems

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#112]
![image](https://cloud.githubusercontent.com/assets/837037/10197495/376612b4-6798-11e5-85cd-8efe88363e02.png)

There are the following problems (these have been spotted on blog.insideout.io): 

1- the text appears in white (this is related to a css setting of the theme) 
2- posts and entity both are in black (this is confusing)

**Comment by pieroit** [comment]
Thing entities are already colored in blue:
![image](https://cloud.githubusercontent.com/assets/6328377/11178661/716e5018-8c4e-11e5-9785-e876b30d4e52.png)

The labeling is working fine on my installation. I'm going to install casper-child to understand what CSS instruction causes the issue.

**Comment by mcolacino** [comment]
This was introduced as hotfix on 3.0

**Comment by ziodave** [comment]
It's still relevant on blog.insideout.io, e.g.:

http://blog.insideout.io/it/entity/smart-grid/
