### ISSUE TITLE
JavaScript error when clicking on Optimize in Media Library with EWWW

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1122]
Please describe the issue here:

1. Install EWWW
1. Open /wp-admin/upload.php?mode=list
1. Click on Re-optimize
<img width="54" alt="image" src="https://user-images.githubusercontent.com/11438/89758827-08514380-dae9-11ea-8c5b-d52cd11f0797.png">

A JavaScript error happens:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/11438/89758854-156e3280-dae9-11ea-8b9d-2bbb7bf12919.png">

**Comment by akshayraje** [comment]
Code in `release/3.27.1`
