### ISSUE TITLE
Chord Widget rendering problems on mobile devices and on Safari

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#113]
![image](https://cloud.githubusercontent.com/assets/837037/10222891/b4dd14ae-6856-11e5-861f-b42e563b3400.png)

Text don't appear on Android 4.4 and on a Mac running Safari (most likely they don't work on iPhone/iPad either for the same reason).

**Comment by mcolacino** [comment]
The problem was resolved with a still pending PR
https://github.com/insideout10/wordlift-plugin-js/pulls
