### ISSUE TITLE
Free <> Plus framework

### ISSUE THREAD

**Issue by akshayraje** [insideout10/wordlift-plugin#1135]

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Premium Version](https://trello.com/c/CbyesY2a/36-premium-version)

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Free Version](https://trello.com/c/IBMyMdk5/35-free-version)

**Comment by ziodave** [comment]
Closing as stale.
