### ISSUE TITLE
Report the WLP version to the API when installing/updating

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1167]

**Comment by leffluis** [comment]
There is two os architectured software available for WebShere application server 8.5.

You might have downloaded the 32-bit software or the path is set to take 32 bit as default. Some of the windows systems do not recognize the bit and installs both 64 and 32 in the same directory i.e x86.

Nothing went wrong with my website <a href="https://infograsps.com">infograsps.com</a>, Go on with the installation and check ./versionInfo.sh from the home binary path once the installation is finished.
