### ISSUE TITLE
Filters for WordLift for WooCommerce

### ISSUE THREAD

**Issue by akshayraje** [insideout10/wordlift-plugin#1174]
To ready the WordLift plugin for upcoming WordLift for WooCommerce, we would need to add filters to disable specific things in WordLift plugin. These filters will eventually be consumed by the WordLift for WooCommerce plugin.

Filters to be added to disable:
- [x] Setup screen
- [x] Automatic Analysis in Classification Box 
- [x] Manual Create Entity if Classification Box 
- [x] All the Blocks in Gutenberg are disabled except the Product Navigator (later on we may want to see if we can leave the Blocks and click to upsell)
- [x] All the widgets are disabled
- [x] All the screens in Dashboard > WordLift are hidden ( add separate hooks )
- [x] Hide the mapping of taxonomy terms to entities
- [x] The vocabulary is hidden
- [x] In Block Editor, the WordLift sidebar only shows the Classification Box with Manual Select and the Synonyms
- [x] Notice to add WordLift's key
- [x] Notice to resume set-up wizard
- [x] Post Excerpt generation

Other changes apart from filters:
- [x] Provide local item IDs when Cloud Services aren’t activated (you don’t have a dataset URI) so that item IDs could be the permalink + “#” + cpt type slug, e.g. if I have a product at http://example.org/my-product the item ID would be http://example.org/my-product#product 

Format for adding filters:
```php
if ( apply_filters( 'wl_features__enable__dataset', true ) ) {
  ...
}
```

**Comment by naveen17797** [comment]
- [ ] 1. Setup screen
- [ ] 1. Automatic Analysis in Classification Box 
- [ ] 1. Manual Create Entity if Classification Box 
- [ ] 1. All the Blocks in Gutenberg are disabled except the Product Navigator (later on we may want to see if we can leave the Blocks and click to upsell)
- [ ] 1. All the widgets are disabled
- [ ] 1. All the screens in Dashboard > WordLift are hidden
- [ ] 1. Hide the mapping of taxonomy terms to entities
- [ ] 1. The vocabulary is hidden
- [ ] 1. In Block Editor, the WordLift sidebar only shows the Classification Box with Manual Select and the Synonyms
- [ ] 1. Notice to add WordLift's key
- [ ] 1. Notice to resume set-up wizard

**Comment by naveen17797** [comment]
1. `wl_feature__enable__setup_screen`  Enables set up screen, default to true
2. `wl_feature__enable__blocks`  Enables all wordlift custom blocks, default to true
3. `wl_feature__enable__widgets` Enables all wordlift widgets, defaults to true

**Comment by ziodave** [comment]
@akshayraje @naveen17797 pls add a filter also for post excerpt generation
