### ISSUE TITLE
Local entities to show in the WL plugin panel if no key provided or cannot reach API

### ISSUE THREAD

**Issue by akshayraje** [insideout10/wordlift-plugin#1178]

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [In WLP add dct:relation to JSON-LD pushed to the Middleware](https://trello.com/c/KIPg6tKO/5-in-wlp-add-dctrelation-to-json-ld-pushed-to-the-middleware)
