### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1188]
I get this error doing the wizrd if I stop it on asking license in file wordlift/wordlift/post-excerpt/class-post-excerpt-meta-box-adapter.php at line 54

Fix:

```
if ( !isset( $wp_meta_boxes[ $post_type ] ) ) {
	return;
}
```

and

There is also on file /wordlift/includes/class-wordlift-countries.php on line 527.

```
if ( !isset( self::$country_codes[ $country_code ] ) ) {
     return '';
}
```
Expand

To add on line 54.

**Comment by Mte90** [comment]
The first one is not enough I get another error:

```
if ( !isset( $wp_meta_boxes[ $post_type ] ) || !isset( $core_meta_boxes[ self::POST_EXCERPT_META_BOX_KEY ] ) ) {
```

Maybe add phpstan on this project will help to avoid this errors.
