### ISSUE TITLE
Entities remain in draft even when they are also related to published articles

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#119]
I've noticed the following: when editing a new blog post all entities been selected become draft as the post is saved as draft. 

This would be a fine but becomes an issue when some of those entities are shared with posts being already published. 

Interesting enough also the following happens: 

1. I make changes to these entities and publish them again (from draft they become published) 
2. I make a change to the article I am writing (this remains in draft and once I save it again in draft) 
3. entities I've been editing are now back to draft and changes are lost :(

This is quite bad.

**Comment by mcolacino** [comment]
Issue #3 is fixed in 3.0.7
