### ISSUE TITLE
Fix structured data error when combining Product Markup with Review (Product) Markup

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#1191]
When we add Product Markup (using ACFs and WL Mappings) and Review Markup (using WL4SO) we are getting an error related to the aggregateRating

<img width="690" alt="Screenshot 2020-11-09 at 09 56 17" src="https://user-images.githubusercontent.com/51078695/98520167-f8750700-2271-11eb-907c-d6b430334a3b.png">

JSON Example:
`[{"@context":"http:\/\/schema.org","@id":"http:\/\/data.wordlift.io\/wl01944\/post\/product_-_wr","@type":["Product","Review"],"description":"","image":[{"@type":"ImageObject","url":"https:\/\/demo.wordlift.io\/wp-content\/uploads\/2020\/06\/SERP-features-rich-snippets-structured-data.png","width":960,"height":540}],"name":"Product - WR","url":"","brand":[{"@id":"http:\/\/data.wordlift.io\/wl01944\/post\/id\/2043"}],"itemReviewed":[{"@id":"http:\/\/data.wordlift.io\/wl01944\/post\/product_-_wr"}],"reviewRating":{"@type":"Rating","ratingValue":"3.4","bestRating":"5","worstRating":"1"},"datePublished":"2020-10-13 12:05:50","publisher":{"@id":"http:\/\/data.wordlift.io\/wl01944\/post\/id\/2043"},"author":{"@type":"Person","name":"Doreid Haddad","@id":"http:\/\/data.wordlift.io\/wl01944\/user\/doreid"},"sku":"123","offers":{"price":"233","priceCurrency":"USD","availability":"InStock","url":"https:\/\/demo.wordlift.io\/product-wr\/"},"aggregateRating":{"worstRating":"1","bestRating":"5","ratingValue":"3.4","ratingCount":"23"}},{"@context":"http:\/\/schema.org","@id":"http:\/\/data.wordlift.io\/wl01944\/post\/id\/2043","@type":"Organization","description":"Every year sees the birth of tens of thousands of new startups. This means it\u2019s getting harder and harder to get some attention as a fledgling company. There simply aren\u2019t enough journalists to give startup the attention they might deserve. TNW\u00a0started out as a prime source for news about startups over ten years ago, and...","mainEntityOfPage":"https:\/\/demo.wordlift.io\/wordlift-is-helping-robots-understand-what-online-articles-are-really-about\/","image":[{"@type":"ImageObject","url":"https:\/\/demo.wordlift.io\/wp-content\/uploads\/2020\/04\/logo_wordlift-publisher-logo-left-publisher-logo.png","width":600,"height":60}],"name":"Wordlift","alternateName":["WordLift","","Wordlift is helping robots understand what online articles are really about"],"email":"hello@wordlift.io","sameAs":["http:\/\/www.wikidata.org\/entity\/Q31998763","http:\/\/dbpedia.org\/resource\/WordLift"],"url":""},{"@context":"http:\/\/schema.org","@id":"http:\/\/data.wordlift.io\/wl01944\/post\/product_-_wr","@type":["Product","Review"],"description":"","image":[{"@type":"ImageObject","url":"https:\/\/demo.wordlift.io\/wp-content\/uploads\/2020\/06\/SERP-features-rich-snippets-structured-data.png","width":960,"height":540}],"name":"Product - WR","url":"","brand":[{"@id":"http:\/\/data.wordlift.io\/wl01944\/post\/id\/2043"}],"itemReviewed":[{"@id":"http:\/\/data.wordlift.io\/wl01944\/post\/product_-_wr"}],"reviewRating":{"@type":"Rating","ratingValue":"3.4","bestRating":"5","worstRating":"1"},"datePublished":"2020-10-13 12:05:50","publisher":{"@id":"http:\/\/data.wordlift.io\/wl01944\/post\/id\/2043"},"author":{"@type":"Person","name":"Doreid Haddad","@id":"http:\/\/data.wordlift.io\/wl01944\/user\/doreid"},"sku":"123","offers":{"price":"233","priceCurrency":"USD","availability":"InStock","url":"https:\/\/demo.wordlift.io\/product-wr\/"},"aggregateRating":{"worstRating":"1","bestRating":"5","ratingValue":"3.4","ratingCount":"23"}}]`

WordPress version: 5.5.1
WordLift plugin version: 3.27.5

**Comment by ziodave** [comment]
You can't apply both `Recipe` and `Product` types to the same entity. Please choose either one, see:

* https://developers.google.com/search/docs/data-types/product
* https://developers.google.com/search/docs/data-types/review-snippet
