### ISSUE TITLE
Enhance filters in Navigator and Faceted Search

### ISSUE THREAD

**Issue by akshayraje** [insideout10/wordlift-plugin#1197]
Enhance filters in Navigator and Faceted Search such that:

- [x] Provide a filter to override complete results after the loop
- [ ] Provide a filter to restrict results by post type(s)

Ryan Shelley from SMA-Marketing:
> I have a client that wants to use the Faceted Search & Navigator but want to know if you can filter based on content type>
For example, On a review page, they want to show only other reviews in Faceted Search and Navigator

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add filters to Navigator and Faceted Search](https://trello.com/c/T3VH8bKb/18-add-filters-to-navigator-and-faceted-search)
