### ISSUE TITLE
Changing entity type from wp backend creates an inconsistent situation

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#120]
If the editor changes the entity type from the backend, this creates and inconsistent situation on related posts: (ea: an entity of type _thing_ related as _what_ is changed in _event_: in this case the previous relation with the scope _what_ is inconsistent.

**More in details to steps are required**:
1. Entity types related css classes has to be removed.
2. Relation instances scopes has to be updated when the entity type changes

**Comment by ziodave** [comment]
I am not sure this should be marked as "bug". Should we change it to an enhancement, such as "when an entity type is changed, warn the editor", and let's spend some time to understand how to handle this situation?

For example one first step could be to add a metabox in the entity page telling the editor where the entity is linked from and what kind of relation.

**Comment by cyberandy** [comment]
@ziodave adding an information metabox might help but the problem remains. IMO if an entity type changes the following things should be done: 

- if the type is required by some other properties (i.e. the entity `Rome` > `type=location` is set as event location for an event entity) and the entity changes its type (i.e. from `type=location` to `type=organisation` in this example) the relationship with other entities is removed (and the editor is warned)

- if the entity changes the association with the 4W also changes (i.e. from _Where_ to _Who_ in this case)

**Comment by ziodave** [comment]
Yep, it's plausible.

**Comment by mcolacino** [comment]
A first solution is provided in 3.4.0 disabling entity type changing for used entities, meaning:
1. entities referencing a post *OR*
2. entities related to other entities *OR*
3. entities referenced by any other entity property

**Comment by ziodave** [comment]
### Properties (as subject)

When the entity type is changed we need to compare the fields for the source and destination types. For this we can rely on the `Wordlift_Schema_Service` which provides the list of _custom fields_ for each type, so we can compare those that do not exist in the destination type and delete them (we want to delete them, right?).

### Properties (as object)

We need to collect all the custom fields where the entity is set as target, then check whether the collected custom fields support the new entity type. If not we need to inform the editor about the number of relationships that would break.

### 4 Ws

Predicates are stored in a custom table, `wp_wl_relation_instances`. The relationship between an entity type and the _W_ is defined in the `WL_CORE_POST_CLASSIFICATION_BOXES` constant. We need to check whether the _W_ is different and, in case, update the `predicate` in the custom table.

**Comment by ziodave** [comment]
@wanbinkimoon I'll need your help here, as we need to define the UX for the entity type change as the user has to be warned about relationships that could be severed.

**Comment by ziodave** [comment]
As per our meeting on the 12th of Jan 2017, we don't ask for confirmation to the editor before performing the change, but we provide a feedback after the change has been done.

The feedback message should appear in [the newly redesigned metabox panels](https://github.com/insideout10/wordlift-plugin/issues/356).
