### ISSUE TITLE
Undefined offset: 0 in /wordlift/wordlift/post-excerpt/class-post-excerpt-meta-box-adapter.php on line 54

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1200]
Please describe the issue here:

Notice: Undefined offset: 0 in wordlift/wordlift/post-excerpt/class-post-excerpt-meta-box-adapter.php on line 54

**Comment by naveen17797** [comment]
Does it still occur on 3.27.6, it seems to be already fixed @ziodave  in this issue https://github.com/insideout10/wordlift-plugin/issues/1188

**Comment by ziodave** [comment]
Ok let's close it then.
