### ISSUE TITLE
saving sameAs in post edit screen doesn't work the 2nd time

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1208]
Please describe the issue here:

When in post edit screen, try to add a sameAs, save. Then add another sameAs, save. The second time the sameAs isn't saved.

see https://wetransfer.com/downloads/45d2bc0d1025453c3726f6becde49eb920201119102814/5274681b1b690184b03785d9a3f5d06620201119102829/9270b9

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.5.3
[ ] WordLift plugin version: 3.27.6.1

**Comment by akshayraje** [comment]
As discussed, we need to change the UI to how ACF repeater field UI is.

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sameAs not saving](https://trello.com/c/OC3Fyhbz/10-sameas-not-saving)

**Comment by akshayraje** [comment]
https://techgaragemedia.slack.com/files/UE0JVB5CJ/F01HW8JHL3T/bildschirmaufnahme_2020-12-23_um_12.00.59.mov

**Comment by claudiopome** [comment]
@navdeepsingh @ziodave Hereby a recap

- first hide url input - only leave `select`
- text Instruction _"Manually add URL"_ and _"Add"_ button to make the `input` field appear
- change `input` styles to be  `width: 100%`
- wrap text `input` around box
- _"Add"_ `button` below the aforementioned box
- _“Remove”_ `button` as ACF (circle with minus sign) - no JS, use css hidden checkbox
