### ISSUE TITLE
UI Consistency  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#121]
The goal is to streamline the user experience by **marking the territory** on the WordPress interface. The objectives for this enhancement are the following: 

1. Information in the WordPress dashboard menu that have to do with WordLift shall be made clearly visible to the user 
2. WordLift buttons, widget menù and editing widget in the editing of post and pages shall be immediately visibile to the user as part of WordLift     

For the first target a solution can be: 

- remove the logo on the top right corner and keep everything under the WordLift menù (no need to grab extra space without adding value)
-- replace in the WordLift menù the label _WordLift_ with _Getting started_ (here we will need to design a page to help the user start using WordLift effectively) 
-- add here the link to add or list SPARQL queries
- remove the _Performance Analysis_ link (this is too technical and not needed at this stage) 
- brand the _Vocabulary_ with the WordLift icon or with an icon of the same color

For the second target: 

- make sure all buttons have the same style used in the editing widget

**Comment by ziodave** [comment]
We can also hide the SPARQL Queries section, which is far too advanced at present time.

**Comment by ziodave** [comment]
@cyberandy can we split this issue in single actions?

**Comment by mcolacino** [comment]
I suggest to have a different icon for the vocabulary (not the WL one) using the icon color as brand identity element

**Comment by cyberandy** [comment]
@mcolacino it is perfectly fine to use the same color of the logo and replace the icon - I believe @ziodave had just a trouble personalising the color there as it is a font and not an image or something like that.

**Comment by ziodave** [comment]
yes, also because @cyberandy asked for the new icon 5 minutes before publishing the new version :-)

**Comment by mcolacino** [comment]
:-) What I mean is the the 'W' does not represent the vocabulary :-)

**Comment by cyberandy** [comment]
This is also top priority :+1: as requested for the launch of v.3 to the public (all buttons with the same color at the very least - if possible we could add some styling but this is not mandatory).

**Comment by mcolacino** [comment]
I suggested to use one of these 2 icons from the official WP icons dataset 
https://developer.wordpress.org/resource/dashicons/#tag
https://developer.wordpress.org/resource/dashicons/#book
Icons could be used also in the widget instead of *** for internal entities
See screenshots below as a preview

![schermata 2015-12-26 alle 16 06 00](https://cloud.githubusercontent.com/assets/1022181/12006902/d366069c-abea-11e5-8b01-48eeff4113fc.png)
![schermata 2015-12-26 alle 16 04 29](https://cloud.githubusercontent.com/assets/1022181/12006903/d3684cea-abea-11e5-8dd5-e9f66b59c144.png)

**Comment by mcolacino** [comment]
I also suggest to change color used for schema.org *Person* type: at the moment it is the same of the brand identity and this can create some conflict.
