### ISSUE TITLE
[Navigator enhancement] 404 error for all Posts %7B%7Bpost.permalink

### ISSUE THREAD

**Issue by techgarageblog** [insideout10/wordlift-plugin#1211]
I register a lot of 404 errors with the ending of %7B%7Bpost.permalink after every post.
When i search inside the Sourcecode it looks like a WordLift Navigator problem.

 
` <template type="amp-mustache" id="template-wl-navigator-widget-5fb7b9b927684">
   <div class="wordlift-navigator">
   <section class="cards">
   {{#values}}
   <article class="card">
   <a href="{{post.permalink}}">
   <amp-img width="16" height="9" layout="responsive" src="{{post.thumbnail}}"></amp-img>
   <div class="card-content">
   <header class="title">{{post.title}}</header>
   </div>
   </a>
  </article>
   {{/values}}
   </section>
   </div>
   </template>
   </div></div>
    `

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.53
[ ] WordLift plugin version: 3.27.6.1

**Comment by techgarageblog** [comment]
Same with Thumbnail /sieht-so-das-neue-samsung-galaxy-note-10-und-note-10-pro-aus/%7B%7Bpost.thumbnail

**Comment by ziodave** [comment]
This is due to Google indexing also things in `script` tags. We may have a solution for that already cc @naveen17797

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [techgarage.blog](https://trello.com/c/aFG2EcQT/11-techgarageblog)

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent Navigator templates links from being followed by Google](https://trello.com/c/zhXPZAo0/19-prevent-navigator-templates-links-from-being-followed-by-google)

**Comment by naveen17797** [comment]
hello @techgarageblog , the issue is now solved on the recent update 3.27.8.

Instead of adding the template to the dom, you can now add it using wordpress filter like this



		add_filter( 'wordlift_navigator_templates', function ( $templates ) {
			$templates['my_custom_template_id'] = "<p>template_string</p>"
			return $templates;
		} );


and add the template id to the shortcode.
