### ISSUE TITLE
Test WP 5.6 and PHP 8.0 compatibility

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1219]
Please describe the issue here:

https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/

**Comment by techgarageblog** [comment]
As my developers find out, the problem is with the Gutenberg Editor. This file creates repeating JS Errors
https://dev.techgarage.blog/wp-content/plugins/wordlift/js/dist/block-editor.js?ver=3.27.6.1.

**Comment by ziodave** [comment]
@techgarageblog can you update to 3.27.6.2 and see if the error is fixed?

**Comment by techgarageblog** [comment]
@ziodave same
![CleanShot 2020-11-27 at 14 55 20](https://user-images.githubusercontent.com/45080766/100456448-aa109680-30c0-11eb-8b2f-067e9f4dd632.jpg)
