### ISSUE TITLE
Entity related posts in the disambiguation are not properly loaded

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#122]
When the entity description is blank related posts loading is not triggered properly.

**Comment by ziodave** [comment]
Can you give more details: where does this happen exactly?

**Comment by mcolacino** [comment]
These are the steps to reproduce the error:
1. Create a post *P1*
2. Create a new entity *E1* with a blank description from the disambiguation widget
3. Save the post with the new entity referenced to the post content
4. Edit the entity resource from the backend

In this situation the disambiguation widget does not load properly related posts for the current entity - in this case the post *P1*.
It is a client side error: updating posts action is triggered once the analysis is runned  - see *EditPostWidgetController* - but **with a blank description the analysis is not performed** (to avoid Redlink errors)

**Comment by ziodave** [comment]
Let's mark it closed only when is on wp.org.

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
