### ISSUE TITLE
WebSite(s) URL are not saved

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#1224]
Please describe the issue here:

When the client adds the URL under WebSite(s) (from our meta fields) and he saves the post, that URL is not saved. 
The client has the latest version of WordLift (3.27.6.3) and WordPress 5.5.2.

**Comment by akshayraje** [comment]
@cyberandy can we see this in staging environment of the client or can we have temp access to production to see this in action.

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [komtilrom.dk](https://trello.com/c/nhBrP6jO/9-komtilromdk)

**Comment by akshayraje** [comment]
Issue not observed with WLP version 3.27.7.1 on komtilrom.dk, so closing the issue.
