### ISSUE TITLE
Chord Widget rendering problems on Firefox

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#123]
This is the way it renders on FireFox (41.0.1 on Mac)
![image](https://cloud.githubusercontent.com/assets/837037/10334100/55e3c16e-6ce8-11e5-8787-bab82e3b0015.png)

This is how it should be
![image](https://cloud.githubusercontent.com/assets/837037/10334119/736a6cb0-6ce8-11e5-8ab2-2d1baeb94a4c.png)

**Comment by pieroit** [comment]
Firefox needs `<text text-anchor="end">` for labels on the left side of the chord.
