### ISSUE TITLE
Context Cards not working in combination with WP Rocket

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1234]
Please describe the issue here:

When WP Rocket is enabled, context cards aren't loaded, e.g. https://scripbox.com/mf/investment-options/

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.5.3
[ ] WordLift plugin version: 3.27.7.1
[ ] WP Rocket version: 3.7.5

The following excludes are configured:

![image](https://user-images.githubusercontent.com/11438/102583205-8ad7b880-4104-11eb-85f4-01c86179a3ac.png)

**Comment by akshayraje** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scripbox, Context Cards not working](https://trello.com/c/1G1z1ntj/14-context-cards-not-working)
