### ISSUE TITLE
Personalise the entity path 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#125]
Some bloggers might prefer to personalise entity URLs (i.e. _/glossary/_ or _/topic/_ instead of _/entity/_).

**Comment by cyberandy** [comment]
This has been requested by two testers now

**Comment by ziodave** [comment]
The [`register_post_type`](https://developer.wordpress.org/reference/functions/register_post_type/) function allows customization of the slug from the default _entity_ to a custom set value.

**Comment by ziodave** [comment]
[This SO answer](http://wordpress.stackexchange.com/a/204210/23194) provides an approach on how to use an empty slug.

But how should we handle conflicts with posts/pages?

**Comment by ziodave** [comment]
In order to avoid conflicts we might look into avoiding using the same slug for posts/pages/entities.

**Comment by ziodave** [comment]
Okey to recap:

1. using the strategy described in [this SO post](http://wordpress.stackexchange.com/questions/203951/remove-slug-from-custom-post-type-post-urls/204210#204210) we can fully customize the entity slug, including no post type slug,
2. the customization will be provided as a constant to set in the `wp-config.php` file (e.g. `define( 'WL_ENTITY_TYPE_SLUG', '[entity|custom|<empty>]');`
3. using `wp_unique_post_slug_is_bad_flat_slug` we check that there is no conflict with posts/pages/entities/... slugs.

Ok?

**Comment by ziodave** [comment]
What should we consider as the entity URL (schema:url) in Linked Data? And what happens if the site admin changes the entity base path?

**Comment by cyberandy** [comment]
We shall preserve the entity URL as configured by the user (with or without
`/entity/` in the path) in Linked Data. We need to keep track of any
changes in the entity URL.


*Andrea Volpini*


*InsideOut10 <http://blog.insideout.io> - WordLift <https://wordlift.io>*


[image: Twitter] <https://twitter.com/cyberandy> [image: LinkedIn]
<https://www.linkedin.com/in/volpini> [image: about.me]
<https://about.me/andreavolpini> [image: Google Plus Page]
<https://plus.google.com/+AndreaVolpini> [image: SlideShare]
<https://www.slideshare.net/cyberandy> [image: Flickr]
<https://www.flickr.com/photos/cyberandy>

**Comment by ziodave** [comment]
This means that if the web site has 1.000 entities, we need to perform 1.000 updates.

**Comment by ziodave** [comment]
Since we're talking about Linked Data and URLs should be permanent, we won't allow changing the entity type path.

**Comment by ziodave** [comment]
The entity base path (aka entity content type slug) should be set using the settings screen, when the key is configured:

![image](https://cloud.githubusercontent.com/assets/11438/18225927/1c62f024-7208-11e6-87e4-3bd0960106c4.png)

Once set, it should be readonly. If WordLift is reinstalled the user should retype the same base path.

**Comment by ziodave** [comment]
Something like this:

![image](https://cloud.githubusercontent.com/assets/11438/18226780/d91784bc-7219-11e6-823d-71c1302d07c0.png)

**Comment by mcolacino** [comment]
I agree to have a *readonly* setting, after the first setup.
More in details it should become readonly once the first entity is added in the vocabulary.

**Comment by ziodave** [comment]
This feature is ready for testing.

**Comment by cyberandy** [comment]
After running a quick test with @mcolacino we had to removed the resolved label from this one. Here is the case: 

1. create a blog post with the title `Marcello Colacino`
2. create an entity with the title `Marcello Colacino` the url correctly becomes `/marcello-colacino-2`
3. create a blog post that mentions `Marcello Colacino`

You will see by looking at the code behind the `Marcello Colacino` annotation that the URL provided is wrong:

`<span id="urn:enhancement-a49ae8ba-37fc-2e52-e9ca-b28b924e2edd" class="textannotation disambiguated wl-person" itemid="http://data.wordlift.it/testwordlift/entity/marcello_colacino">Marcello Colacino</span>`

The issue is related to the fact that, when generating the URL for the linked data publishing ([build_uri method](https://github.com/insideout10/wordlift-plugin/blob/develop/src/includes/class-wordlift-entity-service.php#L291)), the function doesn't take into account this specific case.

![image](https://cloud.githubusercontent.com/assets/837037/18679627/ca3d696c-7f60-11e6-9ef3-781535827ed5.png)

**Comment by ziodave** [comment]
This is the expected behavior. The entity path is about the path in WordPress, not in Linked Data, which is correctly reflected in the _schema:url_ property.

**Comment by cyberandy** [comment]
Yes - @mcolacino thought there was a bug there 😃 but in fact it works just
fine.

**Comment by Rainer-Edlinger** [comment]
;-)
