### ISSUE TITLE
compress 3rd party library vis.js

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#129]
The file `src/js-client/visjs/vis.js` is 1.4M, we need to minify this file if we want to provide to clients.

**Comment by mcolacino** [comment]
@ziodave @cyberandy  vis.js is at the moment used only by the **blog_map** shortcode that is not included in the shortcode select being just a prototype ... Do we want to keep it in the code? Maybe itìs better to remove it and introduce it again when ready for the production ...

**Comment by ziodave** [comment]
@mcolacino I agree, we could move it to a separate branch.

**Comment by mcolacino** [comment]
ok so i fork a branch with this functionality from develop and after that remove the code from the develop branch

**Comment by mcolacino** [comment]
Solved on *feature/blog_map_shortcode* branch

**Comment by ziodave** [comment]
This library appears not to be used anymore.
