### ISSUE TITLE
Classifications suggestions disappear when manually adding Entity

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1290]
Please describe the issue here:

> Whenever we add a tag manually to a post (by selecting something in the text that isn’t blue, hitting the blue ‘Add’ button in the WL sidebar widget, filtering for the relevant tag, selecting the right one, and then the green confirmation notification appears) this happens: all already selected tags and suggested tags in the sidebar widget disappear, and we can only see those again when we either save the draft or refresh the page.

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.9.16
[ ] WordLift plugin version: 3.27.8

**Comment by ziodave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Classification Box suggestions disappear, TheNextWeb](https://trello.com/c/4m5Arv20/79-classification-box-suggestions-disappear-thenextweb)

**Comment by akshayraje** [comment]
This is reproducible in classic editor
