### ISSUE TITLE
Editors to be able to edit vocabulary pages

### ISSUE THREAD

**Issue by akshayraje** [insideout10/wordlift-plugin#1313]
Only admin users are currently able to edit vocabulary pages. 

The proposal is to let editors edit vocabulary pages and this also fits with the no vocabulary.

**Comment by akshayraje** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Editors to be able to edit vocabulary pages](https://trello.com/c/ec17ge8l/100-editors-to-be-able-to-edit-vocabulary-pages)

**Comment by ravisoni6262** [comment]
as discussed on the call, we should not open it to the editor role, but create a new capability - something like wordlift-editor and open it to this capability.

**Comment by ravisoni6262** [comment]
The solution is to add `role` and in its `capabilities` we need to provide `capability_type`
https://wordpress.stackexchange.com/questions/108338/capabilities-and-custom-post-types

**Comment by ravisoni6262** [comment]
The solution is working now but the view is hidden because some `CSS` is hiding the views to add and edit the `entities`

```
@media (min-width: 782px)
body.js.is-fullscreen-mode #adminmenumain, body.js.is-fullscreen-mode #wpadminbar {
    /* display: none; */
}
```
