### ISSUE TITLE
update the screenshots on the WordPress plugins page

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#132]
The screenshot on this page, https://wordpress.org/plugins/wordlift/screenshots/, refer to the old version of WordLift, we should update them.

**Comment by cyberandy** [comment]
I need a bit of help here - I've done some updates recently to the `readme.txt` but these updates are not online on the WordPress repository (I still see the old version online).

**Comment by ziodave** [comment]
To have it land sooner to wordpress.org, we should probably update it directly on the _master_ branch as well. I'll help you later today.

**Comment by cyberandy** [comment]
I've done a first review here. More to come in this direction but for the time being this issue can be closed.
