### ISSUE TITLE
Images not loading when creating Entities.

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#135]
This bug has been spotted on taoroma.it but it is actually present in all installations (I've tested also on other sites).
 
When creating a specific entity like `ombelico` or `cuore` the image first appears in the WordLift Editor Widget but after saving the post; the image disappears. 

**Before**
![image](https://cloud.githubusercontent.com/assets/837037/10849004/fe299fc2-7f1e-11e5-8a47-18d5dfb42ad4.png)
 
**After**
![image](https://cloud.githubusercontent.com/assets/837037/10849030/136e64ee-7f1f-11e5-8d8c-58527d6fa7a2.png)

**Comment by ziodave** [comment]
Published with 3.0.15
