### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#138]
When trying to select the option provided by the auto-complete something goes wrong. 
![image](https://cloud.githubusercontent.com/assets/837037/10896268/27d115e8-81b9-11e5-97d6-2e50d7462cc7.png)

![image](https://cloud.githubusercontent.com/assets/837037/10896275/35428d1a-81b9-11e5-97b0-3065404e8cc8.png)

I'm using Chrome 46 on Mac.

**Comment by pieroit** [comment]
resolved

**Comment by pieroit** [comment]
verified from the UI
