### ISSUE TITLE
Single founder while expecting multiple founders

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#139]
The founder property under organisation only allows to enter ONE single value (missing cardinality).

**Comment by pieroit** [comment]
Added `cardinality => INF` to the founder custom field

**Comment by pieroit** [comment]
Resolved but not merged into master

**Comment by geospatialmedia** [comment]
great, waiting for this update!

**Comment by pieroit** [comment]
@geospatialmedia the feature is implemented and verified. Coming live in the next hours.
![image](https://cloud.githubusercontent.com/assets/6328377/11148614/fa826980-8a1d-11e5-9684-f89be5484425.png)
