### ISSUE TITLE
Organization expected fields

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#140]
Here I would expect to see: 

- Email
- Address
- URL (for the website) 
- PO Box
- City 
- State/Region
- Postal code
- Country

**Comment by pieroit** [comment]
Partially resolved. Still missing the properties `email` (available for Person) and `website URL`

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11689963/939e6486-9e94-11e5-8940-150a99cd774c.png)

`email` has been added.
We need to further discuss the difference between `Entity URL`, `owl:sameAs`, `schema:sameAs` and `schema:url`,

**Comment by ziodave** [comment]
To recap:

* _Entity URL_ is the _itemId_
* _schema:sameAs_ has the following definitions:
** "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website." (schema.org web site)
** "This property is inspired by owl:sameAs and has essentially the same semantics, although schema.org HTML data tends to blur distinctions which are important to OWL users, such as URIs for entities versus the pages that describe them." ([w3.org](http://www.w3.org/wiki/WebSchemas/sameAs))
* _owl:sameAs_ is related to OWLs, we shouldn't discuss about it
* _schema:url_ is the:
** "url of the item" (schema.org)
** "While 'url' points from something to a page/record that's mostly about it and is in some sense 'its' page, sameAs can be used more freely wherever we have useful identifiers (direct or via-some-page) for an entity of interest."  ([w3.org](http://www.w3.org/wiki/WebSchemas/sameAs))

The main discussion therefore is about the _schema:url_ predicate, which we currently automatically set to the WordPress page of the entity.

IMHO we should continue to use the WordPress entity page URL as _schema:url_ unless the editor provides another URL which might be more pertinent or specific, e.g. the official company web site for an organization.

**Comment by ziodave** [comment]
Ok, I had a call with @cyberandy (sorry folks, I didn't manage to get you onboard), we agreed on the following:

* the _same as_ meta-box won't change (it'll feed the _owl:sameAs_ property) - we'll change the label soon into something more understandable (sic!) by editors
* the _schema:url_ will stay the same, i.e. the URL of the entity page on the WordPress site
* we allow to define 1+ URLs by the user which will be added to the (relaxed) _schema:sameAs_ property, the label for these inputs is "Web Addresses"

**Comment by mcolacino** [comment]
@ziodave have a custom metabox for a non-schema property as *owl:sameAs* represents an exception for the current metabox engine. At the moment the *sameAs* metabox feeds both owl and schema sameAs on Redlink side. So the question is to me why we cannot have web addresses both on *owl:sameAs* and *shema:sameAs*?

**Comment by ziodave** [comment]
@mcolacino because they have different requirements. _owl:sameAs_ requires you to point to an ontology, whereas _schema:sameAs_ can also point to a human-readable HTML page (w/o any markup for computers)

See also here: [http://www.w3.org/wiki/WebSchemas/sameAs](http://www.w3.org/wiki/WebSchemas/sameAs)

> It adds a property to schema.org, 'sameAs' that can be used to indicate when a single real-world entity is being described.
> 
> This property is inspired by owl:sameAs and has essentially the same semantics, although schema.org HTML data tends to blur distinctions which are important to OWL users, such as URIs for entities versus the pages that describe them. It is also similar in intent to the microformats community's use of rel='me' .

**Comment by mcolacino** [comment]
@ziodave I see there is great a difference, but maybe it's not so clear for the standard end user to understand this very technical difference ... What about if keep just sameAs (schema.org) in the UI having a way to automatically detect which *schema:sameAs* has to be also published as *owl:sameAs* (ea: looking at domain name)?

**Comment by ziodave** [comment]
@mcolacino choosing on behalf of the domain name requires a curation effort that we can hardly code in the plugin: a predetermined list of domains which expose triples doesn't exist.

Currently we're treating _schema:sameAs_ and _owl:sameAs_ as if they were the same thing, but they're not.

We need to allow editors to add URLs to _schema:sameAs_ and this should happen in the main content area, with a labels of "Additional URLs" (or something similar).

I understand that the side metabox may generate some confusion for the editor, so maybe we should simply disable it (i.e. the _owl:sameAs_ values are the ones we retrieve from an analysis and we don't allow the editor to add others).

I suggest we set-up a meeting to quickly get to an agreement on this point.

Ciao!

**Comment by mcolacino** [comment]
mmm @ziodave I agree that an extra curation effort is not a good option ...
Maybe we could check calling each sameAs forced accepted formats header in order to automatically detect if a single sameAs has to be managed as an owl:sameAs or not ... But ok, let's set-up a meeting on this point

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11929755/f2aeb6d6-a7dd-11e5-8870-6c759b472140.png)

Email and Address are present. I will open a separate issue for the sameAs/URL modifications.
