### ISSUE TITLE
Properties when published to Redlink have no links (and no meaning)

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#141]
When adding a property for Person like `knows` the information published is not comprehensible and has no link.

![image](https://cloud.githubusercontent.com/assets/837037/10896521/ea1728ee-81ba-11e5-8bad-7533fe0c9d68.png)

**Comment by pieroit** [comment]
Unit tests should be added for this part. Before that, an object oriented refactoring is necessary in order to reduce functions length (some are more than 150 lines) and improve readability.

**Comment by pieroit** [comment]
verified on Redlink
