### ISSUE TITLE
Address incomplete

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#143]
When adding the `address` under Place I was expect something like: 
![image](https://cloud.githubusercontent.com/assets/837037/10896657/9435dad2-81bb-11e5-8983-026b8b83a1ed.png)

and instead I have only one field and it's hard to guess what is the detail level expected (is Country needed? Shall I add the PO Box? ...).  
![image](https://cloud.githubusercontent.com/assets/837037/10896775/6ec5f86c-81bc-11e5-9891-543f73fc1cec.png)

**Comment by pieroit** [comment]
Metabox field:
![image](https://cloud.githubusercontent.com/assets/6328377/11528613/2d9ad9a0-98e8-11e5-8015-ba516c8fc369.png)

On Redlink:
![image](https://cloud.githubusercontent.com/assets/6328377/11528581/0841f85a-98e8-11e5-920d-59a9b4d51a79.png)

Verified on test.wordlift.it

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
