### ISSUE TITLE
Changing type on WordLift doesn't reset the property list on Redlink

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#144]
![image](https://cloud.githubusercontent.com/assets/837037/10896913/3c3c9896-81bd-11e5-8409-1e379ad06174.png)

When the same entity is used let's say for Person and converted into Organisation all fields related to Person shall be removed from Redlink. This doesn't happen.

**Comment by pieroit** [comment]
Issue is resolved but there are still problems since not always the triples are updated on RL.

**Comment by pieroit** [comment]
Resolved (with the exception above) and merged into develop

**Comment by pieroit** [comment]
verified on WL and Redlink
