### ISSUE TITLE
Controlling the creation of new entities from metaboxes

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#145]
When adding the property `knows` for instance I create a new entity. 
If I misspell the name of the entity in the first place (writing Andres instead of Andreas) and I re-write it a second time I will find on my sites two separate entities (Andres and Andreas) and the corresponding pages - this is confusing. 

We can either add a control or make sure only the entities being used are saved permanently in the blog.

**Comment by pieroit** [comment]
resolved

**Comment by pieroit** [comment]
verified from the UI
