### ISSUE TITLE
Incompatibility issue with the Redirection plugin

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#146]
This has been spotted on http://www.lafabbricadellarealta.com/ and fixed (it was a bug on this Redirection plugin - https://wordpress.org/plugins/redirection/). We shall investigate this further and eventually document the incompatibility or write to the plugin team.

**Comment by cyberandy** [comment]
This can be solved by de-activating the following option on the plugin:

![image](https://cloud.githubusercontent.com/assets/837037/10973810/54540530-83df-11e5-9029-48149ffc5280.png)

The plugin with this option activated monitors 404 errors and creates automatically 301 redirects that are generating the issue.

**Comment by cyberandy** [comment]
We need to add an Incompatibility section on the documentation.

**Comment by ziodave** [comment]
We should also raise admin notices when the plugin is installed and active. We can take this chance to use the boilerplate.

**Comment by cyberandy** [comment]
Good idea. Let's keep this one open and do both (updating documentation and raising admin notice)

**Comment by mcolacino** [comment]
This can be managed as part of #240
