### ISSUE TITLE
Implementing a version of the navigator widget that works on entity pages 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#147]
This has come as _request/suggestion_ from http://www.lafabbricadellarealta.com/. 
Right now to build the interlinking between an entity page and the correlated posts we provide two options:

- faceted search widget 
- chord

While the first one is functional it has its own complexity and only makes sense once I've done several annotations; on the other hand the second one can be too invasive for the minimalistic design of some websites and a simpler version might help.

Let's see what are the options around:
**Outbrain** 
![image](https://cloud.githubusercontent.com/assets/837037/10933343/13d42722-82d8-11e5-91f4-30e57e498bbf.png)
![image](https://cloud.githubusercontent.com/assets/837037/10933375/51211b44-82d8-11e5-9728-27aeeff43990.png)

**Taboola** 
![image](https://cloud.githubusercontent.com/assets/837037/10933421/a9edce3e-82d8-11e5-82da-3b7f872567e1.png)

This issue requires the insights from Mausa on what is best for the reader and a flexible technical approach to bring as much freedom as possible to the site owner (in terms of CSS personalisation, Javascript libraries or APIs).

**Comment by pieroit** [comment]
Should we revamp this?
https://github.com/insideout10/wordlift-plugin/blob/hackathon-2015/src/shortcodes/wordlift_shortcode_related_posts.php

**Comment by cyberandy** [comment]
It can work as long as we provide it as `vanilla widget` (this means Keeping It Super Simple) for entity pages and with the sole purpose of presenting _the list of related blog posts_ for that entity. 

Another addition would be a companion widget presenting the _list of related entities_ for that entity.

**Comment by mcolacino** [comment]
The content of this issue is developed in issue #253
