### ISSUE TITLE
Overlapping tiles on VideoObject modal window

### ISSUE THREAD

**Issue by claudiopome** [insideout10/wordlift-plugin#1476]

**Comment by claudiopome** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overlapping tile on VideoObject modal](https://trello.com/c/o7x6iyc6/587-overlapping-tile-on-videoobject-modal)

**Comment by claudiopome** [comment]
<img width="1423" alt="Screen Shot 2021-09-24 at 18 26 18" src="https://user-images.githubusercontent.com/5725682/134883928-7d25af1e-54cc-4a60-902c-af3a387ba5b1.png">

**Comment by naveen17797** [comment]
Fixed in 3.33.2
