### ISSUE TITLE
Incompatibility issue with SEO Ultimate

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#148]
On the entity pages being created with websites that are running the latest version of the **SEO Ultimate** plugin Version 7.6.5.8 (here is an example: http://taoroma.it/wp-admin/post.php?post=3119&action=edit) 

The SEO Ultimate plugin re-uses the meta description of the blog post that generated the entity (or more simply the latest blog post edited by the author). This creates an issue as this is metadata is **inconsistent** with the entity itself. 
![image](https://cloud.githubusercontent.com/assets/837037/10933546/7eac922c-82d9-11e5-810d-89d4db0229ce.png)

We shall bring this one to the attention of the SEO Ultimate team and ask for their advice.

See also https://github.com/insideout10/wordlift-plugin/issues/156

**Comment by geospatialmedia** [comment]
Hi Andy, As discussed, we look forward for the changes to this. Thanks in advance.

**Comment by ziodave** [comment]
In SEO Ultimate [class.seo-ultimate.php:231](https://github.com/wp-plugins/seo-ultimate/blob/master/plugin/class.seo-ultimate.php#L231), a hook is added:

`add_action('save_post',  array(&$this, 'save_postmeta_box'), 10, 2);`

The hook calls the function [`save_postmeta_box`](https://github.com/wp-plugins/seo-ultimate/blob/master/plugin/class.seo-ultimate.php#L1723) when a post is saved, which stores the values set in the admin form on the newly created entities.

**Comment by ziodave** [comment]
Published with 3.0.14
