### ISSUE TITLE
Person expected fields

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#149]
Here I would expect to see:

- Email
- Organization

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11398744/1132dd0e-9383-11e5-8f96-74dc83af024a.png)


![image](https://cloud.githubusercontent.com/assets/6328377/11398775/1f52b2ba-9383-11e5-83ed-9137d14af0b4.png)

**Comment by pieroit** [comment]
Verified on test.wordlift.it

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
