### ISSUE TITLE
the property schema-org:author on blog post lod view goes on error

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#150]
When publishing a blog post the metadata published on Redlink for the property `schema-org:author` is a IRI (and this is correct in principle) 
![image](https://cloud.githubusercontent.com/assets/837037/10963897/e5e4fd74-83a3-11e5-91f1-b44758b48571.png)
The problem is that this IRI doesn't exist and therefore the error
![image](https://cloud.githubusercontent.com/assets/837037/10963924/197bf7aa-83a4-11e5-99f5-0db879d41466.png). 

The options I see are the following: 
- 1. we create the IRI based on the list of users on WordPress 
- 1. we add a literal and not a IRI

**Comment by ziodave** [comment]
Exposing the list of users (using their usernames) might represent a security threat in WordPress. Moreover there are WP plugins that let you change the username and may represent a future issue.

We need to think this through, maybe the user URI can use the numeric ID, and the information published for the user may be the *display name and a link to the user page on WP with the list of posts.

**Comment by ziodave** [comment]
In WP the user's page uses a slug generated according to the display name. We could do the same for users URIs. However that means we should monitor changes and update URIs accordingly (i.e. URIs might not be as "stable" as they should be, but I think that's acceptable as changing an URL on the web site is also not advisable).

**Comment by ziodave** [comment]
Fixed in 3.1.7, updates to authors in the triple stores are made when posts are saved (i.e. old links may still appear until a post is updated).
