### ISSUE TITLE
Geo coordinates are not populated for well known places.  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#151]
When creating an entity `type:place` like _Mexico City_ (http://test.wordlift.it/entity/mexico-city) the geo coordinates have to be added by hand and this is frustrating for the user.

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11624374/c4d965d6-9cd3-11e5-82b9-3c32782e61ff.png)

Done.
In the `entity->properties` data structure posted from the 4W widget it is possible to insert any properties we want to save. As a convention we just use the schema.org property name (e.g. `latitude`, `startDate`) and an array of values.
This will solve issue #75 without further modification to the php code.

**Comment by pieroit** [comment]
Now working on the tests. A manual verification of the effect on the entity as it is pushed back to RL
![image](https://cloud.githubusercontent.com/assets/6328377/11624528/d34e1188-9cd4-11e5-8b84-f4bd9418cada.png)

**Comment by ziodave** [comment]
reopening issue, will close only when on wp.org
