### ISSUE TITLE
Losing images on curated entity pages 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#152]
This has been first spotted on http://www.lafabbricadellarealta.com/ and it could be reproduced as follows: 

- create a blog post _x_
- select an entity _y_ for that blog post
- enrich the entity (by going into _vocabulary_ > [entity-_y_] > _edit_  ) with one or more images
- get back on the blog post _x_ 
- unselect the entity _y_
- save again the blog post _x_ so that the analysis starts again
- select the entity _y_

All images in the entity page _y_ and any other text you might have added by going into _vocabulary_ > [entity-_y_] > _edit_ are **lost**.

The WordLift Edit Post Widget saves the entity as a _new entity_ and all additional contents are removed. 

**This is critical** and very painful as in some cases we see also widgets and other valuable links being removed from entity pages. It might require a more in-depth testing to be properly reproduced.

**Comment by mcolacino** [comment]
Should we manage as an hotfix instead?

**Comment by ziodave** [comment]
Yes

**Comment by mcolacino** [comment]
The analysis returns entity descriptions as they are on Redlink side (text plain version without html markup). The disambiguation widget generally shows the text plain version coming from Redlink. If the current entity is available in the local storage (meaning that a given entity is previously related to the current post). **For the rest, the plain text version is used: this creates the bug**. Looking at the workflow the unselection step that creates the bug. A solution could be **avoid description overriding if the current entity is not already linked to the current post**.

**Comment by cyberandy** [comment]
An even simpler way to put this is to *avoid description overriding when
the current entity is locally stored*.




*Andrea Volpini*


*InsideOut10* <http://blog.insideout.io>
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>
