### ISSUE TITLE
Entity properties change is not always reflected on Redlink

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#155]
If you change an entity's property or its type and save, sometimes the changes are updated to Redlink, sometimes not. TODO:

1 - isolate the error (I did not find a deterministic way to reproduce it... seems to be random)
2 - understand if it's an error in WL or a delayed update on RL, or if there is a communication problem
3 - write two unit tests, one for property change, and another for type change. They must be reflected on Redlink (sooner or later)

**Comment by ziodave** [comment]
@pieroit @cyberandy I cannot really reproduce this issue, maybe we can check this together.

**Comment by ziodave** [comment]
I changed the labeling from bug to enhancement as this is WIP on the new metaboxes, I'll create also a dedicate branch (as a feature).

**Comment by ziodave** [comment]
merged to develop
