### ISSUE TITLE
create an entity from the edit post page

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#157]
Currently, when an entity is created while editing a new or existing post from the edit post page, we save the entity data at the same time the post data is saved using the `wp_insert_post` method.

This poses an issue with plugins that hook to `wp_insert_post` and save additional data to the post, e.g. SEO Ultimate or Yoast.

We should change the way entities are saved from the edit post page, probably by creating them as soon as the editor clicks on "save entity" using AJAX.

See also for reference https://github.com/insideout10/wordlift-plugin/issues/156 and https://github.com/insideout10/wordlift-plugin/issues/148

**Comment by mcolacino** [comment]
I agree this could be the right direction ... We should consider how to manage entity post status transitions related to post status transitions.
