### ISSUE TITLE
Fix the date controller in the metabox for Person birthDate

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#159]
Right now we ask the editor to fill date and time for the Person birthDate property. 

![image](https://cloud.githubusercontent.com/assets/837037/11097265/c1fb1c36-889e-11e5-9d8e-d4a5726450d8.png)

When writing though this data as linked data we only use the date. 
![image](https://cloud.githubusercontent.com/assets/837037/11097331/0f7b198e-889f-11e5-91ba-8042a1a3891e.png)
I see here two options: 

1. changing the controller so that only a date is requested to the user
2. storing date and time as linked data

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11396626/13ea6c16-9373-11e5-9347-932cbe369255.png)

**Comment by pieroit** [comment]
There are two different pickers, one for datetime:
![image](https://cloud.githubusercontent.com/assets/6328377/11528357/5fe0a446-98e6-11e5-846e-9dfafe061f89.png)

And one for the date without time:
![image](https://cloud.githubusercontent.com/assets/6328377/11528375/8d1ef1e2-98e6-11e5-881b-0e8ad66ab295.png)

They are both correctly reflected on RL.
Verified on test.wordlift.it

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
