### ISSUE TITLE
Missing title tag on entity links

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#1593]
Please describe the issue here:

1. I have an entity (ie "structured data"), 
2. I add a synonym to the entity for internal linking purposes (ie "structured data seo")
3. I write an article that mentions "structured data seo" 
4. the NLP detects the entity correctly and adds the link but 

I aspect (as it used to be) that the title tag for the href link that WordLift create around the structured data seo is "structured data" the main name of the entity. 

Right now I have this:
`<a class="wl-entity-page-link" href="https://demo.wordlift.io/recipe-2/" data-id="http://data.wordlift.io/wl01944/post/recipe-6126" aria-expanded="false">structured data seo</a>`

I would expect to see this:
`<a class="wl-entity-page-link" title="structured data" href="https://demo.wordlift.io/recipe-2/" data-id="http://data.wordlift.io/wl01944/post/recipe-6126" aria-expanded="false">structured data seo</a>`

These are tiny details that helps usability and SEO as well.

**Comment by elmeligy** [comment]
cannot replicate on test WP
closing as per Andy's request.
