### ISSUE TITLE
When creating a new entity via autocomplete the entity type for birthPlace is set to LocalBusiness rather than Place

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#160]
This is easy to be reproduced: 
- From an entity type Person enter as birthPlace a new value (i.e. New York)  
![image](https://cloud.githubusercontent.com/assets/837037/11097429/ab449b9c-889f-11e5-909c-0d674791c753.png)
- The new entity `New York` is created by the type is `LocalBusiness` and not `Place`

**Comment by pieroit** [comment]
verified from the UI
