### ISSUE TITLE
GeoMap for entity type = Places should render the map on the entity page  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#161]
If I'm working on the entity of **New York** and I've filled up the geo coordinates I expect to see the GeoMap widget rendere the map with New York in it. This currently doesn't happen as the widget only consider related entities and not the entity itself.

**Comment by cyberandy** [comment]
Here is a case where the map is not being displayed on the _event entity_ page http://geobuiz.com/entity/geospatial-world-forum/ - I've increased the priority.

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11631727/afe0b24e-9d03-11e5-99b1-110092a379b3.png)

**Comment by pieroit** [comment]
Two improvements:
1 - query to populate the geomap considers both the presence of coordinates and the entity type (just the coordinates would create confusion when changing entity type)
2 - works for child types (e.g. LocalBusiness)

![image](https://cloud.githubusercontent.com/assets/6328377/11684121/9f2a30fc-9e6f-11e5-8c20-0d7fcf41f001.png)
