### ISSUE TITLE
Only dates are stored for events - the information on time for endDate and startDate is lost

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#162]
When editing an entity type event the controller allows me to store date and time for the properties endDate and startDate. 
When this information is published though the time is lost:
**on Redlink**
![image](https://cloud.githubusercontent.com/assets/837037/11098148/53c098d6-88a3-11e5-8fc9-0618959f39ee.png)

**on the microdata**
![image](https://cloud.githubusercontent.com/assets/837037/11098159/6580188a-88a3-11e5-94a6-ab894ec6f13b.png)

**Comment by ziodave** [comment]
The issue is that the in the SPARQL query an `xsd:date` data type is used:

```<http://data.redlink.io/91/be2/entity/jane_doe> <http://schema.org/startDate> "2015-11-01T14:35:00Z"^^xsd:date .
 <http://data.redlink.io/91/be2/entity/jane_doe> <http://schema.org/endDate> "2015-11-02T14:35:00Z"^^xsd:date .```

**Comment by pieroit** [comment]
verified on both WL microdata and Redlink
