### ISSUE TITLE
Places stored for events are missing or incorrect when sent to Google 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#163]
When creating an event and adding a place (i.e. http://test.wordlift.it/entity/arriva-la-porchetta-ad-ariccia/) the microdata written on the page does not have this information.

`<span itemscope itemtype="http://schema.org/Event" itemid="http://data.wordlift.it/wl028/entity/arriva_la_porchetta_ad_ariccia"><span itemprop="startDate" content="2015-11-12T20:00:00Z"></span>
                                <span itemprop="endDate" content="2015-11-12T21:00:00Z"></span>
                                New York<link itemprop="url" href="http://test.wordlift.it/entity/arriva-la-porchetta-ad-ariccia/" /><a class="wl-entity-page-link" href="http://test.wordlift.it/entity/arriva-la-porchetta-ad-ariccia/" itemprop="name" content="Arriva la porchetta ad Ariccia"></a></span>` 

Here is what I have in the back-end:
![image](https://cloud.githubusercontent.com/assets/837037/11098322/6b73d51e-88a4-11e5-945a-c9a43de8c361.png)
New York is a place and has the geo coordinates. This is the error I get from Google.  

![image](https://cloud.githubusercontent.com/assets/837037/11098190/94e3c270-88a3-11e5-824f-e4ff43d45ced.png)

**Comment by ziodave** [comment]
There's another issue here as well, this is conceptually wrong:

```<span itemprop="startDate" content="2015-11-12T20:00:00Z"></span> <span itemprop="endDate" content="2015-11-12T21:00:00Z"></span>```

1. SPANs should be used only with visible information and shouldn't be empty
2. `Dates, times, and durations: use the time tag with datetime`
3. Missing/implicit information: use the meta tag with content

So a better choice here is to find a page fragment where the date and time are written for the user as well or, if missing, use the meta tag.

See: http://schema.org/docs/gs.html

**Comment by ziodave** [comment]
This issue happened because the entity post referenced by the _location_ predicate was set as _draft_ (although in the source code of the web page I can see the title of the web page, w/o markup, when it is draft).

**Comment by ziodave** [comment]
This is fixed, I'll open a separate issue for my comment above.

**Comment by pieroit** [comment]
verified from the UI
