### ISSUE TITLE
latitude and longitude set to zero

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#166]
It appears that if latitude and longitude are not set, then they're set to zero which is not right.

![screenshot 2015-11-12 00 40 31](https://cloud.githubusercontent.com/assets/11438/11105193/03c9112c-88d6-11e5-80c2-0bb2e1dc8d60.png)

**Comment by pieroit** [comment]
If coordinates have no value the map in the entity editor remains gray and there is an error about an undefined value. It's easily resolved in the map script (if coordinates are null, set a large zoom and center on planet view)

![image](https://cloud.githubusercontent.com/assets/6328377/11148019/64472ce2-8a1a-11e5-9953-173dbee6f6da.png)

**Comment by pieroit** [comment]
verified form the UI
![image](https://cloud.githubusercontent.com/assets/6328377/11148804/51f68344-8a1f-11e5-99e9-27716a7f737b.png)

**Comment by ziodave** [comment]
When the coordinates are not provided, the geomap will now ask for user's location to center the map (the marker will be placed at 0,0 - this needs to be changed in future release as 0,0 is not a good default).
