### ISSUE TITLE
schema.org markup for hidden data is not correct

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#167]
This is wrong:
```
<span itemprop="startDate" content="2015-11-12T20:00:00Z"></span>
<span itemprop="endDate" content="2015-11-12T21:00:00Z"></span>
```

1. SPANs should be used only with visible information and shouldn't be empty
2. Dates, times, and durations: use the time tag with datetime
3. Missing/implicit information: use the meta tag with content

So a better choice here is to find a page fragment where the date and time are written for the user as well or, if missing, use the meta tag.

See: http://schema.org/docs/gs.html

**Comment by pieroit** [comment]
verified from the browser
