### ISSUE TITLE
WP shortcodes in timeline contents

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#168]
WP shortcodes are shown in timeline contents, e.g.:

![pasted image at 2015_11_12 16_30](https://cloud.githubusercontent.com/assets/11438/11120781/be7f5c2c-895a-11e5-82ee-ed4367cbd986.png)

from here:
http://test.wordlift.it/entity/arriva-la-porchetta-ad-ariccia/

**Comment by pieroit** [comment]
verified from the UI
