### ISSUE TITLE
non events may be returned by the `Wordlift_Schema_Service.get_events` method

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#169]
When an entity type is changed for an entity, the old properties are not erased. So if I switch an Event to, let's say, a Person, that person might still have some event's properties set.

This affects the query `get_events` in the `Wordlift_Timeline_Service` which might return the person:

			'meta_query'     => array(
				'relation' => 'AND',
				array(
					'key'     => Wordlift_Schema_Service::FIELD_DATE_START,
					'value'   => null,
					'compare' => '!=',
				),
				array(
					'key'     => Wordlift_Schema_Service::FIELD_DATE_END,
					'value'   => null,
					'compare' => '!=',
				)
			)

**Comment by pieroit** [comment]
verified from the UI
