### ISSUE TITLE
Disable entity editing in disambiguation widget for internal entities.

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#170]
Remove the Edit Description when the entity is already in the local vocabulary and add a link to the edit page for that entity instead.

Remove also - for these entities that are already in the vocabulary the information on the Entity Type, the Entity Id and the Entity sameAs.

![schermata 2015-11-13 alle 13 42 11](https://cloud.githubusercontent.com/assets/1022181/11149174/71f282ea-8a21-11e5-87f5-bf387802f8fc.png)

**Comment by pieroit** [comment]
Entity already saved: 
![image](https://cloud.githubusercontent.com/assets/6328377/11528247/d4b1ae88-98e5-11e5-9d35-d55161f8b0bd.png)

New Entity form RL:
![image](https://cloud.githubusercontent.com/assets/6328377/11528268/fa5b5530-98e5-11e5-9f0f-b0911ba28dcb.png)

Verified on test.wordlift.it

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
