### ISSUE TITLE
videos in iframe doesnt work

### ISSUE THREAD

**Issue by elmeligy** [insideout10/wordlift-plugin#1708]
### Issue Description

When using the Classic Editor in WordPress to embed a YouTube video inside an iframe, the WordLift plugin fails to detect the video. This is problematic for users - that are using Classic editor, that need to re-size the video embed and  who rely on WordLift to automatically analyze and enrich their video content.

#### Expected Behavior

When a YouTube video is embedded in a WordPress post using the Classic Editor, WordLift should automatically detect the video and offer relevant options for content enrichment and SEO optimization.

#### Current Behavior

WordLift does not detect the YouTube video when it is embedded within an iframe using the Classic Editor.

#### Steps to Reproduce

1. Open WordPress and navigate to the Classic Editor to create a new post.
2. Embed a YouTube video using the iframe tag.
3. Save or publish the post.
4. Open WordLift and try to analyze the post for content enrichment.

#### Example Code

Here is an example of how a YouTube video might be embedded in a WordPress post using the Classic Editor:

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allowfullscreen></iframe>
```

Replace `VIDEO_ID` with the actual video ID from YouTube.

#### Possible Solutions

- Update WordLift's content analysis algorithms to recognize iframe tags containing YouTube URLs.

#### Impact

Failing to detect embedded videos can lead to less effective content enrichment and SEO optimization, which could potentially affect website traffic and user engagement. 

#### Additional Information

This issue seems to be specific to the Classic Editor and does not occur when using the Gutenberg editor.

By addressing this issue, WordLift can offer a more comprehensive and automated solution for content creators who still prefer using the Classic Editor.

client : https://www.famelounge-ps.com/
post to check : https://www.famelounge-ps.com/wp-admin/post.php?post=31381&action=edit
WP version : 6.3

**Comment by ziodave** [comment]
Yeas, it's meant to work only when embedded according to WordPress official documentation
