### ISSUE TITLE
Entity listing - add related posts counter

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#171]
In the backend, add the # of related posts as custom column within entity posts listing

**Comment by mcolacino** [comment]
For the issue **1** we have to understand if have the new column *sortable* is a requirement or not: if it is, we have to choose how to implement it. We have (at least) *two options*
1. we can pre-calculate the total number of related posts and save the results on the db: it's the approach  natively used for *comments count* sortable columns
2. we can calculate at runtime *hacking* the main wp query trough the [posts clauses filter](https://codex.wordpress.org/Plugin_API/Filter_Reference/posts_clauses). This is why it's needed a custom join with the *wl_relation_instances* custom table.

**Comment by mcolacino** [comment]
Also for the issue **3** we have to consider if we need to pre-calculate the value or calculating it at runtime during the filtering: the first option allows better performances during the filtering but at the same time potentially introduces sync issues.

**Comment by ziodave** [comment]
For issue 1, this is the right way to do it (let's open a new issue for this specific implementation):

we can pre-calculate the total number of related posts and save the results on the db: it's the approach natively used for comments count sortable columns

**Comment by ziodave** [comment]
For issue 3, also it's better to "precalculate" it. Let's open a separate issue where we can discuss the implementation.
