### ISSUE TITLE
Remove WordLift upper-right corner icon

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#173]
![schermata 2015-11-14 alle 23 25 33](https://cloud.githubusercontent.com/assets/1022181/11166122/84104de8-8b27-11e5-88be-45930747a80d.png)

**Comment by pieroit** [comment]
Admin bar deleted, and removed duplicate from the WL utility pages in the left sidebar

![image](https://cloud.githubusercontent.com/assets/6328377/11304736/ab6e09bc-8fa9-11e5-88d5-0f2a2f8830b6.png)

**Comment by pieroit** [comment]
verified by @cyberandy

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
