### ISSUE TITLE
Remove performance analysis menu item

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#174]
![schermata 2015-11-14 alle 23 30 37](https://cloud.githubusercontent.com/assets/1022181/11166128/c582fe24-8b27-11e5-8ccd-7113e4f77a13.png)

**Comment by pieroit** [comment]
see #175

**Comment by ziodave** [comment]
I am removing the resolved label because I'd like to further discuss this one.

**Comment by ziodave** [comment]
I removed the actual code.

**Comment by pieroit** [comment]
verified by @cyberandy

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
