### ISSUE TITLE
Remove SPARQL queries menu item

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#175]
![schermata 2015-11-14 alle 23 32 26](https://cloud.githubusercontent.com/assets/1022181/11166136/08942648-8b28-11e5-8b0d-b3c2e61636ca.png)

**Comment by pieroit** [comment]
SPARQL Queries and Performance Analysis are hidden from the UI

![image](https://cloud.githubusercontent.com/assets/6328377/11301750/9f9dcac4-8f99-11e5-9c55-8146d49b3aab.png)

**Comment by ziodave** [comment]
I am removing the resolved label, because I'd like to further discuss this one.

**Comment by ziodave** [comment]
I removed the actual code.

**Comment by pieroit** [comment]
verified by @cyberandy

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
