### ISSUE TITLE
Remove the option "color coding on front-end"

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#176]
Remove the option “color coding on front-end” from the Wordlift Configuration Page
![schermata 2015-11-14 alle 23 34 36](https://cloud.githubusercontent.com/assets/1022181/11166152/f8c437e8-8b28-11e5-8d09-809f6a956bb1.png)

Ensure that backend text annotation html markup is safely cleaned during the the frontend content rendering even if the schema.org markup replacement fails.

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11527957/315d332a-98e4-11e5-8364-dfc82923a058.png)

Verified on test.wordlift.it

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
