### ISSUE TITLE
Fix WL admin notices

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#177]
1. Uniform all color coding for all admin notice using WL brand color
2. Check translations consistency between IT and EN
3. Change the WL key admin notice message in order to better clarify that WL keys are still not available and asking to join the WL newsletter
4. Include in WL the class https://github.com/insideout10/helixware-mico-plugin/blob/develop/src/admin/class-helixware-mico-notice-service.php

![schermata 2015-11-14 alle 23 49 07](https://cloud.githubusercontent.com/assets/1022181/11166186/6094a064-8b2a-11e5-88ff-fc778c16022a.png)

**Comment by ziodave** [comment]
Point 3 has been resolved with #183

**Comment by ziodave** [comment]
Point 1 is done (added class `wl-notice` that can further be customized via CSS).
Point 2 should be reviewed in translations.
Point 4 is done.

**Comment by pieroit** [comment]
Working on #195 in order to confirm this.

**Comment by pieroit** [comment]
#195 resolved

Point 1 verified, all notices have the `wl-notice` CSS class
Point 2 translation present for the missing key notice but not for the duplicated title (which is appended to the DOM via js, so no PHP translation is not called)
Point 3 verified on test.wordlift.it
Point 4 verified in the codebase

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
