### ISSUE TITLE
Add WordLift in the naming of the Metabox

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#178]
![schermata 2015-11-14 alle 23 51 15](https://cloud.githubusercontent.com/assets/1022181/11166192/a607ae20-8b2a-11e5-8cba-f91993754bad.png)

**Comment by ziodave** [comment]
I am removing the resolved label, I'd like to discuss further the implementation of this one.

**Comment by pieroit** [comment]
verified by @cyberandy

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
