### ISSUE TITLE
 Faceted search widget NOT working on 3.1.*

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#179]
We've spotted this bug yesterday on test.wordlift.it (see here: http://test.wordlift.it/entity/castelluccio-norcia/) 

![image](https://cloud.githubusercontent.com/assets/837037/11236272/95276f7c-8dd8-11e5-80b0-8461e232dab2.png)

The same bug is also present in 3.1.2 and it is urgent as all installations are affected.

**Comment by ziodave** [comment]
pushed online 3.1.3
