### ISSUE TITLE
Adding the possibility to add/edit alternative labels for entities

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#181]
When creating a new entity (following the way the system already works for entities already available in DBpedia) we shall give the user the option to add and edit alternatives labels. 

An example - where this becomes **very important** - is when the name of an entity like `Geographic Information Systems` is commonly abbreviated with the initial letters as `GIS` (acronym). 

Rather than creating two separate entities and matching them by sharing the same `sameAs`attribute we shall let the user add the acronym as an alternate label (and these shall be multiples). 

Alternate labels (as seen already) shall be processed in the analysis so that `GIS`and `Geographic Information Systems` are equally recognised.

**Comment by geospatialmedia** [comment]
Hey Andrea, thank you adding this!

**Comment by ziodave** [comment]
This has been merged to develop, however we need to add unit tests and merge the CSS/JS code in the related files.

**Comment by pieroit** [comment]
verified by @cyberandy

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
