### ISSUE TITLE
Missing ShareThis on entity pages

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#184]
On http://taoroma.it/ the editor noted that entity pages like this one http://taoroma.it/entity/laozi/ don't automatically inherit the social sharing buttons provided by ShareThis as it happens with articles: 

![image](https://cloud.githubusercontent.com/assets/837037/11318379/039f892a-9050-11e5-85ca-e9303889b462.png)

Here is an article: http://taoroma.it/qi-gong-con-gli-alberi-5-elementi/#sthash.J4kMfXn0.dpbs

Here are the script tags on the article page:
```
<script charset="utf-8" type="text/javascript">var switchTo5x=true;</script>
<script charset="utf-8" type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script charset="utf-8" type="text/javascript">stLight.options({"publisher":"3f12e4ff-67c7-46f1-b69b-1831b88e7cdc","doNotCopy":false,"hashAddressBar":true,"doNotHash":false});var st_type="wordpress4.3.1";</script>
```
and here are the HTML tags:
```
<span class='st_sharethis_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
<span class='st_pinterest_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
<span class='st_plusone_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
<span class='st_fblike_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
<span class='st_linkedin_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
<span st_username='taoroma' class='st_twitter_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
<span class='st_facebook_large' st_title='<?php the_title(); ?>' st_url='<?php the_permalink(); ?>'></span>
```
While this can be seen as an enhancement the missing sharing button are perceived as crucial to start disseminating entity pages over social network.

**Comment by ziodave** [comment]
The problem is that that ShareThis plugin specifically activates itself on `post`s and `page`s, `sharethis.php#310`:

    if(($post->post_type == 'page' && !in_array($post->ID , $selectedPage)) || $post->post_type == 'post') {

**Comment by ziodave** [comment]
I added a service which checks whether ShareThis is present and hooked. If so, it'll disguise the entity as a post and call [ShareThis](https://wordpress.org/plugins/share-this/) (100,000+ active installs).

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/11527853/a0f3303c-98e3-11e5-8877-4ee21a04b782.png)

Verified on test.wordlift.it

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
