### ISSUE TITLE
Default permalink structure in WP 4.3 makes local entity URLs to 404

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#187]
Instructions to repeat the error:
* install a WP 4.3
* install WL (develop 3.2.0)
* set WL key
* create and annotate a post
* go on the entity editor page
* click on the `View Entity` button ---> 404

Default permalink structure is
![image](https://cloud.githubusercontent.com/assets/6328377/11445987/adb8c31e-9531-11e5-8cf2-b45cf361f26e.png)

* If you choose any other permalink structure it starts to work again. If you *go back to default permalink structure*, it still works.

This may have something to do with the default permalink structure, not with the structure in itself but with any default.

**Comment by ziodave** [comment]
@pieroit with a vanilla WordPress I am unable to reproduce it. This is the default permalink structure on a freshly installed WordPress:

![screenshot 2015-11-29 10 00 32](https://cloud.githubusercontent.com/assets/11438/11455992/15ae9d46-9680-11e5-8832-f1ae1e48e668.png)

I will now try "Day and name".

**Comment by ziodave** [comment]
@pieroit changing to "Day and name" yields "Not found".
