### ISSUE TITLE
Entity recognition is not working when I use bullet points 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#189]
In this post http://test.wordlift.it/2015/11/30/this-is-a-blog-post/ I'm mentioning two custom _event-entities_ and the entity recognition works when I have one event after the other but does NOT work when I use the bulletin points to organise the two events in a list (_see image below_):  

![image](https://cloud.githubusercontent.com/assets/837037/11469310/b31dbee2-9755-11e5-8d65-5e3b12aa9802.png)

**Comment by mcolacino** [comment]
The issue is not only related to custom entities, as proofed by the example below
![schermata 2015-12-02 alle 21 29 54](https://cloud.githubusercontent.com/assets/1022181/11543289/1436e860-993c-11e5-90c1-d9fc36eaad74.png)

**Comment by mcolacino** [comment]
The problem is due in how the Traslator manages <li> tags ... That text is passed to Redlink as 
![schermata 2015-12-02 alle 21 54 33](https://cloud.githubusercontent.com/assets/1022181/11543912/7047130c-993f-11e5-9a26-edbe2f0db51c.png)

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
