### ISSUE TITLE
Semantic Analytics with WordLift - How to Track Performance and ROI with WordLift entities

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#190]
The scope of this issue is to summarise the implementation required to implement **Semantic Analytics** using WordLift. This concept - first introduced by Mike Arnesen in this blog post [here](https://moz.com/blog/semantic-analytics) - can be explained as follows: 

![image](https://cloud.githubusercontent.com/assets/837037/11469403/6b0324fc-9756-11e5-9f26-dc1df9ab86ed.png)

Using WordLift, the initial implementation can be done as follows: 
- 1. Generating a .CSV file by extending the work done for MICO with the `admin-ajax.php?action=wp5_export`export function (this returns a json including `post id`, `post body`, `post entities > who`, `post entities > what`, `post entities > when`, `post entities > what`) 
- 2. Adding two custom dimensions in the Google Analytics profile (any website using WordLift can be used for testing): `ga:Entity` `ga:W`
- 3. Importing the generated .CSV in as Data Set in Google Analytics (type: _Content Data_) and use as _Key_ for matching the internal with the .CSV file `ga:pagePath`
- 4. Visualising performance and ROI using WordLift entities instead of pages 

The .CSV shall be structured as follows: 

| ga:PagePath | ga:Entity | ga:W |
| --- | --- | --- |
| http://mywebsite.com/this-is-a-test | save_the_arctic | thing |

**Comment by mcolacino** [comment]
Here more info about CSV supported format
https://support.google.com/analytics/answer/6014981

**Comment by cyberandy** [comment]
Please refer to #552

**Comment by cyberandy** [comment]
Right now we support standard permalinks only and we shall extend the support to any type of permalink. For this reason, I will re-open the issue.
