### ISSUE TITLE
display an error when geocoordinates are invalid

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#193]
This is easy to reproduce - here are the steps: 
- create an entity 
- set the type to `Place` or `LocalBusiness`
- add wrong geocoordinates 
- update the entity 

After saving (pressing the _Update_ button) data is NOT stored (see below). 
![image](https://cloud.githubusercontent.com/assets/837037/11497907/5b90dc82-981c-11e5-803b-d578ce2afa53.png)

This is probably due to the fact that if the coordinates are wrong they simply are removed from the metaboxes. Adding an error message might help here.

**Comment by ziodave** [comment]
@cyberandy can you make an example of geocoordinates you're setting? are you using the dot (.) or the comma (,) as decimal separator?
