### ISSUE TITLE
Tedious newline bug

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#194]
To reproduce this one: 
- write a sentence on a single line ending with an entity 
- save the post
- try to add a word AFTER the last entity on that same line and you will face this problem 
![image](https://cloud.githubusercontent.com/assets/837037/11498444/c2fda776-981f-11e5-8ebe-799a1c27644a.png)

Everything you write is included within the entity `<span>` tag that remains open. 

![image](https://cloud.githubusercontent.com/assets/837037/11498503/207db454-9820-11e5-84a7-a3a01abc0b20.png)

**Comment by mcolacino** [comment]
contenteditable=false on annotation span could resolve

**Comment by mcolacino** [comment]
Fixed in 3.2.1

**Comment by ziodave** [comment]
v3.2.1 published to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
