### ISSUE TITLE
Duplicated entity notice not present on test.wordlift.it

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#195]
Can't repeat the error on my local installation, but on test.wordlift.it the notice is not present.

Local:
![image](https://cloud.githubusercontent.com/assets/6328377/11529885/43c4e38a-98f0-11e5-8a30-2ff9a23382d0.png)

test.wordlift.it
![image](https://cloud.githubusercontent.com/assets/6328377/11529927/9feb05ae-98f0-11e5-97fe-6e4020706f13.png)

It's necessary to fix this in order to confirm the resolved #177.

**Comment by ziodave** [comment]
v3.2.0 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
