### ISSUE TITLE
Unexpected annotations with no entity matches

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#198]
Sometimes - it's a random behaviour - we have unexpected annotations with no entity matches from the analysis ... These annotations are not consistent, so they are skipped producing the following results
![schermata 2015-12-03 alle 17 17 05](https://cloud.githubusercontent.com/assets/1022181/11566258/e3d14b56-99e1-11e5-85a2-29c897c1dffc.png)

**Comment by mcolacino** [comment]
The issue seems to be related to a WLS bug in processing Redllink response.

**Comment by ziodave** [comment]
Solved with WLS 1.2.1.
