### ISSUE TITLE
New entity form is still visible with undefined current text annotation

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#200]
When the user clicks to deselect the current text annotation the form is not properly hidden as expected
![schermata 2015-12-04 alle 12 23 10](https://cloud.githubusercontent.com/assets/1022181/11588583/f60105a0-9a81-11e5-920f-abe69f5f523d.png)
![schermata 2015-12-04 alle 12 25 09](https://cloud.githubusercontent.com/assets/1022181/11588595/1b6c5cd6-9a82-11e5-90cd-b5f805afad7d.png)

**Comment by mcolacino** [comment]
Fixed in 3.2.1

**Comment by ziodave** [comment]
v3.2.1 published to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
