### ISSUE TITLE
Entity Page with a blank space on the top 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#202]
This issue is specific to one of our testers that is using PrimaShop for Woocommerce (http://www.primathemes.com/products/primashop-for-woocommerce/). Entity pages like http://www.sartoriascavelli.it/entity/ermenegildo-zegna/ have an empty space on the top.
![image](https://cloud.githubusercontent.com/assets/837037/11625516/deb822be-9cdb-11e5-9165-bb3a02ce41ef.png)

This is probably some settings on the theme that prevent the slider to appear. 
See the slider in action in one of their blog posts instead: http://www.sartoriascavelli.it/abiti-eleganti-e-impeccabili-ermenegildo-zegna/

![image](https://cloud.githubusercontent.com/assets/837037/11625683/0be547ca-9cdd-11e5-96b5-70ebe826455c.png)

**Comment by cyberandy** [comment]
I can start having a look at the theme settings.

**Comment by cyberandy** [comment]
The problem seems related to the fact that _entity pages_ don't inherit from the theme two layout modules: 
- Content Settings
- Header Settings

![image](https://cloud.githubusercontent.com/assets/837037/11625836/41e583ac-9cde-11e5-8963-531c7d4429c0.png)

The second one allows the editor to configure the slider. 
![image](https://cloud.githubusercontent.com/assets/837037/11625854/4c1b8196-9cde-11e5-9bc7-34dcd48fdcc6.png)

**Comment by ziodave** [comment]
This happens because in the (theme) code the slider is displayed only if the header type is set to `slider`, while for entities it's `image-default`.

**Comment by ziodave** [comment]
The function `prima_header_featured_from_page` returns a header of type `slider` for normal posts and an empty one for entities.

**Comment by ziodave** [comment]
The function `prima_get_post_meta( "_prima_header_featured", $page_id )` returns a header of type `slider` for normal posts and empty for entities.

**Comment by ziodave** [comment]
v3.2.3 published to [wordpress.org/extend/plugins/wordlift](http://wordpress.org/extend/plugins/wordlift)
