### ISSUE TITLE
Alternative labels are duplicated among two separated entities.

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#203]
The case can be reproduce here as follows: 

1. let's create two entities: 
 - **Knowledge**
 - **Knowledge representation** (a.k.a. _Knowledge representation and reasoning_)

2. let's add the alternative label **KR** to **Knowledge representation**
![image](https://cloud.githubusercontent.com/assets/837037/11628263/d4ffa264-9cf0-11e5-901b-ecb2081a3684.png)

3. **KR**, as alternative label, has now mistakenly added also to the entity **Knowledge** and this is wrong
![image](https://cloud.githubusercontent.com/assets/837037/11628283/f47ad136-9cf0-11e5-9bfc-aaa94214b4db.png)

I could not reproduce this behaviour on test.wordlift.it but I can reproduce it on blog.insideout.io/en

**Comment by ziodave** [comment]
v3.2.2 pushed to [https://wordpress.org/plugins/wordlift/](https://wordpress.org/plugins/wordlift/)
