### ISSUE TITLE
Bold formatting is not working on entity annotations 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#210]
Easy to be reproduced (and yes, we need a lot of testers like @matteoc): 

- Write a sentence containing at least one entity 
- Let the analysis run 
- Highlight few words including the entity being detected
- Select the **Bold**

![image](https://cloud.githubusercontent.com/assets/837037/11695089/ab67b914-9ead-11e5-88c6-7d0a1cf75a12.png)

What happens is that - regardless of the selection of the entity (is it correct or not?) the editor CANNOT apply the **Bold** formatting to entities. 

This is a strong limitation and shall be quickly fixed.

**Comment by mcolacino** [comment]
Text annotations **are not editable** - *contenteditable=false*. 
This behaviour was introduced to salve a previous bug (see issue #194).

A workaround here could be:
1. remove the text annotation
2. rewrite the text
3. apply the bold and save
4. disambiguate the text annotation.

**Comment by cyberandy** [comment]
@mcolacino thx for your feedback here. 
@matteoc this can be a quick solution to go live with the blog post while we think of any other possible alternatives. I've tested the workaround and it works just fine (see below). 

![image](https://cloud.githubusercontent.com/assets/837037/11698856/4af0c53a-9ec1-11e5-9f48-389a5f363cc8.png)

**Comment by matteoc** [comment]
Workaround is rather un-practical in my case as my whole article is full of bold phrases.
I temporarily disabled the wordlift plugin, published the post and then re-enabled it.
I have thus lost the entity but will restore once the bug is fixed.

**Comment by ziodave** [comment]
IMHO we should rollback #194 to solve this issue, and think about another solution to #194.

**Comment by mcolacino** [comment]
If you think it's so blocking (ad it seems so looking at @matteoc feedback) I agree with @ziodave

**Comment by mcolacino** [comment]
Fixed on 3.2.4
