### ISSUE TITLE
Adding support for the Accelerated Mobile Pages (AMP) on WordLift Entity Pages

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#212]
AMP is a Google open source initiative that makes it easy for news publishers to create mobile-friendly content once and have it load instantly everywhere (https://www.ampproject.org/). 

The implementation is HTML based and Automattic has created its WordPress plugin for adding AMP support (the plugin is available on: https://github.com/Automattic/amp-wp/). The plugin is still an early stage version as we can read on GitHub. 

> Developers: please note that this plugin is still in early stages and the underlying APIs (like filters, 
> classes, etc.) may change.

Boosting entity pages with AMP can further optimise the ranking over Google and increase the quality of the user experience. 

While this is definitely not a top priority it is something worth considering for helping bloggers and publishers boost search impressions.

**Comment by cyberandy** [comment]
![image](https://cloud.githubusercontent.com/assets/837037/13291914/f4ced904-db19-11e5-868f-95cbfa93090a.png)
AMP have been [launched by Google](https://searchenginewatch.com/2016/02/23/google-has-launched-accelerated-mobile-pages/?utm_source=Search+Engine+Watch&utm_campaign=4424f11427-24_02_2016_NL&utm_medium=email&utm_term=0_e118661359-4424f11427-16938421).

**Comment by ziodave** [comment]
The amp is out of beta, we need to ensure that we integrate/support the amp plugin ("do not reinvent the wheel").

**Comment by cyberandy** [comment]
OK - I've installed the Automattic AMP Plugin on the EN IO10 Blog - unfortunately the plugin only supports posts; it doesn't support archives, pages and, most importantly **our entity pages**. 
See here:

- http://blog.insideout.io/en/2015/10/science-fiction-movies-on-the-linked-data-cloud/amp/ (`supported`)
- http://blog.insideout.io/en/entity/artificial-intelligence/amp/ (`not supported` - and redirected to the original source)

**Comment by cyberandy** [comment]
![image](https://cloud.githubusercontent.com/assets/837037/13314978/545917a2-dba8-11e5-9dc8-8bcc6f58a024.png)

Qui si vede come appare il nostro navigator - su AMP (http://blog.insideout.io/it/2016/02/10/il-primo-wordlift-hackathon-del-2016/amp/). Anche questo aspetto va verificato.

**Comment by cyberandy** [comment]
One more reason to work on this issue: http://digiday.com/platforms/pitch-deck-inside-googles-plans-give-amp-pages-prominence-search-results/

**Comment by cyberandy** [comment]
I've run other tests and now things look good on everything but our entity pages (we need to extend the support here).

**Comment by markkap** [comment]
Seems like there two plugins used for it, with the bigger one being the one by automattic. For it, according to its documentation https://github.com/Automattic/amp-wp/wiki/Custom-Post-Type-Support it should be easy to add support for entity pages. 

The other plugin https://wordpress.org/plugins/accelerated-mobile-pages/ probably has also a way to do that but I didn't see any explicit relevant mention.

Yoast btw, just integrates with the automattic one.

**Comment by gcuofano** [comment]
Hi @markkap @ziodave just to let you know we've one new client using AMP (in this case the plugin used is PageFrog that works also for Facebook Instant Articles, Google AMP, and Apple News). We can of course - once the work is done for the Automattic plugin suggest to use this rather than PageFrog.

**Comment by markkap** [comment]
@gcuofano I looked into integration with the PageFrog plugin, and it fells like it is abandoned right now https://wordpress.org/support/plugin/pagefrog/reviews/. Will hate to spend time to figure out how to integrate with something that probably will not be used in the future.

**Comment by cyberandy** [comment]
Hi @markkap no need to integrate with the PageFrog plugin. As soon as we add the support for the AMP Automattic plugin we will ask the client to switch from PageFrog to Automattic.
