### ISSUE TITLE
Allow different entities with the same label and different types (safely)

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#215]
The use case is presented in following screenshots: a *user can need to create more custom entities with same label and different schema.org types*. This **breaks** WL becouse the entity uri is composed only considering the label: the side effect is to create in this case just one entity overriding it's data 2 times.
 
![schermata 2015-12-21 alle 10 26 45](https://cloud.githubusercontent.com/assets/1022181/11927622/268fa70e-a7ce-11e5-88b4-256319b70f21.png)
![schermata 2015-12-21 alle 10 26 35](https://cloud.githubusercontent.com/assets/1022181/11927623/2690a1cc-a7ce-11e5-97ad-39c07160962b.png)
![schermata 2015-12-21 alle 10 26 19](https://cloud.githubusercontent.com/assets/1022181/11927624/269341ca-a7ce-11e5-9b2a-bb267aae96c9.png)

**Comment by mcolacino** [comment]
As described, the issue is related to how the *entity_uri* is defined at the moment. Just the *label* is used to compose the uri: this means that different entities with same label and different schema.org types  has **the same entity uri**. An obvious fix can be to consider both label and *schema.org* type in entity uri generation. Entity uri is also used to check if an entity already exists in internal vocabulary or not. This means that the *wl_get_entity_post_by_uri()* method has to be fixed mantaining a retrocompatibility with already existings entities already created on active installations that have a *label-only* generated uri,

**Comment by cyberandy** [comment]
Probably adding a unique identifier in the _entity_uri_ is another option that can eventually be combined with the _type_ (_type_ alone might not be enough). 

`/id/{type}``

Both Wikidata and Freebase use their internal ID in the IRI path (https://www.wikidata.org/wiki/Q15428819 | https://www.freebase.com/m/0kybkd_) 
 
Here I found something on the topic https://data.gov.uk/resources/uris

**Comment by mcolacino** [comment]
@cyberandy the identifier could create issues for already existing entities detection ... But we can investigate also in this direction for sure.

**Comment by mcolacino** [comment]
As we discussed in the hackathon the final solution is to continue to use the label to compose the uri appending an *integer* when a given uri already exists. **In this way we could also support multiple entities with same label and same type** (entities synonyms).
 
@cyberandy @ziodave there is only  a warning about this approach: we are supposing the the entities match within the analysis cannot fault and we know that it's not so true indeed.

I suggest to deploy this change together with a UI enhancement for disambiguation widget: we have to suggest existing entities during the new entity creation workflow to avoid to create unexpected duplicated entities when the analysis fails in detecting internal entities in the post content.

**Comment by mcolacino** [comment]
as discussed with @ziodave we start with a first implementation that already use the counter but do not allow to create different entities with the same label and the same type. This to prevent unexpected duplicated entities also due to missing named entities in the analysis results.
