### ISSUE TITLE
Adding Geotagging to WordLift 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#217]
The target is to be able to geotag posts and pages by attaching a physical location to them via WordLift.
This functionality available on [WordPress.com](https://en.support.wordpress.com/geotagging/) can be added under the *WHERE* classification (see screenshot below) 

![image](https://cloud.githubusercontent.com/assets/837037/11928623/428c47bc-a7d5-11e5-8b65-3b7c82eb3dec.png)

Few details on this new features: 

* it is key for the launch as it will provide at least one _tag_ under _WHERE_ :+1: 
* we can use the geo location from the browser
* there is no need to match it against existing _entities_ of type _Place_
* for privacy reason it would be good to convert the geo coordinates into _City, Nation_
* there are two properties that can be used for describing the place where an article has been written in schema.org: 
  * https://schema.org/dateline (this one seems very appropriate but it expect a text and not a place)
  * https://schema.org/contentLocation (this one is somehow generic but it expect an actual place)

**Comment by mcolacino** [comment]
Here are my doubts about that:

* the current widget contains just things that also appears in content while the published date breaks this rule and makes the UI more inconsistent
* the WHERE accordingly to the 5W journalism classification (see here in italian https://it.wikipedia.org/wiki/Regola_delle_5_W) should be referred to the WHAT. It's the temporal context fro the WHAT. While the current location it's not directly referred to WHAT even if it can be meaningful to know where the content was published accordingly to the WHERE defined.
*If we see that current beta testers creates and uses not so many WHERE we should try to understand why this happens instead to find a workaround to assure at least a when can be provided.

**Comment by mcolacino** [comment]
Further https://schema.org/contentLocation could be added to the current LOD output for each referencing entity of type Place. I suggest to manage this enhancement as a separated issue.
