### ISSUE TITLE
Add the Publishing Time under WHEN in the WordLift Widget

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#218]
While today we're publishing as linked open data both `schema-org:datePublished` and `schema-org:dateModified` we shall make `schema-org:datePublished` visible under the **WHEN** in the WordLift Edit Widget (see below)  

![image](https://cloud.githubusercontent.com/assets/837037/11928995/f87ce7e6-a7d7-11e5-9351-802466691142.png)

Few details on this new features:

* it is derived from the WordPress publishing time (to edit the user shall use the _Publish Widget_ of WordPress - see below) 
* it is therefore **read-only** (the user cannot remove it nor change it from WordLift) 
* it is key for the launch as it will provide at least one tag under WHEN :+1:
* we are already publishing this piece of information along with the article's metadata - no need to make any changes there

Here is the _Publish Widget_ of WordPress that the editor can use to update this piece of information:
![image](https://cloud.githubusercontent.com/assets/837037/11929127/ce8130f4-a7d8-11e5-93ca-138c1d0fcf90.png)

**Comment by mcolacino** [comment]
Here are my doubts about that:
*  the current widget contains just things that also appears *in* content while the published date breaks this rule and makes the UI more inconsistent
*  the **WHEN** accordingly to the 5W journalism classification (see here in italian https://it.wikipedia.org/wiki/Regola_delle_5_W) should be referred to the **WHAT**. It's the temporal context fro the **WHAT**. While the publishing date it's not directly referred to **WHAT** even if it can be meaningful to know if a content has been published before, during, or after a given **WHEN** entity
* If we see that current beta testers creates and uses not so many **WHEN** we should try to understand why this happens instead to find a workaround to assure at least a when can be provided.
