### ISSUE TITLE
Missing image displayed in the WordLift Edit Widget

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#223]
To reproduce it: 

- create a blog post containing the following text "Use a color highlighter to ..."
- by opening the entity in the widget you will see that the widget uses the [missing image placeholder] (http://test.wordlift.it/wp-content/plugins/wordlift/public/images/missing-image-150x150.png) rather than the image itself (it seems to exist on [DBpedia](http://en.wikipedia.org/wiki/Special:FilePath/Highmark.jpg) in this case) or simply nothing.

![image](https://cloud.githubusercontent.com/assets/837037/12018643/c50ebd10-ad65-11e5-9a86-9fbd7d7e24c7.png)

Here is an example of entity with no image (this is correct of course - no need to display the image placeholder).

![image](https://cloud.githubusercontent.com/assets/837037/12018681/78a79bc6-ad66-11e5-9132-861b12c17dba.png)

**Comment by mcolacino** [comment]
@cyberandy, as I explained the image placeholder is a fallback used when the current image return a 404 http code ... In this case, the not founded image is https://upload.wikimedia.org/wikipedia/commons/5/5c/Highmark.jpg
And not https://upload.wikimedia.org/wikipedia/en/5/5c/Highmark.jpg that exists indeed

**Comment by mcolacino** [comment]
Please notice that you can see trough the browser console when and for what this fallback is in action
![schermata 2015-12-28 alle 17 16 17](https://cloud.githubusercontent.com/assets/1022181/12021419/e9c5358c-ad86-11e5-8899-e102f6df3129.png)

**Comment by mcolacino** [comment]
Further this is the only image related to that entity
![schermata 2015-12-28 alle 17 20 43](https://cloud.githubusercontent.com/assets/1022181/12021491/762b7dc4-ad87-11e5-95db-7ac6c79b3ee9.png)

**Comment by cyberandy** [comment]
Right so I see here two directions to follow: 

1- close this issue by simply replacing the placeholder with a single-pixel image (or by simply *not displaying the image when is not available*) 
2- create a new enhancement to retrive images from dbpedia when these are not found (in most cases there are multiple images for a given entity).

**Comment by mcolacino** [comment]
It's ok to consider this issue an *enhancement* on *wl-src* angular directive: this directive allows to define a callback image to be used when the main image return *404*. If a fallback is not defined the **new behaviour** will be to hide / delete the current *img* element. This new approach has to be used within the disambiguation widget where placeholders are not meaningful for editors expecting content suggestions.
