### ISSUE TITLE
Add article classification

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#229]
Together with the content classification already implemented we should offer article classification capabilities. **We should use "4W approach" both for content and article classification, but it's important to clearly split these 2 aspects within the UI**. What follows is a first real prototype we could start from.

![schermata 2016-01-08 alle 16 22 39](https://cloud.githubusercontent.com/assets/1022181/12201963/7c4cbec2-b627-11e5-8c82-31aa97b5380a.png)

Follows more implementation details:

1. **Author**. It's a **read-only** metadata. The property value is derived from **WordPress current user display name**. The editor can decide to publish this info into the LOD or not by checking the flag. This data is published by default.
2. **Publishing Place**. The editor can decide to **use his own current location* to populate this info. Once. This data is not published by default. If published into the LOD has to be mapped on https://schema.org/locationCreated. If an *entity* of type *place* with the same label exists within the internal vocabulary, that entity is used.
3. **Publishing Date**. It's a **read-only** metadata. The property value is derived from **current post published date**. The editor can decide to publish this info into the LOD or not by checking the flag. This data is published by default. If the post is not published yet this metadata will be blank.  
4. Also a **what* scope has to be added to manage *dbpedia* categories already available in RL analysis results as **dct:subject** properties. WLS data manipulation is required here to provide the most relevant *n* categories for the whole article.  

**This issue re-thinks previous open issues #217 and #218**.

**Comment by mcolacino** [comment]
Also a **WHAT** section could be added with topics coming from *dbpedia* via *RedLink*. See #109 comments for details about available topics

**Comment by mcolacino** [comment]
Here is an enhancement including also dbpedia category as WHAT
![schermata 2016-02-20 alle 20 32 52](https://cloud.githubusercontent.com/assets/1022181/13198741/3323470a-d811-11e5-94a7-227cd6721b9e.png)

**Comment by mcolacino** [comment]
**DbPedia categories** should be managed as a **custom taxonomy** in order to allow content filtering
https://codex.wordpress.org/Function_Reference/register_taxonomy

**Comment by mcolacino** [comment]
@cyberandy @david here there is another decision to take about *PublishingPlace" for *articles*. 

This is the use case at the moment:

1. the editor grants WL to retrieve his geolocation coordinates;
2. these coordinates are processed via google maps api in order to transform coordinates in a human readable place;
3. this reverse geocoding text result - ea: "Roma, Italia" is analyzed by WLS / RL;
4. a collection of suggested entities - of type *place* - is returned to the editor;
5. the editor can choose which place - tipically there is just one option - has to be used as *publishedPlace*.

**We can save this place entities wihtin the inner vocabulary (scenario 1) or not (scenario 2)**

**Scenario 1 - Pro** - we can save also entity metadata accordingly to the standard workflow. Please consider here that at least the label should be used in the backend widget.
**Scenario 1 - Pro** - we enhances the internal graph, allowing in the future new content discovery approaches.
**Scenario 1 - Against** - it is another entity creation task to be runned within *save_post hook* (at least until we go for the planned refactoring ad described in issue #157)

**Scenario 2 - Pro** - No entity creation task is required: we could save just the entity (external) uri as simple metadata. 
**Scenario 1 - Against** - We should define a way to save at least the entity label.

I suggest to go for the scenario 1. @ziodave @cyberandy what do you think?

**Comment by ziodave** [comment]
I think the first scenario (using the WordLift Vocabulary) instead of a WordPress taxonomy (scenario 2) is more appropriate for a couple of reasons:
 1. Topics are entities, i.e. they have labels, descriptions, thumbnails, ... most of these data we would loose using a WP taxonomy I believe (unless using some expedients)
 2. WordLift widgets are based on entities, and using WP taxonomy would inhibit reusing topics in most of the widgets or create an unnecessary overhead and complication in WL code in order to handle the Topics taxonomy
 3. Using entities for topics brings the same advantages we have with entities in terms of mark-up, SEO, interlinking, ...
 4. Using entities now and getting all the pros, doesn't prevent us from using taxonomies in the future.

**Comment by cyberandy** [comment]
All right - let me add my comments on this one. 

> We should use "4W approach" both for content and article classification, but it's important to clearly split these 2 aspects within the UI

Now as this is one UI requirements we shall discuss it more detailed and in a joint session - 

![image](https://cloud.githubusercontent.com/assets/837037/13564649/79bccb32-e44b-11e5-9b1b-652d47e26af9.png)

As for the time being having a _Show/Hide_ element can be a first step. The image above is from the WordPress.com editor (it also shows how the location is handled). 

> Scenario 1 - A custom taxonomy VS Scenario 2 - DbPedia topics are entities with their own metadata. 

Here it gets more complicated. Keeping the user at the center of the product design means providing **immediate solutions to problems** and **lower hanging fruits** (opportunities that translate  into measurable positive results). A taxonomy immediately enables to the end-user a **universal** (yes, this is the real value here - a meaningful way to benchmark contents by topics and within a larger system) content-filtering feature that translates into something like `/wl_topic/matematica` and probably a lot more. 

On the other hand - treating topics like entities - Scenario 2 - not only makes the product more consistent (as we'll always have entities in the end) but preserve the value and depth of the metadata. Here the questions are - **how do we differentiate on the vocabulary and on the discovery widgets (faceted search and navigator) an entity `type:topic` from all other entities?** - assuming we can work on answering properly this question and assuming we can have the taxonomy anytime soon - I would go for this second scenario.

**Comment by mcolacino** [comment]
@cyberandy about the visualization we have to use for the location, I don't think we should use a kind of map: the aim is not (only) retrieve geo coordinates, but an entity matching geo coordinates: this is why I would like to go with the current UI approach
About topic entities, I think that they should be managed as simple thing entities within the vocabulary
About the widgets I suggest to avoid to merge these entities with those one used for content classification.

**Comment by cyberandy** [comment]
Sure the map is not relevant in our case - we deal with entity. No need to
show a map right now.
