### ISSUE TITLE
Download Your Data from WordLift  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#230]
As seen in #105 WordLift provides a paid service and the ownership of the data remains of the user. 
It would be therefore important to let the user download the data associated with his/her own WordLift Key so that he/she can use it in another service or keep a copy for their own records.

To request this info we shall add a “Download your Data” as menu item under WordLift (just below the settings). 

Here we shall give the option to the user to choose the preferred format (json, xml, csv, tabs, ...) and to add an email where we will send the results or a link to download the dataset (as the processing might not be immediate for large graphs we need to ask for the email).

**Comment by cyberandy** [comment]
A first implementation here could be as simple as a `mailto:` link in the user dashboard (see #233). Something like - click here to ask for the raw data in CSV, JSON or XML format.

**Comment by mcolacino** [comment]
@cyberandy which email address we want to use?

**Comment by cyberandy** [comment]
support@wordlift.it would do.

On Monday, January 11, 2016, Marcello Colacino <notifications@github.com>
wrote:

> @cyberandy <https://github.com/cyberandy> which email address we want to
> use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insideout10/wordlift-plugin/issues/230#issuecomment-170699265>
> .
>


-- 


*Andrea Volpini*


*InsideOut10* <http://blog.insideout.io>
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>

**Comment by cyberandy** [comment]
Here we have a good update - we can add the link from day one in the dashboard. 

As documented at http://dev.redlink.io/api/1.0/#linked-data-endpoints, the API we are using already provides a method for dumping an entire dataset. 

You just need to send a GET to https://api.redlink.io/1.0/data/<DATASET>. 
Support is also provided in RL SDKs.

**Comment by mcolacino** [comment]
@ziodave is this api already proxied by WLS?

**Comment by ziodave** [comment]
Not yet :-)

David

**Comment by mcolacino** [comment]
I move this issue to 3.5 waiting for WLS proxy of needed RL api call

**Comment by ziodave** [comment]
The dataset is available from v1.3.0 onwards at the following end-point:
`/key={key}/dataset.{suffix}`

where `{key}` is the WordLift's key and `{suffix}` can be any of RL's supported outputs (e.g. json).

**Comment by ziodave** [comment]
I think we can move this to 3.7

**Comment by ziodave** [comment]
@mcolacino I'll take over :-)

**Comment by ziodave** [comment]
These should be the output formats we support: json, xml, tabs, csv
