### ISSUE TITLE
Introduce dom parsing to better remove text annotations

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#236]
The current implementation is based on a simple regex, but there are some limits. Ea: **text annotations containing not blank html markup are not properly detected**

The solution here is to refactor the code in order to use a more advanced **dom parsing** to perform this task.

See http://php.net/manual/en/domdocument.loadhtml.php 
and http://htmlparsing.com/php.html as implementation references.

**Comment by ziodave** [comment]
No more relevant. Feel free to reopen in case.
