### ISSUE TITLE
When editing an article all related entities disappear from the site (as they are set to DRAFT)

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#243]
As I was editing a new article on blog.insideout.io/en I noticed that **all entities being mentioned in the new article have been put as DRAFT and hence have disappeared**. 

This seems to be a minor issue but it can dramatically affect the site ranking. 
I can spend one or two days (and more) with my article in draft and I shall not affect the navigation on the site. 

In this specific case an entity page that brings already search traffic like http://blog.insideout.io/en/entity/wordlift is simply gone!

**Comment by mcolacino** [comment]
it's strange: at the moment if a published entity is used in a post draft, the publish status should be preserved for every published entity.

**Comment by mcolacino** [comment]
I found the issue ... it's a mispelling in the previous hotfix (3.0.10) and related tests :-) See here for tech details https://github.com/insideout10/wordlift-plugin/commit/3170a3c4a00112608c4ec044cffcb80084236b8c
@cyberandy stay tuned for a quick (meta) fix

**Comment by mcolacino** [comment]
it will be fixed in 3.3.3
