### ISSUE TITLE
Entity containing numerals don't work as expected

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#245]
To reproduce this one:

1. when editing a blog post
2. create an entity labeled _Appartamento9_
3. add it to the post 
4. save the post

**The entity disappears from the analysis' results** after saving. 
I've also noticed on our English blog another similar case where an entity's alternative label has a numeral and the analysis stops working (enity: _MICO_ alternativeLabel: _FP7-MICO_).

**Comment by ziodave** [comment]
I checked on the test web site, the entity wasn't published (still draft) therefore it wasn't public and not available for analysis.
