### ISSUE TITLE
Entities type:LocalBusiness cannot be used as Location for entities type:Event 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#246]
Here is the case. A local business is a place, in our testing _Appartamento9_ is an entity `type:LocalBusiness` and when I am creating an event that will take place at _Appartamento9_ I expect the entity _Appartamento9_ to be in the list but the list apparently only takes entities `type:Place`

**Comment by mcolacino** [comment]
@cyberandy looking at https://schema.org/Event it seems that LocalBusiness is not allowed as location
![schermata 2016-01-21 alle 22 50 18](https://cloud.githubusercontent.com/assets/1022181/12495701/87a76226-c091-11e5-9947-4ae8f2b2a7ae.png)

**Comment by mcolacino** [comment]
Fixed in 3.3.4
