### ISSUE TITLE
Entities type:LocalBusiness cannot be used as Affiliation for entities type:Person

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#248]
Here is the case. A local business is an organization, in our testing Appartamento9 is an entity type:LocalBusiness and when I am creating a person for the founder I expect the entity Appartamento9 to be in the list of the affiliation property but the list apparently only takes entities type:Organization.

**Comment by mcolacino** [comment]
Also in this case looking at the schema.org documentation https://schema.org/Event it seems that only Organizations are supported as Person affiliation
![schermata 2016-01-21 alle 22 52 47](https://cloud.githubusercontent.com/assets/1022181/12495764/e71dfe40-c091-11e5-8192-757b6a1397cd.png)

**Comment by mcolacino** [comment]
Fixed in 3.3.4
