### ISSUE TITLE
Featured image missing on the linked data representation of an entity   

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#249]
Here is the case. The entity diego http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl050/entity/diego has a featured image (see screenshot below) but the image is missing in the metadata on _data.wordlift.it_
 
![5caea27fc192bb8bdc18ef9adf82a422d6086cfe9454515ce9pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/837037/12515813/75a7a7f4-c12a-11e5-8863-259536685cff.jpg)

**Comment by mcolacino** [comment]
@cyberandy I tested 2 different workflow without being able to reproduce the issue. The thumbnail url is properly updated on RL side in these 3 use cases:

1. The entity is already published and the editor sets the thumbnail from the entity edit post page
2. The entity is still in *draft*. The editor sets the thumbnail from the entity edit post page and then make the post *publish*
3. The entity is linked to a given post during the annotation process. After that the post is saved.

Here it could be useful to have the exact uri for the missing image in order to try to reproduce exaclty the same use case.

**Comment by mcolacino** [comment]
Further looking at the code we should be able to find something the the log when the thumbnail update on RL fails ... See here for more details: https://github.com/insideout10/wordlift-plugin/blob/master/src/includes/class-wordlift-thumbnail-service.php#L121 ... At the moment the log seems to be disabled or at least not available on http://www.appartamento9.it/wp-content/debug.log

**Comment by cyberandy** [comment]
Here it is: http://www.appartamento9.it/wp-content/uploads/027-1.jpg

On Sunday, 24 January 2016, Marcello Colacino <notifications@github.com>
wrote:

> @cyberandy <https://github.com/cyberandy> I tested 2 different workflow
> without being able to reproduce the issue. The thumbnail url is properly
> updated on RL side in these 3 use cases:
>
>    1. The entity is already published and the editor sets the thumbnail
>    from the entity edit post page
>    2. The entity is still in *draft*. The editor sets the thumbnail from
>    the entity edit post page and then make the post *publish*
>    3. The entity is linked to a given post during the annotation process.
>    After that the post is saved.
>
> Here it could be useful to have the exact uri for the missing image in
> order to try to reproduce exaclty the same use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insideout10/wordlift-plugin/issues/249#issuecomment-174290256>
> .
>


-- 


*Andrea Volpini*


*InsideOut10* <http://blog.insideout.io>
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>

**Comment by mcolacino** [comment]
See #299
