### ISSUE TITLE
Unexpected proliferation of entities after editing the affiliation property of a person

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#251]
![image](https://cloud.githubusercontent.com/assets/837037/12608243/3e3b6a8a-c4db-11e5-88cd-e767f5da445c.png)

To replicate: 

- create an entity `type:person` 
- add in the text an entity `type:organization` (already present in your vocabulary)
- select the organization and save 

Everything is smooth until this point.   

- now add the same `type:organization` as _affiliation_ property of the entity `type:person`
- the following will happen: the entity `type:organization` is no longer recognised in the text and everytime you save various duplicates will be generated. 

This has been spotted recently on IO10 English Blog as well as on Appartamento9.

**Comment by cyberandy** [comment]
I've remove the duplicates from the vocabulary, and removed the affiliation link but every time I save the entity page a new entity for Insideout10 is created!

**Comment by cyberandy** [comment]
The same behaviour has been spotted also in http://camminandocon.org/ where an event has been re-created by WordLift 3 times.

**Comment by mcolacino** [comment]
@cyberandy (at least) this particular case seems to be not related to entity properties data entry: the duplication happens even if you try to associate the entity to the text ...

Further the entity uri in the text is **http://data.redlink.io/91/be9/entity/insideout_10** while the entity uri you can find associated to the entity is **http://data.redlink.io/91/be9/entity/insideout10**... This can be the origin of the issue ...

Further investigations are required here

**Comment by cyberandy** [comment]
On Camminandocon.org this bug can be seen on this page here: http://camminandocon.org/wp-admin/post.php?post=560&action=edit

**Comment by mcolacino** [comment]
Bug detected: entity uri is properly preserved on label update, but is overridden during the post content disambiguation. Further the old entity uri is set as *sameAs*: these 2 steps determines an inconsistency that come up with the entities duplication.

**Comment by cyberandy** [comment]
@mcolacino I would keep this one open as this behaviour is still present on http://blog.insideout.io/en that is running 3.4 (and I will check later on on the other two cases we have). 

Basically every time this article is saved http://blog.insideout.io/en/wp-admin/post.php?post=1188&action=edit regardless of the fact that the InsideOut10 entity is no longer selected, WordLift will create a copy of the InsideOut10 entity and it will duplicate the logo in the media library.
