### ISSUE TITLE
Focus problem with the calendar widget 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#252]
![image](https://cloud.githubusercontent.com/assets/837037/12608445/6dd9ed9c-c4dc-11e5-9519-e935d8a2ecec.png)

To replicate this simply: 
- create a property `type:person`
- add the birthday date 
- save 
- reload the edit page
- scroll down the edit page and **when scrolling down you will see that the date changes**

**Comment by mcolacino** [comment]
Fixed in 3.3.4
