### ISSUE TITLE
Introduce navigator and faceted search configuration

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#253]
1. Allow to configure **the widget title** (default: 'related articles')
2. Allow to decide to **hide facets displaying a toggle button instead** (default: *visible*)

**Comment by cyberandy** [comment]
This is issue has been _clearly brought up_ in the testing with Appartamento9. The need is to have a simpler visualization aligned with Taboola and Outbrain (see below) 

![image](https://cloud.githubusercontent.com/assets/837037/12746172/937861c6-c99d-11e5-9650-e6c63fa9629b.png)

**Comment by cyberandy** [comment]
For the Faceted Search Widget the requirements (as per #261) are: 
- reducing the number of entities displayed in the list by choosing the most relevant in a given context 
- add a _show/hide toggle switch_ (as in the previous version of this widget) to keep the widget as compact as possible

**Comment by mcolacino** [comment]
The first point is covered by #263 and included in WL 3.4.0
