### ISSUE TITLE
Timeline visualization problem

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#254]
On the timeline we shall provide the option to prevent the description of the event from being displayed in the widget. As in this case (http://camminandocon.org/index.php/archivio-escursioni/) the description is way too long and creates a **bad user experience**. 

![image](https://cloud.githubusercontent.com/assets/837037/12724606/f0a65658-c90e-11e5-9744-d5f6a602a6d9.png)

**Comment by ziodave** [comment]
This has been closed with #370 #373.
