### ISSUE TITLE
Conflicting Calendars prevent from adding startDate and endDate

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#256]
The case has been encountered on http://geobuiz.com/ and seems to be related with a conflicting library for handling dates in the `startDate`and `endDate` property of an entity `type:event`. 

When adding a date the following calendar displays: 
![image](https://cloud.githubusercontent.com/assets/837037/12778832/48a23bcc-ca65-11e5-8144-3e7a908f429b.png)

and replaces our ordinary one:
![image](https://cloud.githubusercontent.com/assets/837037/12779074/61b164a2-ca66-11e5-8b62-75c73129f533.png)

This seems to be a conflict with the calendar library in the theme of the site:
![image](https://cloud.githubusercontent.com/assets/837037/12779172/e22a630e-ca66-11e5-8ac4-7fb5efc2dfc4.png)

The issue is of high priority since when adding dates with the conflicting calendar these are not saved in the entity - therefore **events cannot be created** at this stage.

**Comment by mcolacino** [comment]
@cyberandy can we have access to the backend to better understand which is responsible for the overridden?

**Comment by mcolacino** [comment]
it's a conflict with the theme ... This file is responsible for the issue http://geobuiz.com/wp-content/themes/truemag/option-tree/assets/js/ot-admin.js

**Comment by mcolacino** [comment]
Fixed in 3.3.5
