### ISSUE TITLE
Faceted Search Widget it's way too invasive! 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#261]
![image](https://cloud.githubusercontent.com/assets/837037/12954041/41c56d8e-d01d-11e5-8149-116b6aab3265.png)
It's clear from this example that the new **Faceted Search Widget** (now accessible for both posts and entity pages) is way too invasive: **the UX shall be quickly revised**. 

On one hand reducing the entities displayed in the list becomes mandatory and on the other a _show/hide_ toggle switch (as in the previous version of this widget) could also help.

**Comment by mcolacino** [comment]
:-) we can add these requirements to #253
