### ISSUE TITLE
Posting a site URL on Google+ uses an entity title instead of the post title

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#262]
The issue has been spotted on the **appartamento9.it** website and more specifically on the editor's computer (I cannot replicate the behaviour on my computer). 

Basically for some reason when the editor clicks on the **sharing button** on this page http://www.appartamento9.it/villa-capezzana-carmignano-docg-2009/ rather than showing the title of the article (as it happens on my laptop - see image below)

![image](https://cloud.githubusercontent.com/assets/837037/12977847/9693bf36-d0cd-11e5-9bea-57daaf3f8fac.png)

the sharing widget (on all social networks) **displays the title of the detected entity page** (see image below)
![image](https://cloud.githubusercontent.com/assets/837037/12977865/b199dfd6-d0cd-11e5-94ba-0e646446f5a8.png)

this occurred after installing WordLift. It is not browser dependant as the editor tried with Firefox and with Chrome. The plugin being used is developed by https://www.shareaholic.com/. On the same computer the sharing provided by ShareThis on Tao Roma (http://taoroma.it/qigong-accosciata-squat/) works. 

So an easy fix would be for the editor to replace _Shareaholic_ with _ShareThis_.

**Comment by ziodave** [comment]
I can't reproduce the issue. I think it's not related to Shareaholic. From the screenshot it looks like the editor is going on plus.google.com and is trying to share the URL, is it?

**Comment by ziodave** [comment]
![image](https://cloud.githubusercontent.com/assets/11438/17975370/1711b244-6af2-11e6-8364-140bae335a4f.png)

**Comment by ziodave** [comment]
The issue is related to Google+ posts:

1. open plus.google.com,
2. post a URL, e.g. http://www.appartamento9.it/raimbow-honey/
3. the title of the page is "Social dinner" instead of "Raimbow honey | APPARTAMENTO9".

It appears that Google+ reads the _itemprop="name"_ of the first entity in the post body.

**Comment by ziodave** [comment]
Reference documentation for Google+: https://developers.google.com/+/web/snippet/article-rendering

**Comment by ziodave** [comment]
A tested solution could be to add ```itemscope itemtype="http://schema.org/Article"``` in the element enclosing the article and ```itemprop="name"``` where the article title is printed.

**Comment by cyberandy** [comment]
It's a good solution of course. What will happen with an entity page?

**Comment by ziodave** [comment]
Not sure yet, the problem is that there are no hooks in WP to do that, we should resort to response buffering and mangling, which might affect performance in some cases.

**Comment by ziodave** [comment]
We have a preliminary patch that handle posts by adding the schema.org microdata tagging. We should test this with care especially in presence of other SEO plugins which might attempt to do the same thing.

**Comment by ziodave** [comment]
I checked both Yoast SEO and SEO Ultimate, they don't do such a thing, so we shouldn't have any conflict.

**Comment by ziodave** [comment]
Hotfix published on appartamento9.it

**Comment by ziodave** [comment]
Test is successful on appartamento9.it
