### ISSUE TITLE
Replacing entity-pages with in-page contextual widgets

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#266]
As noted during the testing with **http://www.shoppersbase.com/**, on _large properties_ where the manual curation of the custom [vocabulary](http://blog.insideout.io/en/2016/01/introducing-wordlift-new-vocabulary/) might not be possible (mainly for time constraints) and, given _the existing amount of data_ WordLift provides for each entity (consisting of a featured image, [the abstract coming from DBpedia](http://dbpedia.org/ontology/abstract) and the `rdf:type` converted in schema.org along with other minor properties) the option of displaying **in-page widgets** rather than links to entity pages might be a valuable alternative.  

An interesting example here is the experiment known as [Knowledge Map](https://www.washingtonpost.com/pr/wp/2015/07/16/the-washington-post-tests-new-knowledge-map-feature/) of the Washington Post where concepts are highlighted in the page (see below) 
![image](https://cloud.githubusercontent.com/assets/837037/13056605/a9736a38-d416-11e5-992d-ef5f9d644dac.png)
when the user clicks on the concept a contextual widget appears on the articles' sidebar (see below)
![image](https://cloud.githubusercontent.com/assets/837037/13056660/f19920aa-d416-11e5-9faf-a7517be36974.png)

The widget typically contains: 
- a content type describing the widget  (Background, Theme, Technology, ...) 
- an image introducing the topic
- a title 
- an abstract of the topic 
- a list of related articles 

In the context of WordLift entity pages might remain on the site but simply:
- have a `no index` to disallow search engines from showing them in their results and 
- the links from the articles (that currently point to entity pages) shall be replaced with contextual widgets (or popups).

**Comment by ziodave** [comment]
Displaying the box on the sidebar is a mess, even of the Washington Post web site itself:

https://www.washingtonpost.com/world/national-security/islamic-states-embrace-of-social-media-puts-tech-companies-in-a-bind/2015/07/15/0e5624c4-169c-11e5-89f3-61410da94eb1_story.html?kmap=1&pr=1

![image](https://cloud.githubusercontent.com/assets/11438/18034023/da8ac2e8-6d3a-11e6-952e-3035252e85e1.png)

It's better to open a card inline in the content area, we found in the past other examples (I am trying to find them again).

**Comment by ziodave** [comment]
Can we recap a little bit what are the options here:

An _entity_ is ...
* non selected
* selected
 * linked to a page
 * linked to an inline bubble
 * non linked

Are there any other options in the _selected_ state?

Also is the state related to the?
1. entity as a whole
2. selection
3. single annotation

**Comment by novedavi** [comment]
Maybe we should open a different issue since showing the widget is a separate topic much further from the current need of not linking the entity?

**Comment by ziodave** [comment]
Following a conversation we had, the state is related to the page selection (so in a page all the states can be either "page links", "no links" or "inline links").

**Comment by wanbinkimoon** [comment]
## Show case
I have evaluated some option based on a series of real case scenarios. I think we can evaluate three main options:

1. **Block**: the entity content is displayed in a block using `details` tag which allows us to have a great compatibility out of the box and a pretty easy customisation for the user. BUT it kind of impose itself in the page. 😐  Here a GIF 

![entity in page opt 1](https://cloud.githubusercontent.com/assets/10087639/23548301/1fa26994-0007-11e7-9b09-79c901d3d7d4.gif)

2. **Inline** : the entity content is displayed inline and show and hidden using custom javascript or the checkbox hack in css (here some docs about it --- > https://css-tricks.com/the-checkbox-hack/). here a GIF of I expect the mechanism to work:

![entity in page opt 2](https://cloud.githubusercontent.com/assets/10087639/23548425/c3d28ec2-0007-11e7-8af8-2b39afff5bcf.gif)

3. **Pop**:  This mechanism has been used inspired by this medium feature 
![medium - interaction - annotation](https://cloud.githubusercontent.com/assets/10087639/23549214/67bf4612-000b-11e7-8c4c-d9e182fee78f.gif)
I think this option could cost a bit more in terms of testing and designing but the final result is way better
![entity in page opt 3](https://cloud.githubusercontent.com/assets/10087639/23549237/80c06a24-000b-11e7-99e8-1356edae1921.gif)
