### ISSUE TITLE
The posts counter in the dashboard displays NaN% instead than 0  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#269]
On **CamminandoCon** only pages have been so far annotated with WordLift and we're currently providing the wrong information in the Dashboard (the cake is full rather than empty and `NaN%` is not meaningful).   

![image](https://cloud.githubusercontent.com/assets/837037/13351310/16db157c-dc86-11e5-8636-6c980feec2e8.png)

A proposal would be: 

1- handle the `0` properly
2- revise the cake graph when `posts = 0`
3- eventually considering pages as well as posts as the total number of _annotated articles_

It is a limit case - therefore priority is low.

**Comment by mcolacino** [comment]
:-D
