### ISSUE TITLE
Simplify faceted widgets layout grid

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#274]
The grid can be further simplified to assure a more flexible layout
![schermata 2016-02-26 alle 19 31 04](https://cloud.githubusercontent.com/assets/1022181/13361539/9bd19fb0-dcbf-11e5-884a-cc7c02f6776f.png)

**Comment by mcolacino** [comment]
@cyberandy also the counter could be remove here: it's already used for entity sorting: it's no so important to display it too. what do you think?

**Comment by cyberandy** [comment]
Makes sense. Let's get rid of it.

On Friday, 26 February 2016, Marcello Colacino <notifications@github.com>
wrote:

> @cyberandy <https://github.com/cyberandy> also the counter could be
> remove here: it's already used for entity sorting: it's no so important to
> display it too. what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insideout10/wordlift-plugin/issues/274#issuecomment-189448907>
> .
>


-- 


*Andrea Volpini*


*InsideOut10* <http://blog.insideout.io>
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>

**Comment by mcolacino** [comment]
![schermata 2016-02-27 alle 11 55 48](https://cloud.githubusercontent.com/assets/1022181/13372575/21f561f6-dd49-11e5-935a-9868ae0be51d.png)
