### ISSUE TITLE
When creating a new entity the duplicate warning appears for entity that have been trashed

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#278]
The error "you already published an entity with the same name" ...

![image](https://cloud.githubusercontent.com/assets/837037/13393846/41e05830-dee4-11e5-854d-a498818d14ee.png)
Brings the user to an empty page since the entity is already in the trash!

![image](https://cloud.githubusercontent.com/assets/837037/13393860/642bd572-dee4-11e5-972e-ae0e353a8a4a.png)

The duplicated entity warning message shall not take in consideration entities that have been already trashed by the user. 

The message disappears when the entity is permanently deleted from the trash.

**Comment by mcolacino** [comment]
Maybe a better option could be here to suggest restoring the trash entity. What do you think?

**Comment by cyberandy** [comment]
@mcolacino yes this would be a better option

**Comment by ziodave** [comment]
The edit page calls the following AJAX end-point to detect existing entities:
wp-admin/admin-ajax.php?action=entity_by_title&title=_title_

There's also another issue here, i.e. the call is immediate, is not taking into the consideration that the user is typing (is sending a request per each keypress).
