### ISSUE TITLE
WordLift Editor Widget not showing on edit article

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#281]
![image](https://cloud.githubusercontent.com/assets/837037/13595173/7b855f42-e509-11e5-870f-1bdc4b50110c.png)

This has been spotted on http://www.seoultimateplus.com  and needs to be investigated. 
As we're running SEO Ultimate Plus v.1 and WordLift on our test blog it shouldn't be a direct conflict between WordLift and SEO Ultimate Plus.

**Comment by cyberandy** [comment]
The provided _activation key_ corresponds to graph `wl030` and it is properly configured.

**Comment by mcolacino** [comment]
@cyberandy if the editor is in text mode the analysis is not runned

**Comment by cyberandy** [comment]
Sorry @mcolacino I didn't notice that - ok - shall we add a simple warning somewhere - i.e. "Please make sure to use the editor in _Visual mode_ to use WordLift"?

**Comment by mcolacino** [comment]
yes it could be an enhancement

**Comment by wanbinkimoon** [comment]
WordLift should display a message explaining why the widget is collapsed

**Comment by wanbinkimoon** [comment]
We decided to use the message panel we already have, with a dedicated copy.
```
WordLift widget is active only in **visual mode**
```
