### ISSUE TITLE
Wrong entity URL 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#282]
While editing the article http://camminandocon.org/2016/03/geologia-della-valle-del-turano/ (with an initial cut&paste from Word of the entire article) WordLift created entities with the wrong URLs - see here few examples: 

![image](https://cloud.githubusercontent.com/assets/837037/13601082/b29f7822-e52d-11e5-95be-0b0d577daf57.png)

![image](https://cloud.githubusercontent.com/assets/837037/13601120/fe703372-e52d-11e5-8b40-edf3b945eec5.png)

Just to add a clue the text as been re-analysed paragraph by paragraph as in the first place - due to the limit of entities returned from the NLP (TWM engine) - WL didn't recognised well know entities like `pangea`. These have been spotted right after as the text was gradually added to the page. 

On the blog we have version 3.4.0

**Comment by mcolacino** [comment]
@cyberandy, were the affected entities created for the first time within this post?
I don't think the Word markup can impact in this sense: the synthom seems to be that the url of the current post is used also as url for new entities ...
Apart the url these entities are well-formed: this let me think to a kind of loop within the save_post callback ... We should identify the exact use case here.

**Comment by mcolacino** [comment]
@cyberandy even if we can keep as it is the situtation for further investigations, please consider that entity urls can be fixed trough the backend (RL will be updated accordingly)

**Comment by novedavi** [comment]
This issue did not happen when posting a new article:
http://camminandocon.org/2016/07/comunicando-con/
All entity created while writing the article have correct urls

**Comment by ziodave** [comment]
@novedavi can you please provide a step-by-step procedure on how to recreate the issue?

**Comment by novedavi** [comment]
As per the description:

When creating from the text new entities (What -> Thing) that do not have a
proper sameAs, after being saved, the entity gets duplicated as (Who ->
Person)

It was as simple as this. After the post was saved, the entity created as
"What", was showed under the "Who" section of the WordLift widget. Checking
inside the vocabulary two entities could be seen: the one created as "What"
and the one duplicated as "Who"

Davide

**Comment by novedavi** [comment]
I can't reproduce it either, as per my previous comment, it did not happen when I wrote my last article and I just tested a new article now and could not reproduce it once more.
When it happened, I remember it was using the title of the article to build the permalink of entity automatically generated annotating what suggested by Wordlift.

**Comment by novedavi** [comment]
We were finally able to reproduce this issue.
When creating this article: https://wordlift.io/8-reasons-why-create-vocabulary-wordpress-website/
we annotated 3 entities suggested by WordLift:
Google - https://wordlift.io/entity/8-reasons-create-vocabulary-wordpress-website/
Schema.org - https://wordlift.io/entity/8-reasons-create-vocabulary-wordpress-website-3/
Plug-in - https://wordlift.io/entity/8-reasons-create-vocabulary-wordpress-website-2/

The entities were properly created and curated right after in the entity page itself.
The urls of these entity took the title of the article instead of the title of the entity.

**Comment by novedavi** [comment]
A client just sent example of this issue happening on his blog:
http://richtopia.com/entity/5-reasons-vpn-service-must-business-7
http://richtopia.com/entity/5-reasons-vpn-service-must-business-2
http://richtopia.com/entity/5-reasons-vpn-service-must-business-3

**Comment by ziodave** [comment]
@novedavi this cannot be reproduced anymore on wordlift.io, can you please make a test again yourself? In case may I get in touch directly with richtopia.com for further tests?

Thanks
