### ISSUE TITLE
The calendar for startDate and endDate of an event cannot be used for historical events

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#291]
The existing calendar accepts as range any date between 1950 to 2150. This creates a problem when tagging historical events.

**Comment by ziodave** [comment]
I suggest we replace the current implementation using this [DateTime Picker](http://www.malot.fr/bootstrap-datetimepicker/demo.php) and eventually splitting the date and time fields.

The advantage of the proposed picker is a clean navigation through years (past, present and future), without limits.

**Comment by ziodave** [comment]
@markkap we need to fix the _date format_, see comments in GH.
