### ISSUE TITLE
Adding support for https://schema.org/Recipe

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#292]
Following the requests from some of our testers such as SLT and Appartamento9 we shall add the support for the https://schema.org/Recipe. The entity type recipe is derived from CreativeWork and adds to it the following properties: 

![image](https://cloud.githubusercontent.com/assets/837037/14177681/b7b5e90e-f757-11e5-82e6-9f8018eab7b2.png)

**Comment by ziodave** [comment]
See also #428 . In the case of SLT, there isn't an existing post type.

**Comment by ziodave** [comment]
Duplicated of #524 .
