### ISSUE TITLE
New UI refinements 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#295]
Based on the immediate feedbacks from two users (Davide and myself) this issue summarise some required adjustments to the new WordLift's UI. 

- topics should be sorted by confidence
- tooltips are missing on all icons (these can greatly help new and existing users)
- considering - _with a top down annotation approach_ (I choose entities from the WordLift Edit Widget and not from the occurrences in the text) that each entity will generate a link I have no means of understanding how many links will be generated. This basically means that, the number of occurrences of an entity in the article is still needed (it's hard to understand what the number is about in the first place but is needed) 
- when I click on an entity from the text editor I expect to edit its property and currently I need to make one more click before editing (this extra click can be removed) 
- when an entity has been detected and is not yet in my vocabulary (as I didn't yet saved the post) I should not see the "Open in Vocabulary" link (this shall only be made visible for entities already in my vocabulary) 
- when an entity has been already saved in the vocabulary I don't expect to read "_Create entity_" when I am editing its property. "_Update_" or "_Save_" is more appropriate in this specific context
- the entity description input box shall be larger (font size also could be a bit bigger) - see below
![image](https://cloud.githubusercontent.com/assets/837037/14427408/ea8f4654-fff4-11e5-8452-388ac50164fe.png)
- on the icon front: the vocabulary icon shall be more immediately visible (the brand color could be used here) than the other one (and the server rack doesn't represent the concept of a vocabulary but simply the fact that the entity is stored locally) 
- on the icon front: the event icon as well as the place icon are hard to read on non-retina screens
![image](https://cloud.githubusercontent.com/assets/837037/14427586/cc94238a-fff5-11e5-9ff6-7c86c1fc7587.png)
![image](https://cloud.githubusercontent.com/assets/837037/14427541/a0035cb4-fff5-11e5-8bb2-0fd533973495.png)
- on the icon front: as we deal with an entity `type:Person` whether we have a person mentioned in the text or an author _of the text_ - we shall probably keep the same icon (and yes an author in one article could be an entity `type:Person` in another.

![image](https://cloud.githubusercontent.com/assets/837037/14428970/bb90edce-fffb-11e5-8f4c-37ee83e4a65e.png)
![image](https://cloud.githubusercontent.com/assets/837037/14429050/0522d218-fffc-11e5-8779-c67e1b6073a6.png)

- the Save/Create button should probably be _before_ the "Open in the Vocabulary"
- for the "Get Location" I expect at least the pointer to become an arrow - it is otherwise hard to see it as something I need to click 
- for the "Get Location" we shall format the resulting string distinguishing City from Country (Rome, Italy) 
![image](https://cloud.githubusercontent.com/assets/837037/14429139/7c2c819c-fffc-11e5-8a2c-edd9d1b81079.png)

**Comment by mcolacino** [comment]
@wanbinkimoon also entity tile look & feel need to be fixed for entities with a long name (see screenshot)

![schermata 2016-04-11 alle 15 16 15](https://cloud.githubusercontent.com/assets/1022181/14428376/242d3c82-fff9-11e5-8a74-70e99d821bec.png)

**Comment by mcolacino** [comment]
@cyberandy about *"when I click on an entity from the text editor I expect to edit its property and currently I need to make one more click before editing (this extra click can be removed)"* there is a **good reason** to have a double click there: **a user could click on a given annotation just because he want to disambiguate it / de-disambiguate it without editing it**. I suggest to leave the workflow as it is.

**Comment by mcolacino** [comment]
@cyberandy about *for the "Get Location" we shall format the resulting string distinguishing City from Country" what is shown is the entity label: I suggest to keep it as it is.
