### ISSUE TITLE
Errors reported in Google Search Console

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#298]
The structured data section in Google Search Console reports errors for `data type = Hentry` 
- Missing: author
- Missing: entry-title
- Missing: updated 

Please see screenshot below for additional info:

![screen shot 2016-04-18 at 11 56 24](https://cloud.githubusercontent.com/assets/18528457/14600495/29dd3d26-055d-11e6-8f2e-eb694ceed5a5.png)

While not strictly related to WL it effects WL's entity pages.

**Comment by ziodave** [comment]
We don't do `hentry`, so I don't think this is relevant?

**Comment by cyberandy** [comment]
If there is nothing we can do on our side we can close the issue.

**Comment by ziodave** [comment]
This is something WordPress related, it's not markup we produce:

https://riseofweb.com/wordpress-google-webmaster-tools-structured-data-error-hentry/
