### ISSUE TITLE
Entities highlighting is not consistent after the first few saves

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#30]
For some reasons after working back and forth on the same post the highlighting of entities in the editor looks messed up (_see screen-shot below_).

![image](https://cloud.githubusercontent.com/assets/837037/8571247/dea00f44-2585-11e5-9ee8-efea6c054037.png)

The post is available here: http://test.wordlift.it/2015/07/04/interstellar/

**Comment by mcolacino** [comment]
Can you provide more details about how to reproduce it?

**Comment by cyberandy** [comment]
The simplest way is to let it run the analysis, save as draft a first
selection of entities. Replace some text hoping other entities get
recognized as well, publish and...t should break.

On Saturday, July 11, 2015, Marcello Colacino <notifications@github.com>
wrote:

> Can you provide more details about how to reproduce it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insideout10/wordlift-plugin/issues/30#issuecomment-120615870>
> .
>


-- 


*Andrea Volpini*
InSideOut10
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>

**Comment by mcolacino** [comment]
There is for sure an issue related to html entities within the markup

**Comment by cyberandy** [comment]
The issue has been fixed.
