### ISSUE TITLE
Hierarchical Custom Taxonomy Permalinks for Topics

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#302]
We have currently introduced new permalinks for _Topics_ such as `http://test.wordlift.it/wl_topic/sport/` and these are a great way to help users see blog contents with well-known `entity-topics` derived from Wikipedia. 

These are very flexible in terms of 3rd party integrations as they can provide oob RSS 2.0 feeds `http://test.wordlift.it/wl_topic/sport/feed/` thanks to WordPress. 

Now a good improvement would be to implement a simple hierarchy to list with `http://test.wordlift.it/wl_topic/` (and the corresponding `http://test.wordlift.it/wl_topic/sport/feed`) all the topics available on the blog. 

This is an enhancement.

**Comment by ziodave** [comment]
Closing, feel free to reopen.
