### ISSUE TITLE
Get Location (Article Metadata) feature refactoring  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#303]
When clicking "Get Location" under article metadata nothing happens. Follows the error from the console.

![image](https://cloud.githubusercontent.com/assets/837037/15292566/f416bc5c-1b83-11e6-8f05-826e74e6842f.png)

**Comment by cyberandy** [comment]
The problem is related to a recent update in Chrome starting from this last April. See here: 

- https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en
- https://mobiforge.com/news-comment/no-https-then-bye-bye-geolocation-in-chrome-50

A possibile evolution here is to implement a geo query (see below) using either Google or OSM to let the editor write the address (this being either a city or a street). This can be later converted into to `log` and `lat` and eventually saved as `entity type:place`. 

![image](https://cloud.githubusercontent.com/assets/837037/15295243/ec394cf0-1b8f-11e6-9438-5c6b0610bbb4.png)

**Comment by ziodave** [comment]
This should be related to #356.
