### ISSUE TITLE
Entity Types' widget should be flat

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#305]
This UI component should look flattened

![schermata 2016-05-17 alle 19 07 29](https://cloud.githubusercontent.com/assets/1022181/15331853/884ad0f4-1c63-11e6-9501-7ae9978e5e19.png)

**Comment by ziodave** [comment]
schema.org is not flat, why should we flatten it?

http://schema.org/docs/full.html

**Comment by cyberandy** [comment]
It's easier to view for an end-user that doesn't know schema.org and its structure. More over the current structure it's not reproducing the hierarchy of schema.org: for instance LocalBusiness we have it under Place and it should be under Organization.

**Comment by ziodave** [comment]
Actually LocalBusiness is also a Place:

> Thing > Organization > LocalBusiness 
> Thing > Place > LocalBusiness

So schema.org is actually more than hierarchical. All right then ...

**Comment by cyberandy** [comment]
Yes sorry this was the other problem besides the fact the hierarchies are
hard to read unless we clearly understand them.

>

-- 


*Andrea Volpini*


*InsideOut10 <http://blog.insideout.io> - WordLift <https://wordlift.io>*


[image: Twitter] <https://twitter.com/cyberandy> [image: LinkedIn]
<https://www.linkedin.com/in/volpini> [image: about.me]
<https://about.me/andreavolpini> [image: Google Plus Page]
<https://plus.google.com/+AndreaVolpini> [image: SlideShare]
<https://www.slideshare.net/cyberandy> [image: Flickr]
<https://www.flickr.com/photos/cyberandy>

**Comment by ziodave** [comment]
@markkap can we create an update function which flattens the taxonomy?
