### ISSUE TITLE
Analysis problem: Dan tian does not work | Dan-tian works

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#307]
While analysing this blog post http://taoroma.it/qi-hai-caricarsi-rilassarsi/ the entity `dan tian` ([here](http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl034/entity/dan_tian) is on _data.wordlift.it_), while present in the internal vocabulary (see screenshot below), is not found by WordLift. The entity is properly found when using the dash `dan-tian`.

![image](https://cloud.githubusercontent.com/assets/837037/15402259/9deee332-1df3-11e6-9f09-c78caad8f385.png)

**Comment by ziodave** [comment]
This problem is not directly related to WL.
