### ISSUE TITLE
Add the support for wp_localize_script to boost translations of WordLift via GlotPress

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#308]
As of today translations of the plugin can be traced with **GlotPress** (see: https://translate.wordpress.org/locale/it/default/wp-plugins/wordlift). 

In case we have strings in the JavaScript part of the plugin that are subject to translations we shall use `wp_localize_script` (more info available here: https://codex.wordpress.org/Function_Reference/wp_localize_script).

**Comment by ziodave** [comment]
We're already using `wp_localize_script`. The legacy Angular code isn't, we'll improve that part while we transition to the new client side code.

**Comment by ziodave** [comment]
Closing, feel free to reopen.
