### ISSUE TITLE
Allow entity selection without entity linking

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#309]
The editor has to be allowed to choose between _entity page linking_ and _in-page entity widget_ on text annotations disambiguation. More in details we have 2 different workflows:
1. **top / down workflow**: when the editor selects an entity within the disambiguation widget he can choose if entity page linking has to be applied or not. This choice impacts on all related annotations. Default value is entity page linking _enabled_. A dedicated css class has to be added to text annotation markup in order to track the choice.
2. **bottom / up**:  when the editor selects a given annotation within the disambiguation widget he can choose if entity page linking has to be applied or not. This choice impacts **only** on that given annotation. Default value is again entity page linking _enabled_. A dedicated css class has to be added to text annotation markup in order to track the choice.
3. Within the entity panel a button has to be added to allow the editor to **embed** a given entity as single entity widget in page.

**A partial UI refactoring / tuning is required here**
**This issue is mandatory to implement the issue #266**

**Comment by wanbinkimoon** [comment]
@ziodave to complete this step, and enhance the main accordion set of the widget, I need to integrate a javascript function that set classes in a time interval.
in plain JS i'd write this code
```
var el = document.getElementsByClassName('*******');

function openClose(){
  // if the tile is closed
  if (this.classList.contains("is-hidden")) {  
    setTimeout(function(){
      // close all the other tabs
      el.removeClass('is-showing').addClass('animate-out');
      // animate this tab to open the box
      this.addClass('animate-in');
    },350);
    setTimeout(function(){
      el.addClass('is-hidden').removeClass('animate-out');
      this.addClass('is-showing').removeClass('animate-in');
    },700); //this value mus be the double of the time of the first timeout
  } 
  // if the tile is opened
  else {
    setTimeout(function(){
      // animate this tab to close the box
      this.removeClass('is-showing').addClass('animate-out');
    },350);
    setTimeout(function(){
      this.addClass('is-hidden').removeClass('animate-out');
    },700); 
  }
}

// here we call the function on click event
el.addEventListener("click", openClose);
```

**Comment by ziodave** [comment]
The developments for this issue are being done in develop and in a dedicated branch.
