### ISSUE TITLE
Entity not found during the analysis 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#313]
On the Tao Roma blog the entity "meridiani straordinari" (ref: http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl034/entity/meridiani_straordinari) **is not detected during the analysis**. 

For example in this entity's description http://taoroma.it/entity/orbita-microcosmica/ the text contains "meridiani straordinari" but the entity is not detected.

**Comment by ziodave** [comment]
If you type it with capital letters it is recognized:

![image](https://cloud.githubusercontent.com/assets/11438/18338736/bae345b6-75a3-11e6-9c3a-2405586e14c0.png)

Therefore is an entity recognition issue.

**Comment by ziodave** [comment]
This problem is not directly related to WL.
