### ISSUE TITLE
Enhancing the compatibility with the WPBakery Visual Composer and Shortcodes in general

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#316]
When editing a page using the **Visual Composer**, in order to use WordLift the user has to switch to classic mode, annotate, save the post and eventually enable the visual composer again. 

This workflow can be greatly optimized if we prevent the analysis to process the shortcodes `[[shortcode] ... [/shortcode]]`. 

As seen below the entity Google is erroneously detected in the text contained within the VC shortcode.   

![image](https://cloud.githubusercontent.com/assets/837037/16798467/67b448ce-48ec-11e6-81dc-24f6e9b05fc7.png)

Preventing the analysis to process any shortcode can greatly improve the user experience. This of course applies to several use cases (not just VC but any plugin that uses shortcodes).

**Comment by ziodave** [comment]
Fixed with the latest WLS update.
