### ISSUE TITLE
Article Title suggested as entity

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#317]
While creating a new Entity-Event (http://camminandocon.org/entity/escursione-grotta-la-pila-domenica-17-luglio/) WordLift suggested the title of an article posted in the blog as an entity in the "What" category. The description of the entity is empty, but it contains two images from the article. The entity "La geologia della valle del Turano" is not in the vocabulary. 
![screen shot 2016-07-13 at 11 46 02](https://cloud.githubusercontent.com/assets/18528457/16799185/d0d0a9b2-48ef-11e6-82c6-96961bf514c3.png)
![screen shot 2016-07-13 at 11 46 15](https://cloud.githubusercontent.com/assets/18528457/16799187/d4cdea16-48ef-11e6-8551-6bed7eb4143f.png)
Tester: CamminandoCon

**Comment by mcolacino** [comment]
@ziodave I remember we already filtered out *BlogPosting* entities from analysis results via WLS to solve this issue, isn't?

**Comment by ziodave** [comment]
Yes, the filter was later removed. I added it back.

**Comment by novedavi** [comment]
I can no longer reproduce this issue, I believe it can be closed.
