### ISSUE TITLE
Display a message when the faceted search has no results

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#318]
When creating a new Entity-Event (http://camminandocon.org/entity/escursione-grotta-la-pila-domenica-17-luglio/) I was expecting WordLift to suggest a related article present in the blog (http://camminandocon.org/2016/03/geologia-della-valle-del-turano/). The entity and the article have 3 common entities:
- Monti Carseolani
- Monti Lucretili
- Castel di Tora
  As a result, navigator and faceted search widget do not show any results.

**Comment by novedavi** [comment]
http://camminandocon.org/2016/07/comunicando-con/ navigator not working

**Comment by mcolacino** [comment]
It seems that a given dependency is not properly loaded
![schermata 2016-07-16 alle 10 46 49](https://cloud.githubusercontent.com/assets/1022181/16893779/c5345950-4b42-11e6-99e2-54c0323bbf05.png)

**Comment by novedavi** [comment]
Similar problem happened yesterday creating an article in our test site:
http://test.wordlift.it/2016/07/26/che-cosa-e-diventata-la-apple/
Similar articles are identified by WordLift but the navigator doesn't work at the end of the article. It loads in the middle, but it takes a different form.
Everything works well in this other article created a few minutes after in the same test site:
http://test.wordlift.it/2016/07/24/e-il-giorno-dellicloud/

Looking at these 3 cases together maybe we can find a pattern?

**Comment by ziodave** [comment]
@novedavi can you check if this is solved with #336 (v3.5.4+)?

**Comment by novedavi** [comment]
Doesn't seem to be working yet:
http://camminandocon.org/entity/escursione-grotta-la-pila-domenica-17-luglio/
Faceted Search is at the end of the article, but since no articles are suggested, it doesn't show.

**Comment by novedavi** [comment]
It works just fine, as per the fix implemented with #336, on an article:
http://camminandocon.org/2016/03/geologia-della-valle-del-turano/

**Comment by ziodave** [comment]
The error in the Developer Tools' console is:

```
angular.js:11598TypeError: Cannot read property 'ajax_url' of undefined
    at Object.e.load (wordlift-ui.min.js?ver=835a2a2…:1)
    at wordlift-ui.min.js?ver=835a2a2…:1
    at l.$eval (angular.js:14388)
    at l.$apply (angular.js:14487)
    at wordlift-ui.min.js?ver=835a2a2…:1
    at Object.e [as invoke] (angular.js:4182)
    at wordlift-ui.min.js?ver=835a2a2…:1
    at wordlift-ui.min.js?ver=835a2a2…:1
```

**Comment by ziodave** [comment]
For some reason WordLift UI instantiates the navigator even when it's not loaded in page:

```coffee
$(
  container = $("""
  	<div ng-controller="NavigatorWidgetController" ng-show="items.length > 0">
      <h4 class="wl-headline">{{configuration.attrs.title}}</h4>
      <wl-navigator-items></wl-navigator-items>
    </div>
  """)
  .appendTo('.wl-navigator-widget')

  injector = angular.bootstrap $('.wl-navigator-widget'), ['wordlift.navigator.widget']
  injector.invoke(['DataRetrieverService', '$rootScope', '$log', (DataRetrieverService, $rootScope, $log) ->
# execute the following commands in the angular js context.
    $rootScope.$apply(->
      DataRetrieverService.load()
    )
  ])
)
```

**Comment by ziodave** [comment]
After further analysis we found out that the faceted search doesn't appear simply because the entity has no referencing posts. In agreement with @novedavi I am changing this to an enhancement if we would like to review the faceted search behaviour.
