### ISSUE TITLE
An non-existent blog post continues to appear in WordLift's navigator widget 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#32]
After creating and **deleting** a blog post titled "The future..." (here is the URL: http://test.wordlift.it/2015/07/03/the-future/) the blog post remains interlinked in the WordLift's navigator (_see screen-shot below_) even it is no longer in WordPress. 

![image](https://cloud.githubusercontent.com/assets/837037/8571894/9d39c8a2-2589-11e5-8a27-b1e838252dd0.png)

Consequently, when clicking on the blog post link in the Navigator the user sees an error (404).
Same happens with the chord widget (_see screen-shot below_)

![image](https://cloud.githubusercontent.com/assets/837037/8572003/400454c6-258a-11e5-9189-6c457a2a16b9.png)

**Comment by pieroit** [comment]
We added a check on the post_status of every post/entity retrieved via the relation methods (wl_core_ ...). The widget now only shows elements with `post_status = 'publish'`

**Comment by pieroit** [comment]
Not to be closed yet. More generic post_status coverage is needed in order to let the admin widget work.

**Comment by pieroit** [comment]
We added the possibility to use wl_core_get_related... methods with a filter for both the predicate (what, who, where, when) and the post_status required (publish, draft, pending, trash).

GUI widget must now be aligned with new API.

**Comment by pieroit** [comment]
Solved.
