### ISSUE TITLE
Entities as Categories 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#320]
Blog posts and pages in WordPress can be organised with categories. Category is one of the pre-defined taxonomies in WordPress and it is used to sort and group content into sections. A website publishing content on a variety of topics can organise their website into sections using categories.

WordLift introduces a complete new way to classify contents by analysing the text and structuring it around the 4Ws (Who, Where, What and When) and by providing Topics that match Wikipedia's categories. In large sites the vocabulary itself though could also be used to replace the categories of WordPress and help users build the navigation of a website with named entities. This enhancement can be described as follows:

> As an editor I want  to be able to choose one or more entity to classify my blog post or page from my vocabulary within the 4Ws classification scope. If these entities are not mentioned in the text of the article (`text position = -1,-1`) they shall be marked up differently (i.e. @ziodave suggested 
> http://dublincore.org/documents/dcmi-terms/#terms-references `A related resource that is referenced, cited, or otherwise pointed to by the described resource`) and presented in the UI as _weak_ links (we know that entities mentioned in the text are more relevant for Google and other search engines and shall preserve their value). 

In the 4Ws classification we shall let editors add other related entities that the analysis might have skipped or that simply the editor wants to use as categories to build the navigation of his/her website.

**Comment by ziodave** [comment]
These entities are not returned from the analysis, therefore I think our focus should be on how we want to represent this feature in WordLift's metabox.

The 'Create new entity' feature should allow to create entities also with no text selected and we shall add an input to look for and add existing entities?

@wanbinkimoon what do you think?

**Comment by cyberandy** [comment]
Challenges on the UX front include: 

- making sure entities that are not detected in the text can be seen as _weaker_ when compared to other entities in the widget UI
- allowing the user to easily find entities from their vocabulary for each of the 4Ws 
- allowing the creation of entities that are not present in the text 

the first aspect is the most crucial as we believe entities mentioned in the text (either directly or via a synonym) provide a stronger ranking signal to search engines.

**Comment by cyberandy** [comment]
As intermediate step we can allow the user to add entities within a shortcode like `[wl_entities]` so that entities are detected and can be used to classify an article but they are not printed on the page.

**Comment by wanbinkimoon** [comment]
I suggest to replace the title entity with an editable text input and (as @ziodave says) add the possibility to create entities with no text selected. 

The wireframe below add the first rect as text input field

![widget - create entity - wireframe 2](https://cloud.githubusercontent.com/assets/10087639/17894947/989fa8aa-694b-11e6-9fe0-68f78665626d.png)

This will also provide us the possibility to suggest related entities which are not in the text.
