### ISSUE TITLE
Entity Dan tian not being detected

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#321]
Our tester http://taoroma.it/ reported an issue with one of the entity in its vocabulary not being properly detected by WordLift.

The entity is http://taoroma.it/entity/dan-tian/
Main name: Dan tian
Synonym: dan-tian 
Synonym: dan tian

It is properly detected only when it's written with the dash (-) therefore appearing as 1 word. 
Is there something we can change to make sure that even an entity made of 2 words, capitalized and with only 3-letters is properly recognized?

**Comment by novedavi** [comment]
The issue was already open: https://github.com/insideout10/wordlift-plugin/issues/307

**Comment by cyberandy** [comment]
Merged with #307
