### ISSUE TITLE
Content dynamically posted should follow both a chronological or a relevancy order.

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#323]
When developing smart navigation systems with WordLift, users should be able to choose between a chronological order (very useful for news or events: http://camminandocon.org/wl_entity_type/event/) or a relevancy order, which could be more useful when aggregating topics, people or places (e.g: http://camminandocon.org/wl_entity_type/place/).
relevancy could be determined by the number of time an entity is used or linked.
Thoughts?

**Comment by cyberandy** [comment]
This also can go very well along with https://github.com/insideout10/wordlift-plugin/issues/373

**Comment by ziodave** [comment]
We can go ahead with the first part, related to events, date start descending.

**Comment by cyberandy** [comment]
This works well for events - it would be great to have also a relevance-based ordering for the other types. Let's look here for example (this is indeed a comment from @novedavi) http://camminandocon.org/wl_entity_type/place/ - this one should present at first the most connected entities (most connected to both entities and articles).
