### ISSUE TITLE
Place entity created from the Location field in the Event Property box is corrupted.

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#328]
While creating a new entity-event on camminandocon.org -
http://camminandocon.org/wp-admin/post.php?post=1880&action=edit - I found the following issues:

1. After running, Wordlift found as °Where° Italia and Polonia, but not Cracovia

2. I typed Cracovia as location inside the event property box, which as been created as new entity since it couldn't be found as open data

3. I saved the article and no location were suggested in the "Where" section, except3-6 Novembre 2016, synonym of the title, which was used as synonym of the place entity Cracovia, automatically created from #2  - http://camminandocon.org/wp-admin/post.php?post=1895&action=edit -

**Comment by cyberandy** [comment]
Something similar occurred in the past with issue #287

**Comment by cyberandy** [comment]
This one can be merged with issue #330 - I will close it.
