### ISSUE TITLE
Bottom-Up annotation, only allows to select one entity one time

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#329]
As reported by our client (www.khemcorp.com) when annotating from the text (bottom-up), one entity can be annotated only one time:
![screen shot 2016-08-16 at 12 33 13](https://cloud.githubusercontent.com/assets/18528457/17696409/63496058-63ae-11e6-93a1-ee9b3a3f47c7.png)
To add the entity a second time the user if forced to create it as a new entity, which is then reconciled automatically after saving.

**Comment by mcolacino** [comment]
It should be possible indeed. This has to be considered as a bug. An hotfix will follow asap.
