### ISSUE TITLE
External Entities not recognised when adding an extra paragraph on long articles.  

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#330]
While in a demo with a partner @novedavi spotted an issue related to the limited number of entities per article that WL can process using the _Machine Linking_ engine. This issue is documented with a screencast (https://db.tt/hyN7BeJN):

As see in the screencast when I have an existing article with a long text (and various entities already being detected) if I add a new paragraph - rather than analysing only the newly added paragraph - WL sends to the analysis the entire text (and therefore all new entities are dropped due to the limitation on the number of entities we process per article). 

A better solution would be to send to the analysis the text incrementally (only the changes and not the entire article). 

When removing the rest of the article the entity `New York City` is properly detected. 

The entity `SEO Design Solutions` that belongs to the internal vocabulary of the user is not affected by this issue.

**Comment by mcolacino** [comment]
As we know the issue behind this behaviour is on RL side: just the first *n* more relevant entities are returned by the analysis.

**Comment by ziodave** [comment]
There is a client-side filter by ranking which we can try to lower in the meanwhile to see how it affects the analysis results.

**Comment by ziodave** [comment]
This is currently undergoing beta testing with selected sites. So far the main issue is the review the classification box to handle many entities.

**Comment by Cupofbrain** [comment]
See the results of our tests on long-form articles [here](https://docs.google.com/spreadsheets/d/1VlmGoncTc0c4dXDBbNr4o3_QAc1I7oDx5ydCbg_iA0E/edit?usp=sharing).
