### ISSUE TITLE
Improve the entity description area with support for HTML code

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#332]
![image](https://cloud.githubusercontent.com/assets/837037/17886742/7e82a850-6923-11e6-9098-d682620482f4.png)

As we can see here in the screenshot the `<span>` for the annotation is shown in the panel and this is generating confusion.

**Comment by ziodave** [comment]
I don't think this should be marked as a bug. We're using a textarea which doesn't render html code.

If we want here a wysiwyg editor we should create a new feature.

**Comment by ziodave** [comment]
It is now possible to instantiate additional TinyMCE editors: https://make.wordpress.org/core/2017/05/20/editor-api-changes-in-4-8/

**Comment by ziodave** [comment]
Linked to #467 .
