### ISSUE TITLE
Germanic umlaut causing troubles when saving sameAs links

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#333]
To reproduce this bug do the following: 

- try to add to an entity the following path `http://dbpedia.org/resource/Hüttau`
- when saving the sameAs links disappears and it's not saved on data.wordlift.it either

**Comment by novedavi** [comment]
@ziodave the issue is still happening in the LOD View Graph. Going to the back end of this link: https://www.onebigpark.at/de/wp-admin/post.php?post=61168&action=edit, click on the LODView button and go to the graph, some entities are not found because of an error in the url

**Comment by ziodave** [comment]
You mean this URL? http://en.lodlive.it/?http://data.wordlift.it/wl062/entity/kaese

This? 
![image](https://cloud.githubusercontent.com/assets/11438/18550026/a439ba22-7b5a-11e6-8d30-f27e982d2de7.png)

**Comment by novedavi** [comment]
Yes
![screen shot 2016-09-15 at 14 47 01](https://cloud.githubusercontent.com/assets/18528457/18550279/478d298c-7b53-11e6-9c82-622ccd2e1c09.png)
See the url of the relation exploded?

**Comment by ziodave** [comment]
Yes, this is unrelated with the current issue (#333). It's an issue related to the resource proxy of LOD View.

We need to create a new issue for this. Can you do that?
