### ISSUE TITLE
New Entities/Thing created without the sameAs attribute are duplicated as Entities/Person

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#334]
Our client SLT found a potential bug.
When creating from the text new entities (What -> Thing) that do not have a proper `sameAs`, after being saved, the entity gets duplicated as (Who -> Person) 
![screen shot 2016-08-25 at 18 00 38](https://cloud.githubusercontent.com/assets/18528457/17976537/3d33b12e-6aee-11e6-9930-6c75ee0c89f7.png)

The duplicate entity as the first one in the `sameAs`:
![screen shot 2016-08-25 at 18 04 05](https://cloud.githubusercontent.com/assets/18528457/17976561/56fd0fc4-6aee-11e6-8377-5a38cfdefd40.png)

More details will be added shortly after more testing is done.

Another example of entities where this issue happened is "almsommer"

I was not able to reproduce the issue on our test enviroment.

**Comment by novedavi** [comment]
Client provided interesting feedback via Skype:
![screen shot 2016-08-25 at 20 03 51](https://cloud.githubusercontent.com/assets/18528457/17980355/3b100404-6aff-11e6-9f1d-e0589d27d513.png)

**Comment by novedavi** [comment]
Client just reported today entities are being created without a default entity type at all.

**Comment by ziodave** [comment]
One of the issues is in this call 

```php
	$terms = get_terms( Wordlift_Entity_Types_Taxonomy_Service::TAXONOMY_NAME, array(
		'hide_empty' => false,
		'fields'     => 'id=>slug'
	) );
```

It appears that WordPress is returning an indexed array instead of using the term IDs as keys:

```php
src/wordlift_entity_type.php:63:
array (size=7)
  0 => string 'creative-work' (length=13)
  1 => string 'event' (length=5)
  2 => string 'localbusiness' (length=13)
  3 => string 'organization' (length=12)
  4 => string 'person' (length=6)
  5 => string 'place' (length=5)
  6 => string 'thing' (length=5)
```

The [get_terms](https://developer.wordpress.org/reference/functions/get_terms/) function reference clearly states this:

> 'id=>slug': returns an associative array with ids as keys, term slugs as values

**Comment by ziodave** [comment]
The issue arises because of AAM, file wp-content/aam/extension/plus-package/Backend.php:ln70 it adds the following filter:

```php
add_filter('get_terms', array($this, 'getTerms'), 10, 3);
```

which calls the following function:

```php
    /**
     * Filter terms based on area
     *
     * @param array $terms
     *
     * @return array
     *
     * @access public
     */
    public function getTerms($terms) {
        if (is_array($terms) && !AAM::isAAM()) { //skip filtering if AAM page
            foreach ($terms as $i => $term) {
                if ($this->checkTerm($term)) {
                    unset($terms[$i]);
                }
            }
        }

        return array_values($terms);
    }
```

which returns only the array values thus removing the term IDs from the array keys.
