### ISSUE TITLE
Wrong type detected in the WordLift Widget 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#337]
The case is the following: 
- an entity (i.e. http://taoroma.it/wp-admin/post.php?post=3253&action=edit) connects to another entity (i.e. http://taoroma.it/wp-admin/post.php?post=3931&action=edit) mentioned in the text that is set as `creative work` and follows under "_What_" (this is correct)

![image](https://cloud.githubusercontent.com/assets/837037/18198023/b8a173b6-70fa-11e6-8edf-735f8d7eb7b9.png)
- The entity's icon in the widget though is representing `thing` and not `creative work`. 
- Also when highlighting (clicking to get into the details) `thing` is bold and not `creative work`  

![image](https://cloud.githubusercontent.com/assets/837037/18198057/dfe7c272-70fa-11e6-89a4-47c1799464a5.png) 
- the entity itself is set as `creative work` 

![image](https://cloud.githubusercontent.com/assets/837037/18198106/1a52dfe6-70fb-11e6-9c68-82423c941beb.png)

Interesting enough - _after saving the annotation_ the widget properly displays the correct type

![image](https://cloud.githubusercontent.com/assets/837037/18198407/27b4f150-70fc-11e6-931f-4448dadf9267.png)

**Comment by cyberandy** [comment]
This occurred again on another site.

**Comment by ziodave** [comment]
I think this is superseded by WL 3.11.

**Comment by ziodave** [comment]
The entity's icon is not shown anymore. We can close this one.
