### ISSUE TITLE
Improving the Import/Export of the user Vocabulary 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#339]
As of today we can use WordPress's native Import/Export functionality to move the vocabulary from one website to another. I was able to: 

1. use the Export button under the Tools menu of WordPress from the origin website 
2. choose to export the _vocabulary_ only   
3. use the Import button under the Tools menu from the destination site (remember to choose Import WordPress and to check the option `Download and import file attachment`) and get all entities imported

When data is imported from a website in one language (let's say English) - the data is saved using the language being set under the WordLift's configuration tab of the destination website.  

There are the following limitations to be considered: 

- images are not properly imported (and need to be replaced with the correct ones)
- in case a user decides to federate multiple websites and needs to interlink data from the source site with data from the destination site we need to make sure that the `entity uri` of the source site is added as `sameAs` in the corresponding entity on the destination site* 

* In these specific case WordLift on the destination site can be configured to use in the analysis the dataset of the source site - this way any new entity added on the source site will be automatically discovered on the destination website (and properly interlinked). Here below we have for instance the `sameAs` for the entity _Castel di Tora_ that has been automatically imported on test.wordlift.it from the CamminandoCon.org website; among the `sameAs` attributes we also have the reference to the entity on the CamminandoCon.org dataset (http://data.wordlift.it/wl049/entity/castel_di_tora). 

![image](https://cloud.githubusercontent.com/assets/837037/18388287/544eff26-76a1-11e6-8524-a49334fecf28.png)

**Comment by ziodave** [comment]
I made a check on the export xml and the entity URL is properly exported with the _entity_url_ meta. I would say that WL should hook to WP's import procedure to copy the _entity_url_ to the _sameAs_ if the entity URL is not within the destination WP's dataset URL.

As for the images this appears to be a limitation in WordPress:
http://wptips.me/how-to-import-images-when-importing-posts-from-a-wordpress-export-file/

**Comment by ziodave** [comment]
There are 3 hooks we could use:

1. `$this->posts = apply_filters( 'wp_import_posts', $this->posts );` called for all the posts,
2. `$post['postmeta'] = apply_filters( 'wp_import_post_meta', $post['postmeta'], $post_id, $post );` called by the importer process when importing posts' metadata,
3. `$key = apply_filters( 'import_post_meta_key', $meta['key'], $post_id, $post );` called for single metas.

I think we should use the 3rd.

**Comment by ziodave** [comment]
We should move the _entity_url_ meta to _entity_same_as_ but also create the new _entity_url_ so the 2nd hook seems more appropriate.

**Comment by ziodave** [comment]
So we got a first version working:

![image](https://cloud.githubusercontent.com/assets/11438/18543790/42eb8040-7b3a-11e6-9dd0-932b79d3bf7f.png)

Although this version is not checking for the _entity_url_ actual value, therefore, if you're importing on the same WP install, it'll copy the _entity_url_ in the _entity_same_as_.

Also WL doesn't store all Linked Data during import, but only the main subset:

http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl040/entity/grosarl

Therefore we would need still to:

1. check the _entity_url_ whether matches the WP install dataset URI (i.e. within `wl_configuration_get_redlink_dataset_uri()`),
2. have WL publish also the entity post metadata to Linked Data.

**Comment by ziodave** [comment]
> check the entity_url whether matches the WP install dataset URI (i.e. within wl_configuration_get_redlink_dataset_uri())

This is solved using the 2nd hook `wp_import_post_meta`

**Comment by ziodave** [comment]
This needs to be addressed still:

1. have WL publish also the entity post metadata to Linked Data,
2. the language tag is set to the language of the current web site.

**Comment by ziodave** [comment]
For the metadata we could hook to the following:

`"added_{$meta_type}_meta", $mid, $object_id, $meta_key, $_meta_value`

**Comment by novedavi** [comment]
When testing this we should also verify that an entity imported inside another website, keeps all the properties, images, and markup, and the author can simply translate the text into another language

**Comment by ziodave** [comment]
As for the images this appears to be a limitation in WordPress:
http://wptips.me/how-to-import-images-when-importing-posts-from-a-wordpress-export-file/

**Comment by ziodave** [comment]
Metadata is now pushed to Linked Data.

As for the language tag we have 2 options, either not importing literals or importing them with the local language tag.

Not importing literals is not feasible, so we'll use the local language tag, this is an example result:
![image](https://cloud.githubusercontent.com/assets/11438/18550543/0f901b98-7b5d-11e6-9b57-b0ebc41dfa39.png)

**Comment by cyberandy** [comment]
Ok from the testing I could see that we now have the `sameAs` containing the URL of the source site as seen below. 

![image](https://cloud.githubusercontent.com/assets/837037/18667180/c5d0d070-7f2f-11e6-89d5-2b3835d91cbd.png)

The procedure only works when I set the option of  `Download and import file attachments`
![image](https://cloud.githubusercontent.com/assets/837037/18667227/f8286e16-7f2f-11e6-8dfe-7ed9a804be53.png)

Unfortunately the problem of the images as noted by @ziodave in his comments still persists but it has nothing to do with WordLift.
