### ISSUE TITLE
Special characters do not display correctly in LodLive

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#341]
see https://github.com/dvcama/resource-to-sparqlresult/issues/1

**Comment by ziodave** [comment]
This appears to be fixed:

![image](https://cloud.githubusercontent.com/assets/11438/21396177/eeb904a6-c7a7-11e6-8d20-7a02dd29fb12.png)

**Comment by novedavi** [comment]
Same case created on test.wordlift.it, it works just fine:
![screen shot 2016-12-27 at 18 31 58](https://cloud.githubusercontent.com/assets/18528457/21504893/e22f5982-cc62-11e6-9fe2-4586e5217841.png)
Verified
