### ISSUE TITLE
Disable Wikipedia images

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#343]
Provide an option to disable the import of images coming from WikiCommons.

**Comment by ziodave** [comment]
Wikipedia images come from the following domain: upload.wikimedia.org

**Comment by ziodave** [comment]
In order to simplify this issue we could use a PHP constant to define in `wp-config.php`, e.g. `WL_EXCLUDE_IMAGES` with a list of domains we want to exclude when importing images from analysis.

**Comment by ziodave** [comment]
The analysis processing happens in the browser client-side. I would avoid transferring data which is not used and delegating to the client its filtering.

**Comment by novedavi** [comment]
Verified in QA
