### ISSUE TITLE
Internal entity not recognized

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#344]
We already created an entity called “Dienten”, synonym “Dienten am Hochkönig”.
 
This internal entity does not appear when the term “Dienten” is in the text – instead the external entity “Dienten am Hochkönig” is suggested.

**Comment by ziodave** [comment]
I think this might be related to #324.

**Comment by mreichhart** [comment]
Same with "Alpen"

![image](https://cloud.githubusercontent.com/assets/22288718/18660332/1b55be22-7f10-11e6-9f6d-54d75c4910dd.png)

![image](https://cloud.githubusercontent.com/assets/22288718/18660310/0935d61e-7f10-11e6-883d-ff0bde509a5b.png)

**Comment by ziodave** [comment]
I ran a check on the analysis results we receive and the local Alps are actually not returned, so maybe a fix we could handle from our side is to match existing entities via the sameAs but that would add some complexity (and processing cycles) on the local WordPress instance.

**Comment by ziodave** [comment]
An update has been deployed server-side. It needs some testing.

**Comment by mreichhart** [comment]
same problem now, but different..
"Alpen" now shows up twice as internal entity.

![image](https://cloud.githubusercontent.com/assets/22288718/18702077/52178852-7fe0-11e6-9aab-e7bd45a25dc5.png)

On clicking "open in vocabulary" entity links to the internal entity correctly, the other one returns an error: "Entity not found". Link: https://www.onebigpark.at/de/wp-admin/admin-ajax.php?action=wordlift_redirect&uri=http%3A%2F%2Fopen.salzburgerland.com%2Fde%2Fentity%2Falpe&to=edit

**Comment by ziodave** [comment]
It's fixed now, I am closing the issue (we can reopen it later should we found errors during further testing).
