### ISSUE TITLE
Add Telephone and URL properties

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#346]
Upon a request of our client SLT, we should add two properties field to the types Organization and Local Business: Phone and Url (website)

We currently do not support them, see pictures below
Organization:
![screen shot 2016-09-21 at 17 44 17](https://cloud.githubusercontent.com/assets/18528457/18718608/7030463c-8024-11e6-96de-ecbf7ac72a26.png)
Local Business:
![screen shot 2016-09-21 at 17 44 04](https://cloud.githubusercontent.com/assets/18528457/18718612/743d7312-8024-11e6-9dab-f699ad92186d.png)

Telephone and URL are listed among the schema properties:
https://schema.org/LocalBusiness
https://schema.org/Organization

I believe this change will be beneficial for all clients as both phone and website are important contact info for any organization and local business

**Comment by ziodave** [comment]
Phone is expressed via the _schema:telephone_ property and it is quite straightforward to add. 

However the web site URL is a bit more tricky because it is expressed via the _schema:sameAs_ property:

> URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.

Which means that we already provide a field for it, but this field is also used to link other correlated URLs such as Wikipedia links.

Therefore we must discuss that one further.

**Comment by ziodave** [comment]
Actually _schema:url_ is the right property:

https://developers.google.com/webmasters/social-markup/

**Comment by ziodave** [comment]
We're currently using WP's _permalink_ as _schema:url_. We should make the _schema:url_ property editable and allow the editor to customize it.

**Comment by ziodave** [comment]
On _entities_ we could remove the _schema:url_ all together when not set, so to recap:

* for _posts_ we use the _permalink_,
* for _entities_:
 * we expose the _schema:url_ property and allow the editor to set it (no default value, not even the _permalink_),
 * the _entity_ permalink should appear in the _schema:sameAs_ property, always.

**Comment by ziodave** [comment]
Right now _schema:url_ is set in the following places:

* `wl_flush_rewrite_rules_hard` (filter of `flush_rewrite_rules_hard`) where the _schema:url_ is set as the _permalink_ of each post/entity when the permalink structure is changed,
* `rl_delete_post` (hooked to `transition_post_status` when a post/entity is deleted) _schema:url_ triples are deleted as well,
* `wl_push_post_to_redlink`/`wl_push_entity_post_to_redlink` where the _schema:url_ is set as the _permalink_ of the post/entity being pushed.

**Comment by ziodave** [comment]
My final proposal is that we behave this way:

* we preset the _schema:url_ for posts/entities to _permalink_ (e.g. `<permalink>`),
* the _schema:url_ property is editable for entities (not for posts),
* the editor may set the following:
 * `<permalink>` (the default) to use the entity _permalink_,
 * an empty value to disable the _schema:url_,
 * any other value, e.g. an official web site for the entity.

**Comment by cyberandy** [comment]
I did some tests here and everything works fine. I would only replace the label "url" in "website" and we can close it IMO.

**Comment by ziodave** [comment]
Still need to change the label here to 'Web Site' and create some unit tests.
