### ISSUE TITLE
Faceted search widget is not working  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#35]
![image](https://cloud.githubusercontent.com/assets/837037/8616733/ead6b7c6-26fd-11e5-8763-40d97ae2e51d.png)

![image](https://cloud.githubusercontent.com/assets/837037/8616777/36c300cc-26fe-11e5-85fb-1861b10b8b95.png)

- http://test.wordlift.it/entity/future/
- http://mico-gp.insideout.io/entity/greenpeace/

**Comment by ziodave** [comment]
Solved.
