### ISSUE TITLE
Text annotations missing for found entities

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#351]
Sometimes text annotations are missing (no text underlined) while entities have been found.

**Comment by ziodave** [comment]
I made a test by copying the post body to a text editor and then copying it back. The analysis then worked.

**Comment by mreichhart** [comment]
I tried this test too, result was the same as before - still annotations missing for found entities.

![image](https://cloud.githubusercontent.com/assets/22288718/18868524/d9c31722-84a8-11e6-9674-fdc8b5bc0f90.png)

**Comment by ziodave** [comment]
Thanks @mreichhart, we've been able to reproduce it in our local environment. We'll keep you posted.

**Comment by ziodave** [comment]
This is a result of #344 .

**Comment by ziodave** [comment]
This is now partially solved.

**Comment by ziodave** [comment]
An update has been deployed to test.wordlift.it for testing.

**Comment by ziodave** [comment]
Still we might have issues we preexisting selections overlaps.

**Comment by ziodave** [comment]
A definitive solution is now available for testing.

**Comment by cyberandy** [comment]
This is great news!
