### ISSUE TITLE
Improve design of the TimeLine Widget

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#352]
Our tester CamminandoCon request some design improvement of the TimeLine widget, such as eliminating the snippet of the description or reducing the size of the title.
I believe that a more user-friendly design would increase the usability of the widget.
![screen shot 2016-09-28 at 16 38 14](https://cloud.githubusercontent.com/assets/18528457/18918259/7b6f7c68-859a-11e6-8102-a105b5b86304.png)

**Comment by cyberandy** [comment]
More over - when doing so we can update the JS library of the timeline that has been updated by the team at timeline.knightlab.com

**Comment by wanbinkimoon** [comment]
This widget is implemented using [TimelineJS](https://github.com/NUKnightLab/TimelineJS). 
The library do not provide natively the possibility to hide de description. Instead we could act in order to edit the `JSON` used by the plugin – which by default is [`undefined`](https://github.com/insideout10/wordlift-plugin/blob/develop/src/coffee/ui/timeline.coffee#L10) – and edit the `timeline.era.text` object.

**Comment by cyberandy** [comment]
@wanbinkimoon @ziodave this also was mentioned today when talking with two users of WordLift.

**Comment by ziodave** [comment]
As far as I know @wanbinkimoon made the change but it filed the automated tests.

**Comment by ziodave** [comment]
The sample page is at http://camminandocon.org/2016/09/open-data-e-la-valle-del-turano/

**Comment by ziodave** [comment]
@cyberandy we're using v2.32 and TimelineJS is at v3.4, that's a big leap forward, I'll create a separate issue for that.

**Comment by ziodave** [comment]
The method that generates the timeline is `ajax_timeline` in `Wordlift_Timeline_Service`.

**Comment by ziodave** [comment]
@novedavi this is what it looks like when removing the text: 
![image](https://cloud.githubusercontent.com/assets/11438/19416049/547215b0-938e-11e6-8374-9b9784b09352.png)

**Comment by ziodave** [comment]
@novedavi pls have a look to [TimelineJS examples](https://timeline.knightlab.com/index.html#examples) and see which one more suits our case.

**Comment by ziodave** [comment]
We need to further assess the design here, it's important also to understand how TimelineJS decides to publish the event components:

```
        // Add to DOM
        if (!this.has.text && !this.has.headline && this.has.media) {
            TL.DomUtil.addClass(this._el.container, 'tl-slide-media-only');
            this._media.addTo(this._el.content);
        } else if (this.has.headline && this.has.media && !this.has.text) {
            TL.DomUtil.addClass(this._el.container, 'tl-slide-media-only');
            this._text.addTo(this._el.content);
            this._media.addTo(this._el.content);
        } else if (this.has.text && this.has.media) {
            this._media.addTo(this._el.content);
            this._text.addTo(this._el.content);
        } else if (this.has.text || this.has.headline) {
            TL.DomUtil.addClass(this._el.container, 'tl-slide-text-only');
            this._text.addTo(this._el.content);
```

Also there's support for background images.

**Comment by ziodave** [comment]
We're going to publish the text as well using the same WP's logic when the list of blog posts is printed.

**Comment by ziodave** [comment]
WordPress is not using the _excerpt_ in _twentysixteen_, _twentyfifteen_ and _twentyfourteen_:

```
			the_content( sprintf(
				__( 'Continue reading %s', 'twentyfifteen' ),
				the_title( '<span class="screen-reader-text">', '</span>', false )
			) );
```

**Comment by ziodave** [comment]
WordPress requires `<!--more-->` to be used in the text, but this is not the case in most of our test sites, if `<!--more-->` is not present the whole text is used.

**Comment by ziodave** [comment]
After some tests on camminandocon.org, with mixed results, it's evident we need to provide the site maintainer the ability to customize TimelineJS options, eventually the number of words for the excerpt (0 = turn it off) and the choice whether to display the images as _media_ or as _background_.

**Comment by ziodave** [comment]
These are the options we support on the shortcode:

```
			'debug'                            => defined( 'WP_DEBUG' ) && WP_DEBUG,
			'height'                           => NULL,
			'width'                            => NULL,
			'is_embed'                         => FALSE,
			'hash_bookmark'                    => FALSE,
			'default_bg_color'                 => 'white',
			'scale_factor'                     => 2,
			'initial_zoom'                     => NULL,
			'zoom_sequence'                    => '[0.5, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]',
			'timenav_position'                 => 'bottom',
			'optimal_tick_width'               => 100,
			'base_class'                       => 'tl-timeline',
			'timenav_height'                   => 150,
			'timenav_height_percentage'        => NULL,
			'timenav_mobile_height_percentage' => 40,
			'timenav_height_min'               => 150,
			'marker_height_min'                => 30,
			'marker_width_min'                 => 100,
			'marker_padding'                   => 5,
			'start_at_slide'                   => 0,
			'start_at_end'                     => FALSE,
			'menubar_height'                   => 0,
			'use_bc'                           => FALSE,
			'duration'                         => 1000,
			'ease'                             => 'TL.Ease.easeInOutQuint',
			'slide_default_fade'               => '0%',
			'language'                         => $this->get_locale(),
			'ga_property_id'                   => NULL,
			'track_events'                     => "['back_to_start','nav_next','nav_previous','zoom_in','zoom_out']",
			'global'                           => FALSE,
			// The following settings are unrelated to TimelineJS script.
			'display_images_as'                => 'media',
			'excerpt_words'                    => 55,
```

Almost all of these options match what's described here: https://timeline.knightlab.com/docs/options.html
