### ISSUE TITLE
Improve the navigator Widget by adding links to the images 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#354]
Adding links in the photos displayed in the navigator widget will most likely increase the CTR - we currently have one user requesting it.

**Comment by wanbinkimoon** [comment]
Need to verify my changes. At the moment i cannot display a navigator on my local machine. 
What i did is basically edit the code in `src/coffee/navigato-widget/app.coffee` and replace the `span` with a `a` including the same `ng-href` of the title. 
So, now the code appears like this: 
```html
<a ng-href="{{item.post.permalink}}"> style="background: url({{item.post.thumbnail}}) no-repeat center center; background-size: cover;"></a>
```

**Comment by cyberandy** [comment]
@wanbinkimoon @ziodave what is the status of this one? Can we put it in the next release? It's needed on few cases.

**Comment by ziodave** [comment]
It's blocked in develop I think.
