### ISSUE TITLE
Redesign metabox section in Vocabulary 

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#356]
At the state of the work metaboxes have several issue that need to be fixed: 
- compiled `input` fields do not have any highlight 
- responsive is not working 
- we need to avoid blue border in order to improve the integration between the widget  and wordpress 
- map section need to be fixed in proportion, focus, colours and details
-  section's leads need to be capitalised

**Comment by wanbinkimoon** [comment]
I suggest a simplified version

<p data-height="265" data-theme-id="dark" data-slug-hash="zNogPW" data-default-tab="result" data-user="wanbinkimoon" data-embed-version="2" data-pen-title="wl - metabox - #356" class="codepen">See the Pen <a href="http://codepen.io/wanbinkimoon/pen/zNogPW/">wl - metabox - #356</a> by nicola bertelloni (<a href="http://codepen.io/wanbinkimoon">@wanbinkimoon</a>) on <a href="http://codepen.io">CodePen</a>.</p>

At the moment this solution still lack of:

- [ ] inline validation
- [ ] suggestion
- [ ] hover effects

**Comment by cyberandy** [comment]
- [ ] field description

**Comment by ziodave** [comment]
[ ] feedback message (e.g. from an entity changing type)

**Comment by wanbinkimoon** [comment]
@cyberandy I intended to use the `placeholder` prop to suggest content

**Comment by wanbinkimoon** [comment]
@ziodave can you be more specific? is this realted to #120 ?

**Comment by ziodave** [comment]
yes

**Comment by wanbinkimoon** [comment]
I updated the pen with the features required:
-  I opted for a textual and minimal layout. 
-  I changed the markup in order to make it more accessible using `fieldset`, `legend` and `label` 
-  I tried to keep everything explicit and easy to understand

<p data-height="265" data-theme-id="dark" data-slug-hash="zNogPW" data-default-tab="css,result" data-user="wanbinkimoon" data-embed-version="2" data-pen-title="wl - metabox - #356" class="codepen">See the Pen <a href="http://codepen.io/wanbinkimoon/pen/zNogPW/">wl - metabox - #356</a> by nicola bertelloni (<a href="http://codepen.io/wanbinkimoon">@wanbinkimoon</a>) on <a href="http://codepen.io">CodePen</a>.</p>

**Comment by markkap** [comment]
From my perspective, only from the visual point of view, I find the "remove" button to be confusing. Some fields like startDate and EndDate for events just can not be removed (I assume). IMHO when there are no multiple values in the field, for example when the entity is just created, there should probably not be a button at all, or at least the text should be "Clear" or "Reset" instead of "Remove"

**Comment by ziodave** [comment]
I think we need to introduce at least some sort of properties groups. For example [LocalBusiness](http://schema.org/LocalBusiness) has tens of properties, but [Google](https://developers.google.com/search/docs/data-types/local-businesses) only defines 3 as required and about 10 as recommended.

We need also to consider complex properties, such as _address_ (a [PostalAddress](http://schema.org/PostalAddress)), _geo_ ([GeoCoordinates](http://schema.org/GeoCoordinates)), _opening hours_ ([OpeningHoursSpecification](http://schema.org/OpeningHoursSpecification)), ...

Maybe you could review the UX proposal using a real case scenario, like a [LocalBusiness](https://developers.google.com/search/docs/data-types/local-businesses) or an [Event](https://developers.google.com/search/docs/data-types/events), using WordLift's data or a Meetup event, and taking into consideration _required_, _recommended_ and _other_ properties, and the complex properties (addresses, geo coordinates, opening hours, ...

You need also to take into consideration that I might want to link an existing entity (Organizations' founders links to a Person entity), so it might be helpful to also define an autocomplete select which displays this data.

**Comment by wanbinkimoon** [comment]
# Approach
I approached this issue designing individual components reusable which could be composed as needed by the entity type. 

Here is a list of examples in two sets for the **desktop** layout and one for **mobile** resolution. 

## Desktop v1
## Image
![image](https://cloud.githubusercontent.com/assets/10087639/22373733/69bd2e8a-e4a3-11e6-8ae9-b1cdc6f14072.png)
![date](https://cloud.githubusercontent.com/assets/10087639/22373731/69b9b228-e4a3-11e6-9e2e-495291858de4.png)
![textarea](https://cloud.githubusercontent.com/assets/10087639/22373730/69b95238-e4a3-11e6-84b0-673a8229f98c.png)
![text](https://cloud.githubusercontent.com/assets/10087639/22373732/69baa46c-e4a3-11e6-90c3-2622d58b7efb.png)

**Comment by cyberandy** [comment]
Few comments here: 

- we're still missing multiple fields such as Web Site (s) and sameAs
- entity type selection is incomplete: 
  - entity types don't match the existing icons/symbols we use on the edit widget
  - category as label is used for the 4Ws so I find it here very confusing  
-  description is the body of the article or is it something else? This is also probably incomplete

**Comment by wanbinkimoon** [comment]
Here a more conservative suggestion, i think @cyberandy will love it. 
Mobile version coming soon…

![desktop hd 5](https://cloud.githubusercontent.com/assets/10087639/22645197/27d0ecee-ec66-11e6-9fe1-7f0d313347c4.png)
![desktop hd 5 copy](https://cloud.githubusercontent.com/assets/10087639/22645198/27d1dd3e-ec66-11e6-919a-fe32d743aba8.png)

**Comment by wanbinkimoon** [comment]
# Changing type message
 Refer #120 
![desktop hd 5 copy 5](https://cloud.githubusercontent.com/assets/10087639/22666353/7ffbeb88-ecb8-11e6-9214-27e93aa9bfde.png)


# Local business
## Address compacted + information tooltip
![desktop hd 5 copy 6](https://cloud.githubusercontent.com/assets/10087639/22666418/bfae4532-ecb8-11e6-8185-3001a3b985fc.png)

## Address expanded
![desktop hd 5](https://cloud.githubusercontent.com/assets/10087639/22666417/bfae52fc-ecb8-11e6-9653-8f2cbdff21ad.png)

# Event
## Initial view
![desktop hd 5 copy](https://cloud.githubusercontent.com/assets/10087639/22666509/17ac0bb6-ecb9-11e6-8984-40db97698164.png)


## Select a location from a list 
![desktop hd 5 copy 3](https://cloud.githubusercontent.com/assets/10087639/22666451/e7f7a542-ecb8-11e6-8c45-93faf7a0e7fa.png)

## Create a new place in page
![desktop hd 5 copy 4](https://cloud.githubusercontent.com/assets/10087639/22666452/e7f7fce0-ecb8-11e6-826b-07726ed724a7.png)

**Comment by ziodave** [comment]
My comments:

- [ ] "74%" in the metabox title is confusing, what is it? a progress bar?
- [ ] the error message for inputs is not understandable, clarify.
- [ ] what happens when I insert the address, should we calculate the geo coordinates? what if the user already set the geo coordinates?
- [ ] I should be able to select more than one image
- [ ] where are the selected images?
- [ ] how does it work when I select an image from the last updates?
- [ ] allow closing a nested form.
- [ ] make more evident the nested form borders.

**Comment by wanbinkimoon** [comment]
## Warning message
I expect the warning message to appear as soon as the user `:focus` out of the `input`
![input - text - warning](https://cloud.githubusercontent.com/assets/10087639/22887770/9b0a04e6-f203-11e6-9183-a25a1f473cf9.gif)

**Comment by wanbinkimoon** [comment]
## Get current location
Here I expect the blue border to complete the circle.
![input - coorcinate - get location](https://cloud.githubusercontent.com/assets/10087639/22891509/e4ffc3ea-f20f-11e6-8a7b-9ac433354a51.gif)

**Comment by wanbinkimoon** [comment]
## Geocoding
I think that we should have an explicit CTA to trigger geocoding 
![input - coorcinate - geocoding](https://cloud.githubusercontent.com/assets/10087639/22925823/694bb088-f2aa-11e6-9250-efbec48d60c8.gif)

**Comment by wanbinkimoon** [comment]
## Image selection
### Initial state
No image selected
![normal](https://cloud.githubusercontent.com/assets/10087639/22940012/c84884ea-f2e0-11e6-8d21-d2a40710ae3e.png)
### Image selection
Multiple image selection is allowed
![selection](https://cloud.githubusercontent.com/assets/10087639/22940010/c82a989a-f2e0-11e6-9dad-809696be6458.png)
### Image removing
user `:hover` or `tap` the image to let the option appears
![remove](https://cloud.githubusercontent.com/assets/10087639/22940011/c8470426-f2e0-11e6-9b51-6bf16f5af530.png)

**Comment by wanbinkimoon** [comment]
## Location 
### Initial state
the map get zoomed on the city where the user is located (IP location maybe?) 
![normal](https://cloud.githubusercontent.com/assets/10087639/22940475/4c7af634-f2e2-11e6-86f9-dc1fbe4addfb.png)

### User types
![typing](https://cloud.githubusercontent.com/assets/10087639/22940488/54f33006-f2e2-11e6-91a2-633ec0e4c842.png)

### Location acquired
![selection](https://cloud.githubusercontent.com/assets/10087639/22940492/58e25a34-f2e2-11e6-9132-bf1a50736cf7.png)

### Another location is acquired
Multiple selection is allowed
![multiple selection](https://cloud.githubusercontent.com/assets/10087639/22940498/5dfa82bc-f2e2-11e6-8351-108ae2dc13bb.png)

**Comment by wanbinkimoon** [comment]
## Nested forms

- Closing button 
- Border for a better recognition

![desktop hd 5 copy 4](https://cloud.githubusercontent.com/assets/10087639/22941325/5c0fc220-f2e5-11e6-9bdb-8c590230f533.png)

**Comment by wanbinkimoon** [comment]
## Entity ranking
### Bar option
#### Over the title inline
![high](https://cloud.githubusercontent.com/assets/10087639/22985007/750e0b20-f3a7-11e6-9f8d-5b85d9727ae6.png)

#### Below the title not in line
![not in line copy](https://cloud.githubusercontent.com/assets/10087639/22985034/8592337c-f3a7-11e6-9772-2333a81f0e78.png)

#### Below the title with flag
![not in line copy 2](https://cloud.githubusercontent.com/assets/10087639/22985065/9336b5de-f3a7-11e6-97f5-867dde6b2ebc.png)

### Star option
#### Yellow stars
![stars](https://cloud.githubusercontent.com/assets/10087639/22984844/f619b7ec-f3a6-11e6-83fa-3a56d5992099.png)

#### Branded stars
![wl color](https://cloud.githubusercontent.com/assets/10087639/22984994/6c74698c-f3a7-11e6-8e38-52cf909ce3bc.png)

**Comment by markkap** [comment]
About the ranking, not sure, but placing anything on the same line of "edit entity" will be at least hard if not weird, as that part of the page is not easily controlled by the code controlling the various "edit boxes". the bar would be easier to implement (and I like it more visually ;) ). 

Another palcing that might be worth concidering, is in the publish box (this is where yaost places his analysis) 

![edit entity wordlift wordpress](https://cloud.githubusercontent.com/assets/1206170/23016806/8ba8dc72-f440-11e6-815b-08fd57a3b9ab.png)

Another place might be in the admin bar.

**Comment by markkap** [comment]
As for nested forms, I truly don't like this visual, maybe accordion or some sort of tabs will be better? (in this case I think yaost is a bad example as he has tabs on top and left and it is generally very confusing, at least for me)

**Comment by wanbinkimoon** [comment]
@markkap Thank you so much for your feedback, I'll work on a second indicator to place on the `publish box`

Regarding the nested form. I ha ve some concern about placing an accordion in that section. 
I focused on be the as explicit as possible, and to avoid hidden section an collapsable content, this because i think we should design to simplify the plugin, but i mean we can change the look and feel of it without using tabs or other solutions.

**Comment by markkap** [comment]
@wanbinkimoon  I just don't like that close button on the inner form. I know that for me it will lack context to understand what is exactly being closed, and should I save anything before doing that. I am also not sure accordion is best there, but if you have a "close", don't you also need an "open", which might end being like an accordion?

**Comment by wanbinkimoon** [comment]
@markkap Maybe the mocks are confusing, that sections shows up only if the user want to create a new entity which is still not listed in is vocabulary. so we do not need an open button because the open button is the `create new entity` link. 
Regarding the close button we can explore other solutions 😄

**Comment by wanbinkimoon** [comment]
## Publisher box
Lat's be discrete 
### Global
![flag publisher](https://cloud.githubusercontent.com/assets/10087639/23062526/6ec702a2-f506-11e6-9b82-03a92704ecbe.png)

### Detail
![screen shot 2017-02-17 at 11 42 45](https://cloud.githubusercontent.com/assets/10087639/23062514/5dcdae88-f506-11e6-83d7-d36546afbfd8.png)

**Comment by wanbinkimoon** [comment]
## Progress bar 
Alternative versions

### Blue
![flag publisher copy](https://cloud.githubusercontent.com/assets/10087639/23062778/788d39f4-f507-11e6-87c8-9e4a1c141005.png)


### Gray
![flag publisher copy 2](https://cloud.githubusercontent.com/assets/10087639/23062781/7ac7b208-f507-11e6-8576-3e6156e9dd5e.png)
