### ISSUE TITLE
Application Key Not Set - Messaging improvement is needed 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#358]
![image](https://cloud.githubusercontent.com/assets/837037/19035103/b743a702-8967-11e6-91a0-63335e8ab553.png)

When the user runs multiple plugins is hard to understand this error - we need to add Please add the WordLift application key in the settings (here we shall add a direct link to the settings page) of the plugin. Here follows an other similar example.

![image](https://cloud.githubusercontent.com/assets/837037/19035140/f59a72d8-8967-11e6-9cf3-4a88da017687.png)

**Comment by ziodave** [comment]
This issue can be closed since we have the new setup #364 #397
