### ISSUE TITLE
Analysis results are inconsistent due to disambiguation hints in the entity titles 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#360]
![image](https://cloud.githubusercontent.com/assets/837037/19111012/922fefec-8afd-11e6-9afe-3f0397cf5c8d.png)

In this specific sentence (see below) there is no mention of Rudolph Michael Schindler nor Rodney Walker.

Here is the annotated text:
"Richard Joseph Neutra (April 8, 1892 – April 16, 1970) was an Austrian﻿ American﻿ architect. Living and building for the majority of his career in Southern California﻿, he came to be considered among the most important modernist architects﻿."

This has been seen on the wl087 vocabulary and is related to the fact that both entities when imported have the word _Architect_ in the title (this comes from dbpedia and is meant to disambiguate this entity from others).

**Comment by cyberandy** [comment]
OK - basically when removing the (architect) from the title of the two entities and Rudolph Michael Schindler and Rodney Walker the problem was fixed. We need to think a solution here.

**Comment by ziodave** [comment]
These results are part of the analysis results.
