### ISSUE TITLE
Entity links are not working as expected

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#361]
the entity base path is set to null

![image](https://cloud.githubusercontent.com/assets/837037/19123745/1ff72638-8b30-11e6-87c6-a6f331683eec.png)

the permalink shows _/entity/_
![image](https://cloud.githubusercontent.com/assets/837037/19123761/32aed348-8b30-11e6-9cf5-b4b2f0ec11e3.png)

and internal links to entity pages as well as the View Entity link in the editor do not have _/entity/_ in the path and therefore don't work.

![image](https://cloud.githubusercontent.com/assets/837037/19123784/5a8c72f8-8b30-11e6-825a-9e8373541020.png)

**Comment by mreichhart** [comment]
in our instances just the permalink shows up wrong:
![image](https://cloud.githubusercontent.com/assets/22288718/19144946/c7d03288-8bac-11e6-8d0b-4968291102ef.png)

links are working:
![image](https://cloud.githubusercontent.com/assets/22288718/19144973/ee567782-8bac-11e6-9a23-1e3c1acc5c8b.png)

as well as internal links:
![image](https://cloud.githubusercontent.com/assets/22288718/19144993/15cb41da-8bad-11e6-8448-4e839214ac89.png)

it would be good, if the linktext of the permalinks show up right as well

**Comment by ziodave** [comment]
Thanks @mreichhart, that's how that's supposed to work. I'll have to check the specific case sent by @cyberandy and see the root cause.

**Comment by ziodave** [comment]
The problem arises when WP is configured with `/%category%/%postname%/` as permalink structure (instead of `/%postname%/`).

**Comment by ziodave** [comment]
I am changing this to medium, since it only affects web sites with the `/%category%/%postname%/` permalink structure and there's a workaround, i.e. don't use an empty base path.

**Comment by ziodave** [comment]
With #565 we've mitigated this issue, since we don't allow to configure an empty path when the permalink structure isn't compatible.

Anyway I am leaving this open since we might want in the future to investigate further the incompatibility cause and make this compatible.
