### ISSUE TITLE
Stop words are analyzed too

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#365]
In some analysis results I find stop words highlighted too. I think we should filter them out, there's a list of stop words:
http://dev.mysql.com/doc/refman/5.7/en/fulltext-stopwords.html

**Comment by cyberandy** [comment]
Probably from the list we shall remove www that is a valid alternative label for World Wide Web.

**Comment by cyberandy** [comment]
We need here to add stop words in WordLift's supported languages (i.e. _und_ for German as requested by @mreichhart). 

I've found these free lists: 

- http://www.ranks.nl/stopwords/
- http://members.unine.ch/jacques.savoy/clef/

**Comment by ziodave** [comment]
We'll use [Lucene](https://mvnrepository.com/artifact/org.apache.lucene/lucene-analyzers/3.6.2)'s stopwords:

"ar"
"bg"
"br"
"ca"
"cz"
"da"
"de"
"el"
"en"
"es"
"eu"
"fa"
"fi"
"fr"
"ga"
"gl"
"hi"
"hu"
"hy"
"id"
"it"
"lv"
"nl"
"no"
"pt"
"ro"
"ru"
"sv"
"th"
"tr"
