### ISSUE TITLE
The layout of the Navigator messes up with long entity titles

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#372]
As depicted in the image below the layout changes for the last tile as the title of the related entity is too long "Orbita Microcosmica" 

![593d670c-6e96-412e-96ca-04f4333a18f6](https://cloud.githubusercontent.com/assets/837037/19515683/bb31b672-95f8-11e6-94e0-65824d961673.jpeg)

**Comment by wanbinkimoon** [comment]
IMO the fastest and more efficient solution is to adda fixed `height` to the `h6` inside the `div.wl-card-header.wl-entity-wrapper`. 
I suggest to add this code to the navigator styles:
```css
.wl-card-header h6 {
  height: 46px;
}
```
`46px` is the height of the double line considering the actual `font-size` and `line-height` of this element.

**Comment by ziodave** [comment]
Is there a chance that we have titles spanning more than 2 lines? and what happens with a long word that doesn't fit?

**Comment by wanbinkimoon** [comment]
Yes, there is but it's very unlikely considering that the actual font fits an average of 16 characheter per row in the actual background, this means that a 3 lines entity should have more than 32 characters divided at least in 3 words.

**Comment by ziodave** [comment]
👍🏼ok, that's fine, we're basically targeting the specific case.

**Comment by wanbinkimoon** [comment]
Another, more invasive and expansive, solution could be add a `display: table` to the wrap addressed as `div.wl-carousel` and structure the content as a `table` this will oblige every cell to be coherent with the height of the row in which is placed.

**Comment by ziodave** [comment]
This sounds better, any reason not to apply this solution?

**Comment by wanbinkimoon** [comment]
the only reason I see is that in this case we are considerably rewriting part of the code, this imply that we need to test again the behaviour of the widget in several contest, and considering that we are re-designing the whole widget we may apply those efforts in this way.

**Comment by ziodave** [comment]
It might also have an impact on the responsiveness of the widget, right?

**Comment by wanbinkimoon** [comment]
Yep, that is implied. I mean this is why we will have to re-write a consistent part of the actual code.

**Comment by wanbinkimoon** [comment]
On a second thought we could use this issue to implement `display: grid` and provide a consistent  fallback considering that this feature is still widely unsupported, and most browser are still  implementing it.   
Here some docs regarding this: 
• https://css-tricks.com/snippets/css/complete-guide-grid/
• https://www.youtube.com/watch?v=SRblTXsBPrY
• http://caniuse.com/#search=grid
