### ISSUE TITLE
Extend the timeline to support start at future events

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#373]
It would be nice if the timeline would start from the first future event, instead from older events.

In order to do this we could extend the `start_at_slide` parameter of TimelineJS (which by default is set to `0`) in order to support they keyword `next` (event).

WordLift would parse the dates and set the `start_at_slide` to the first next event slide. If no next events are available then `start_at_slide` would be set to `0`.

**Comment by novedavi** [comment]
I agree!
