### ISSUE TITLE
Enable revisions for entities

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#376]
We can't find the revisions for entities, check whether this gets enabled with _register type_ in WP.

**Comment by ziodave** [comment]
This and #395 can be enabled together.

**Comment by ziodave** [comment]
See https://codex.wordpress.org/Function_Reference/register_post_type

**Comment by novedavi** [comment]
I can't verify this issue on the test site CamminandoCon. 
Revision is not an option offered in the entity page http://camminandocon.org/entity/camminandocon/

![screen shot 2016-12-27 at 18 21 35](https://cloud.githubusercontent.com/assets/18528457/21504687/79d5cd36-cc61-11e6-94b3-d8de3289b277.png)

**Comment by ziodave** [comment]
Revisions will appear in the following metabox, only after some edits:

![image](https://cloud.githubusercontent.com/assets/11438/21516231/0011297c-ccdf-11e6-8e4e-43f313d4a768.png)

**Comment by ziodave** [comment]
Revisions are now disabled because of #462.

**Comment by ziodave** [comment]
Before re-enabling revisions we should fix #157 .

**Comment by ziodave** [comment]
Tests:

- [ ] Try to restore an existing revision for an Entity
- [ ] Try to restore an existing revision for a Post
