### ISSUE TITLE
Broken images in the WordLift widget

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#38]
![image](https://cloud.githubusercontent.com/assets/837037/8675920/980dd5d2-2a46-11e5-9ce9-51506af70312.png)

After the analysis of the blog post http://test.wordlift.it/wp-admin/post.php?post=1744&action=edit&message=10 the entity "New Horizons" appears with a broken image (here is the image https://upload.wikimedia.org/wikipedia/commons/2/2e/New_horizons_Pluto.jpg).

**Comment by mcolacino** [comment]
Fixed. Can be see here: http://test.wordlift.it/wp-admin/post.php?post=2339&action=edit
