### ISSUE TITLE
Chord wigdet layout

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#380]
Although this widget is very useful the layout is incredibly unnatural in the flow of most webpages. This means that the impact on the page is too invasive to be used widely by our users. 

IMO the fastest fix could be evaluate other D3 visualisation, I'll evaluate this ASAP.

**Comment by ziodave** [comment]
Pls add a description with the requirements or the use case.

**Comment by wanbinkimoon** [comment]
@cyberandy suggest to use another D3 element which is the [Sankey Diagrams](https://bost.ocks.org/mike/sankey/) I think that this could be a fast solution if we apply a strong approach in the design process
