### ISSUE TITLE
Faceted widget 

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#381]
- [ ] Redesign Faceted like Google Mini Apps (see Refinement Chips).
- [ ] Use Moustache.

---
IMO this widget needs to be an enhancement of the navigator widget. 
The actual layout have two major issues: 
1. The categorisation of the entities is displayed in four cols the same number of the articles displayed by default. This cause a "Gestalt problem": the user tend to consider the list of entity displayed above related with the article below. CFR the image below for a more intuitive explanation. 
   ![faceted explain](https://cloud.githubusercontent.com/assets/10087639/19775388/859a8358-9c70-11e6-91df-4bb4caf186a5.jpg)
2. The 4 different categories are displayed in english. I think that in this case we have to avoid words and use, instead, icons in order to prevent a too simplistic perception of the categorisation. 

I think that the process of re-design of this widget should follow these steps: 
1. Change the `background-color` of the panel above to a light grey as `#F9F9F9`
2. Replace the labels on top with equivalent icons
3. Implement the design developed for the navigator widget applying styles and font changes
4. On Desktop: move the top panel to the left and remove one suggestion in order to reduce the impact of the widget on the page and help the user understand the consequence of his acts on the selection of articles on the right.

**Comment by cyberandy** [comment]
There is room for improvement here also in terms of mobile UX when the phone is in layout mode:  

**Nexus 5x - portrait** **FINE**
![image](https://cloud.githubusercontent.com/assets/837037/20211132/69a627d6-a7fd-11e6-8900-f257e6f5c38f.png)

**Nexus 5x - layout** **VERY HARD TO READ**
![image](https://cloud.githubusercontent.com/assets/837037/20211326/43f83c12-a7fe-11e6-9ff6-71d4d6cd0d7c.png)

**Comment by wanbinkimoon** [comment]
Here is what we got so far. 
- [x] Entity categories have now their dedicated space
- [x] We are working on icons in order to define an iconography widely understandable in orderr to avoid text and separate textual tags from categories. 

We are designing mobile first and we will post interactions prototypes ASAP

![tablet v6 dark](https://cloud.githubusercontent.com/assets/10087639/20211857/bb7c9510-a800-11e6-9764-7d7fcdaacf95.png)

**Comment by wanbinkimoon** [comment]
IMO the widget should have a natural flow when refining the filters and display new content in a consistent way. 
![wl-widget-faceted](https://cloud.githubusercontent.com/assets/10087639/20214450/99d93734-a80e-11e6-831d-9936c5964e74.gif)

**Comment by wanbinkimoon** [comment]
Here the mobile layout
![faceted_mobile](https://cloud.githubusercontent.com/assets/10087639/20394087/9a35605c-acde-11e6-8f8f-73b4cb604ce9.png)

**Comment by cyberandy** [comment]
The goal here would be to create an HTML mockup while making sure that :

- the list of articles is presented using the same style of the navigator 
- the list of articles can be personalized using a mustache template (as for the navigator )
- we provide a default set of icons for WHO | WHERE | WHAT | WHEN (these provided here in the mockups were temporary) and we give the user the option to personalize it. @claudiopome can you work on it? @ziodave does it make sense?
