### ISSUE TITLE
Chord - text overlapping issue

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#383]
![image](https://cloud.githubusercontent.com/assets/837037/19809771/12a5cfcc-9d2b-11e6-9953-36fcd5014e5e.png)

The user likes to use the chord on the website but we have two branches where the text overlaps:
- SilverLake Reservoir
- Los Angeles

**Comment by ziodave** [comment]
I think we should change the labels to display like in this example:

http://projects.delimited.io/experiments/chord-diagrams/uber.html

**Comment by ziodave** [comment]
The other option would be a visualization like this, maybe on two rows:

http://bl.ocks.org/mbostock/1308257

**Comment by ziodave** [comment]
Longer titles would be cut, slices that are too small would be displayed w/o title or wouldn't be displayed at all.

**Comment by novedavi** [comment]
The chords main goal is to collect and repurpose entities and articles, cutting or no inserting the title would be a waste of real estate on the page, since no click would go to that relationship. 
I prefer option on, at least to fix this issue. 
We already discuss with @wanbinkimoon the need to redesign the chord as the circle shape doesn't fit most website navigation and design style, which discourages usage.

**Comment by ziodave** [comment]
There is no way long titles would fit with the current chord size. I made 4 proposals to fix this issue:

1. labels perpendiculars to arcs,
2. labels in line with the arcs, on two rows,
3. and 4. cut labels or hide slices with labels which would be cut.

What's your proposal?

**Comment by novedavi** [comment]
There was a typo in my comment (on vs one), just fixed. I expressed my preference for 1. 
Cutting long titles is an acceptable second best until the design is repurposed.
Showing a title without a title, with the current design, should not be an option instead.

**Comment by ziodave** [comment]
@cyberandy can you please provide the URL for this Chord.

**Comment by cyberandy** [comment]
Here is a case where the Chord - as soon as we go live with the new release - shall be fixed. 

http://bestlaneighborhoods.com/architecture-for-sale/case-study-houses-program/

**Comment by wanbinkimoon** [comment]
I think this case was the one which upon @ziodave based his fix
