### ISSUE TITLE
Use data.wordlift.io (instead of data.wordlift.it) for all new installations

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#384]
The goal is to consolidate the information being published as linked data (by clients not requesting the custom domain) under the branded domain of WordLift that is now WordLift.io. 

It would be probably also good to migrate all entities from the wordlift.io website to the new domain.

**Comment by ziodave** [comment]
I created a separate issue #385 for the migration of wordlift.io's vocabulary.

**Comment by ziodave** [comment]
We can do this at the next platform update.

**Comment by ziodave** [comment]
Done.
