### ISSUE TITLE
Widget accordion

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#387]

**Comment by ziodave** [comment]
@wanbinkimoon a description for the issue?

**Comment by wanbinkimoon** [comment]
This issue is split in two instances:  
  1. The arrow on the right of the tile needs to rotate up when the tab is open  
![screen shot 2016-11-07 at 10 44 48](https://cloud.githubusercontent.com/assets/10087639/20053088/3ff7e510-a4d7-11e6-970f-16b90bfe2da3.png)
  2. Empty sections must be hidden   
![screen shot 2016-11-07 at 10 44 56](https://cloud.githubusercontent.com/assets/10087639/20053102/559e212c-a4d7-11e6-8b0f-53073fab0a4a.png)

**Comment by ziodave** [comment]
See also #374.
