### ISSUE TITLE
Finalize backend widget accordion 

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#388]
This issue has 2 minor topics: 
  1. Arrows need to reverse if the tab is open 
![screen shot 2016-11-04 at 12 11 23](https://cloud.githubusercontent.com/assets/10087639/20003623/d842afa0-a287-11e6-90b4-e1ae78aef3d7.png)
  2. Empty section of the accordion needs to be hidden

**Comment by ziodave** [comment]
Let's review this point as we replace the WordLift Edit Widget (metabox) with React components.

**Comment by ziodave** [comment]
Duplicate of #387 ?
