### ISSUE TITLE
Remove JetPackt's Related Posts from entity pages 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#389]
Clients using JetPack might use the related posts functionality of the plugin. To disable this functionality on entity pages we need to provide a tweak to the following code snippet in order to 
exclude entities

`function jetpackme_no_related_posts( $options ) {
    if ( is_single( array( 17, 19, 1, 11 ) ) ) {
        $options['enabled'] = false;
    }
    return $options;
}
add_filter( 'jetpack_relatedposts_filter_options', 'jetpackme_no_related_posts' );`

Here is the link to the documentation: https://jetpack.com/support/related-posts/customize-related-posts/#disable

**Comment by ziodave** [comment]
I think this could solve:

```
function wl_issue_389( $options ) {

    if ( !isset( $GLOBALS['post'] ) ) {
        return $options;
    }

    $post = $GLOBALS['post'];

    if ( Wordlift_Entity_Service::get_instance()->is_entity( $post->ID ) ) {
        $options['enabled'] = false;
    }

    return $options;
}
add_filter( 'jetpack_relatedposts_filter_options', 'wl_issue_389' );
```

I didn't test this, so please handle with care 💥
