### ISSUE TITLE
Html code messed u when using WordLift on previous posts and with Twitter embeds

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#391]
The client Richtopia.com reported some issue when working with WordLift old posts. Please find below his description and images of the issue: 
"When we first create posts, the plugin works fine. However, when we go to edit posts from the past, it messes the posts & codes making it difficult to update posts. Also, the same thing happens when we include Twitter embeds: at first they work when we first publish them, but when we update the posts and publish again it messes up the code."
![1](https://cloud.githubusercontent.com/assets/18528457/20054832/db0db1fe-a4de-11e6-97d4-e94286b2695d.jpg)
![2](https://cloud.githubusercontent.com/assets/18528457/20054833/db116272-a4de-11e6-906c-dcd78e033c04.jpg)

**Comment by ziodave** [comment]
Tweets are embedded using the standard Twitter "Embed Tweet" command and copying and pasting in WordPress' editor, correct?

![image](https://cloud.githubusercontent.com/assets/11438/20054999/edaff714-a4e7-11e6-89c9-814ebd49850a.png)

**Comment by cyberandy** [comment]
Yes this is correct - I reproduced the case on test.wordlift.it by copying the embed code of a tweet and copying and pasting it into the article:

![image](https://cloud.githubusercontent.com/assets/837037/20055257/86506b50-a4e0-11e6-9dbe-bf278f9e1f20.png)

Here is the code generated by Twittter and annotated by WordLift:

`<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">📌 <a href="https://twitter.com/hashtag/ThrowbackThursday?src=hash">#ThrowbackThursday</a> check us out in this article by <a href="https://twitter.com/digitalinkwell">@digitalinkwell</a> (thanks!) about <span id="urn:enhancement-1398dd3d-d3d2-8ba9-d968-063b5253a7e2" class="textannotation">Barack Obama</span> optimization! <a href="https://t.co/yABYNR1bvB">https://t.co/yABYNR1bvB</a></p>
— WordLift (@wordliftit) <a href="https://twitter.com/wordliftit/status/794208021110988800">November 3, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by ziodave** [comment]
In this case it's good though? I mean Barack Obama has been correctly annotated.

**Comment by cyberandy** [comment]
We should avoid annotating these cases as it might create troubles in the
page rendering.

**Comment by ziodave** [comment]
We should basically disable annotations within the following:

```
<blockquote class="twitter-tweet" data-lang="en"> ... </blockquote>
```

**Comment by ziodave** [comment]
Server-side we're ready to ignore Twitter embeds. The next step is to move the _traslator_ server-side and have WL send the full HTML content to WLS.

**Comment by ziodave** [comment]
See #425.

**Comment by cyberandy** [comment]
![image](https://cloud.githubusercontent.com/assets/837037/21505118/b2ae1052-cc64-11e6-9964-96f37180a26a.png)

Works!
