### ISSUE TITLE
JSON-LD problem with OSDS

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#393]
![image](https://cloud.githubusercontent.com/assets/837037/20062294/84eadcbe-a503-11e6-8afb-ebb3fa633c6b.png)

When accessing the on-page metadata with the OpenLink Structured Data Sniffer (OSDS) on this event - http://camminandocon.org/entity/sagra-del-fagiolo-a-pisello-2/ I get the error above. 

An error also displays using the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/?url=http://camminandocon.org/entity/sagra-del-fagiolo-a-pisello-2/#url=http%3A%2F%2Fcamminandocon.org%2Fentity%2Fsagra-del-fagiolo-a-pisello-2%2F). The name of the location seems missing even if the event does have "_Colle di Tora_" has location.  

![image](https://cloud.githubusercontent.com/assets/837037/20062383/cdc7828e-a503-11e6-880f-b273d32084ef.png)

**Comment by ziodave** [comment]
The problem is in the database:
```
+---------+---------+-------------+----------------+
| meta_id | post_id | meta_key    | meta_value     |
+---------+---------+-------------+----------------+
|   19904 |    2250 | wl_location | Colle di Tora  |
+---------+---------+-------------+----------------+
```

It's not a reference to an entity, but a textual value.

**Comment by ziodave** [comment]
This is now solved in a way that we print a Place with the provided name. However Google Structured Data Tool will complain about a missing address.

I will open an issue about entity references in metaboxes which are actually textual values.

![image](https://cloud.githubusercontent.com/assets/11438/20064028/e67d36f8-a511-11e6-8c57-23c24e5ee12a.png)
