### ISSUE TITLE
Review WordLift's setup process

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#397]
The current WordLift setup process is cumbersome, after the user activates WordLift:

![image](https://cloud.githubusercontent.com/assets/11438/20134463/2750fbb6-a674-11e6-939b-7346a758a203.png)

s/he's presented with the following message in WordPress' notices' area:

![image](https://cloud.githubusercontent.com/assets/11438/20134487/3e5d0854-a674-11e6-9c16-8d44fe05b1cc.png)

Besides the fact that **signup** links to join.wordlift.it which redirects to [WordLift's website](https://wordlift.io), there is no explanation on how to get a key or **how to set a key** for users who already have one.

**We want review the set-up process** by providing a step-by-step form to configure WordLift the first time:

![first_activation](https://cloud.githubusercontent.com/assets/10087639/20098299/6f40a7c6-a5b3-11e6-9945-2f89b1c92228.gif)

in a similar way to what [WooCommerce](https://wordpress.org/plugins/woocommerce/) does, i.e. when the user clicks on **activate**.

While the above shows a *sliding* effect, we might want to skip it for the first iteration in order to focus on the core features of the set-up screen.

![image](https://cloud.githubusercontent.com/assets/11438/20134620/cc99164e-a674-11e6-8864-3166d231e9a7.png)

the user is redirected to a full page which displays WordLift's set-up pages.

There are 5 steps:

### Return to WordPress

At any time it's possible to return to WordPress by clicking the X sign on the top right corner. In case installation isn't complete the plugin will remain not configured.

An Desktop example:
![desktop-2](https://cloud.githubusercontent.com/assets/11438/20141537/80825cfa-a699-11e6-8811-0e98b5c65339.png)

A Mobile example:
![iphone 7 activation step 5 v4](https://cloud.githubusercontent.com/assets/11438/20141524/7570c8ce-a699-11e6-86f9-34085197bce9.png)

### Validation

Some inputs have validation, this is how we display it:

Data not valid:
![wl activation step 2 v4 copy](https://cloud.githubusercontent.com/assets/11438/20141616/d85bbac0-a699-11e6-93b8-a5f9c32c109a.png)

Data valid:
![wl activation step 2 v4-1](https://cloud.githubusercontent.com/assets/11438/20141625/e3118616-a699-11e6-922e-3c9c248f41e1.png)

### Step 1

![wl activation step 1 v4](https://cloud.githubusercontent.com/assets/11438/20138434/fbaf379c-a688-11e6-8640-1a1a13028d64.png)

The six "cat" icons must be replaced respectively with the following font-awesome characters ([Font Awesome 4.0](http://fontawesome.io/) is already available in WordLift):

* Trustworthiness: `fa-university`
* Enrichment: `fa-map-marker`
* Engagement: `fa-heart`
* Smart Navigation: `fa-hand-o-right`
* SEO Optimization: `fa-google`
* Content Marketing: `fa-group`

The [5 circles](#bullets) in the top center part of the container represents the number of steps. The current step is highlighted with a full circle.

"Learn More" links to https://wordlift.io/blogger in a new tab.

"Get Started" goes to the next step.

### Step 2

![wl activation step 2 v4](https://cloud.githubusercontent.com/assets/11438/20138397/ced988da-a688-11e6-8043-7b6ea9777eba.png)

A real-time validation process for the key takes place here, when the user types the activate key or clicks next step, an API is called (@@TODO provide specs for the API) to validate the key. **If the key is not valid, the user cannot proceed to the next step.**

"Grab a Key" links to https://wordlift.io/#plan-and-price in a new tab.

"Next Step" goes to the next step.

### Step 3

![wl activation step 3 v4](https://cloud.githubusercontent.com/assets/11438/20138392/c69c2952-a688-11e6-82d9-6cdc798471ce.png)

We need to validate the vocabulary path, check for a WordPress function that can perform the validation.

"Next Step" goes to the next step.

### Step 4

![wl activation step 4 v4](https://cloud.githubusercontent.com/assets/11438/20138376/bb06491a-a688-11e6-821e-315ea9b7ef26.png)

The list of languages: English, 中文 (Chinese), Español (Spanish), Русский (Russian), Português (Portuguese), Français (French), Deutsch (German), Italiano (Italian), Nederlands (Dutch), Svenska (Swedish), Dansk (Danish), Türkçe (Turkish).

The list of languages must show only the language name in the original language (no need for the english translation). The preselected language should match the one selected in WordPress if available, otherwise english should be preselected.

"Next Step" goes to the next step.

### Step 5

![wl activation step 5 v4-1](https://cloud.githubusercontent.com/assets/11438/20141590/b4f859a8-a699-11e6-8677-d134cc4bff1f.png)

"Add your logo" opens WP's Media Browser to select an existing image or upload a new one. 

Once the logo is uploaded it is displayed, so that the user may delete it and upload a new logo:

![wl activation step 5 v4 copy-1](https://cloud.githubusercontent.com/assets/11438/20141570/9e4f7ad8-a699-11e6-8b33-5190f0e0eefd.png)

"Let's Start" saves the configuration and redirect to the *wp-admin* area.

Check the existing settings screen to see where each configuration parameter should be saved.

## Responsive

The UI is thought to be fluid in order to adapt to desktops and mobiles:

```
.box {
	width: 718px;
	min-height: 400px;
	/* mobile fallback */
	max-width: 100%;
	max-height: 100%;
}
```

<img src="https://cloud.githubusercontent.com/assets/10087639/20096296/84da6522-a5a9-11e6-9d73-960d4189765a.png" width="200"/>
<img src="https://cloud.githubusercontent.com/assets/10087639/20096298/84e11e62-a5a9-11e6-86f4-2a37aa54a5b5.png" width="200"/>
<img src="https://cloud.githubusercontent.com/assets/10087639/20096299/84e29d8c-a5a9-11e6-9cd1-8f946cb80b15.png" width="200"/>
<img src="https://cloud.githubusercontent.com/assets/10087639/20096302/84f1f200-a5a9-11e6-8e3b-83bc7853a58c.png" width="200"/>
<img src="https://cloud.githubusercontent.com/assets/10087639/20096303/84f705d8-a5a9-11e6-8b37-9a9a6f749ba9.png" width="200"/>

### Bullets

Bullets may use the following css code (please check that it is cross-browser):

```
.bullet {
	height: 8px;
	width: 8px;
	border: 1px solid #fff;
	border-radius: 50%;
	background-color: transparent;
}
/* this is the bullet of the current page */
.bullet.plain {
	background-color: #fff;
}
```

### Colors

* Gray (page background): `#f5f5f5`
* Blu: `#2e92ff`
* Black: `#000`
* White: `#fff`

### Input Styling

Suggested styling for input is provided here:
http://codepen.io/wanbinkimoon/pen/QGjMPx?editors=1100

### Other images

Please optimize the images using a tool like OptiPNG or similar.

The X sign:
![close-icon](https://cloud.githubusercontent.com/assets/11438/20138271/203601fa-a688-11e6-8de4-d99ff671c9eb.png)

'Circle, Square, Hexagon' logo:
![shapes-white](https://cloud.githubusercontent.com/assets/11438/20138297/41741c94-a688-11e6-8d89-beeb57cf8109.png)

Valid icon:
![combined shape-1](https://cloud.githubusercontent.com/assets/11438/20138449/1577faf6-a689-11e6-870b-6be9a2909bb1.png)

Invalid icon:
![combined shape](https://cloud.githubusercontent.com/assets/11438/20138446/0ee1daea-a689-11e6-8040-579d966db7e5.png)

**Comment by ziodave** [comment]
Currently the setup screen must be manually launched. We want a behaviour similar to WooCommerce.

WooCommerce performs a redirect to the _wc-setup_ page if three conditions are met:
* the transient '_wc_activation_redirect' is set,
* we're not already on the _wc-setup_ page,
* plugin state is _install_ (via `WC_Admin_Notices`).

**Comment by ziodave** [comment]
Integration tasks:
* style `a.button`s like `input.type[button]`, see 'Grab a Key' at step 2.
* style the `input[type=submit]` button, see 'Finish' at the final step.
* style the `.valid` / `.invalid` classes for `input`s.
* style the `.wl-logo-preview` class with the size for logo preview (100x100px?) and at `background-size: contain;` to keep the preview ratio.

**Comment by wanbinkimoon** [comment]
I just noticed that wordpress media manager seems to have some major issues on mobile. 
![screen shot 2016-12-19 at 16 33 48](https://cloud.githubusercontent.com/assets/10087639/21318330/08ba6d04-c609-11e6-83af-3070d779af35.png)

**Comment by novedavi** [comment]
Verified. This issue is correct, an enhancement is needed as per https://github.com/insideout10/wordlift-plugin/issues/427
