### ISSUE TITLE
Hard return on visual mode, moved the </span>, creating a formatting issue.

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#399]
The page Programma 2016, inside CamminandoCon - http://camminandocon.org/programma-2016/ - produces a bug.

When simply adding a "hard return" inside a paragraph in the visual editor, right after an annotated term, the </span> tag was moved as well
![screen shot 2016-11-17 at 12 35 20](https://cloud.githubusercontent.com/assets/18528457/20387934/dc57b6c2-acc2-11e6-850e-b62d2d89c647.png)
creating a formatting issue in the front end:
![screen shot 2016-11-17 at 12 40 15](https://cloud.githubusercontent.com/assets/18528457/20387988/168d10c6-acc3-11e6-807b-7c6fe6507717.png)

After saving the page, and additional </span> tag is then added.
![screen shot 2016-11-17 at 12 42 02](https://cloud.githubusercontent.com/assets/18528457/20388043/5d355056-acc3-11e6-8f82-eaada16446ed.png)
![screen shot 2016-11-17 at 12 41 35](https://cloud.githubusercontent.com/assets/18528457/20388051/625e849e-acc3-11e6-8743-e940d9630c5d.png)

**Comment by ziodave** [comment]
@novedavi I have difficulties understanding the issue, let's check this together.

**Comment by ziodave** [comment]
This should be solved with the new regex. Feel free to reopen.
