### ISSUE TITLE
Free months with 6 or 12 months packages should not delay the payment of the subscription

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#401]
Clients purchasing the 6-month or the 12-month package are given respectively 1 and 3 months free. 
Our original plan was to add the free months and the end of the subscription but process the payment immediately.
The only way to set this offer up on WooCommerce default settings, was to add the 1 or 3 free months as a free trial period, which delays the initial payment for the amount of the "free trial"
This is not correct since, after the 14 days "money-back-guarantee" period, the amount is due by the client and creates a financial credit risk, delaying the payment up to 3 full months.

**Comment by cyberandy** [comment]
Moved to GitLab.
