### ISSUE TITLE
New entity pop-up mechanism

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#405]
IMO we need to communicate the user – in a more explicit way – what change when WordLift runs. 
In order to accomplish this i think we should evaluate the possibility to declare the origin of the new entity arriving. 

Here some examples: 

![new_entity](https://cloud.githubusercontent.com/assets/10087639/20392888/11e5ef4a-acda-11e6-9d41-f9fde91a44c9.gif)  ![new_entity gif_2](https://cloud.githubusercontent.com/assets/10087639/20393413/29e89582-acdc-11e6-8c11-c21deb629bee.gif)

**Comment by ziodave** [comment]
Not conformant with how the classification box works at the moment (entities are loaded once). Feel free to reopen.
