### ISSUE TITLE
Duplicated entities are allowed from the backend

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#41]
If I try to create an entity from the backend (not from the widget) also duplicated entities are allowed. This behaviour makes the vocabulary inconsistent. A validation should be added on entity creation: it should be not possible to create entities with the same label. As enhancement, also the entity schema type could be considered in the label definition when the type is different from thing. This could allow to create for instance Rome both as place and organization.

**Comment by cyberandy** [comment]
In terms of enhancement it would be good to consider the use of _Thing > Property >_ **alternateName** to allow editors adding multiples labels for the same entity. 

The use of different entity types should be an intrinsic feature of the NED provided by Redlink (is this _Roma_ as a place or _Roma Capitale_ as an organisation?)

**Comment by ziodave** [comment]
First thing, we need an AJAX method in WordLift that, provided a *title*, returns whether an entity already exists with that title, its URI and its type.

**Comment by ziodave** [comment]
PR #48
