### ISSUE TITLE
Triples not showing on the WordLift dashboard

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#410]
![image](https://cloud.githubusercontent.com/assets/837037/20703326/95ee5f3a-b61b-11e6-96ce-91223cca9078.png)

I've noticed on wordlift.io that the triples counter is not progressing. Can this be related to the fact we're saving metadata to data.wordlift.io?

**Comment by mreichhart** [comment]
just scratching the issue: number of triples not shown completely..

![image](https://cloud.githubusercontent.com/assets/22288718/20705941/46e414d4-b625-11e6-881f-d27edff2ffa2.png)

**Comment by cyberandy** [comment]
Thx @mreichhart we need to fix this also.

**Comment by ziodave** [comment]
@cyberandy can you please check if WordLift's key is set in your install?

**Comment by ziodave** [comment]
The font-size has been solved.

**Comment by cyberandy** [comment]
The key is set ... 

![image](https://cloud.githubusercontent.com/assets/837037/20720788/d865898e-b660-11e6-8591-35f54e277818.png)

**Comment by ziodave** [comment]
Ok, this is due to that key being suspended, therefore the triples count returned 0. The triples count is cached 24 hours. In less than 24 hours you should see the correct count.

**Comment by cyberandy** [comment]
Yes works fine.
