### ISSUE TITLE
Add a toggle to disable WordLift's analysis on certain pages/post

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#412]
This feature request goes in the direction of giving more control to the user: 

"Automatically scanning a page whether we want/need it or not might not be very productive [...] I was wondering if it’s possible to manually disable WordLift parsing on certain pages/posts. This would save me a lot of time."

Somehow I believe that this shall go along with the possibility of adding entities to the article even when they are not detected by the analysis see issue #322.  

This can be also useful when you're writing an article. Some people prepare the blog post within the editor and don't need to look at annotations until they finish writing. 

A possible idea here is to de-activate the widget following the click of the user on the open/close icon on the WordLift Edit Widget.

**Comment by novedavi** [comment]
AriArt Italy asked for the same thing today during a live training

**Comment by cyberandy** [comment]
Here is another comment: 

> ... to have some sort of toggle button on the side that, when clicked, highlights the available entities. Then I can hover over them and select them as needed. When I'm done picking entities, I then toggle off the selector function, and when I do that the only words with any visible markup are just those that I've selected.

**Comment by cyberandy** [comment]
We got another request in this direction. This is becoming urgent.

**Comment by ziodave** [comment]
Publishing #330 would already help.

**Comment by ziodave** [comment]
@claudiopome can you make a storyboard for this?

**Comment by claudiopome** [comment]
@ziodave we might add an on/off button in order to let users disable wordlift while they are editing the posts 
<img width="297" alt="screen shot 2017-06-30 at 13 01 41" src="https://user-images.githubusercontent.com/5725682/27736076-d85e51f2-5da2-11e7-870c-4257a7b1f7ac.png">
![wordlift-on](https://user-images.githubusercontent.com/5725682/27736090-e934a076-5da2-11e7-9d38-5884c37a0f9e.png)
![wordlift-off](https://user-images.githubusercontent.com/5725682/27736094-ed87e55c-5da2-11e7-9483-61d55a568d78.png)

**Comment by claudiopome** [comment]
<img width="440" alt="screen shot 2017-06-30 at 14 54 37" src="https://user-images.githubusercontent.com/5725682/27736375-341f077e-5da4-11e7-9b7a-cb38dbbe41ad.png">
<img width="413" alt="screen shot 2017-06-30 at 14 55 12" src="https://user-images.githubusercontent.com/5725682/27736380-384de9dc-5da4-11e7-9c44-9ef3af1e9aad.png">

**Comment by claudiopome** [comment]
<img width="866" alt="screen shot 2017-06-30 at 16 23 27" src="https://user-images.githubusercontent.com/5725682/27740002-cfeaca1a-5db0-11e7-980c-bbc177c947a2.png">
<img width="860" alt="screen shot 2017-06-30 at 16 23 52" src="https://user-images.githubusercontent.com/5725682/27740008-d459e34c-5db0-11e7-8656-505d1f9d0342.png">

**Comment by claudiopome** [comment]
<img width="1150" alt="screen shot 2017-06-30 at 16 39 20" src="https://user-images.githubusercontent.com/5725682/27740553-b7a96338-5db2-11e7-9d20-64ab039b5500.png">
<img width="1142" alt="screen shot 2017-06-30 at 16 36 27" src="https://user-images.githubusercontent.com/5725682/27740558-bca14af4-5db2-11e7-9b70-56fbe4f77549.png">

**Comment by ziodave** [comment]
I think this is the way to go:

![image](https://user-images.githubusercontent.com/11438/27790377-e0158dea-5ff8-11e7-8999-8bec6a063a54.png)

**Comment by ziodave** [comment]
At the end we opted to disable the analysis if the metabox is closed (instead of launching it even when the metabox is closed).

WordPress remembers whether the user is keeping the metabox open or close.

If the metabox is closed, and the user opens it, then the analysis is launched.
