### ISSUE TITLE
Underlining pollutes the text editor

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#414]
See https://plus.google.com/b/112007778192372418730/photos/photo/105103058358743760661/6361517223418229186

We need to define a better use case for this.

**Comment by wanbinkimoon** [comment]
Linked page is no longer available 
![screen shot 2017-01-16 at 18 06 34](https://cloud.githubusercontent.com/assets/10087639/21992391/923768f2-dc16-11e6-8db1-cdf639278b45.png)

**Comment by ziodave** [comment]
Here it is:

![image](https://cloud.githubusercontent.com/assets/11438/21993796/595a21e6-dc25-11e6-8ac5-3d0e51f2dbbb.png)

**Comment by ziodave** [comment]
Moved to #440.
