### ISSUE TITLE
WordLift not working after updating to WP 4.7

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#415]
As reported by our client http://richtopia.com, when updating to WP 4.7, WordLift doesn't run properly. 
The client reported this error:
![error pic](https://cloud.githubusercontent.com/assets/18528457/21045542/2509fc8c-be01-11e6-8383-660ec8cfcdf2.jpg)
Checking on our test enviroment I get a 500 error when saving both a post or an entity page after running WordLift.
![screen shot 2016-12-09 at 11 12 54](https://cloud.githubusercontent.com/assets/18528457/21045571/3d3f185a-be01-11e6-81c1-ea2c961ceb4b.png)

**Comment by ziodave** [comment]
This is due to the new way hooks are handled.

**Comment by ziodave** [comment]
A fix is going under testing now.
