### ISSUE TITLE
Entities created by ConfineLive.it turn into 404

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#419]
A new client is creating entities which all result in 404 pages.
See example here: http://www.confinelive.it/notizie/comune/

The entity in the example was created directly from the widget.
The client setup the plugin with the correct key, language and adding the word "notizie" in the entity path field.

I can provide access to the site if needed.

**Comment by ziodave** [comment]
I think this is related to #361 , i.e. the permalink structure being set something different from **Post Name** (i.e. _/%postname%/_):

![image](https://cloud.githubusercontent.com/assets/11438/21182632/b0171c74-c20c-11e6-991e-53dbb27deb2b.png)

Can you check the permalink structure in http://www.confinelive.it/wp-admin/options-permalink.php ?
