### ISSUE TITLE
Entity metadata updating within the disambiguation widget does not work

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#42]
If I try to update an existing entity metadata (ea: description) the update does not work 
The bug is demonstrated by EntityCreationViaPostCreationTest->testEntityMetadataAreProperlyUpdated() (please uncomment assertion on raw 232 to let the test fail)
Entity updating should be managed properly in wl_save_entity() function ...
Entity updating should be performed only if needed (only if the current metadata are different from the saved one) in order to avoid unuseful calls to redlink api

**Comment by pieroit** [comment]
Partially closed. Right now a check is made on entity title, content and status. It should be done also on images, sameAs, schema type.

**Comment by pieroit** [comment]
Checks are done for all entity properties, unit tests updated.
