### ISSUE TITLE
Images in the Vocabulary appear oversized 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#421]
![image](https://cloud.githubusercontent.com/assets/837037/21232579/60470e6c-c2ec-11e6-8db0-8f20a4e7019b.png)

We've seen that while there is a constraint to keep images 50x50 - this constraint is not working on attachments. 

![image](https://cloud.githubusercontent.com/assets/837037/21232596/71387788-c2ec-11e6-8c3e-6f56134eaeee.png)

Here can be seen http://mico-gp.insideout.io/wp-admin/edit.php?post_type=entity

**Comment by ziodave** [comment]
`width` and `height` attributes appear to be missing on this install.

**Comment by ziodave** [comment]
The issue is related to the web site theme, _sleek_, which actively removes the `width` and `height` of images:
```
// Remove width and height dynamic attributes to thumbnails
// Remove width and height dynamic attributes to post images
add_filter('post_thumbnail_html', 'sleek_remove_thumbnail_dimensions', 10);
add_filter('image_send_to_editor', 'sleek_remove_thumbnail_dimensions', 10);

if( !function_exists( 'sleek_remove_thumbnail_dimensions' ) ){
        function sleek_remove_thumbnail_dimensions( $html ) {
                $html = preg_replace('/(width|height)=\"\d*\"\s/', "", $html);
                return $html;
        }
}
```

from file _themes/sleek/framework/functions/theme_functions.php_
