### ISSUE TITLE
Link to Dbpedia source should be target _blank

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#423]
When I was creating a new entity, WordLift suggested me a same as page from DBpedia. I clicked on the link on the right side to open the DBpedia page and check the content, and the page has been opened on the same tab of the browser. In this way I lost the changes to my article. 
It would be better if the links open in another window or tab with a target _blank.

**Comment by ziodave** [comment]
@Cupofbrain can you paste here a screenshot of the link we need to change?

**Comment by Cupofbrain** [comment]
I'm trying, but I can't reproduce this issue: now when I create a new entity WordLift never suggests me any sameAs. It may be solved in the WordLift latest release. 
I'd close it, since there is no evidence it's still happening.
