### ISSUE TITLE
Related articles needs to be limited and/or paginated

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#426]
As of today we don't provide any way to limit and/or control over the list of related articles displayed in the WordLift Edit Widget. 
![image](https://cloud.githubusercontent.com/assets/837037/21352535/36750088-c6c2-11e6-93ef-5b22980e6ed8.png)

This is something that needs to be addressed with a relevancy filter and the implementation of a limit (i.e. give me the top 5 most relevant articles) and/or a pagination mechanisms (in some cases there might be more than 5 articles to choose from).

**Comment by ziodave** [comment]
I've set a hard limit to 5 posts at the moment.
