### ISSUE TITLE
Add support for custom post types

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#428]
The analysis of WordLift right now cannot be used on custom post types as we need to know the actual semantic meaning of these custom post types before activating the editor.

**Comment by ziodave** [comment]
For example, a WooCommerce product should be mapped to a http://schema.org/Product.

**Comment by markkap** [comment]
A lot of flexibility was added in #596 including a filter to control which post types can "host" entities and set their default entity type.

Next step is a UI to let the admin configure it?

**Comment by ziodave** [comment]
We now support post/page as entities as well. This task may continue to add support for other custom types (e.g. WooCommerce's Product).

**Comment by ziodave** [comment]
This is supported via custom integration plugins.
