### ISSUE TITLE
Automatically avoid search engines to index entities with a low rating 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#434]
This requires #433 and ensures that search engines index only entities that bring concrete value to end users and that do not feature [duplicated content](https://moz.com/learn/seo/duplicate-content). In our case duplicate content is the content we provide from scratch. 

The procedure should remove the noindex tag to entity pages that have reached a minimum rating.

**Comment by ziodave** [comment]
Depends on #433 .

**Comment by gcuofano** [comment]
We also have a case where entities were already in the sitemap. Therefore, even though, the entity pages were placed in no-index they still get indexed.
