### ISSUE TITLE
Analysis might lock editor for too long

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#441]
When the analysis runs, the editor is locked, sometimes for too long. Can we find a solution?

**Comment by Cupofbrain** [comment]
Sometimes you don't need to edit your article, but just to copy some extract of it (a few lines, words, a short quote for social sharing...). In this case, it would be great if you could just **copy from the editor**, without actually changing anything. Is it possible?

**Comment by ziodave** [comment]
@Cupofbrain yes, to select and copy text is still possible, also when the editor is locked (which basically means read-only).

**Comment by Cupofbrain** [comment]
May this be a browser issue? See the gif. 
![wl-copy](https://cloud.githubusercontent.com/assets/24609125/23268679/c23beb86-f9ee-11e6-99c4-79a070995cfd.gif)

**Comment by ziodave** [comment]
Oh wow, no it happens to me as well on long articles. So we need to check this as well.

**Comment by ziodave** [comment]
The new analysis strategy in #330 greatly reduce the time waiting for the analysis, especially on longer texts. After #330 is deployed we need to decide whether to keep this issue open or not.

**Comment by ziodave** [comment]
@Cupofbrain I think we can close this one? 3.13 is much faster.
