### ISSUE TITLE
Entities consisting of two or more words with existing hyperlinks are not properly annotated

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#449]
Here is how to reproduce the issue: 

- create a new entity such as `modern architecture`
- remove the annotation and write again _modern architecture_ in the article
- add an hyperlink only to the word _architecture_ 
- run the analysis again  

![image](https://cloud.githubusercontent.com/assets/837037/22057978/7a3f2972-dd67-11e6-8cf4-fee402543ce1.png)

- while the entity is found it is impossible to select it and the front-end appears messed up (see below)

![image](https://cloud.githubusercontent.com/assets/837037/22058005/a0daff98-dd67-11e6-95ca-f9da72179ed4.png)

**Comment by ziodave** [comment]
This is solved as HREFs aren't annotated anymore.
