### ISSUE TITLE
Disable analysis on users' defined posts

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#450]
## Requirements
* Users need to have the chance to disable WordLift analysis

Some editors on specific posts or pages want to be able to disable WordLift analysis and annotation.

**Comment by ziodave** [comment]
Can you detail this issue? Is it front-end or back-end related?

**Comment by wanbinkimoon** [comment]
This issue is partially UI related and partially backend related.
We need to implement a solution that both:
1. makes disappear every annotation on the text and the body of the widget
2. prevent the plugin to add markup and content in the wp editor when used in text mode

**Comment by ziodave** [comment]
This has been fixed, feel free to reopen.
