### ISSUE TITLE
Improve schema:Article markup

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#451]
There's an interesting thread here:
https://plus.google.com/u/1/b/112007778192372418730/+TeodoraPetkova/posts/DZyQdF1sSUE?cfem=1

@jvandriel highlights some relevant points that we need to address:
- [ ] "topics aren't chained to the schema.org/Article, [...] while they should be chained to the schema.org/Article by means of properties like 'about', 'mentions', 'citation', etc."
- [ ] WordLift needs to "let you express the relation between the main entity of a page and the topic(s) its about."

Some background links:
* [How to use schema.org V2.0’s mainEntityOfPage property](http://www.seoskeptic.com/how-to-use-schema-org-v2-0s-mainentityofpage-property/)
* [Data Model: mainEntity(OfPage)
 ](http://schema.org/docs/datamodel.html#mainEntityBackground)
* [about the _about_](https://plus.google.com/106943062990152739506/posts/cEGdA1Gxu4X) ("using schema.org/about is that it can be specified multiple times eg, an Article can be about multiple topics.")
* [Add a mainEntity property that relates a page to the main thing it describes + inverseOf mainEntityOfPage](https://github.com/schemaorg/schemaorg/issues/301)

**Comment by jvandriel** [comment]
Thanks for picking up my comments. If there's anything I can do to help out just let me know.

**Comment by ziodave** [comment]
Following WordLift 3.10 release we need to improve on the following points:

- [ ]  if you specify a "width" or "height" value you should leave out 'px'. For example: "width":"4608px" should be "width":"4608".
- [ ] check about appending a fragment identifier (#MainEntityOfPage) to the Article's @id as such:
http://open.salzburgerland.com/en/post/marcel_hirscher_-_a_skiing_legend#MainEntityOfPage
- [ ] instances like:

```
"mainEntityOfPage": {
  "@type":"WebPage",
  "@id":"https://www.salzburgerland.com/en/salzburgerland/"
}
```

can be changed to:

```
"mainEntityOfPage":"https://www.salzburgerland.com/en/salzburgerland/"
```
- [ ] add support for the `about` property
- [ ] add support for _@reverse_

**Comment by cyberandy** [comment]
Following today's discussion, @jvandriel suggests to select the entity for the `about` property by looking at the occurrences of entities appearing in `page title`, and heading elements (H1...H6).

**Comment by ziodave** [comment]
This is not relevant in our case, because the `@id` differs from the `url`, the `@id`is a full Linked Data persistent URI, while `url` is the actual web address of the article:

> check about appending a fragment identifier (#MainEntityOfPage) to the Article's @id as such:
http://open.salzburgerland.com/en/post/marcel_hirscher_-_a_skiing_legend#MainEntityOfPage

However we're not currently publishing the `url` property for the Article and I am unsure whether we should.

**Comment by ziodave** [comment]
It might be useful to add `@reverse` on the JSON-LD for the entity, not in the context of the `Article` though since a correct definition is already done via the `@id` property.

I'll create another issue for this.
