### ISSUE TITLE
When the plugin is installed in a directory not named "wordlift" initialization hook ignored

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#457]
which cause entity types to not be initialized and probably other problems

possible solution - replace 
add_action( 'activate_wordlift/wordlift.php', 'wl_core_install' );

with a proper call to register_activation_hook https://developer.wordpress.org/reference/functions/register_activation_hook/

**Comment by ziodave** [comment]
@markkap as an admin I cannot edit the Entity Types anymore:

![image](https://cloud.githubusercontent.com/assets/11438/24585954/5a3e07ac-179f-11e7-9ec6-9a5a03db654f.png)

Can you please have a look?
