### ISSUE TITLE
Analysis Works but the WordlLift Edit Widget does not display

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#466]
![image](https://cloud.githubusercontent.com/assets/837037/22821848/336c38dc-ef7d-11e6-95aa-23b75fc0e4f0.png)

Here is the error.

**Comment by markkap** [comment]
What I see when I try to access the relevant url is a wordpress 404 page which means that the file do not exist on the server or that the access to it is denied by the server's configuration.

Trying higher directories give me an "access denied" 403 code, which suggests that there is some configuration that prevent full or partial access to that part of the directory tree

**Comment by ziodave** [comment]
I tried the following:
* http://antoniotombolini.simplicissimus.it/wp-content/plugins/wordlift/readme.txt
* http://antoniotombolini.simplicissimus.it/wp-content/plugins/wordlift/LICENSE.txt

they yield 404.

While these:
* http://antoniotombolini.simplicissimus.it/wp-content/plugins/wordlift/wordlift.php
* http://antoniotombolini.simplicissimus.it/wp-content/plugins/wordlift/css/wordlift-ui.min.css

yield 200.

*It looks like the server is generically denying access to txt and html files*.

In fact also WordPress standard txt and html files aren't found:

* http://antoniotombolini.simplicissimus.it/license.txt
* http://antoniotombolini.simplicissimus.it/readme.html

**Comment by michelem09** [comment]
Thanks, it was a web server configuration problem.
