### ISSUE TITLE
Manually select an entity

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#467]
As an editor I would like to manually annotate the text by selecting an existing entity from the vocabulary. Right now I can only manually annotate and create a new entity.

**Comment by ziodave** [comment]
@claudiopome can you make a storyboard for this?

**Comment by claudiopome** [comment]
@ziodave @cyberandy once the user highlights the entity they want to add to the vocabulary, a tooltip appears below the entity letting them choose whether to create a new entity from scratch or add an existing one.

![01](https://user-images.githubusercontent.com/5725682/28021780-57362be2-6589-11e7-90ce-5d03576663bd.png)
![02](https://user-images.githubusercontent.com/5725682/28021779-57340ff6-6589-11e7-8950-726ca68ed354.png)

**Comment by ziodave** [comment]
I like the contextual tooltip, but what happens next, when the editor clicks on "Create New" or on "Add" ?

**Comment by claudiopome** [comment]
Basically, clicking on "create new" on the tooltip would be the same than clicking on "create new entity" on the right sidebar, the user, in fact, will need to complete te process of adding an entity (only a non-existing one) always in the "create new entity" meta box. Then when the "Add" button is clicked, the entity gets automatically added to the vocabulary

**Comment by ziodave** [comment]
> Then when the "Add" button is clicked, the entity gets automatically added to the vocabulary

This is not what we need: we need to allow the user to select an existing entity from the vocabulary.

**Comment by claudiopome** [comment]
@ziodave Probably I didn't explain myself. If the entity is already stored in the vocabulary, but for some reason, it doesn't get recognized after the analysis runs, then the user could manually re-add it to the entities using the "add" option in the tooltip.

**Comment by ziodave** [comment]
I need a way to select the existing entity, e.g. a _select_ element (like the one we use in settings screen for the publisher setting): it's not automatic.

**Comment by claudiopome** [comment]
1. The user selects the entity and opens the 'Create new entity' tab 

![01](https://user-images.githubusercontent.com/5725682/28290987-e581ca90-6b48-11e7-9237-2fc77a275fb1.png)
![02](https://user-images.githubusercontent.com/5725682/28290988-e582b46e-6b48-11e7-9fa3-a9f8a3adcb4e.png)

2. The 'link' icon adds the 'search existing' functionality since it's a new feature the tooltip on the rollover state works as an aid for the user 

![03](https://user-images.githubusercontent.com/5725682/28291115-6694c20e-6b49-11e7-8259-55a28afdd5da.png)
![05](https://user-images.githubusercontent.com/5725682/28291116-66996084-6b49-11e7-8ff3-25b3cd7de826.png)

3. When the 'search existing' icon is clicked an HTML select is attached to let the user search inside the vocabulary and add the existing entity to the current notation. 

![06](https://user-images.githubusercontent.com/5725682/28291214-cb59a998-6b49-11e7-9ac2-080c3d54fd03.png)
![07](https://user-images.githubusercontent.com/5725682/28291215-cb5a5df2-6b49-11e7-9a9c-5d07d80f6c29.png)

4. The entity is added to the notation within the current post 

![08](https://user-images.githubusercontent.com/5725682/28291242-e9d1e8b8-6b49-11e7-84b8-af3b6016a100.png)

**Comment by claudiopome** [comment]
I'm still working on the edge cases (like when there's no image or description for the searched entity 
![09](https://user-images.githubusercontent.com/5725682/28291311-347f6606-6b4a-11e7-9aa2-6f34860a227a.png)

**Comment by ziodave** [comment]
@claudiopome I'd like to propose a different flow which I discussed together with @mreichhart:

 1. the 'Create New Entity' button is hidden, unless a text is selected,
 2. the 'Create New Entity' button is renamed to 'Add Entity',
 3. when the editor selects a text, the 'Add Entity' button appears,
 4. if the editor clicks on the 'Add Entity' button, the button slides on the left and shows an autocomplete select, the 'Create New Entity' form is hidden,
 5. the autocomplete select text is prefilled with the selected text,
 6. the first option in the autocomplete select is 'Create {selected text}...'
 7. the other options are entries from the vocabulary that match the selected text,
 8. if the editor clicks on 'Create {selected text}...' then the select turns into the create new entity form following the usual flow, with the exception that, after the entity is created, it is added to the classification box, selected, and the form disappears (go back to step 1)
 9. if the editor clicks on an entity from the list, then the selected entity is added to the classification box, selected, the select disappears (go back to step 1)

In this process we need to handle the following edge case: the editor selection intersects, is contained, or contains another text annotation (selected or not).

**Comment by claudiopome** [comment]
[export1.pdf](https://github.com/insideout10/wordlift-plugin/files/1156153/export1.pdf)

**Comment by claudiopome** [comment]
@david here's the screens for the first solution if the editors click on 'Create {selected text}...'
![01](https://user-images.githubusercontent.com/5725682/28322445-67388cc6-6bd6-11e7-82d6-5351b9772235.png)
![02](https://user-images.githubusercontent.com/5725682/28322444-6737ccdc-6bd6-11e7-8bb1-6fc4807e33e8.png)
![03](https://user-images.githubusercontent.com/5725682/28322447-673a34d6-6bd6-11e7-8ec0-c925791ab945.png)
![04](https://user-images.githubusercontent.com/5725682/28322448-673c3934-6bd6-11e7-8e16-878b34992377.png)
![05](https://user-images.githubusercontent.com/5725682/28322446-6738a17a-6bd6-11e7-9cd1-1751f1c13be0.png)
![06](https://user-images.githubusercontent.com/5725682/28322443-67356122-6bd6-11e7-9f7e-97d912b2fd51.png)
![07](https://user-images.githubusercontent.com/5725682/28322449-677452c4-6bd6-11e7-8f7b-3daccf47a9c5.png)

**Comment by ziodave** [comment]
Here are the final storyboards, from a selected text:

 * create new entity:

![create_new_entity_from_selection](https://user-images.githubusercontent.com/11438/28844164-0b383e9c-7704-11e7-844a-524d17e73da2.gif)

 * select an existing entity:

![select_existing_entity](https://user-images.githubusercontent.com/11438/28844191-20db8e84-7704-11e7-9f5a-2fea6921c3dc.gif)
