### ISSUE TITLE
Chord Rendering Problem on Firefox  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#469]
![image](https://cloud.githubusercontent.com/assets/837037/22940817/77c92e86-f2e3-11e6-8dcb-d3518ff78d0b.png)

The configuration is the following:

- OSX Yosemite 10.10.5 (iMac)
- Firefox 51.0.1 (64 bit)

**Comment by ziodave** [comment]
Can you provide the URL to the web page?

**Comment by cyberandy** [comment]
Sure, here it is: http://magazine.greenpeace.it/entity/isola-di-lampedusa/

**Comment by ziodave** [comment]
It's a regression due to #383. At this point it's better to remove `text-anchor: initial` and to rename the `label` class into something that's hardly customized by themes (e.g. `wl-chord-label`).

**Comment by wanbinkimoon** [comment]
I commented the styles we added to fix issue #383 and changed te attributed class in `chord.coffee` line `150`

**Comment by ziodave** [comment]
In the commit there's a font color changed from black to white?

![image](https://cloud.githubusercontent.com/assets/11438/23021557/314bcd10-f455-11e6-8e99-2f4938226dd9.png)

**Comment by ziodave** [comment]
Need to fix font-size:

![image](https://cloud.githubusercontent.com/assets/11438/23100440/26b4f88c-f689-11e6-854e-5b06cad4a3ab.png)
