### ISSUE TITLE
Styling internal links to entity pages

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#47]
Styling internal links directed to **entity pages** can be a good practice to let users know when they are being sent to an internal resource. 

These links are useful for three reasons:
- They allow users to navigate the website (this is true when there is a faceted search widget on the entity page)
- They help establish information hierarchy using the network of entities
- They could help spread link juice (ranking power) around the websites (SEO).

Using Schema.org the links to entity pages could be defined as `WebPageElement > SiteNavigationElement`

**Comment by pieroit** [comment]
We added a CSS class `wl-entity-page-link` to every entity <a> tag. This is also reflected in the tests. A default styling is being added to the wordlift-plugin-js repo.
