### ISSUE TITLE
Providing the option of adding Linked Data URIs rather than asking the editor to create new entities when these entities don't exist in the vocabulary 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#472]
When creating an entity in some cases we have properties that points to other entities, for example an organization is linked to its co-founders using the `founder` property of schema.org. 

Right now the user can choose an entity accordingly to the supported type available in his/her own vocabulary or create a new entity. This could be improved by adding a third option and revising the overall user experience we have for these type of fields. 

Creating a new entity just for the sake of filling up a property is not always the best option for the user. There are two situations where a user might not like the idea of creating a new entity: 
- the entity is well known and the editor doesn't want to create it on his/her vocabulary simply because might not be relevant 
- I have already created with WordLift that same entity on another website I work for and I would like to re-use that specific instance 

The best option would be: 

1. Check if the entity is already in the local vocabulary
        _if not_ 
2. Check if the entity is already available elsewhere (in the public LOD or in data.wordlift.io)
       _and in any case_  
3. Ask the user if he/she wants to create the entity in his/her vocabulary as _new entity_

This issue is somehow related to the improvement of the metaboxes #356.  
An interesting example is provided by the widget that uses the Google Knowledge Graph search.

![image](https://cloud.githubusercontent.com/assets/837037/23161229/a0d3b9b8-f829-11e6-83e8-382d88b5238d.png)
 
See here for more info: https://developers.google.com/knowledge-graph/how-tos/search-widget-example

**Comment by ziodave** [comment]
Related to #467 (in combination with the Autocomplete Select).
