### ISSUE TITLE
Entity Lookup in Metabox presents multiple aliases for the same entity

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#473]
![image](https://cloud.githubusercontent.com/assets/837037/23033595/f39a2844-f478-11e6-96ff-b8e1e48b70b7.png)

In this case I am adding an affiliation for an `entity type=person`. When I start writing I can chose between two results, the reality here is that both results are aliases of the same entity. 

At this level I expect to see just one result per entity. 

Somehow this one relates also to #356

**Comment by markkap** [comment]
core problem is in wl_entity_get_by_title getting a union of results from the post title and alt label meta which might end up having two results per entity, one from each "search". Punting to @ziodave as he said there is an sql solution for that.
