### ISSUE TITLE
Preserve alternative labels when an entity is saved in the local vocabulary 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#477]
A good example is when the entity is found thanks to an acronym by the NLP the first time (ie. "MDA" is detected and is the acronym for for "IBM Monochrome Display Adapter") - when the entity is save in the local vocabulary only the primary name for the entity is stored ("IBM Monochrome Display Adapter" in this specific case). The second time that the user analyses a text containing MDA the detected entity is not from the local vocabulary but from the cloud. 

We need to save all the alternative labels for an entity so that the entity is found and interlinked with the local vocabulary.

**Comment by ziodave** [comment]
Since we don't receive the additional labels from the analysis results (I'll double-check that) we will add the text annotation label as synonym to the entity (new or existing).

**Comment by ziodave** [comment]
I can confirm we don't receive additional labels.

**Comment by ziodave** [comment]
We don't have alternative labels, so we're using the annotation text as additional synonyms.
