### ISSUE TITLE
Add the possibility to configure NOLINK by default 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#485]
In #335 WordLift introduces the possibility to add/remove links from the annotated entities. 
The default behaviour is that a link is created every time the editor picks up an entity. 

In some cases though, the opposite (links are not created unless the editor decides to do so) would be preferable.  

This configuration could be done in WordLift's configuration panel.

**Comment by ziodave** [comment]
We need to take into consideration that the Navigator could be impacted.

**Comment by wanbinkimoon** [comment]
I tried to design the simplest and most explicit solution possible 
![no link](https://cloud.githubusercontent.com/assets/10087639/24348365/bd8396d8-12db-11e7-808e-c47546e46f82.png)

**Comment by ziodave** [comment]
This is incorrect:

![image](https://cloud.githubusercontent.com/assets/11438/24348432/5efa0e54-12e4-11e7-84d7-3e50f57e9bfb.png)

The setting applies to all the entities, including existing ones.

**Comment by wanbinkimoon** [comment]
Copy fixed
![nolink](https://cloud.githubusercontent.com/assets/10087639/24348495/3613924c-12dc-11e7-816e-73b7647d78bd.png)

**Comment by ziodave** [comment]
* [ ] create the setting (and update the related settings page)
* [ ] update the function `link` to behave according to the global settings and then allow exceptions on behalf of the `wl-no-link` / `wl-link` (new) class
* [ ] update the classification widget to display link / no link by default according to the setting (@ziodave)
