### ISSUE TITLE
Adding support for editing categories when using Quick Edit from the Vocabulary

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#487]
As we've introduced the possibility to add categories #442 for entities it would be nice to have the option of configuring the category straight from the quick edit link. 

Example: 

Here is the quick edit of an entity: 
![image](https://cloud.githubusercontent.com/assets/837037/23943646/67f1f274-0970-11e7-9625-be1dd18bd315.png)

Here is the quick edit of a blog post:
![image](https://cloud.githubusercontent.com/assets/837037/23943665/7ebfd764-0970-11e7-9516-4d1399eb974f.png)

**Comment by markkap** [comment]
@cyberandy @ziodave After digging into it, apparently wordpress actually want to show the categories and enity type in the quick edit but we use css to hide that section of the quick edit (which is the wrong way to go about it). with the following css

.inline-edit-entity .inline-edit-categories {
  display: none;
}

Not sure about the original reasoning for hiding this, so the question is should only the categories be enabled, or entity types as well?

**Comment by ziodave** [comment]
Only the categories.
