### ISSUE TITLE
When changing the type of an entity the color coding in the text is not consistent 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#49]
When I change the type of an entity using the WordLift Edit Post Widget (in this case I'm changing the entity Kepler-22b from `Thing` to `Place` 
![image](https://cloud.githubusercontent.com/assets/837037/9352852/7f15cb40-4664-11e5-954a-aaccd2b9e45b.png) the underlying below the entity remains black (`Thing`). 

The expected behaviour would be to see the underlying changing from black to orange accordingly.

**Comment by mcolacino** [comment]
The issue was fixed in this way: it's possible to change the entity type only if the entity has no disambiguated occurrences within the current post content: in this case a disabled input is shown instead of the standard select.
