### ISSUE TITLE
Add id propriety to the json-ld script printed by WordLift  

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#492]
I think that could be useful have a solid hook on the json-ld script printed by WordLift in the head of webpages which are affected by the plugin. I think that a solid and persistent  `id ` could also help us to develop widget and scripts without facing the risk of get in conflict with others json-ld in page.

**Comment by ziodave** [comment]
The JSON-LD is currently loaded asynchronously, so that wouldn't help.

Closing for now, feel free to reopen.
