### ISSUE TITLE
Re-writing Freebase sameAs links

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#499]
Currently for entities linked with Freebase, WordLift adds an `owl:sameAs` link to Freebase triples using URIs like `http://rdf.freebase.com/ns/m.025v4rr`. These URIs since the Freebase API have been shut down (April 2016) do not work. 

In Freebase, objects have MIDs that look like `/m/025v4rr`. In RDF those MIDs become `m.025v4rr`. Likewise, Freebase schema like `/common/topic` are written in RDF as `common.topic`. 

The existing links to Freebase, by preserving the same MIDs, can be converted from let's say `http://rdf.freebase.com/ns/m.025v4rr` into `https://g.co/kg/m/025v4rr` just like wikidata does when referencing entities that are now part of the Google Knowledge Graph and that share the same MID as Freebase.

**Comment by cyberandy** [comment]
Here are some useful insights to be considered https://github.com/code4lib/shortimer/issues/38

**Comment by ziodave** [comment]
This has been implemented in the server.
