### ISSUE TITLE
Setup Wizard behaviour with long translations

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#500]
**1. First Step.** WordLift's Setup Wizard does not wrap text in the list of values, so the items overlap.
(In Italian I used as a workaround a shorter alternative translation, so you can't see the screen below anymore.)

![schermata_2017-03-17_alle_15 41 27_720](https://cloud.githubusercontent.com/assets/24609125/24155483/436493a6-0e54-11e7-81c8-6e0747afc109.png)

**1. Second Step.** The button should adapt itself to the number of characters of the CTA. 

![schermata_2017-03-21_alle_16 24 08_720](https://cloud.githubusercontent.com/assets/24609125/24155586/8d673684-0e54-11e7-8085-88fe2ec9d088.png)

**Comment by ziodave** [comment]
@wanbinkimoon all the buttons need to be fixed as we cannot foresee how long a text will be in another language:

![image](https://cloud.githubusercontent.com/assets/11438/24585858/e5366690-179c-11e7-8bd6-8c4a5f7fdcfc.png)
