### ISSUE TITLE
*.html Templates contain text which can not be translated

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#504]
The article metadata for example contains the strings "Article metadata", "Topic", etc...

Since this is neither PHP nor JS it is impossible to translate.

@ziodave, This will need some restructuring of the code, and I am not sure which direction will be best  here (do the templates in PHP or go for JS parameters)

**Comment by ziodave** [comment]
Related to #308 . Not a blocking bug.

**Comment by ziodave** [comment]
Closing in favor of #804.
