### ISSUE TITLE
Add support for the about property

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#511]
Select the entity for the about property by looking at the occurrences of entities appearing in page title and heading elements (H1...H6).

**Comment by ziodave** [comment]
In order to avoid too much load on WP we're considering the _title_ only for the time being.

I'll create a follow up task in order to move this processing on the cloud and include also _headings_.

**Comment by cyberandy** [comment]
While testing I've noticed this one is also affected by #477

**Comment by ziodave** [comment]
#477 is technically unrelated.
