### ISSUE TITLE
Add the occurrences of an entity within an article by default in Content Classification

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#514]
Currently under Content Classification in the WordLift editor, by default WordLift returns a zero:

![screen shot 2017-04-10 at 10 51 25](https://cloud.githubusercontent.com/assets/26247261/24853525/abe80110-1ddb-11e7-96b7-400384518edf.png)

In order to understand how many times a word occurs within an article I have to click on it: 

![screen shot 2017-04-10 at 10 52 46](https://cloud.githubusercontent.com/assets/26247261/24853577/ddd587c4-1ddb-11e7-994b-140693cb1cfa.png)

For a content creator it would be very useful to have that information by default. Thus, instead of showing a zero, show the number of occurrences by default.

**Comment by ziodave** [comment]
The indicator was meant to show the number of *selected* annotations. If we change the behavior to show the number of *available* annotations, how should it behave when the user deselects an annotation, should it keep the number of *available* annotations?

**Comment by cyberandy** [comment]
It can become a bit confusing. The problem I also have with this implementation is the number `0`.
 
I believe that, as originally designed by @wanbinkimoon in #335, we shall replace the `0` with the `+` sign 

![image](https://cloud.githubusercontent.com/assets/10087639/21542603/3a12d504-cdbf-11e6-9b39-b083f38f4fa6.gif)

**Comment by ziodave** [comment]
Ok, so the aim of this issue is just to replace the initial `0` with `+` ?

**Comment by wanbinkimoon** [comment]
@ziodave yes
