### ISSUE TITLE
Visual Composer tags appearing in the article's description  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#516]
https://search.google.com/structured-data/testing-tool/u/0/?url=http://www.markcom.it/presenza-online-efficace-azienda/#url=http%3A%2F%2Fwww.markcom.it%2Fpresenza-online-efficace-azienda%2F

As seen from the link above in the entity description the tags from the Visual Composer Pagebuilder for WordPress by WP Bakery shall be removed. In this specific example we can also see HTML code that is not supposed to be there. 

![image](https://cloud.githubusercontent.com/assets/837037/24864877/d4d8003c-1e05-11e7-8ffb-979cccc64100.png)

**Comment by ziodave** [comment]
We're using WP's own `get_the_excerpt` which is supposed to cleanup shortcodes and html:

> The auto-generated excerpts have all shortcodes and tags removed which means it is just an unformatted string that would not see any line-breaks in any form of output, since the actual line-breaks in the raw text are also removed.

(see https://codex.wordpress.org/Function_Reference/get_the_excerpt)

Therefore something else installed on this specific WP instance is preventing that from happening, or is the excerpt manually set?

**Comment by ziodave** [comment]
Which version of Visual Composer is installed on the web site? Versions prior to 3.4.9 are known to have issues:
https://wpbakery.atlassian.net/wiki/display/VC/Release+Notes

**Comment by ziodave** [comment]
I can see, 09.03.2017 - ver 5.1.

**Comment by ziodave** [comment]
There's some filter which is preventing the shortcodes from being removed. The html code is removed, but then this is added again:

`<br><br><a class="readmore" href="http://www.markcom.it/2017/04/alternative-a-ubersuggest/">Approfondisci</a>`

- [ ] We can control the more text for WordLift however, so this is surely an action point.

**Comment by ziodave** [comment]
I think at the end of the day that it's better for us to call again
* [wp_strip_all_tags](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/)
* [strip_shortcodes](https://developer.wordpress.org/reference/functions/strip_shortcodes/)

to avoid any conflict with any potential customization, plugin or theme on a WP instance.

**Comment by markkap** [comment]
generating the excerpt by ourselves will help get us to old age easier and
in better health. there is enormous amount of unrelated junk being stuffed
into the `the_content` and `the_excerpt` filters, usually by social
plugins, but not only them.

On Tue, Apr 11, 2017 at 12:02 PM, David Riccitelli <notifications@github.com

**Comment by ziodave** [comment]
It's important to highlight that WP only removes shortcodes it knows. Is it possible that some plugins have been removed from the web site?
