### ISSUE TITLE
Adding support for schema.org/Recipe  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#524]
We had recently collected 3 new requests to add this type that was already introduced in our roadmap by SLT. It's becoming important.

**Comment by ziodave** [comment]
@cyberandy there are many properties for `Recipe`: http://schema.org/Recipe

Which ones are we looking to support?

**Comment by cyberandy** [comment]
I believe we can start with the basic one as seen here: https://github.com/brainstormforce/all-in-one-schemaorg-rich-snippets/blob/master/meta-boxes.php (for recipe)

**Comment by cyberandy** [comment]
Some more documentation to take into account: https://developers.google.com/search/docs/data-types/recipes

**Comment by cyberandy** [comment]
Here is an example from SLT and the corresponding rich snippet:

```
<script type="application/ld+json">
{
 "@context": "http://schema.org",
 "@type": "Recipe",
   "name": "Pinzgauer Kasnockn",
"alternateName": "Pinzgauer Kasnocken",
"recipeCuisine": "Österreichische Küche",
   "image": "https://www.salzburgerland.com/de/magazin/wp-content/uploads/2012/04/Newsletter3_tipp_Kasnocken.jpg",
   "author": 
   {
      "@type": "Person",
      "name": "Ulli Hammerl",
      "url": "https://www.salzburgerland.com/de/magazin/author/uhammerl/",
"SameAs": "http://open.salzburgerland.com/de/user/uhammerl"
    },
   "datePublished": "2012-01-17",
   "dateModified": "2017-03-22",
    "recipeIngredient": [
"250 g Mehl",
"2 Eier",
"1/8 l Wasser",
"1/8 Liter Milch",
"Salz",
"30 g Butter",
"100 g Zwiebeln, klein gewürfelt",
"150 ml Gemüsebrühe",
"200 g Käse (Pinzgauer Bierkäse)",
"30 g braune Butter",
"100 g Zwiebel",
"1 Handvoll Schnittlauch"
    ],
    
"recipeInstructions": [
"Mehl mit den Eiern, Milch, Wasser und etwas Salz mit einem Kochlöffel kurz zu einem Nockerlteig verrühren. Wichtig: Nicht lange rühren, nur grob zusammenmischen! Den Teig einige Minuten ziehen lassen. Anschließend durch ein groblöchriges Sieb (oder durch ein verkehrt gehaltenes Reibeisen!) in kochendes Salzwasser hobeln. Kurz (ca. 3 Min.) kochen lassen, bis die Nockerl an der Oberfläche schwimmen. !" 
],
    "description": "Pinzgauer Kasnockn: Auf den Skihütten im SalzburgerLand einer der Klassiker! Jetzt daheim nachkochen - einfach zu machen und extrem gut.",
     "recipeYield": "4 Portionen",
"prepTime": "PT10M",
"totalTime": "PT0H30M"
}
</script>
```

![image](https://cloud.githubusercontent.com/assets/837037/25483285/765f5cf0-2b55-11e7-8267-b55f09d05ca0.png)

**Comment by Rainer-Edlinger** [comment]
This Plugins looks nice: https://wordpress.org/plugins/wp-recipe-maker/

Using the functions of that Plugin including a mapping to existing WL-Entities would be great ;-)

**Comment by ziodave** [comment]
These are strings:
* recipeCuisine
* recipeIngredient
* recipeInstructions
* recipeYield

These are durations, so we need a proper way for editors to insert these data:
* prepTime
* totalTime

**Comment by ziodave** [comment]
* [ ] taxonomy term
* [ ] schema definition
* [ ] prepTime and totalTime widgets
* [ ] JSON-LD

**Comment by ziodave** [comment]
Code Review:

## src/admin/WL_Metabox/WL_Metabox_Field_duration.php and WL_Metabox_Field_multiline.php

### Redundant constructor

Removing:

```
	public function __construct( $args ) {
		parent::__construct( $args );
	}
```

### File naming issues

There's no need to continue the wrong practices we had with naming the files and classes in "WL_Metabox":

1. Filenames should be all lowercase with hyphens as word separators. E.g. expected wl-metabox.php, but found WL_Metabox.php
2. Class file names should be based on the class name with "class-" prepended. E.g. expected class-wl-metabox.php, but found WL_Metabox.php

Renaming `WL_Metabox_Field_duration` to `Wordlift_Metabox_Field_Duration`

**Comment by cyberandy** [comment]
While testing for the QA I noticed the following: 

- fields and input format can be ambiguous and we shall at least provide labels for each field along with some examples (this is particularly important for prepTime and totTime)
- I miss the cookTime (http://schema.org/cookTime)
- the number of calories also could be helpful (http://schema.org/calories)

These should be enough - I will open another issue for displaying the data on the website. As we do for other types (not for all types) - in this case, it can be very helpful to create a widget that - for every article that mentions a recipe displays its basic information. 

This is also particularly important since the description in our implementation does not correspond with the preparation. So I have to do the input twice (once for the body of the entity and once for instructions).

**Comment by cyberandy** [comment]
While working on the CamminandoCon website I have noticed the following problem:
- minutes for the recipe total time cannot be entered - after adding the numbers and saving the format error is displayed (this works on test.wordlift.io)  

![image](https://user-images.githubusercontent.com/837037/28463557-4f920cda-6e21-11e7-9998-0536586a5c2e.png)

**Comment by cyberandy** [comment]
Another minor issue: the remove button for the author has a different size. (I'm on Chrome Version 59.0.3071.115 - 64-bit). 

![image](https://user-images.githubusercontent.com/837037/28463757-6c2fc372-6e22-11e7-90a1-4fc44a0ab5a1.png)
