### ISSUE TITLE
Content dynamically posted should follow a relevancy order

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#525]
This is somehow related to #323.  We now have events ordered chronologically - it would be great to have also a _relevance-based_ ordering for the other entity types. Let's look here for example (this is indeed a comment from @novedavi) http://camminandocon.org/wl_entity_type/place/ - this one should present at first the most connected entities (most connected to both entities and articles).

**Comment by ziodave** [comment]
@markkap I think it would be nice here to actually split the class into an event- and a default-entity ordering class, maybe with an abstract class with common functions for validating the current request.
