### ISSUE TITLE
Multisite network activation fails to create the entity types on newly created subsites

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#526]
There are basically two causes for that
1. we store the "current DB version" in a network global option which means that upgrade of the DB is done for only one subssite.

2. We do not actually initialize the entity types during upgrade.

@ziodave 1. is easily solved by using get_option instead of get_site_option in the upgrade, but 2 needs some thinking. Probably should just call "activate" if the version option is not set at all, but than maybe we do not need the trigger on plugin activation.

**Comment by markkap** [comment]
we agreed tht th activation should use the upgrade path for setup

**Comment by ziodave** [comment]
- [ ] add _unit tests_
