### ISSUE TITLE
Error fetching angular-animate.min.js

### ISSUE THREAD

**Issue by daylanKifky** [insideout10/wordlift-plugin#527]
Apparently `angularjs.org` is down at the moment.
It can be fixed changing 

```
wp_enqueue_script( 'angularjs-animate', 'https://code.angularjs.org/1.3.11/angular-animate.min.js' );
```

for

```
wp_enqueue_script( 'angularjs-animate', 'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.11/angular-animate.min.js' );
```
in src/wordlift.php:192

**Comment by ziodave** [comment]
it appears to be still down, I think we need to push soon a hotfix on wp.org using CloudFlare.

**Comment by ziodave** [comment]
This is happening again, we need to move away from code.angularjs.org

**Comment by ziodave** [comment]
Published to WP.org, v3.14.4
