### ISSUE TITLE
The components-font-awesome directory is 1.2 M

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#529]
Do we really need 1.2 M of _components-font-awesome_ directory?

**Comment by markkap** [comment]
@ziodave if the font is actually being used, can always make a subset with http://fontello.com/

**Comment by ziodave** [comment]
Great, I am not sure which font is being used. I noticed that we also have a _fonts_ directory in the root with more font-awesome fonts which might be redundant.
