### ISSUE TITLE
Links not working properly on Chord widget for DOL

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#530]
I've just noticed that the chord on the homepage of [DOL](http://www.degreesoflatitude.com/) has links but these don't work as expected.

![image](https://cloud.githubusercontent.com/assets/837037/25694148/6366ee3a-30ad-11e7-8ae7-45116fffb48a.png)

> It might be an issue with the theme and not related to WordLift.

**Comment by ziodave** [comment]
it's also not responsive:

![image](https://cloud.githubusercontent.com/assets/11438/25694192/13647494-30b6-11e7-8579-5adfc3fc5290.png)

**Comment by ziodave** [comment]
It's a css conflict of some sort which causes the tooltip to appear and cause a mouseout event, causing a flickering.

Adding the following style will fix:
`.home .tooltip { margin-left: 10px; }`

We should change the class anyway from `tooltip` to `wl-chord-tooltip` as `tooltip` is too generic and could conflict with other class definitions.
