### ISSUE TITLE
Inform the editor when a subscription is not active

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#534]
Here it would be good to provide also a quick link to simply re-activate the subscription by accessing to the WL website.

**Comment by ziodave** [comment]
When a subscription is not active, WordLift metabox in the post edit screen looks the same as if the subscription is active. This may mislead the editor into trying to perform usual actions, such as create a new entity:

![image](https://cloud.githubusercontent.com/assets/11438/25754662/b6819a7c-31c8-11e7-84ac-649dd195ae1c.png)

**Comment by inetbiz** [comment]
I believe you should offer a freemium offer at https://wordpress.org/plugins/wordlift/ that allows entities to be created within the domain as a CPT. Just don't go out and aggregate other sources such as wikidata and wikipedia to be imported back to domain.

**Comment by cyberandy** [comment]
Thanks @inetbiz for your feedback.

**Comment by Cupofbrain** [comment]
When a subscription is not active, WordLift metabox in the post edit screen looks like this now:

![schermata 2017-06-21 alle 16 03 12](https://user-images.githubusercontent.com/24609125/27388250-407c3858-569b-11e7-80e0-e17d3c585e3c.png)

**Comment by ziodave** [comment]
Yes, we can customize this message using POEdit.
