### ISSUE TITLE
Translate all labels in plugin languages in the Faceted Search Widget 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#537]
![screen shot 2017-05-12 at 16 35 19](https://cloud.githubusercontent.com/assets/26247261/26002838/283fac5e-3731-11e7-8475-4a86f2df165e.png)

**Comment by ziodave** [comment]
The translation can be added via POEdit:

![image](https://cloud.githubusercontent.com/assets/11438/26780159/08d97318-49f1-11e7-8b63-402f22d6db45.png)
