### ISSUE TITLE
AMP version of a page with a map displays a gray box

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#541]
We should avoid the gray box. @cyberandy can you link the actual page and the AMP preview?

**Comment by cyberandy** [comment]
https://wordlift.io/tnw-conference-2017-mom-packing-bags-amsterdam/amp/

**Comment by ziodave** [comment]
This happens because the `div`'s width/height are set in the HTML code (via PHP). Since AMP prevents the JavaScript from loading, the `div` remains empty.

**Comment by cyberandy** [comment]
I also noticed that the same behavior applies to the chord widget.

**Comment by ziodave** [comment]
Opened #551
