### ISSUE TITLE
Tweaks or possible improvements (no issues)

### ISSUE THREAD

**Issue by apilot52** [insideout10/wordlift-plugin#542]
UI is easy to use, once you figure it out. However, I think it could be more intuitive with minor tweaks. 

First, for example, automatic highlighting of potential entities is good, but more involved if it is NOT the word you want highlighted. Sometimes I need to add an adjacent word to the entity which is not an easy process. In other words, it would help to be able to deselect a highlighted wordlift word without going into the text editor to remove wordlift’s markup.

Second, I want to be able to edit the vocabulary page (the page that lists all the entities) the same way I can edit posts or pages in wordpress. One solution might be to have wordpress create a page, then put a shortcode in the content section which then lists all the entities. Since the vocabulary page is virtual, and not a page or post, there is no way to add SEO metrics to it. 

Otherwise I have no way to edit thing like title, description, or any other meta data (ie: rel = canonical ) for the vocabulary page.

-just some ideas, otherwise awesome plugin!!

**Comment by cyberandy** [comment]
Thanks for your inputs @apilot52, we've them both under our radar. The first issue is described in #296 and can really make the UX smoother in a lot of cases. 

The second one is a more strategic one but we've started to look at it just recently. Entities right now are CPT in WordPress but of course, a lot of people might already have these content structured on their site as CPT (think for instance of products being created in WordPress with WooCommerce) and/or existing articles. Have a look at #540 and specifically [how we're planning to approach the issue](https://github.com/insideout10/wordlift-plugin/issues/540#issuecomment-302311570). This, we believe, it is really going to be a game changer to let our users get started with WordLift without the need to revise completely the information architecture of the site.
