### ISSUE TITLE
Analysis does not start

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#545]
The analysis doesn't start. Here is what we found on the developer's console. Not sure if it is related to the issue. 

![image](https://cloud.githubusercontent.com/assets/837037/26621717/f9610584-45e7-11e7-866c-5e59faf72842.png)

**Comment by ziodave** [comment]
Can we get an access to the admin area to understand the root cause of the issue?

**Comment by cyberandy** [comment]
yes I'm sending you the credentials

**Comment by ziodave** [comment]
This is the error:
```
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"entities":{"http://dbpedia.org/resource/Network_packet":...}```

**Comment by ziodave** [comment]
This is due to our call:

```
if ( $analysis = wl_analyze_content( file_get_contents( "php://input" ) ) ) {
 ...
```

**Comment by ziodave** [comment]
We don't use `$HTTP_RAW_POST_DATA`, it seems to be an issue related to PHP 5.6:

> The only fix is for users to add this to their php.ini:
> always_populate_raw_post_data=-1


See also:
 * [Php 5.6 "Automatically populating $HTTP_RAW_POST_DATA is deprecated"](https://github.com/piwik/piwik/issues/6465)
* [Doc Bug #66763	always_populate_raw_post_data=0 BC issue with in-built web server](https://bugs.php.net/bug.php?id=66763)
* [PHP Warning: $HTTP_RAW_POST_DATA is deprecated](https://forum.piwik.org/t/php-warning-http-raw-post-data-is-deprecated/13952)
* [PHP 5.6: “Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version.”](https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/)
* [""PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version."](https://github.com/woocommerce/woocommerce/issues/8848)
* [Warning about `$HTTP_RAW_POST_DATA` being deprecated](https://stackoverflow.com/questions/26261001/warning-about-http-raw-post-data-being-deprecated)
