### ISSUE TITLE
Validate URIs

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#547]
In the _sameAs_ entity metabox, I found a URL with a space before the `http` protocol, and it wasn't pushed because of this error.

We should validate URLs fields.

**Comment by markkap** [comment]
@ziodave the JS code actually works for multiple "sameas" but it is ugly to have multiple elements with the same id in the DOM. I guess all the metabox fields code should be changed to use classes instead of IDs.

**Comment by ziodave** [comment]
Becase of the #608 we need to review this one from scratch.
