### ISSUE TITLE
The WordLift's Editor is picking up old description in "Entity Description" 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#554]
An entity named "Artista" was created thru WordLift editor. 
It was then customized. Although the text of the entity has been customized the editor still shows the old entity description coming from DBpedia: 

![screen shot 2017-06-06 at 15 57 18](https://cloud.githubusercontent.com/assets/26247261/26832917/3702ab66-4ad1-11e7-832c-85217f7a2c8d.png)

![screen shot 2017-06-06 at 15 58 37](https://cloud.githubusercontent.com/assets/26247261/26832941/4e329ba2-4ad1-11e7-945b-f5df5887e120.png)

**Comment by ziodave** [comment]
This issue also related to #332.

**Comment by ziodave** [comment]
Related to #556.
