### ISSUE TITLE
In WP backend "View Linked Data" and "Test Google Rich Snippets" buttons to be shown 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#555]
"View Linked Data" and "Test Google Rich Snippets" need to show up in the editor 

![screen shot 2017-06-06 at 16 43 14](https://cloud.githubusercontent.com/assets/26247261/26835127/c7e2f90a-4ad7-11e7-9afa-5e5009dbdb02.png)

**Comment by ziodave** [comment]
Is the entity published? It doesn't look so, since also WordPress' own "View" button is missing.

**Comment by gcuofano** [comment]
It seems to be published, from here you can see the link to it: http://www.solaris.it/index.php/vocabulary/artista/

**Comment by ziodave** [comment]
What about the permalink structure?

**Comment by ziodave** [comment]
I can see that also WP's own buttons are missing, this is how it should look like:

![image](https://user-images.githubusercontent.com/11438/26836237-fa76618a-4ae2-11e7-9b93-56494be8b0b5.png)

**Comment by ziodave** [comment]
This plugin is hiding our buttons:

https://it.wordpress.org/plugins/edit-flow/

**Comment by ziodave** [comment]
Added compatibility in commit for #556.
