### ISSUE TITLE
Widgets don't load

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#559]
This is what appears in the Developer Console:
```
wordlift-faceted-entity-search-widget.min.js?ver=4.7.5:1 Uncaught ReferenceError: jQuery is not defined
    at wordlift-faceted-entity-search-widget.min.js?ver=4.7.5:1
    at wordlift-faceted-entity-search-widget.min.js?ver=4.7.5:1
```

**Comment by ziodave** [comment]
It appears the Faceted Search Widget doesn't declare its jQuery dependency:

```wp_enqueue_script( 'wordlift-faceted-search', dirname( plugin_dir_url( __FILE__ ) ) . '/js/wordlift-faceted-entity-search-widget.min.js' );```

**Comment by ziodave** [comment]
Beside the issue with the faceted search, we're experiencing the issue on a theme that is explicitly removing jQuery:

```
    function my_init()   
    {  
        if (!is_admin())   
        {  
            wp_deregister_script('jquery');  
      
          
        }  
    }  
    add_action('init', 'my_init'); 
```

**Comment by markkap** [comment]
not much to do against themes that remove jquery :( why would anyone do that at all?

**Comment by ziodave** [comment]
Closing this one due to lack of feedback.
