### ISSUE TITLE
"404" showing up on entity pages 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#564]
The entity base path has been removed during the configuration phase. The permalinks within the vocabulary seem they were created correctly. But when clicking on them a 404 error shows up: 

![screen shot 2017-06-19 at 12 54 03](https://user-images.githubusercontent.com/26247261/27281973-6cd5ea88-54ee-11e7-9d6d-5ecec74a7610.png)

![screen shot 2017-06-19 at 12 55 03](https://user-images.githubusercontent.com/26247261/27282008-89a7dbe4-54ee-11e7-8ba2-599484558cf9.png)

Here an example: www.tharawat-magazine.com/manhattan
The same entity is reachable at: www.tharawat-magazine.com/entity/manhattan/

**Comment by ziodave** [comment]
It's not possible to use an empty vocabulary path when permalinks are set to `%category%/%postname%`.

See
 * https://github.com/insideout10/wordlift-plugin/issues/419
 * https://github.com/insideout10/wordlift-plugin/issues/361#issuecomment-251950564
