### ISSUE TITLE
saving entity without a title fails, but message that post saved is emitted

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#566]
didn't track it down to the real cause, but making a new entity and changing only the entity type and saving the draft (want to get the proper meta box for the type) fails to change the type, but a message that the post was saved is displayed.

I assume that the root cause is that wordpress do not allow to create posts without title and content.

**Comment by Stoyan0v** [comment]
This is WordPress issue and there is a ticket for it already [#17115] (https://core.trac.wordpress.org/ticket/17115)
