### ISSUE TITLE
Faceted Search not displaying correctly

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#571]
![image](https://user-images.githubusercontent.com/837037/27731868-2124c916-5d8f-11e7-9085-ca1e59942139.png)

Probably an issue with the theme. We have two problems: 

1. red dots appearing on the side of some of the entities
2. articles not showing up

**Comment by ziodave** [comment]
The red dots is a matter of conflicting styles. We'll force a `display: none` for bullets in the faceted search.

**Comment by ziodave** [comment]
The other issue is a compatibility issue with the theme, if I resize the window the contents appear:

![image](https://user-images.githubusercontent.com/11438/27770025-730548d4-5f40-11e7-94d6-ef9aa0a11adb.png)


Can we can get a copy of the theme to perform more tests in our own lab?

**Comment by ziodave** [comment]
The second part of the issue has been moved to #577.
