### ISSUE TITLE
WL should give priority to entity stored locally 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#572]
An entity "Castro Real Estate Team" has been created with several synonyms. 
![screen shot 2017-07-06 at 11 43 48](https://user-images.githubusercontent.com/26247261/27905501-6bc94b76-6240-11e7-8fde-2c367bdb7fef.png)
Yet after several attempts WL seems to give priority to other entities without recognising the proper one stored locally 
![screen shot 2017-07-06 at 11 45 15](https://user-images.githubusercontent.com/26247261/27905595-a9b44e54-6240-11e7-810b-94ff601dbccb.png)

**Comment by cyberandy** [comment]
There is an overlap between the entity in the vocabulary and the entity Estate that is recognized from the cloud.

**Comment by ziodave** [comment]
It's not related to overlaps. The NLP doesn't highlight "Castro Real Estate Team":

![image](https://user-images.githubusercontent.com/11438/27905942-42fd4cec-624a-11e7-8c3f-f57245138226.png)

A mitigation factor will be available with #467 .

**Comment by ziodave** [comment]
I made further checks, the dataset doesn't contain any of the entities defined in the WP web site.

It looks that _wp-cron_ isn't working:
![image](https://user-images.githubusercontent.com/11438/27908981-395b13e2-6257-11e7-9345-8f34bce9f900.png)

**Comment by ziodave** [comment]
The issue here is related to the entities not being saved in the dataset because of the cron issue. Solved with #575 .

**Comment by ziodave** [comment]
After fixing the issue with the dataset, I found that _estate_ from the Cloud was preferred to the local entity. This is now fixed in WLS 1.12.0.

**Comment by ziodave** [comment]
![image](https://user-images.githubusercontent.com/11438/27992725-583b0440-64a3-11e7-927b-6c69ec3eaf6a.png)
