### ISSUE TITLE
Allow Editor to set by default a limit to the number of links in a page/article

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#573]
Feature request: limit links applied to a set number per post/page automatically within the WL settings

**Comment by gcuofano** [comment]
To simplify things when the link option is activated, we can allow WordLift to add one link only on the first occurrence in the text

**Comment by cyberandy** [comment]
One more interesting feedback to push this feature forward (this is also being requested by Tharawat and WindowsReport). 

![image](https://user-images.githubusercontent.com/837037/33997165-d3166f94-e0e3-11e7-878d-5a64887d0e9d.png)

Comment on @matteoc's blog >> https://www.lafabbricadellarealta.com/how-to-end-a-presentation-your-final-impression-should-be-as-good-as-your-first/#comment-3662026203

**Comment by ziodave** [comment]
How would this work, an option in WordLift's settings?

**Comment by ziodave** [comment]
@cyberandy is this superseded by #736 ?

**Comment by cyberandy** [comment]
Yes this can be merged with #736

**Comment by ziodave** [comment]
Closing in favor of #736.
