### ISSUE TITLE
Adding support for the locationCreated attribute on Articles

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#586]
WordLift, extract the place where the piece is being written. We should do the following: 

- [ ] ensure that the way we extract this information is reliable (I remember we had issues based on the browser)
- [ ] add the information in the JSON-LD and on LOD using <http://schema.org/locationCreated>  
- [ ] provide a way to add the extracted location on the front-end (a shortcode could be an option here)

**Comment by ziodave** [comment]
Related to #303 .

**Comment by ziodave** [comment]
Related to #574 .

**Comment by ziodave** [comment]
It's important to note that Geolocation is disabled on Chrome 50+: https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
