### ISSUE TITLE
Vocabulary Widget

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#587]
The request is related to the possibility of having a page that groups all terms of the vocabulary using an alphabetical order. This has been requested by DOL.

**Comment by ziodave** [comment]
@cyberandy what kind of page? private? public? a mockup maybe?

**Comment by cyberandy** [comment]
It's a public web page that we will need to implement on DOL to let users
browse entities in alphabetical order.

**Comment by ziodave** [comment]
We need more details on this issue.

**Comment by cyberandy** [comment]
We need to be able to create a page that lists all entities in the vocabulary with an AZ ordering. Let's see an example from https://www.wired.com/glossary 

![image](https://user-images.githubusercontent.com/837037/29882750-53241328-8dae-11e7-9edb-775c1197c299.png)

Behind a page like this we could have a widget `[vocabulary_atoz /]` (and [here](http://www.tcbarrett.com/wordpress-plugins/wp-glossary/wp-glossary-how-to-make-an-a-to-z-of-glossary-items/#.Wabi0ncjH_Q) are some of the useful options that we could implement) or we could provide this type of ordering from existing permalinks like `/wl_entity_type/thing/?order=atoz` and add the letter on top of each term.

**Comment by markkap** [comment]
@cyberandy I can see that people might want such a thing but in different formats. In addition to the plain top-down list, they might want the letters in the header to be more of tabs, or to organize the list in columns. Should we worry about it now, or just go with the plain design above?

as for the options for the shortcode as are in the plugin you referred to, the only one that seems applicable to me is "excerpt" as the others seem to be specific to that plugin and "full" will result in a long page which might not look like an actual glossary.

Maybe other possible options are "entity type" which will limit the glossary to one entity type, and a"referenced at" which will show links to N posts related to the entity

**Comment by cyberandy** [comment]
@markkap for sure it's a good idea to provide different options in terms of design. Ideally, if we present a good data structure and clear pointers along with the first top-down list, designers can implement via CSS whatever visualization they like here. 

I like both "entity type" and "referenced at" - I believe we can start with this. Testing it live on DOL and move ahead by sharing with the other clients.

**Comment by markkap** [comment]
@cyberandy @ziodave core functionality of the shortcode (I called it wl_glossary) is now in the branch, but there has to be some minimal styling for this to look presentable. Can copy the one in wierd, if there is no time to design anything different.

**Comment by cyberandy** [comment]
![image](https://user-images.githubusercontent.com/837037/30602460-e79bcfe4-9d64-11e7-81aa-c16460a917bf.png)

A preview from @claudiopome

**Comment by ziodave** [comment]
it looks nice, how would it look like on a mobile?

**Comment by gcuofano** [comment]
a client asked us where we are with this enhancement

**Comment by ziodave** [comment]
It needs code review, it won't make it for 3.16, but we can prioritize it for 3.17 ?
