### ISSUE TITLE
Entity Type: concept

### ISSUE THREAD

**Issue by ghost** [insideout10/wordlift-plugin#591]
an abstract idea. 

Point being, that 'choice of law' is more of a concept than a thing.  I can think of several examples..

**Comment by ziodave** [comment]
We need a schema.org type, I don't think Concept exists, but surely something similar?

**Comment by mediaprophet** [comment]
maybe; a broad 'concept' for an appropriate type is: 'claim'.   schema.org/claim as a higher-level type.   Example being;  

Claim.

"@context": "http://schema.org/",
  "@type": "Claim",
  "ChoiceofLaw": "AU",
  "Copyright": "Timothy Holborn" 

Then perhaps enable the means to scale via a bunch of identifiers relating to 'copyright holder' or means to reference CC or whatever. 

Another Example; Say, in a document someone is attempting to add a sourceReference to improve the reputation of their article that contains a bunch of 'claims' including (but not limited to) a statement about the approximate population of America.  The author has used data from SomeSource to make a claim; and by adding the RDF into their document that references the claim; so long as the claim URL is retained (or available via https://web.archive.org/web/*/ for instance) then the URI can be checked; ideally also, both for whether the statement can be checked for the date of publication; and, whether the statement has changed at all overtime.

(ie: population of the USA will be different next year, in 20 years, etc.  but the context of the article will change if the date of authorship isn't mentioned. - without going into 'dynamic publications' vs. 'static publications') 

NoteAlso: Say some other thing (not listed below) enables the statement to be categorised as 'approximate' or 'exact' (and thereafter, a bunch of other considerations around statistical works, means to clarify statistical works - seperate, but part of the broader framework overtime?)  


"@context": "http://schema.org/",
  "@type": "Claim",
  "Cite": {
   "Text":  "Population of America",
   "numericalValue":  "323100000"
  "checksum": "8D3748CC8D7590082404E985ABD044B4" 
  "checksumType": MD5
  "CiteSourceUri'": "https://www.google.com.au/search?q=population+of+America#[someOperator ie: #fact] 
   }
    "signature": {
    "type": "EcdsaKoblitzSignature2016",
    "created": "2017-09-27T01:18:24Z",
    "creator": "ecdsa-koblitz-pubkey:1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER",
    "signatureValue": "IA60HA5eG9mWrgJS9FbDEVLSo2AI3QWPtHudXpuwGY0CISyDoPEF3IaZw+URUoZzCHab4csa2y3/uhHm2KcS+NU="
  }
}

So; theory is, claim is a trust concept of some sort that is different to a thing.

Tim.

**Comment by mediaprophet** [comment]
seeAlso: https://www.w3.org/TR/2017/CR-odrl-vocab-20170926/#policyConcepts
