### ISSUE TITLE
suggested image not easily linked to 'feature image'

### ISSUE THREAD

**Issue by ghost** [insideout10/wordlift-plugin#592]
The suggested image thing comes-up with images, but i couldn't figure out how to make the suggested image the 'feature image' for the post.

**Comment by cyberandy** [comment]
Hi @mediaprophet, it's great to have you here 🤙
When an entity is stored in the user's vocabulary all the associated media are copied into the WordPress media library and from there they can be used as `featured image` of the blog post. 

Adding a simple click on the proposed image to making it become the `featured image` for the post is for sure a nice to have feature.
