### ISSUE TITLE
Allow regular posts/pages to be entities

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#596]
Main goal is to let users convert posts to be an entities without having to do any change in the post. First step is to let a user a associate a post with an entity term and enable the relevant meta boxes and jsonld output.

**Comment by ziodave** [comment]
From the Linked Data perspective we still need to address:
- [ ] relations
- [ ] images
- [ ] 2nd level properties (such as addresses, nutritions, ...)

**Comment by ziodave** [comment]
- [ ] Related Posts in the Entities List screen doesn't work as it should:
![image](https://user-images.githubusercontent.com/11438/29173971-9b809cfc-7ded-11e7-9867-385fef9aa54b.png)
