### ISSUE TITLE
Revising the order of the proposed entities in the WordLift Edit Widget

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#599]
Right now the list of entities is provided in Alphabetical order and each entity is presented with the number of occurrences set to `0`. 

![image](https://user-images.githubusercontent.com/837037/29027290-5acdd1b2-7b80-11e7-8e74-1d88704c4d6e.png)

In order to save the time that editors need to read the list we shall: 

- [x] order the list by the number of occurrences 
- [x] remove the number of occurrences for each entity

**Comment by ziodave** [comment]
Related to #335 and #514 .

**Comment by cyberandy** [comment]
The best way here is to analyze few cases, present the existing logic and how we got here and do some UX testing involving a selected pool of users to decide how this one can be improved.

**Comment by Stoyan0v** [comment]
The cff9dfc3f05636bf92ad46d565c24200e16348a0 orders the entities by the number of occurrences.
