### ISSUE TITLE
Post entity relations are not preversed on new entity creation 

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#60]
When I try to create an entity as 'L'Aquila' using and existing entity as http://dbpedia.org/resource/L'Aquila the relation between the current post and the related entity is not managed properly: this let the entity disappear from the widget.
Please notice that this bug is now fixed for entities created from scratch.
Please notice - see attachment - how the apix in the uri is not properly managed by dbpedia itself ;-)
![schermata 2015-08-20 alle 11 05 20](https://cloud.githubusercontent.com/assets/1022181/9379760/cf1811da-472b-11e5-9cae-1f3629d818e7.png)

**Comment by mcolacino** [comment]
Fixed

**Comment by cyberandy** [comment]
Well done!
