### ISSUE TITLE
WordLift slowing down RSS feed

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#611]
https://freeyork.org/feed/ taking a long time to load (~30 secs), is causing RSS aggregators like Feedly, Google Newstand, Instant Articles not to fetch any updates from the website.

WordLift seems to be the cause:
![image](https://user-images.githubusercontent.com/11438/30272804-e8a877e6-96fe-11e7-807e-753cbf22d39a.png)

**Comment by markkap** [comment]
sorry, forgot to indicate the issue... https://github.com/insideout10/wordlift-plugin/commit/7ec70c8573713799890ca069084c4b530c72cb90
