### ISSUE TITLE
Improve the performance of the Content Filter and JSON-LD Generation

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#612]
#611 shows high CPU usage when wordlift is active. I didn't investigate it but from the fact that it had an impact or the RSS generation I assume that the entity link generation is not very efficient. One way to combat this is to cache the results as part of the post meta.

The challenge will be to decide when and how to clear this cache.

@cyberandy , @ziodave opinions? 

- [ ] cache links in content filter.
- [ ] cache JSON-LD.

**Comment by markkap** [comment]
@ziodave lets do it for 3.16 for at least json-ld, store the generated json in a meta, after calculating it, remove it on post save.

**Comment by ziodave** [comment]
Yes, it makes sense. We could also cache it on the disk, since it might become quite large.

**Comment by markkap** [comment]
+1, just need a strategy where to place it. options are to have it by default under the uploads directory and have a "define" to let people configure different place

**Comment by ziodave** [comment]
See #626 .

**Comment by ziodave** [comment]
This has been handled using the caching service.
