### ISSUE TITLE
Faceted Search generates a SQL error

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#615]
```
SELECT object_id as ID, count( object_id ) as counter
            FROM wp_wl_relation_instances
            WHERE subject_id IN () and object_id != (123729)
            GROUP BY object_id;
```

> made by 
> do_action('wp_ajax_nopriv_wl_faceted_search'),
> WP_Hook->do_action, 
> WP_Hook->apply_filters, 
> wl_shortcode_faceted_search_ajax

The code is executed in the context of a single post page.

**Comment by Stoyan0v** [comment]
I've tested this several times, but there were no error on my side.

**Comment by markkap** [comment]
Big diff, but basically the if in line 175 is the only real change

**Comment by Stoyan0v** [comment]
@markkap There are two minor issues(I left comments), but otherwise LGTM.
