### ISSUE TITLE
PHP Notice:  ob_clean(): failed to delete buffer

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#617]
Notice generated when clearing the output buffer before handling json-ld ajax requests. probably should try to suppress the notice if possible to reduce php error log noise. 

full log with version 3.15 code - 
> [15-Sep-2017 08:29:48 UTC] PHP Notice:  ob_clean(): failed to delete buffer. No buffer to delete in /Applications/MAMP/htdocs/wordlift-plugin/src/includes/class-wordlift-jsonld-service.php on line 78

**Comment by ziodave** [comment]
Let's deprecated `wl_core_ob_clean` and just call `ob_clean` with an `@` sign: `@ob_clean();`.
