### ISSUE TITLE
Faceted Search shortcode return unbound number of result

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#618]
Need to bound it to some reasonable number like 20.

sample log 

> INFO   [ROOT                                    ] Going to find related entities for the current post [ post ID :: 127679 ] [ query ::             SELECT object_id as ID, count( object_id ) as counter 
            FROM wp_wl_relation_instances 
            WHERE subject_id IN (1183,1198,2399,2451,2976,3098,3152,3195,3391,3466,5394,8095,8137,8142,8312,8316,8356,8561,8728,10152,12059,12858,13119,15174,16316,23109,24119,26196,26258,28835,29530,30908,35444,37160,37167,37472,37984,38830,39248,39393,47399,47667,49469,52605,53435,55008,57182,58018,59003,59114,59213,59310,59447,59469,60855,61052,62256,62485,65250,65777,66509,67109,68230,69403,70659,73706,73734,73783,74085,74683,75242,75324,75354,75568,75741,75764,75810,79055,80328,81530,82738,83484,83636,84484,85099,85228,85231,85823,85858,86038,88008,89222,90329,90620,90747,90846,90880,91420,92508,93228,93707,93844,94314,95039,96555,96936,97880,97940,98059,98392,98482,98581,98708,98805,98816,99162,99823,99919,99938,100078,100337,100368,100732,100757,100932,101077,101397,101783,101848,102211,102251,102296,102308,102385,102427,102444,102516,102713,102739,103047,103505,103922,103942,103974,103995,104040,104126,104205,104318,104374,104391,104401,104413,104434,104471,104530,104543,104558,104979,105044,105052,105077,105119,105134,105274,105286,105292,105303,105483,105495,105549,105738,105750,105814,105826,106023,106222,106280,106480,106526,106678,106739,106798,106928,106937,107020,107107,107201,107268,107285,107313,107354,107503,107566,107582,107795,107905,108264,108284,108887,109079,109528,109643,110783,110792,110859,116907,116939,116967,116997,117131,117145,117202,117228,117241,117282,117312,117342,117464,117521,117736,118035,118216,118696,118877,118957,119258,119299,119308,119365,119420,119469,119523,119697,119816,120014,123503,123509,123518,123617,124346,124667,124735,125546,127169,127612,127907,127941,128265,128291,128725,128909,128922,128941,129194,129204,129365,129460,129509,129587,129602,129640,129719,129727,129765,129779,129949,129971,130006,130046,130055,130108,133418,133610,133620,133937,134046,134131,134443,134508,134547,134622,134751,134995,135006,135133,135436,135541,135658,135762,136010,136027,136064,136078,136089,136295,136314,136748,136789,137058,137293,137458,137478,137564,137796,137819,137869,137893,137943,137951,138049,138468,138541,138574,138633,138779,138820,138885) and object_id != (127679)
            GROUP BY object_id; ]
 INFO   [ROOT                                    ] Entities found 872

**Comment by markkap** [comment]
@ziodave do we have a strategy? The core of the performance issue was doing a get_post over each of the related posts which most likely does a request for the meta and maybe for the terms associated with it. We can improve on that by "feeding" all the post IDs to one query and let it sort out by post publish date or whatever other criteria. This will also handle getting the met in one request instead of one per post.

**Comment by ziodave** [comment]
@markkap we remove the `wl_core_` functions, so we need to check in 3.13 what was the sorting and limit strategy.
