### ISSUE TITLE
Compatibility with DIVI

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#624]
We have a case of a client willing to use WordLift within the DIVI editor.

**Comment by gcuofano** [comment]
When opening a DIVI text module the text can be edited. However, there is no access to the WordLift editor on the right which goes in background.
![schermata 2017-09-07 alle 18 08 05](https://user-images.githubusercontent.com/26247261/30741831-cbfa39b8-9f96-11e7-8126-99800243a224.jpg)
