### ISSUE TITLE
Add a WordPress filter to allow customers to extend the post types that can be turned into entities

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#625]
The use case is the following. I have a website that uses a theme or a plugin that allows me to organize content in a meaningful way using custom post types. 

As an example, on this website here: http://informationdevelopmentworld.com/, the theme allows me to organize with custom posts: speakers, sessions, sponsors, point of interests, tickets, and exhibitors. As I chose to add WordLift into the mix the need is to let the editors convert some of these content types into entities (ie. speakers should become entity of type person). 

By adding a filter in WordLift to expand the list of custom post type that can be transformed into entities we could develop a small plugin that by leveraging on this filter adds the required post types.

**Comment by markkap** [comment]
Filter is already part of 3.15 and it is called 'wl_valid_entity_post_types'

Possible usage to add a post type called "gallery" (just as an example)

```
add_action('wl_valid_entity_post_types', function ($post_types) {
  $post_types[] = 'gallery';
  return $post_types;
});
```
