### ISSUE TITLE
Check the status of Content Classification in the WordLift editor 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#628]
On a client website, the editor option to change the text of the entity under content classification does not show up 
 
![screen shot 2017-09-27 at 11 09 47](https://user-images.githubusercontent.com/26247261/30905307-b7c2e846-a374-11e7-9172-09af8dd37bbc.png)
![pasted image at 2017_09_27 12_18 pm](https://user-images.githubusercontent.com/26247261/30905835-5429e896-a376-11e7-8140-27f8accc7466.png)

**Comment by ziodave** [comment]
It's a css issue, to the "what, where, ..." button group and to the single `LI`s we need to add an explicit: `box-sizing: border-box;`
