### ISSUE TITLE
Suggested images are missing after the update 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#646]
![image](https://user-images.githubusercontent.com/837037/31433202-e483bc48-ae78-11e7-9d4d-3bee2ce2ae83.png)

This should have come out from the testing 😞 
Requires a quick fix.

**Comment by ziodave** [comment]
It doesn't look an issue of 3.15. With 3.14 images are not returned either for the existing annotated entities. New entities discovered are displaying in suggested images as usual.
