### ISSUE TITLE
Disable conflicting JSON-LD from Yoast

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#651]
Yoast too may publish a JSON-LD for the Web Site (see https://yoast.com/json-ld/). We should find a way to disable it (maybe a filter?).

**Comment by Stoyan0v** [comment]
We could use the `wpseo_json_ld_output` filter. If we return empty array or false it will prevent json-ld creation.

```
$this->data = apply_filters( 'wpseo_json_ld_output', $this->data, $context );

if ( is_array( $this->data ) && ! empty( $this->data ) ) {
```
