### ISSUE TITLE
When the user does not choose a publisher WordLift picks up the first one from the list 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#652]
![image](https://user-images.githubusercontent.com/837037/31500252-3af2bdc4-af67-11e7-8055-edaebb1b3fa8.png)

This is something that requires our attention. We shall: 

1- prompt the user to choose/create an entity for the publisher (UX aspect - an alert box will do here)  
2- make sure that if the user did  not choose/create an entity we do not save the first one as we're doing now

**Comment by ziodave** [comment]
I added the _none_ option:

![image](https://user-images.githubusercontent.com/11438/31501402-7740bf12-af6a-11e7-830d-813f9dd3b518.png)
