### ISSUE TITLE
Increase compatibility with wordpress.com VIP coding expectations

### ISSUE THREAD

**Issue by markkap** [insideout10/wordlift-plugin#656]
The coding expectation are https://vip.wordpress.com/documentation/code-review-what-we-look-for/

The list is long, therefor this is a meta issue to track compliance with that list.

Out of the bat, main issues we have are usage of additional table, direct DB queries  and the extensive use of AJAX we do.

**Comment by ziodave** [comment]
The initial thoughts that I have is that we need to move the JSON-LD generation to WLS side to avoid increasing the number of requests on WordPress and overloading it.
