### ISSUE TITLE
startDate and endDate are not recorded on some Events

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#665]
The attributes _startDate_ and _endDate_ of an Event are not working properly: when I save an entity after selecting them, the data is not recorded. 
I've encountered this issue on the website of the event IDW. 

![schermata 2017-10-17 alle 18 02 20](https://user-images.githubusercontent.com/24609125/31676275-5e2998ae-b367-11e7-871c-ea42f3049eff.png)

**Comment by ziodave** [comment]
This happens because the metabox saves the data to the post using `get_the_ID()` to get the current post, which eventually is changed by some other plugin installed on the web site.

Changing `get_the_ID()` with `$_POST['post_ID']` should fix this.
