### ISSUE TITLE
View Linked Data on a post shows a 500 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#668]
On a post, the view linked data option shows the following problem: 

![screen shot 2017-10-18 at 15 38 16](https://user-images.githubusercontent.com/26247261/31721721-765ffa4a-b41a-11e7-879c-4f9b6447cc77.png)

Additional data about your WordPress install:
[ ] WordPress version: 4.8.2 (theme: Reverzo)
[ ] WordLift plugin version: 3.15.12
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: open an existing post annotated with WL 
 - Step 2: click on view linked data
 - Step 3: see page showing 500

**Comment by ziodave** [comment]
Posts (articles) are not published to the Linked Data store (they're assigned a unique ID anyway), so clicking on "View Linked Data" shows an error.

We need to remove the "View Linked Data" button for posts/pages (articles).

For the time being the error can be safely ignored.
