### ISSUE TITLE
Sometimes authors are not correctly matched with their entities

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#677]
When you write an article which contains the name of a WordPress user that has been connected with a _Person_ from the Vocabulary, you would expect WordLift to detect the existing entity. What happens, though, is that WordLift still suggests you **two local entities** (one for the WordPress user, the other one for the _Person_) as they were disjointed. 

For the editor, it's impossible to guess which one of the two is the curated entity from the vocabulary. 

![schermata 2017-10-20 alle 16 41 08](https://user-images.githubusercontent.com/24609125/31827534-5167ba1c-b5b8-11e7-8c66-7124462cc10d.png)

![schermata 2017-10-20 alle 16 42 22](https://user-images.githubusercontent.com/24609125/31827413-f931aaba-b5b7-11e7-911a-a51882118a36.png)

I have also tried to downgrade this User from Administrator to Author in order to see if there was any improvement, but the result of the analysis didn't change. 

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.8.2
[ ] WordLift plugin version: 3.15.2
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Match a WordPress user with an entity (type: _Person_), in this case, an Administrator
 - Step 2: Type the author/person name on a post. 
 - Step 3: Two local entities are identified, it's impossible to understand which is the previously curated one, and which is the one generated starting from the user.

**Comment by ziodave** [comment]
@Cupofbrain I don't understand: WordPress users are not entities and they're not returned with the analysis results. It appears that you have a duplicated entity on this site? can you send me the access data privately?

**Comment by ziodave** [comment]
It appears that yes, that was the issue. With 3.15.3 this should be fixed, since we don't save anymore to the Linked Data store users (or anything that doesn't have a content).
