### ISSUE TITLE
H1 disappears on a page when WL is activated 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#678]
Please describe the issue here:
When WL gets activated, the H1 tag disappear. When it is deactivated, it gets back. 
![screen shot 2017-10-20 at 18 51 12](https://user-images.githubusercontent.com/26247261/31832613-eeb140e0-b5c7-11e7-8657-d3e073b6b5a1.png)
Please provide additional data about your WordPress install:
[ ] WordPress version: WordPress 4.8.2 running Betheme Child theme
[ ] WordLift plugin version: 3.15.2
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: get into website where WL is deactivated 
 - Step 2: activate it again 
 - Step 3: notice how the H1 tag disappears on the page

**Comment by ziodave** [comment]
Are we talking about this URL ?

https://www.glaciervehicles.com/vans/refrigerated/used

**Comment by gcuofano** [comment]
that's correct

**Comment by ziodave** [comment]
The theme is:

```
/*
Theme Name: Betheme
Theme URI: http://themes.muffingroup.com/betheme
Description: Betheme - Premium WordPress Theme
Tags: one-column, two-columns, left-sidebar, right-sidebar, custom-background, custom-header, custom-menu, editor-style, featured-image-header, featured-images, post-formats, responsive-layout, theme-options, translation-ready
Author: Muffin group
Author URI: http://muffingroup.com
License: GNU General Public License version 3.0
License URI: http://www.gnu.org/licenses/gpl-3.0.html
Version: 9.6

All css files are placed in /css/ folder.
If you want to add your own css code, please do it in /css/custom.css

*/
```

There's also a child theme (betheme-child) although it appears there also some customizations in the parent theme.

**Comment by ziodave** [comment]
It's an issue in _betheme_: the function `mfn_page_title` in _theme-functions.php_ has the following:

```
		} elseif( get_post_taxonomies() ){

			// Taxonomy -----------------------------------
			$title = single_cat_title('', false);		
		} else {

			// Default ------------------------------------
			$title = get_the_title( mfn_ID() );		
		}
```

Since we add a taxonomy (`wl_entity_type`) to the _page_ post type, this function now returns our taxonomy and _betheme_ doesn't get the title of the post.

Fix the theme by changing the line 482, from 
`} elseif( is_single() ) {`

to
`} elseif ( is_singular() ) {`
