### ISSUE TITLE
[Feature-Request] Enable tooltip on vocabulary pages 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#684]
A client asked us to enable a tooltip on the vocabulary pages that allows the hovering on the vocabulary pages to get an extract of that page without accessing it: 

![screen shot 2017-10-30 at 15 04 49](https://user-images.githubusercontent.com/26247261/32174988-b822e6b4-bd83-11e7-9ca4-6bfcc6b71f77.png)

**Comment by ziodave** [comment]
I added the _needs ux_ to define things for example, from where do you enable the option? is it a global option, or per annotation, etc ...
