### ISSUE TITLE
Check WL compatibility with UX builder part of Flatsome themes

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#691]
A client signaled that when WordLift gets activated on a website that uses a builder (called UX Builder), part of Flatsome themes (flatsome3.uxthemes.com), the builder stops working. 

Wordpress Version 4.8.3
WordLift Version 3.15.3
Flatsome ChildVersion: 3.0
FlatsomeVersion: 3.4.0

[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: go to an article and see that UX builder works 
 - Step 2: activate WordLift 
 - Step 3: go back to the same article and see how UX builder does not work anymore

**Comment by ziodave** [comment]
The UX Builder uses angular which clashes with our Angular.
