### ISSUE TITLE
WL annotates image URLs in visual builder

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#692]
Please describe the issue here:

In an article like this one: bestlaneighborhoods.com/properties/midcentury-modern-time-capsule-glendale, we noticed that at times WL annotates image URLs. 

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.8.3
[ ] WordPress Theme: Avada 5.1.6, Fusion Builder 1.1.6
[ ] WordLift plugin version: 3.15.3

[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Go inside one article and open WL editor for the analysis 
 - Step 2: Save the article 
 - Step 3: See how in place of the images show the shortcode since WL has annotated the URLs

**Comment by ziodave** [comment]
![image](https://user-images.githubusercontent.com/11438/32454377-5e05e180-c31f-11e7-9312-591ecdf9ed62.png)

**Comment by ziodave** [comment]
Solved server-side.
