### ISSUE TITLE
schema:location places are turned into things in article's markup

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#695]
When events are mentioned in one article, the location attributes are not correctly displayed: schema:location places are turned into things in article's markup and, apparently, it loses the information about the address. 

[ ] WordPress version: 4.8.3

[ ] WordLift plugin version: 3.15.3

[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Mention an event in an article 
 - Step 2: See data with Google's Structured Data Testing Tool
 - Step 3: The location is apparently categorized as a _Thing_ and the address is missing - even if data is complete and correct. 

In this article, we have mentioned 3 events, so [I see 6 errors](https://search.google.com/structured-data/testing-tool/u/0/?url=https://wordlift.io/blog/en/making-your-website-talk/#url=https%3A%2F%2Fwordlift.io%2Fblog%2Fen%2Fmaking-your-website-talk%2F):

![schermata 2017-11-10 alle 12 18 03](https://user-images.githubusercontent.com/24609125/32656280-6f19ee54-c611-11e7-9e0d-75272727a4fe.png)

Each location has been considered a 'Thing' and the address disappears. 

![schermata 2017-11-10 alle 12 18 38](https://user-images.githubusercontent.com/24609125/32656305-88ff90a8-c611-11e7-9759-4e303afb1756.png)

Truth is that data is there, see how the page of the entity of the event itself has been [analyzed by Google's Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/?url=https://wordlift.io/blog/en/entity/smxl-milan-2017/). 

![schermata 2017-11-10 alle 12 22 41](https://user-images.githubusercontent.com/24609125/32656393-eb9cd6b2-c611-11e7-83a5-83b242f8afac.png)

**Comment by ziodave** [comment]
I don't see the issue:

![image](https://user-images.githubusercontent.com/11438/32661096-d306a8a8-c625-11e7-9592-81153ee06b39.png)


Is it possible that, when you tested, it was in fact a Thing?

https://search.google.com/structured-data/testing-tool/u/0/?url=https://wordlift.io/blog/en/entity/smxl-milan-2017/#url=https%3A%2F%2Fwordlift.io%2Fblog%2Fen%2Fentity%2Fsmxl-milan-2017%2F

**Comment by ziodave** [comment]
Ok, I saw the issue. When we implemented the JSON-LD we decided not to publish more than 2 levels, in this case Post (1st level) and Event (2nd level). Location is referenced by the Event and is therefore 3rd level.

Revising this strategy is a new feature but we should carefully take into consideration the performance.

**Comment by ziodave** [comment]
This issue doesn't happen anymore. Feel free to reopen.
