### ISSUE TITLE
Chord is not displaying all the information 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#697]
Please describe the issue here:
Here is what happens
![image](https://user-images.githubusercontent.com/837037/32716912-162354fe-c858-11e7-8ac3-02b977e5b8ea.png)

This has been spotted on WordLift.io website (try opening an entity like this [one](https://wordlift.io/blog/en/entity/e-c-segar/)) and it seems to be a performance-related issue. After reloading the page the data is correctly displayed.

I noticed - while not sure if it is related - that we referenced the sankey module (though this is only used [here](https://wordlift.io/blog/en/crafting-texts-age-fragmented-reader-experience/#the-networked-text-in-a-fragmented-reality) and should not be referenced on other pages) - @claudiopome you might need to check this.

![image](https://user-images.githubusercontent.com/837037/32717028-7e532b44-c858-11e7-9290-33951857478f.png)

Please provide additional data about your WordPress install:
[ ] WordPress version: 
[ ] WordLift plugin version:
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
I am not sure it's a performance issue, otherwise we wouldn't see any result.
