### ISSUE TITLE
Font Awesome on the front-end may conflict with themes

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#699]
Please describe the issue here:

We might need to reconsider our font-awesome usage on the front-end to avoid conflicts with themes.

See https://freeyork.org/photography/atlas-of-beauty-photographer-travels-the-world-to-capture-the-beauty-of-500-women-around-the-world/

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.8.3
[ ] WordLift plugin version: 3.15.5

**Comment by ziodave** [comment]
We use font-awesome in 3 less/CSS files:
* wordlift-faceted-entity-search-widget.less, used by the faceted search shortcode.
* wordlift-ui.less, used by the shortcodes geomap, chord, navigator, and wordlift in general.
* wordlift-reloaded.less, used in admin.

**Comment by ziodave** [comment]
I found out that the conflicting Font Awesome is loaded by another plugin and it's an older Font Awesome version 4.6.3 while we load 4.7.0.

Therefore I am putting this on-hold, since we want to refactor generally speaking the widgets, this will be solved then.

**Comment by ziodave** [comment]
font-awesome is currently referenced by the following css:
* wordlift-reloaded.css: 
  * dashboard (`wordlift.php`).
  * TinyMCE editor (`wordlift_editor.php`).
* wordlift-ui.css
  * navigator shortcode (`class-wordlift-navigator-shortcode.php`).
  * chord shortcode (`class-wordlift-chord-shortcode.php`).
  * geomap shortcode (`class-wordlift-geomap-shortcode.php`).
  * frontend (`wordlift.php`).
* wordlift.css: never used
* wordlift-faceted-entity-search-widget:
  * faceted search shortcode (`wordlift_shortcode_faceted_search.php`).

**Comment by cinghaman** [comment]
hmm so there is no easy way I could just add_action > wp_deregister_style fontawesome from your plugin

**Comment by ziodave** [comment]
Nope, in the medium term I think we should remove the font-awesome dependency.

In the short term we could however split the font loading to a separate style sheet which could then be filtered.

**Comment by cinghaman** [comment]
That would be great

**Comment by ziodave** [comment]
I think we should focus on `wordlift-ui.css` and `wordlift-faceted-entity-search-widget.css` because these are loaded in the front-end.

**Comment by cinghaman** [comment]
Yea, it's the front end issue only as it adds additional resource/request and especially in my case I am loading the font-awesome from my assets folder so they get cached properly.
And this additional request adds few microseconds

**Comment by ziodave** [comment]
Yes, I can totally relate to that. Ok, I'll send an update soon.

**Comment by ziodave** [comment]
Find here a development version for WordLift 3.19.3. The font-awesome fonts are now loaded in a separate dependency and there's a new filter that you can use to turn that off (only for the front-end), e.g.:

```
add_filter( 'wl_include_font_awesome', function( $include ) {
 return false;
} );
```

Travis is running UTs [here](https://travis-ci.org/insideout10/wordlift-plugin/builds/402665389).

Please remember *not* to uninstall WordLift before updating otherwise the vocabulary would be deleted.

[wordlift-3.19.3-dev.zip](https://github.com/insideout10/wordlift-plugin/files/2184628/wordlift-3.19.3-dev.zip)
