### ISSUE TITLE
GSC complains about organization-name missing

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#708]
Please describe the issue here:

GSC complains about the following:

![image](https://user-images.githubusercontent.com/11438/33166326-2a805458-d03a-11e7-99a5-43e8d9f41c08.png)

This is due to the fact that the Person Andrea Volpini is a 2nd level entity (i.e. connected via another Person) and the Organization is linked via the `http://schema.org/affiliation` property:

* affiliation
 * @type: Organization
 * @id: http://data.wordlift.io/wl0216/entity/wordlift_2

GSC is complaining that the `http://schema.org/name` is missing.

The name is missing because we don't go deeper than the 2nd level to avoid overloading WP with queries.

This is somewhat related to #695 .

Please provide additional data about your WordPress install:
-[ ] WordPress version: 4.9.0
-[ ] WordLift plugin version: 3.16.1

cc: @cyberandy

**Comment by mreichhart** [comment]
same here:

![image](https://user-images.githubusercontent.com/22288718/33202375-9612bbda-d0fc-11e7-9f5d-4e2d51da2142.png)

**Comment by ziodave** [comment]
In order to avoid going too deep and to avoid circular loops, I think we should define the "minimal" properties, i.e. properties that must be provided anyway and that express a value (never a reference, otherwise we might risk going too deep).
