### ISSUE TITLE
Some properties are not saved in LOD for schema:Place

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#710]
The following properties, while present in WordPress, are not saved on data.wordlift.io:
 
- schema-org:latitude
- schema-org:longitude
- schema-org:postalCode
- schema-org:addressLocality
- schema-org:addressCountry
- schema-org:addressRegion
- schema-org:postOfficeBoxNumber

This occurred on:
- WordPress 4.8 with WordLift 3.15.3-rc5 (website: https://wordlift.io/blog/en) 
- WordPress 4.8 with WordLift Version 3.16.2 (https://chatbot.wordlift.it)

[ ] Step-by-step procedure on how to reproduce the issue:

 - Step 1: go to [edit entity for Quadrus Conference Center](https://chatbot.wordlift.it/wp-admin/post.php?post=6881&action=edit)
 - Step 2: fill up the missing properties and hit save
 - Step 3: click on the View Linked Data button 
-  Step 4: check if the properties have been stored

**Comment by ziodave** [comment]
They're actually saved, but in the `schema:location` reference of an event.
