### ISSUE TITLE
Image storage strategy

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#715]
Please describe the issue here:

Currently the images stored from the public cloud are stored (as an example) as follows:

/wp-content/uploads/goo/gle/_pl/ay_/log/o-2/017/120/116/-5a/218/032/33b/a6/Google_Play_logo-2017120116-5a21803233ba6.svg

The nested folder structure is too deep, we want to simplify the image storage strategy, yet at the same time we don't want to storage all the images in the same folder to avoid _overloading_ the folder itself (and slow down list ops).

We have at least two solutions:
1. Simply save the file in /wp-content/uploads/_yyyy/MM_ folder,
2. Create a simpler nested structure, by md5 the filename and grabbing the first two bytes, e.g. /wp-content/uploads/wl/07/Google_Play_logo-2017120116-5a21803233ba6.svg

**Comment by igoschia** [comment]
Absolutely the 1 but using the wordpress settings and adding a custom folder.
 I need that my image structure will be the same of my settings or i need to setup a folder inside the upload like /wp-content/uploads/Wordlift/
