### ISSUE TITLE
Batch Analysis should invalidate caches

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#716]
Please describe the issue here:

It appears that entities found using batch analysis disappear when opening the edit post page. Maybe invalidating the cache solves this.

Please provide additional data about your WordPress install:
* [ ] WordPress version:  4.9.1
* [ ] WordLift plugin version: 3.16.3

**Comment by Stoyan0v** [comment]
I spend some time on this issue and it seems that it's not related to the cache service, but the coffee script. The annotations are not being found by [findAnnotation](https://github.com/insideout10/wordlift-plugin/blob/develop/src/coffee/editpost-widget/app.services.AnalysisService.coffee#L24) for some reason, but I need more time to debug it.

![1](https://cldup.com/tdMBC3JLOe-3000x3000.png)

**Comment by ziodave** [comment]
It's not an issue in the client side code: they're not found because they're not written by the PHP code in the page.
