### ISSUE TITLE
Batch Analysis updates train

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#724]
This issue keeps track of the state of the following issues:
* [ ] see #716 .
* [ ] see #717  - PR #738.
* [ ] see #719 - PR #731.
* [ ] see #720  - PR #737.
* [ ] see #721 - PR #734.
* [ ] see #722 - PR: #725.
* [ ] see #723 - PR #737..

**Comment by Stoyan0v** [comment]
These issues are also part of this updates:

* [ ] see #729 .
* [ ] see #726 .
* [ ] see #602 .
