### ISSUE TITLE
Set correct post types to Batch Analysis

### ISSUE THREAD

**Issue by Stoyan0v** [insideout10/wordlift-plugin#726]
Please describe the issue here:
Currently Batch Analysis process posts only, because it uses `get_posts`, without specifying the post type. The issue it that we set the post metas to posts and pages [here](https://github.com/insideout10/wordlift-plugin/blob/develop/src/includes/class-wordlift-batch-analysis-service.php#L218), but process only posts.

There are two ways to address this:

1. We can use the `Wordlift_Entity_Service::valid_entity_post_types()` to set the post types. This approach will allow us to analyses also the other custom post types that uses WordLift. The only issue here is that the SQL query (https://github.com/insideout10/wordlift-plugin/blob/develop/src/includes/class-wordlift-batch-analysis-service.php#L192) will become bigger if we have more custom post types.

2. We can use param that will be passed to the request and then we can use that param to specify the post type. This is more flexible but we have to trigger the Analysis for each post type.  Of course if there is no param specified, we will fallback to `post`.

**Comment by ziodave** [comment]
It's a bug. Let's do solution 2. adding another filter option post_type (by default only `post`) to the Batch Analysis submission function.

Solution 1. isn't good because it would analyze in batch also the entities which is unwanted.
