### ISSUE TITLE
Gutenberg Integration

### ISSUE THREAD

**Issue by Stoyan0v** [insideout10/wordlift-plugin#728]
## Please describe the issue here:
Currently WordLift doesn't work when Gutenberg is installed and used as text editor. WordPress 5.0 is the release where it will be merged to core and it will be nice if we are prepared for this step. The time between releases is approximately 5 - 6 months and we have this time to integrate WordLift with Gutenberg. Of course, we can wait for final release, but there is pretty much done and I don't think that there will be big changes from the current version.

**Comment by ziodave** [comment]
We're working on WordLift's Roadmap to define the actions. I'll share it with you soon.

**Comment by claudiopome** [comment]
I worked on some mockups for the the WordLift's Gutemberg integration. Let me know what you think about it! 

![32440949-a8efd3ec-c2f5-11e7-97f5-04fae054b6edd](https://user-images.githubusercontent.com/5725682/35162389-7bd49c98-fd43-11e7-8e0d-929d7a04f79a.png)

![32440951-ad4c1f86-c2f5-11e7-8bf1-6796c7949af3](https://user-images.githubusercontent.com/5725682/35162399-85f8c5d2-fd43-11e7-8590-8348810ae3c3.png)

![32440951-ad4c1f86-c2f5-11e7-8bf1-6796c7949af33](https://user-images.githubusercontent.com/5725682/35162403-8b33ea0e-fd43-11e7-9dcc-62121c2d6038.png)

![32440951-ad4c1f86-c2f5-11e7-8bf1-6796c7949af3334](https://user-images.githubusercontent.com/5725682/35162487-d7dab0d6-fd43-11e7-8fcd-68571f41f6a9.png)

**Comment by akshayraje** [comment]
As discussed on call with @ziodave:

- Gutenberg Sidebar with classification that talks with annonations in content
- Enable taxonomies in sidebar (enable rest_api)
- Move 'view linked data' & 'test classifications' to classifications box
- Move 'add synonym' to meta box of entities' properties
- Meta box of entities' properties will stay down below
- Convert / add stuctured blocks for shortcodes
