### ISSUE TITLE
Extensible Entities

### ISSUE THREAD

**Issue by mediaprophet** [insideout10/wordlift-plugin#741]
I'm realising the use of this plugin can significantly alter the authorship of posts; as the 'semantic encyclopaedia' that is formed through the use of the plugin provides an array of internal references that may otherwise be further described in articles.  (if that makes sense).

Please describe the issue here:

I was writing a post about 'introduction to structured data' and wanted to add references to 'semantic web' and 'linked data', etc.  

When i goto 'vocab'; i see, for instance, TimBL, but i can't add 'maker' and/or 'author', and related semantics. 

Thoughts were to be able to add ontological terms (and values) to the Vocab.

**Comment by cyberandy** [comment]
Hi @mediaprophet - if the entity type is set to **Creative Work** you could use the `author` property to link let's say _Semantic Technologies_ with _TBL_

![image](https://user-images.githubusercontent.com/837037/34382334-6106461a-eb0e-11e7-9a43-59529c802d83.png)

**Comment by mediaprophet** [comment]
So, thought was....

Usually; in a non-semantic web publishing environment, what you'd do is
create in-line hyperlinks to external resources. whereas WITH semantic
resources, the 'vocab' section (in which, vocab may not be the best term);
you're then able to add a bunch of resources that form a semantic db
in-itself, to better describe a concept otherwise noted in a post.

Therein; i was going to start by referencing
http://www.sims.monash.edu.au/subjects/ims2603/resources/week9/9.1.pdf and
the image https://www.w3.org/History/1989/proposal.html which loosely
denotes relationships (early days); and therein, there's different
organisations, different co-authors, etc.

mapping the data is quite different to creating a user-experience that
leverages it.   Perhaps herein; it's about a 'knowledge base' rather than
'vocab' specifically?

The next consideration was; whether and how this may in-turn become
linkable / able to be published as a series of resources.

The net result; would be that when some basic notes are provided about a
particular topic, the means to use wordlift to go-in and fully map-out the
relations around that 'soundbyte' of text noted in an article; and provide
the means for a user of the blog, to go through and do more investigations
internally.

I'm not sure if you've seen: https://www.youtube.com/watch?v=En_2T7KH6RA
??

underlying it all; i guess, it's a different way of providing references to
underlying knowledge, which should in-turn aid the author by enabling the
user to understand whether or not the author has done the underlying
research to know what they're talking about (or not).

Hope that helps.

Tim.
