### ISSUE TITLE
http://rdf.freebase.com --> https://www.wikidata.org/ ??

### ISSUE THREAD

**Issue by mediaprophet** [insideout10/wordlift-plugin#742]
Please describe the issue here:

plugin is generating freebase URIs.  seeAlso: https://developers.google.com/freebase/ 

suggestion is remapping to WikiData.

**Comment by cyberandy** [comment]
@mediaprophet we added Wikidata now with the `sameAs` search box (see image below) we decided to keep references to Freebase MID much like DBpedia still does (see [here](http://dbpedia.org/page/Storytelling) for example). We can still investigate and see if this can be added also from the analysis. 

![image](https://user-images.githubusercontent.com/837037/34479709-a436af94-efa8-11e7-909a-2cf829a605d1.png)

![image](https://user-images.githubusercontent.com/837037/34479803-fc728ba6-efa8-11e7-8f04-bb57f311b3f2.png)

I will keep you posted here

**Comment by mediaprophet** [comment]
i use http://osds.openlinksw.com/ to inspect the created metadata.  it's
not looking good atm, check it out.   https://openseason.online/ is dev /
testbed site.

**Comment by ziodave** [comment]
hi @mediaprophet can you send us a test URL and a screenshot of the issues you see in OSDS ?

**Comment by mediaprophet** [comment]
Statement Collection #1
Entity https://openseason.online/user/openseason_vs2mak
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Person
<http://schema.org/Person>
Name <http://schema.org/name> openseason_vs2mak
Statement Collection #2
Entity http://data.wordlift.io/wl0293/entity/data
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Thing
<http://schema.org/Thing>
schema:description <http://schema.org/description> Data are values of
qualitative or quantitative variables, belonging to a set of items. Data in
computing are represented in a structure, often tabular (represented by
rows and columns), a tree (a set of nodes with parent-children
relationship) or a graph structure (a set of interconnected nodes). Data
are typically the results of measurements and...
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/vocabulary/data/
Name <http://schema.org/name> Data
schema:sameAs <http://schema.org/sameAs> dbpedia:Data
<http://dbpedia.org/resource/Data>
schema:sameAs <http://schema.org/sameAs> fb:m.026sq
<http://rdf.freebase.com/ns/m.026sq>
schema:url <http://schema.org/url>
https://openseason.online/vocabulary/data/
Statement Collection #3
Entity http://data.wordlift.io/wl0293/entity/open_season_online
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
schema:Organization <http://schema.org/Organization>
Name <http://schema.org/name> Open Season Online
Statement Collection #4
Entity http://data.wordlift.io/wl0293/entity/use_law
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Thing
<http://schema.org/Thing>
schema:alternateName <http://schema.org/alternateName> use
schema:description <http://schema.org/description> Use, as a term in real
property law of common law countries, amounts to a recognition of the duty
of a person, to whom property has been conveyed for certain purposes, to
carry out those purposes. Uses were equitable or beneficial interests in
land. In early law a man could not dispose of his estate...
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/vocabulary/use-law/
Name <http://schema.org/name> Use (law)
schema:sameAs <http://schema.org/sameAs> dbpedia:Use_(law)
<http://dbpedia.org/resource/Use_(law)>
schema:sameAs <http://schema.org/sameAs> fb:m.05r4j5
<http://rdf.freebase.com/ns/m.05r4j5>
schema:url <http://schema.org/url>
https://openseason.online/vocabulary/use-law/
Statement Collection #5
Entity http://data.wordlift.it/wl0353/entity/evidence
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Thing
<http://schema.org/Thing>
schema:description <http://schema.org/description> Evidence is and includes
everything that is used to reveal and determine the truth, and therefore is
presumed to be true and related to a case. Giving or procuring evidence is
the process of using those things that are either (a) presumed to be true,
or (b) were in fact proven to be true by...
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/vocabulary/evidence/
Name <http://schema.org/name> Evidence
schema:sameAs <http://schema.org/sameAs> dbpedia:Evidence
<http://dbpedia.org/resource/Evidence>
schema:sameAs <http://schema.org/sameAs> fb:m.0d9cbr
<http://rdf.freebase.com/ns/m.0d9cbr>
schema:url <http://schema.org/url>
https://openseason.online/vocabulary/evidence/
Statement Collection #6
Entity http://data.wordlift.it/wl0353/entity/iphone
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Thing
<http://schema.org/Thing>
schema:alternateName <http://schema.org/alternateName> phone
schema:description <http://schema.org/description> The iPhone is a line of
smartphones designed and marketed by Apple Inc. It runs Apple's iOS mobile
operating system, known as the "iPhone OS" until mid-2010, shortly after
the release of the iPad. The first generation iPhone was released on June
29, 2007; the most recent iPhone, the sixth-generation iPhone 5, on
September 21,...
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/vocabulary/iphone/
Name <http://schema.org/name> IPhone
schema:sameAs <http://schema.org/sameAs> dbpedia:IPhone
<http://dbpedia.org/resource/IPhone>
schema:sameAs <http://schema.org/sameAs> fb:m.027lnzs
<http://rdf.freebase.com/ns/m.027lnzs>
schema:sameAs <http://schema.org/sameAs> yago:IPhone
<http://yago-knowledge.org/resource/IPhone>
schema:url <http://schema.org/url>
https://openseason.online/vocabulary/iphone/
Statement Collection #7
Entity http://data.wordlift.it/wl0353/entity/mobile_app
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Thing
<http://schema.org/Thing>
schema:alternateName <http://schema.org/alternateName> app
schema:alternateName <http://schema.org/alternateName> apps
schema:description <http://schema.org/description> A mobile application (or
mobile app) is a software application designed to run on smartphones,
tablet computers and other mobile devices. They are usually available
through application distribution platforms, which are typically operated by
the owner of the mobile operating system, such as the Apple App Store,
Google Play, Windows Phone Store, and BlackBerry App...
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/vocabulary/mobile-app/
Name <http://schema.org/name> Mobile app
schema:sameAs <http://schema.org/sameAs> dbpedia:Mobile_app
<http://dbpedia.org/resource/Mobile_app>
schema:sameAs <http://schema.org/sameAs> fb:m.0h94y36
<http://rdf.freebase.com/ns/m.0h94y36>
schema:url <http://schema.org/url>
https://openseason.online/vocabulary/mobile-app/
Statement Collection #8
Entity http://data.wordlift.it/wl0353/entity/smartphone
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Thing
<http://schema.org/Thing>
schema:alternateName <http://schema.org/alternateName> smart phones
schema:description <http://schema.org/description> A smartphone is a mobile
phone built on a mobile operating system, with more advanced computing
capability connectivity than a feature phone. The first smartphones
combined the functions of a personal digital assistant (PDA) with a mobile
phone. Later models added the functionality of portable media players,
low-end compact digital cameras, pocket video cameras, and...
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/vocabulary/smartphone/
Name <http://schema.org/name> Smartphone
schema:sameAs <http://schema.org/sameAs> dbpedia:Smartphone
<http://dbpedia.org/resource/Smartphone>
schema:sameAs <http://schema.org/sameAs> fb:m.0169zh
<http://rdf.freebase.com/ns/m.0169zh>
schema:sameAs <http://schema.org/sameAs> yago:Smartphone
<http://yago-knowledge.org/resource/Smartphone>
schema:url <http://schema.org/url>
https://openseason.online/vocabulary/smartphone/
Statement Collection #9
Entity
http://data.wordlift.it/wl0353/post/mobile_devices__data_recovery___collection
Attributes
rdf:type <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Article
<http://schema.org/Article>
schema:about <http://schema.org/about>
http://data.wordlift.io/wl0293/entity/data
schema:dateModified <http://schema.org/dateModified> 2017-12-28T03:56(
schema:Date <http://schema.org/Date>)
schema:datePublished <http://schema.org/datePublished> 2017-12-28T03:10(
schema:Date <http://schema.org/Date>)
schema:description <http://schema.org/description> Have you got a bunch of
important messages on your phone and you're wondering how you can store
this data for safe-keeping.  Have you experienced an incident that has made
you feel unsafe, and your wondering how to make a record of it to report it
to your employer, school or police. if you type...
schema:headline <http://schema.org/headline> Data Recovery & Collection:
Mobile Devices
schema:mainEntityOfPage <http://schema.org/mainEntityOfPage>
https://openseason.online/2017/12/28/mobile-devices-data-recovery-collection/
schema:mentions <http://schema.org/mentions>
http://data.wordlift.io/wl0293/entity/use_law
schema:mentions <http://schema.org/mentions>
http://data.wordlift.it/wl0353/entity/evidence
schema:mentions <http://schema.org/mentions>
http://data.wordlift.it/wl0353/entity/iphone
schema:mentions <http://schema.org/mentions>
http://data.wordlift.it/wl0353/entity/mobile_app
schema:mentions <http://schema.org/mentions>
http://data.wordlift.it/wl0353/entity/smartphone
schema:publisher <http://schema.org/publisher>
http://data.wordlift.io/wl0293/entity/open_season_online
schema:wordCount <http://schema.org/wordCount> 967(xsd:integer
<http://www.w3.org/2001/XMLSchema#integer>)
https://openseason.online/mobile-devices-data-recovery-collection/

**Comment by ziodave** [comment]
I see the following issue, `mainEntityOfPage` for the `Article` entity points to 

https://openseason.online/2017/12/28/mobile-devices-data-recovery-collection/

instead of 

https://openseason.online/mobile-devices-data-recovery-collection/

Do you see other issues?

The JSON-LD is cached, can you deactivate and reactivate the plugin in order to clear the cache and then we'll check if the URL is updated (*do not uninstall the plugin, this would destroy the vocabulary*).

**Comment by mediaprophet** [comment]
i've re:initiated the plugin.  It's clearly generating JSON-LD FreeBase
links.  I suggest you check that out; i've posted the plugin links here -
https://gitter.im/wordlift/wordlift

**Comment by ziodave** [comment]
Great, the _mainEntityOfPage_ is now correct:

https://openseason.online/mobile-devices-data-recovery-collection/

I am now going to create a couple of new issues:

1. to check that, changing the URL permalink structure in WordPress clears the cache.
2. to track implementation of Wikidata.org URIs in the analysis results.
