### ISSUE TITLE
Import startDate, endDate properties from WL APIs

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#75]

**Comment by ziodave** [comment]
Latitude and Longitude are already provided?

**Comment by pieroit** [comment]
Latitude and longitude are received from RL and we are working on #151 to store them in local DB.
I leave this issue open for the moment we can also include `startDate` and `endDate`

**Comment by cyberandy** [comment]
We should check a set of properties within http://dbpedia.org/datasets/events that restricts the list of events to let's say Sport Events and Institutional Events (we need to reduce the noise / signal ratio as events are numerous and constantly updating).
