### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by Stoyan0v** [insideout10/wordlift-plugin#757]
We have to address all issues/notices that occur when running php7.2.

Currently `count( )` on non array show notice. 

There may have other issues too.

**Comment by ziodave** [comment]
Reopening for 3.20.0

**Comment by ziodave** [comment]
```~/.composer/vendor/bin/php7cc --except=vendor ./wordlift-plugin/src
Checked 260 files in 15.496 seconds```
