### ISSUE TITLE
Add support for offers and performer on entities type Event

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#759]
Please describe the issue here:
I've noticed we couldn't reach the top with our latest event (yet) - and I would like to be able to provide these two pieces of information here. 

![image](https://user-images.githubusercontent.com/837037/35501337-da8d79f6-04d9-11e8-8081-c45bcbde06fa.png)

Please provide additional data about your WordPress install:
[ ] WordPress version: 
[ ] WordLift plugin version:
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
While performer is a reference to an Organization/Person, Offer is a reference to Offer which is a type we don’t actually support and has many properties. Which subset would we like to support?

**Comment by ziodave** [comment]
See https://developers.google.com/search/docs/data-types/product#offer_properties for required/recommended properties.
