### ISSUE TITLE
Add a reference to the articles being annotated with an entity in the rdf graph

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#760]
Please describe the issue here:

In order to keep track of all annotated articles - we can add the following property to entities and this will be the property to be used:  

- http://www.dublincore.org/documents/dcmi-terms/#terms-isReferencedBy

**Comment by ziodave** [comment]
There is a lot of legacy code: we can hook to some actions provided by the `wl_core_*` functions to add/remove the relationships from the linked dataset.

The relationships are created in the `wl_linked_data_save_post_and_related_entities` function (src/includes/class-wordlift-linked-data-service.php): first the relationships are deleted calling the `wl_core_delete_relation_instances` function (src/modules/core/wordlift_core_post_entity_relations.php) and then they're recreated using the `wl_core_add_relation_instance` function (src/modules/core/wordlift_core_post_entity_relations.php).

`wl_core_delete_relation_instances` and `wl_core_add_relation_instance` functions call respectively the following action hooks: `wl_relation_deleted` and `wl_relation_added`.

We can hook to the above to make the calls to the Linked Dataset.
