### ISSUE TITLE
Develop a mechanism to get feedback after deactivation of the plugin 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#767]
Something like the mechanism in the image below can be useful to develop a constructive conversation with WordLift users 

![image 8](https://user-images.githubusercontent.com/26247261/36255315-ccd9a370-124e-11e8-8bd4-41b0315bda5e.png)

**Comment by gcuofano** [comment]
- Ask permission at set up to improve the service (a check-box)
- At the end a questionnaire to understand the reason for deactivation 

To include the following points. If the user selects that, it will trigger a question: 
- it was too complicated and unclear to me
- there aren't enough features
- it costs too much
- I found another tool that I like better
- I'm not using it right now
- Something didn't work right
- Another reason

**Comment by claudiopome** [comment]
@gcuofano 
![modal-form-closed](https://user-images.githubusercontent.com/5725682/37148980-a0610534-22cc-11e8-83b1-ce5425a04dc8.jpg)
![modal-form-open](https://user-images.githubusercontent.com/5725682/37148992-a83750a6-22cc-11e8-8131-b455a853a432.png)
![modal-form](https://user-images.githubusercontent.com/5725682/37148998-ad13d0c2-22cc-11e8-9b51-f03579985d9e.gif)

**Comment by claudiopome** [comment]
As @gcuofano suggested, we could add a different question, changing the text below the text input for every option selected by the user. For example "I found another tool that I like better" -> "What tool you liked better?" or "Something didn't work right" -> "Tell us what went wrong" and so on

**Comment by claudiopome** [comment]
Copy updates

- It was too complicated and unclear to me
- It misses some important feature to me (Tell us what this feature is)
- It costs too much (Ho much would you like to pay)
- I'm not using it right now
- Something didn't work right
- Another reason

**Comment by claudiopome** [comment]
![data-sharing](https://user-images.githubusercontent.com/5725682/37164997-d6bdfb12-22fb-11e8-8d59-c5a429cc59bb.png)

**Comment by claudiopome** [comment]
![data-sharing-2](https://user-images.githubusercontent.com/5725682/37166133-85bc0756-22fe-11e8-98dd-59c06846bb53.jpg)

**Comment by ziodave** [comment]
We need to change the following properties name:
* reason_id to code
* reason_info to details
* wp_version to wordPressVersion
* version to wordLiftVersion
