### ISSUE TITLE
Entity recognition and disambiguation issue on France.com

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#770]
When WordLift analyzes the entity Champs-Élysées (https://www.france.com/entity/champs-elysees/) it suggests to annotate the entity itself. 

See the image below:
![schermata 2018-03-07 alle 10 34 49](https://user-images.githubusercontent.com/24609125/37084812-c5bd7508-21f3-11e8-8e53-79a2587a9949.png)

Notice that the owl:sameAs is filled with the right data:

![schermata 2018-03-07 alle 10 39 57](https://user-images.githubusercontent.com/24609125/37084896-fbd41246-21f3-11e8-8613-cbc12e259e7f.png)

The same issue was also spotted on the entity Sacre-Coeur Basilica.  

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.9.4
[ ] WordLift plugin version: 3.17.2

**Comment by ziodave** [comment]
The dbpedia.org address doesn't look right, it should look like this http://dbpedia.org/resource/Champs-Élysées

I manually added it and now it works correctly:

![image](https://user-images.githubusercontent.com/11438/37085801-44a3f926-21f6-11e8-8e8f-252ceb22ace4.png)

It's a bug in the autocomplete, we'll check, as a workaround manually add the ids.

**Comment by Cupofbrain** [comment]
Thank you, David! 
I will try to solve the issue also on Sacre-Coeur Basilica in the same way. I suppose it may be a matter of accents.
