### ISSUE TITLE
Changes on Author from vocabular not updated in JSON-LD markup of existing posts

### ISSUE THREAD

**Issue by mreichhart** [insideout10/wordlift-plugin#774]
Please describe the issue here:

On changing "Author from the vocabulary" the author-markup of existing posts is not changing

![screencapture-salzburgerland-de-wp-admin-user-edit-php-2018-03-12-11_27_57](https://user-images.githubusercontent.com/22288718/37278886-697f6a90-25e9-11e8-9ccd-7e8659cd5f64.png)

![screenshot markup](https://user-images.githubusercontent.com/22288718/37278927-8adf3dfa-25e9-11e8-9f3d-a900e1919d5a.jpg)

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.9.4
[ ] WordLift plugin version: 3.17.3-rc1
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Change "Author from the vocabulary"
 - Step 2: Have a look at the markup of exisiting posts

**Comment by Stoyan0v** [comment]
This has been merged in 3.18.2
