### ISSUE TITLE
Annotation markup in image description

### ISSUE THREAD

**Issue by mreichhart** [insideout10/wordlift-plugin#781]
Please describe the issue here:
Annotation markup (HTML) shows up in image description, this confused editors.

![image](https://user-images.githubusercontent.com/22288718/37770352-6edadf22-2dd4-11e8-9946-481159e08694.png)

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.9.4
[ ] WordLift plugin version: 3.18
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Open post in backend and edit image
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
I think we should ignore the `[caption ...][/caption]` shortcode in analysis.

**Comment by ziodave** [comment]
Solved server-side.
