### ISSUE TITLE
Nested spans when using shift + return 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#782]
It can be reproduced by using shift + return before a detected entity. See below

![image](https://user-images.githubusercontent.com/837037/37777779-aa071dea-2de8-11e8-892c-af8c0edbd50a.png)

Here is what happens on the code.

![image](https://user-images.githubusercontent.com/837037/37775806-2b570a90-2de4-11e8-8251-9442ea61927c.png)

The issue has been detected on https://www.salzburgerland.com/de/wp-admin/post.php?post=60883&action=edit 

Please provide additional data about your WordPress install:
[ ] WordPress version: 
[ ] WordLift plugin version:
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
The traslator is causing this because it's mapping the text position to the html position after the HTML code (which might be correct for starting positions, but not always for ending positions).
