### ISSUE TITLE
accents not showing up properly on setup wizard

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#784]
Please describe the issue here:

![schermata 2018-03-25 alle 23 58 59](https://user-images.githubusercontent.com/837037/37892370-f1cf9110-30d7-11e8-95a3-79bd407f26a7.png)

Please provide additional data about your WordPress install:
[ ] WordPress version: 
[ ] WordLift plugin version:
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
Which version of WordLift is this?

This is what I see in 3.18:
![image](https://user-images.githubusercontent.com/11438/37900254-f2e9e13e-30ed-11e8-8c56-b1bf741d080f.png)

"Autorevolezza" not "Attendibilità".
