### ISSUE TITLE
Use set user language (user locale) as base for WordLift translations in backend

### ISSUE THREAD

**Issue by mreichhart** [insideout10/wordlift-plugin#802]
Please describe the issue here:
The set user language (user locale) of the language switcher in user profile should be used for all settings and translations of WordLift in backend (if translated, default English?). E.g.: In our Italian instance, all WL settings are now shown in Italian instead of German (which is set in profile settings of user).

![image](https://user-images.githubusercontent.com/22288718/39242034-f4a77da8-4888-11e8-92fc-274b5c0e6953.png)

![image](https://user-images.githubusercontent.com/22288718/39241711-2328856a-4888-11e8-9dc4-301e063f8c97.png)

Please provide additional data about your WordPress install:
[ ] WordPress version: 4.9.5
[ ] WordLift plugin version: 3.18.2
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
That's quite interesting, since we use WordPress own translations functions I would expect WordPress to pick up automatically the correct translation.

**Comment by ziodave** [comment]
The German translation isn't up to date, I'll contact you privately to update it. We could also use https://translate.wordpress.org/projects/wp-plugins/wordlift/stable/de/default in the future.
