### ISSUE TITLE
Revise Recipes Structured Data according to Google's update 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#803]
See details here: https://www.searchenginejournal.com/recipe-structured-data/251365/

**Comment by ziodave** [comment]
> I’ve created a recipe, and it looks like the SDTT is not recognising the featured image - plus, a few alerts. 

![image](https://user-images.githubusercontent.com/11438/40615782-80a1f5ae-6288-11e8-8879-97abf4b664fd.png)

https://search.google.com/structured-data/testing-tool/u/0/?url=https://alpha.wordlift.io/vocabulary/apple-cake/#url=https%3A%2F%2Falpha.wordlift.io%2Fvocabulary%2Fapple-cake%2F

**Comment by cyberandy** [comment]
We have a case where Recipe can play a good role and we are currently missing: 

- aggregateRating (can be added), 
- recipeCategory (can be added),
- nutrition (we have it but it is no longer considered valid by Google - we need to check it),
- video (not sure how this can be added). 

Tests have been done on WordLift 3.19.0 (test.wordlift.io) here is the [link](https://test.wordlift.it/lionfish-fillets-with-mango-salsa-and-watermelon-mash/).

The official documentation from Google is available [here](https://developers.google.com/search/docs/data-types/recipe).

**Comment by ziodave** [comment]
Yes, this will be fixed with #835 and #852.
