### ISSUE TITLE
Strings in the sidebar widget are not translated

### ISSUE THREAD

**Issue by stoyan0v** [insideout10/wordlift-plugin#804]
Please describe the issue here:
The strings in sidebar widget are not being translated.
The [following files](https://github.com/insideout10/wordlift-plugin/tree/develop/src/templates/wordlift-widget-be) needs to be changed to php and all strings should be wrapped in i10n functions.

**Comment by ziodave** [comment]
Duplicate of #504, closing #504 in favor of this one. See also #308.
