### ISSUE TITLE
When changing type from the Edit Entity page labels don't update

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#82]
I've created an Entity from the **Edit Entity page**. I've set the entity type as *LocalBusiness* and saved. 

After that I've changed the type from *LocalBusiness* to *Person* using the available metabox. 

![image](https://cloud.githubusercontent.com/assets/837037/9435770/c768e58c-4a4a-11e5-9f3f-97708b536a30.png)

The label for the **sameAs** attribute kept referring to *Local Biz* even if the entity was now changed to *Person*

![image](https://cloud.githubusercontent.com/assets/837037/9435751/aa939448-4a4a-11e5-9365-81b58e0bf6d0.png)

**Comment by pieroit** [comment]
Is `Test Local Biz` the title/name of the Entity?

**Comment by cyberandy** [comment]
Yes http://test.wordlift.it/wp-admin/post.php?post=2368&action=edit


*Andrea Volpini*
InSideOut10
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>

**Comment by pieroit** [comment]
The label of the metabox uses the title you give to the entity, it is not related to the type.
This does not happen with the Url property because that property is not yet included in the schema <-> WL mapping.

![image](https://cloud.githubusercontent.com/assets/6328377/9435972/7366f148-4a4c-11e5-8af1-5a66fb175c2b.png)
