### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by mediaprophet** [insideout10/wordlift-plugin#826]
Please describe the issue here:

"[Composer\Repository\InvalidRepositoryException]                                                                                            
No valid composer.json was found in any branch or tag of git@github.com:insideout10/wordlift-plugin.git, could not load a package from it."

**Comment by ziodave** [comment]
You need to follow the instructions here:

https://roots.io/bedrock/docs/composer/

> To add a plugin, add it under the require directive or use composer require <namespace>/<packagename> from the command line. If it's from WordPress Packagist then the namespace is always wpackagist-plugin.

As far as I can read you need to do:

‘composer require wpackagist-plugin/wordlift’

**Comment by mediaprophet** [comment]
I'll try that tomorrow
