### ISSUE TITLE
Improve image markup on AMP pages to enhance the appearance in Google Search results.

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#830]
Proper structured data on AMP pages can enhance the appearance of an article in Google Search results. Enhanced features include an entry in a **top stories carousel** and rich result features such as headline text and larger-than-thumbnail images. 

This is an issue related to **AMP pages that have structured data** and that can, therefore, appear in a carousel of stories in search results. 

Without structured data, AMP pages can appear only as standard blue links in Google Search results.

With issue #671 we've done a great job in replacing the existing markup of the AMP plugin by Automattic, Google and XWP with WordLift's markup. Now, with this issue, the goal is to specifically improve the image markup for Article and NewsArticle of AMP pages. 

Here is the list of additional image guidelines to be supported in the markup[1]:

- Images should be at least 1200 pixels wide (and if they are not we can add a warning) 
- Every page must contain at least one image (whether or not you include markup). Google will pick the best image to display in Search results based on the aspect ratio and resolution.
- Images must be in .jpg, .png, or. gif format.
- For best results, **provide multiple high-resolution images** (minimum of **800,000 pixels when multiplying width and height**) with the following aspect ratios: **16x9, 4x3, and 1x1**.

[1] https://developers.google.com/search/docs/data-types/article#amp-sd

**Comment by ziodave** [comment]
Given that we need at least 800,000 pixels 1,200 pixels wide, that means that we need at least the following:

* 16:9 = 1,200 w x 675 h (810,000 pixels)
* 4:3 = 1,200 w x 900 h (1,080,000 pixels)
* 1:1 = 1,200 w x 1,200 h (1,440,000 pixels)
