### ISSUE TITLE
Underscores in URLs raise warning in WooRank reports

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#838]
We might consider replacing wl_entity_type with entity-type because of the following warning, although it can be safely ignored.

Please describe the issue here:

Underline in URLs
Errors

We have detected this URL and / or its internal pages.

https://www.showmetech.com.br/wl_entity_type/article/

We have detected that you underline (these are not doubts) in your URL and / or your in-page URLs. You must replace by these methods to optimize your SEO.

Google and commerce are considered as word separators, but not underlines.

**Comment by cyberandy** [comment]
would be good to get this done on a next update
