### ISSUE TITLE
add a window global object with WLP version

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#843]
Please describe the issue here:

E.g. `window.wordlift.version`.

**Comment by ndemoor** [comment]
@ziodave has this already been pushed out to production sites?

**Comment by ziodave** [comment]
With 3.19.4, available since yesterday on wp.org, take into account though that web sites aren't forced to update.

**Comment by ndemoor** [comment]
ok, I will keep the old one backwards compatible then

**Comment by ziodave** [comment]
makes sense, if you find the wordlift global object though you can query for WLP version.
