### ISSUE TITLE
add the default language to JSON-LD

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#844]
Please describe the issue here:

We should add the default language to the JSON-LD, see https://json-ld.org/spec/FCGS/json-ld/20180607/#string-internationalization

This would allow us also to start supporting different languages in literals in the near future.

However currently SDTT doesn't seem to support this feature yet, this JSON-LD can be used to evaluate support:

```
{
   "@context":{
      "@vocab":"http://schema.org/",
      "@language":"en",
      "givenName_zh":{
         "@id":"givenName",
         "@language":"zh"
      },
      "givenName_i18n":{
         "@id":"givenName",
         "@container":"@language"
      }
   },
   "@type":"Person",
   "givenName":[
      "David",
      {
         "@value":"데이빗",
         "@language":"ko"
      }
   ],
   "givenName_zh":"大卫",
   "givenName_i18n":{
      "ja":"ダビド"
   },
   "familyName":"Riccitelli"
}
```

Also refer to https://github.com/schemaorg/schemaorg/issues/561#issuecomment-107618227 for language related to URLs.

**Comment by kesenwang** [comment]
Also, would desirable to separately enter simplified Chinese as "zh-ch" and traditional Chinese as "zh-tw". I’ve only ever seen zh used in markup.
