### ISSUE TITLE
add the schema.org dataset markup

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#849]
Please describe the issue here:

In order to appear in the [Google Dataset Search](https://toolbox.google.com/datasetsearch) add the [schema.org/Dataset markup](https://developers.google.com/search/docs/data-types/dataset).

See also #105.

**Comment by cyberandy** [comment]
We could add the markup to the homepage of the website using the following properties: 

- name [required by Google] w/ "Knowledge graph for the website [website_name]" as default, 
- license (cc-0, public domain, pddl, cc-by, cdla-permissive-1.0, odc-by, cc-by-sa, cdla-sharing-1.0, odc-odbl, cc by-nc, cc by-nd, cc by-nc-sa, cc by-nc-nd, other, no license) w/ cc-by as predefined value and no license for all the existing clients.
- url 
- identifier
- description [required by Google] w/ "[website_name] dataset <published by [publisher_name] and built with WordLift" as default - we can add here the logo of the publisher (if available) as embedded image. 

These properties can be added to the settings screen under "Dataset configuration", I don't see the need for updating the wizard at this stage. 

More information, such as a page dedicated to the dataset, can be later added based on https://developers.google.com/search/docs/data-types/dataset.
