### ISSUE TITLE
Add structured data in entity pages related to the entity itself

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#85]
On the entity pages right the markup of the properties related to the entity is missing. For example the entity page ``http://test.wordlift.it/entity/mars/``only displays the entity **Solar System** that is related to the entity **Mars** but there are no specification on **Mars** itself.  

![image](https://cloud.githubusercontent.com/assets/837037/9470803/deb752a6-4b4d-11e5-8613-56784e087407.png)

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/9550142/e55f48da-4da9-11e5-8c3a-b1e2a677f8fb.png)

**Comment by mcolacino** [comment]
Fixed in 3.0.12
