### ISSUE TITLE
Possible issue with the [wl_faceted_search] 

### ISSUE THREAD

**Issue by slim16165** [insideout10/wordlift-plugin#856]
Sorry, again for bothering.

In this [page](https://www.nonsolodiete.it/pdw-analisi-del-sangue/) the [wl_faceted_search] shows the following results: Tibia (Anatomia), Osso, Osteoporosi, Protesi

But the article speaks of blood analysis and don't even connect with the entity bone...

Please provide additional data about your WordPress install:
[ ] WordPress version: latest
[ ] WordLift plugin version: latest
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Edit the file single.php in the /wp-content/themes/ThemeName/ folder
 - Step 2: modify the code as follow:

```
<div class="td-pb-span8 td-main-content" role="main">
<div class="td-ss-main-content">
<?php

echo do_shortcode("[wl_chord]");
**echo do_shortcode("[wl_faceted_search]");**

locate_template('loop-single.php', true);
comments_template('', true);
?>
</div>
```

 - Step 3: load the page frontend

I suspect the issue may relate to having the Widget inserted in the main template code of every post.

**Comment by ziodave** [comment]
Hello @slim16165,

> I suspect the issue may relate to having the Widget inserted in the main template code of every post.

I think so, the faceted search requires a current post (`get_post()`). If you do a `var_dump( get_post() );` before the faceted search do you see one?

**Comment by slim16165** [comment]
mmm..

It's populated when I write in the calling function
do_shortcode("[wl_chord]");

But you are probably right.. inside the do_shortcode WP Function maybe that value doesn't arrive.. (it's not global)

Have you got any suggestion? 


object(WP_Post)#7839 (24) {
--
  | ["ID"]=>
  | int(1307)
  | ["post_author"]=>
  | string(1) "5"
  | ["post_date"]=>
  | string(19) "2018-09-27 16:17:39"
  | ["post_date_gmt"]=>
  | string(19) "2018-09-27 14:17:39"
  | ["post_content"]=>
  | string(7701) "Tutti prima o poi nella v

**Comment by ziodave** [comment]
It should get there, we use `get_post` in faceted search, are you sure the results aren't compatible with the page contents: they should be posts related to the current post via entities relations.

**Comment by slim16165** [comment]
Feel free to answer when you have time. 
I tried also with another page. 

![image](https://user-images.githubusercontent.com/4086781/46211419-cb846500-c333-11e8-8f2f-4a3f39dcdc3a.png)
The part which I don't understand well is the section called: "che cosa"

So I've tried to analyze the content of the first page starting from the WordLift markup.
And these are the proposed related articles.
![image](https://user-images.githubusercontent.com/4086781/46209947-92e28c80-c32f-11e8-94cb-beb79b05745e.png)

This are the most related article in my opinion:
https://www.nonsolodiete.it/mpv-alto-basso/ => not shown
https://www.nonsolodiete.it/rdw-basso/

But the biggest "problem" (from my point of view) could relate on how WL choose the entity for the section "che cosa".

The first image shows the amount of time Wordlift finds a key inside [this article](https://www.nonsolodiete.it/pdw-analisi-del-sangue/)
![image](https://user-images.githubusercontent.com/4086781/46209436-29ae4980-c32e-11e8-9ba3-d27c079e5954.png)

As you can see it's pretty clear what's the main topic of the page..
Then I did a similar job with only the words I have annotated
![image](https://user-images.githubusercontent.com/4086781/46209575-801b8800-c32e-11e8-9e8d-a32975b4289c.png)

I would say that using only the entities it requires an harder analysis to realize that the page speaks of "piastrine" and blood (maybe it could be achieved by a complicated algorithm which see piastrina and sangue and emocromo are all connected, but I have no idea..).

Maybe calculating and saving the weight of the most common proposed annotation for every article could help?
