### ISSUE TITLE
Graph navigation optimization

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#86]
Two main courses of improvements:
- use the LIMIT parameter in `wl_core_...` methods, so that in big blogs you don't get tens of posts for each entity
- establish a cache mechanism for the chord ajax call (used also from the blog_map)

**Comment by cyberandy** [comment]
@pieroit on this one it would be good - according to Mausa - to set the limit to maximum 18 connections. It has been highlighted already by Tao Roma so I will increase the priority. Here follows his comment:

- http://taoroma.it/entity/ciclo-di-controllo/  GOOD
- http://taoroma.it/entity/qi-gong/                NOT SO GOOD

**Comment by cyberandy** [comment]
Here is a case where the number of nodes exceeds what is required to properly read all labels. 
Also following the request from CamminandoCon we shall add here the `limit` parameter to let the user choose the maximum number of nodes that shall be displayed.   

![image](https://cloud.githubusercontent.com/assets/837037/14172613/29dd106c-f739-11e5-91a8-50b77e502384.png)
