### ISSUE TITLE
Showing different information in the checkout page info based on products in the cart 

### ISSUE THREAD

**Issue by claudiopome** [insideout10/wordlift-plugin#860]
Based on products that are in the current cart, we need to show different information on the checkout page. In this particular case, we are talking about products that are discounted and have no trial period. A possible solution might be: 

1 - Check the product variation ID 
2 - Display the information accordingly (e.g. "You will not be charged during the trial period and you can cancel any time." becomes "you have 14 days money back guarantee")

**Comment by ziodave** [comment]
This has nothing to do with WordLift Plugin.
