### ISSUE TITLE
Wizard|Vocabulary step: when leaving the input field empty does not progress

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#864]
Please describe the issue here:
![image](https://user-images.githubusercontent.com/837037/47153985-5f1cd600-d2e1-11e8-9221-bed029e44a27.png)

**Comment by ziodave** [comment]
Hello @cyberandy 

Can you please send a screenshot of the Permalink structure for the web site?

**Comment by cyberandy** [comment]
@mreichhart can you pls share the Permalink structure?

**Comment by mreichhart** [comment]
![image](https://user-images.githubusercontent.com/22288718/47164261-0147b880-d2f8-11e8-8021-4515a7a41ea6.png)

**Comment by ziodave** [comment]
That explains it: an empty vocabulary slug is supported only when permalinks are set to `/%postname%/`.
