### ISSUE TITLE
PHP errors: file_put_contents(/tmp and mkdir permission denied

### ISSUE THREAD

**Issue by slim16165** [insideout10/wordlift-plugin#870]
I have 2 strange errors and I don't know if this is the cause of the caching problems I have:

mkdir(): Permission denied
wp_dashboard()
wp-admin/index.php:160
do_meta_boxes()
wp-admin/includes/dashboard.php:230
Wordlift_Dashboard_Latest_News->render()
wp-admin/includes/template.php:1073
Wordlift_Dashboard_Latest_News->get_last_wordlift_articles()
wp-content/plugins/wordlift/admin/partials/wordlift-admin-news-widget.php:1
Wordlift_Dashboard_Latest_News->get_wordlift_articles_data()
wp-content/plugins/wordlift/admin/class-wordlift-admin-dashboard-latest-news.php:58
Wordlift_File_Cache_Service->__construct()
wp-content/plugins/wordlift/admin/class-wordlift-admin-dashboard-latest-news.php:84
mkdir()
wp-content/plugins/wordlift/includes/cache/class-wordlift-file-cache-service.php:81
wp-content/plugins/wordlift/includes/cache/class-wordlift-file-cache-service.php:81

file_put_contents(/tmp/wl_131b71d09c6eea5cbe887e6d1e6887cb/articles/65f4849099e61806b959a239afdc7070/ad5fd701794ca7200cbdb9f01a5bc8cf.wlcache): failed to open stream: No such file or directory

wp_dashboard()
wp-admin/index.php:160
do_meta_boxes()
wp-admin/includes/dashboard.php:230
Wordlift_Dashboard_Latest_News->render()
wp-admin/includes/template.php:1073
Wordlift_Dashboard_Latest_News->get_last_wordlift_articles()
wp-content/plugins/wordlift/admin/partials/wordlift-admin-news-widget.php:1
Wordlift_Dashboard_Latest_News->get_wordlift_articles_data()
wp-content/plugins/wordlift/admin/class-wordlift-admin-dashboard-latest-news.php:58
Wordlift_File_Cache_Service->set_cache()
wp-content/plugins/wordlift/admin/class-wordlift-admin-dashboard-latest-news.php:112
file_put_contents()
wp-content/plugins/wordlift/includes/cache/class-wordlift-file-cache-service.php:146
wp-content/plugins/wordlift/includes/cache/class-wordlift-file-cache-service.php:146

I've reset the permissions but it still doesn't work. Where is it trying to build it's cache? 
Here?
![image](https://user-images.githubusercontent.com/4086781/48770227-e92fd400-ecbd-11e8-85d5-009c61c2e3af.png)

Or inside the wp-content/plugins/wordlift/includes/cache folder?

Please provide additional data about your WordPress install:
[ ] WordPress version: the latest
[ ] WordLift plugin version: the latest
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by slim16165** [comment]
I've also cheked that do exist a tmp folder, maybe it fails to find it?
![image](https://user-images.githubusercontent.com/4086781/48770331-390e9b00-ecbe-11e8-902a-815323badc43.png)

**Comment by slim16165** [comment]
However the issue produce quite a big issue: 
![image](https://user-images.githubusercontent.com/4086781/48775517-8a725680-eccd-11e8-9913-af0cda3f29e0.png)

**Comment by slim16165** [comment]
If you need to access the environment I can give you the credentials by mail

**Comment by ziodave** [comment]
We use WordPress own `get_temp_dir` function to determine the temporary directory. Most probably WordPress has issues as well?

**Comment by slim16165** [comment]
mmm.. if I disable Wordlift the error disappears. Maybe wordpress doesn't
use that folder so often?

The problem arised cloning the whole environment from one server to
another.


ᐧ

Il giorno mar 20 nov 2018 alle ore 16:20 David Riccitelli <
notifications@github.com> ha scritto:

**Comment by ziodave** [comment]
Most probably a permissions issue then. I think WordPress silently ignores the error.

This is the function signature:

```
/**
 * Determine a writable directory for temporary files.
 *
 * Function's preference is the return value of sys_get_temp_dir(),
 * followed by your PHP temporary upload directory, followed by WP_CONTENT_DIR,
 * before finally defaulting to /tmp/
 *
 * In the event that this function does not find a writable location,
 * It may be overridden by the WP_TEMP_DIR constant in your wp-config.php file.
 *
 * @since 2.5.0
 *
 * @staticvar string $temp
 *
 * @return string Writable temporary directory.
 */
function get_temp_dir()
```

**Comment by ziodave** [comment]
Can you actually upload media files?

**Comment by slim16165** [comment]
Yes.. uploading works.
How can I find which is the default temporary directory used by wordpress?
ᐧ

Il giorno mar 20 nov 2018 alle ore 16:36 David Riccitelli <
notifications@github.com> ha scritto:

**Comment by ziodave** [comment]
`echo get_temp_dir();` somewhere in the theme should print it in the web page.

See this SO solution to specify a temporary folder inside WordPress:
https://wordpress.stackexchange.com/a/165195/23194

**Comment by ziodave** [comment]
Find hereby WL 3.19.6-rc1. This version will ignore file system errors, however pls note that this might prevent the linked data cloud for updating correctly (and the analysis to provide the right results):

[wordlift-3.19.6-rc1.zip](https://github.com/insideout10/wordlift-plugin/files/2600465/wordlift-3.19.6-rc1.zip)

So it's better anyway to configure the `WP_TEMP_DIR` as defined in the previous comment.

**Comment by slim16165** [comment]
Thanks, this solve my biggest issue.

However, is it possible that the issue come from how the variable is used?

Have a look, I've created tmp folders almost everywhere..
[image: image.png]


I've seen that the  echo get_temp_dir(); returns: "/tmp/", which it's a
relative path..
But mkdir( "/tmp/"  , 0755, true ); is going to createan absolute path
somewhere.. maybe in the root of the environment? maybe it depends on the
server configuration?

I see the behaviour changes between a server hosted on Digitalocean and one
hosted on Linode. Both servers are configured by Cloudways.
Maybe wordpress, on the upload, use a specific function to understand which
absolute path to use and using mkdir (relative path) has this issue on some
server?



ᐧ

Il giorno mar 20 nov 2018 alle ore 16:47 David Riccitelli <
notifications@github.com> ha scritto:

**Comment by ziodave** [comment]
> "/tmp/", which it's a relative path..

`/tmp/` is not a relative path, since it starts with `/` it is an absolute path.

> Maybe wordpress, on the upload, use a specific function ...

The upload folder is determined as a folder inside of WordPress, it's unrelated to the temporary folder (it was my mistake before to make a parallel with the media library).

We don't use the uploads folder (or similar) because the files we write do not need to be accessible via the web.
