### ISSUE TITLE
Dashboard Overhaul, Phase 1

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#879]
Please describe the issue here:

This is the current state of the dashboard:

![image](https://user-images.githubusercontent.com/11438/49866159-3f98ba00-fe07-11e8-948f-0d210c379f79.png)

We want to evolve it to:

![image](https://user-images.githubusercontent.com/11438/49866229-72db4900-fe07-11e8-8ad2-a9d91f00a6af.png)

Following are the areas explained:

![image](https://user-images.githubusercontent.com/11438/49866255-8ab2cd00-fe07-11e8-947c-facc36ce3f36.png)

== Communication area

Should get the latest tip from wordlift.io web site in a similar way as Latest news does:

![image](https://user-images.githubusercontent.com/11438/49866313-b33ac700-fe07-11e8-99c5-04c75d5e35dc.png)

Tips are posts with the Tips taxonomy term in the Post category taxonomy. WP-JSON can be used to retrieve the tips.

== Backlinks

_Not yet available_

== Keyword rankings

Visible only to editorial and business plans displays the count of the keywords and the average ranking. These data is available from the entity-rank end point (needs to be aggregated).

== Top entities

Data for _Top entities_ is available within WordPress:
* Link with entities is the count of in/outbound relations among entities
* Post with entities is the count of inbound references from posts to entities.

== Major KPIs

Post enriched is the number of posts with references to entities the total number of posts.
Entities created is the total number of entities in the vocabulary.
Average entity ranking is the (contrary to what is depicted in the mockup) the min / avg / max entity rankings from the entity-ranking end-point.

== Graph data

Is the number of triples created and ratio over triples in wikidata same as the existing box:

![image](https://user-images.githubusercontent.com/11438/49866555-5f7cad80-fe08-11e8-8c6f-8dd74d4e2ca3.png)

== Caching

It's important to cache all the data for 24 hours to avoid slowing down the dashboard.

== Development

Development can be done using the React libraries and the new project in src-js/webpack.

**Comment by edrusano** [comment]
Cache configurable: last updated time will be shown below the dashboard.
