### ISSUE TITLE
Support more entity properties and improve metaboxes

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#88]
- Add more properties to the already supported types (e.g. author of a CreativeWork).
- Improve the metabox for properties expecting a specific entity type

**Comment by pieroit** [comment]
Would also be nice to move the `url` as a property of Thing

**Comment by pieroit** [comment]
![image](https://cloud.githubusercontent.com/assets/6328377/9579218/3524a7a4-4ff1-11e5-9bcc-365ee0add897.png)

**Comment by pieroit** [comment]
Working on multiple values per metabox.

**Comment by pieroit** [comment]
Done:
- converting sameAs metabox into a general uri ingestor
- give each metabox a cardinality parameter (accepts 1, 2, ... or n values)
- implement cardinality on general uri ingestor

ToDo:
- implement AJAX completion of entity names in metaboxes
- implement cardinality for the other metaboxes (???)

**Comment by pieroit** [comment]
Done:
- autocomplete for metaboxes expecting an Entity as argument
- support for cardinality on the above metanoxes

To do:
- Improve 'accepted types' system to include descendant types
- extend cardinality to other expected types (string, boolean, etc.)

**Comment by cyberandy** [comment]
@pieroit can you update the status on this one? Thx 💖

**Comment by pieroit** [comment]
Of the things mentioned above, still to do are:
- bring the `url` property with the rest of properties (I managed to incluce the sameAs but the url is more delicate)
- extend cardinality to other low-level expected types like boolean (the metabox system is in place to do it)

This issue should be considered resolved

**Comment by ziodave** [comment]
This issue is marked _resolved_ but there are no commits associated.
