### ISSUE TITLE
Adding https://schema.org/Product 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#91]
Adding the possibility for structuring a pair of shoes; a concert ticket; the rental of a car; a haircut; or an episode of a TV show streamed online (definition from `schema.org`).

Properties recommended by Google in this specific case are: 

_Property   Type_   _Description_
- **name** (required)   _Text_  The name of the product.
- **image** _URL_   The URL of a product photo. Pictures clearly showing the product
- **description**   _Text_  Product description.
- **brand** _Text_  The brand of the product.
- **review**    _Review_    A nested Review of the product.
- **aggregateRating**   _AggregateRating_   A nested aggregateRating of the product.
- **offers**    _Offer_ An offer to sell the product. Includes a nested Offer or AggregateOffer.
- **sku**
- **gtin8**
- **gtin13**
- **gtin14**
- **mpn**   _Text_  Various identification properties; these are described at schema.org/Product. Google recommends including brand and at least one identifier for each product.

**Comment by ziodave** [comment]
This is related to #428 .

**Comment by ziodave** [comment]
In 3.25.5 we added support for the `product` post type (WooCommerce).
