### ISSUE TITLE
Is correct to link a Wikidata page in the SameAs field?

### ISSUE THREAD

**Issue by slim16165** [insideout10/wordlift-plugin#915]
Hi David,
I've published a wordpress [article](https://search.google.com/structured-data/testing-tool/u/0/?hl=ta#url=https%3A%2F%2Fwww.nonsolodiete.it%2Ftransaminasi%2F) in which I've put as SameAs a WikiData page. But when I tried to analize wikidata with the structured data testing tool I realized that the page doesn't use schema markup.. [link](https://search.google.com/structured-data/testing-tool/u/0/?hl=ta#url=%09%20https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FQ424288) wikidata page

So I'm wondering if Google will understand that data anyway. How can I check?

Please provide additional data about your WordPress install:
[5.2] WordPress version: 
[the latest] WordLift plugin version:

**Comment by slim16165** [comment]
Does Wordlift recognize this URL https://www.wikidata.org/wiki/Q190148
Or should I force the link to http://www.wikidata.org/entity/Q190148

**Comment by ziodave** [comment]
Hello @slim16165 

The correct URI is http://www.wikidata.org/entity/Q190148, this is the entity ID in Wikidata, not https://www.wikidata.org/wiki/Q190148 (which is the human URL).

**Comment by slim16165** [comment]
Thanks. Is there a search engine for entity? The research in Wordlift sometimes is not always effective for me (for this reason and for the impossibility to filter the results excluding Articles).
