### ISSUE TITLE
Current entity shows in the sameAs autocomplete

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#917]
Please describe the issue here:

When looking for sameAs using the autocomplete the current entity is also returned.

The current entity shouldn't be returned.

Please provide additional data about your WordPress install:
* [ ] WordPress version: 5.2
* [ ] WordLift plugin version: 3.20

**Comment by akshayraje** [comment]
Cannot reproduce this. It would be great to have a screencast or detailed steps to reproduce.

**Comment by ziodave** [comment]
Closing, feel free to reopen.
