### ISSUE TITLE
Entities are not selectable with Gutenberg Editor

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#919]
1-From the back-end of the website (our VIP client: https://www.icelandtravel.is/wp-admin/post.php?post=1640&action=edit) I find this message when I try to modify the article:

> WordLift content analysis is not compatible with Classic Editor blocks. Switch to Classic Editor, Convert to Gutenberg Blocks.

2-When I choose to edit the article with Gutenberg Blocks I find the entities but they are not selectable. 

WordPress version: **5.2**
WordLift plugin version: **3.20.1**

**Comment by akshayraje** [comment]
This was also a known issue in the 3.20.x versions. Basically, in 3.20.x versions after classic to Gutenberg block conversion, the user has to toggle WordLift Analysis button for it to work as expected. We also show a small notice to this effect which reads: _Toggle between settings and WordLift sidebar to initiate analysis._

<img width="1398" alt="Screen Shot 2019-05-28 at 5 22 42 PM" src="https://user-images.githubusercontent.com/5327602/58476184-acadcb00-816d-11e9-971a-ac10b534f29b.png">

This is enhanced in 3.21.0 and the analysis auto-triggers in the planned plugin release.
