### ISSUE TITLE
Can't place entities in the root folder of the website

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#922]
During the activation of WordLift on the staging site of our new VIP client (https://pagenews.teliaco.gr/) I wasn't able to leave the field empty to place the entities in the root folder of the website. A path must be written in order to go the next step for the activation.

WordPress version: 4.8.6
WordLift plugin version: 3.21.0

<img width="758" alt="Screenshot 2019-06-07 at 10 35 00" src="https://user-images.githubusercontent.com/51078695/59092270-6a288300-8911-11e9-98a1-d39768182b45.png">

**Comment by ziodave** [comment]
That's correct.

**Comment by ziodave** [comment]
Let's remove the check for an empty vocabulary.

**Comment by akshayraje** [comment]
@ziodave in the current code of wordlift-plugin, the one branched from master, it accepts blank string here. Did we make any change recently for this?

<img width="760" alt="Screen Shot 2019-06-22 at 10 36 44 PM" src="https://user-images.githubusercontent.com/5327602/59966751-5d757300-953e-11e9-95fc-85aa2a695379.png">

**Comment by novedavi** [comment]
uhm, not really. We’ll need to recheck with Doreid.

David

**Comment by ziodave** [comment]
@Doreid can you retest? We can’t reproduce the issue.
