### ISSUE TITLE
OneSignal is sending push notifications of entities when an article is published

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#928]
The plugin wordpress.org/plugins/onesignal-free-web-push-notifications
sends out push notifications on the entities annotated on an article that gets published. 

![unnamed](https://user-images.githubusercontent.com/26247261/60161624-39dd5180-97f8-11e9-8185-7b3c0d730e03.jpg)

For instance, once the article below got published OneSignal also sent the notifications related to the tagged entities: 

![unnamed (1)](https://user-images.githubusercontent.com/26247261/60161623-39dd5180-97f8-11e9-82cc-15e97dc2c7ac.jpg)

**Comment by ziodave** [comment]
See https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/39 and https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/123.

In particular the customer may add 
```
add_filter( 'onesignal_exclude_post', 'onesignal_exclude_post_filter', 10, 3 );
function onesignal_exclude_post_filter( $new_status, $old_status, $post ) {
    return ( 'entity' === get_post_type( $post ) );
}
```
