### ISSUE TITLE
Can't select ''Albania" as a country during the plugin setup

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#937]
During the plugin setup, I was able to choose the Albanian language but we don't have the choice to select Albania or Kosova as a country.

<img width="1042" alt="Screenshot 2019-07-09 at 14 52 32" src="https://user-images.githubusercontent.com/51078695/60889464-57c79f00-a259-11e9-99b4-cca6d9b5011f.png">

WordPress version: 5.2.1
WordLift plugin version: wasn't able to verify as we don't have the permissions for the site plugins, probably it's 3.20.0

**Comment by ziodave** [comment]
The above countries aren't supported by Woorank, see https://developers.woorank.com/#operation/DELETE_websites-id-serp-keywords.
