### ISSUE TITLE
Add support for CollectionPage on taxonomy pages, tags and categories 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#938]
We can add for taxonomy pages, tag pages, category pages and date archives pages the markup for `CollectionPage` as WebPage (i.e. `https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fyoast.com%2Ftag%2Fsoftware-yoast-seo-wordpress%2F`).

We shall add also the entity markup in order to help search engines understand - yes this is a collection and yes this is representative of the entity _xyz_.

**Comment by ziodave** [comment]
https://developers.google.com/search/docs/data-types/carousel
https://support.google.com/manufacturers/answer/9389726?hl=en

**Comment by cyberandy** [comment]
The goal here would be to implement:

- the entity markup (if there is an entity associated to the term)
- the summary page + multiple full details pages markup as specified by Google [here](https://developers.google.com/search/docs/data-types/carousel#summary).

Here is a case of a tag page that could benefit from this update:
>  https://windowsreport.com/tag/kiosk-software/
