### ISSUE TITLE
Vocabulary is NOT accessible from the Dashboard if you're NOT Administrator

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#94]
Editors and Authors shall be able to work on the WordLift vocabulary and this means that the Vocabulary button shall be made accessible.

**Comment by ziodave** [comment]
@cyberandy I can't reproduce this one. Editors can see and edit the vocabulary. We can this one together and then eventually close it.

**Comment by ziodave** [comment]
closing since it cannot be reproduced.
