### ISSUE TITLE
Geomap improvements

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#949]
When you click on a map it opens a list of articles which are connected with the place entity you've just selected. Unfortunately, the UX has some glitches and the design of the map itself is quite poor.  

![The Geomap](https://user-images.githubusercontent.com/24609125/64625981-5ba8a680-d3ed-11e9-9378-7bf75d05b1a2.png)

![What happens when you click on a country on this map](https://user-images.githubusercontent.com/24609125/64626053-7bd86580-d3ed-11e9-900f-f945ff2ec2c7.png)

**Comment by cyberandy** [comment]
Here are some interesting visualization ideas based on Open Street Map: 

- https://app.flourish.studio/@flourish/time-map
- https://app.flourish.studio/@flourish/3d-marker-map

@ziodave have a look
