### ISSUE TITLE
WordPress image edit controls disappears after installing WordLift 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#95]
These buttons here to edit an image in the blog post disappear after installing WordLift:

![image](https://cloud.githubusercontent.com/assets/837037/9661101/74d6b51c-5259-11e5-911c-49c7391b9d43.png)

This can be seen on the blog posts published on blog.insideout.io (ie http://blog.insideout.io/2015/09/mico-testing-one-two-three/).

**Comment by mcolacino** [comment]
The bug is related to wordlift callbacks attached to tinymce events. 
More in details when a callback return *false* event propagation is stopped
https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/util/EventDispatcher.js#L114

**Comment by mcolacino** [comment]
Fixed 3.0.14

**Comment by pieroit** [comment]
Verified on the UI.
