### ISSUE TITLE
New Entity Annotation can't be saved

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#952]
After activating the WL support for all entites I wasn't able to change the entity type form Event to FlightReservation. Once I change the entity and click on update it comes back automatically to Event.

WordPress version: 5.2.3
WordLift plugin version: 3.21.4

**Comment by ziodave** [comment]
The custom integration plugin we made for this specific install is handling the entity type and resetting it to Event as per initial requirements.

This is working as expected.
