### ISSUE TITLE
Map fields from ACF to schema.org classes 

### ISSUE THREAD

**Issue by claudiopome** [insideout10/wordlift-plugin#953]
We need to provide a feature that enables to map existing fields (ex: present inside CPTs) to Schema.org classes. The user needs to:

1. Be able to select the CPT that contains the fields that they want to map to Schema.org classes (ex. "Casino", "Jet Destinations")
2. Select the Schema.org type that they want to associate to the previously selected CPT (ex. Place, Local Business)
3. Map an existing value, or, if not present at all, associate a new value to required/recommended Schema.org classes (ex. PriceRange)

An option to accomplish this might be to create a 3-step wizard inside WordLift > Settings called "Map Entity type" or similar. The steps would be as follows:

1. The user can select CTPs using a dropdown select
2. After the user selects the CTP they want to edit a button for "Next step" appears
3. The user can then select the Schema.org type they want to associate to that CPT using an autocomplete input 
4. A list of required/recommended classes relevant for that Schema type is shown to the user where they can associate a new value or map it to a field already present inside the specific CPT using a select dropdown.

See attached storyboard: 

![IMG_0398](https://user-images.githubusercontent.com/5725682/64876404-534fa600-d64f-11e9-994b-3ac20ed95d15.JPG)

**Comment by claudiopome** [comment]
Further requirements: 

1. Differentiate CPTs that have already been mapped from the ones that need to be mapped (different color/styling) 

2. Add a message, with a CTA linking to the wizard page (Settings) in the Edit Post page to let the user know they can map that CPT (something like "Hey, what do you think about mapping these articles with structured data using WordLift?")

**Comment by claudiopome** [comment]
![953-mapping_01](https://user-images.githubusercontent.com/5725682/66141623-44cc2d00-e604-11e9-965f-6e8bf51cad66.JPG)
![953-mapping_02](https://user-images.githubusercontent.com/5725682/66141634-4990e100-e604-11e9-9a58-02148c439b24.JPG)

**Comment by claudiopome** [comment]
@ziodave @cyberandy I re-sketched all the process including the Edit part that was missing. Ideally, this should be done in the same wizard creating two different paths for the user, Instead of creating an additional step/screen. Let me know what you think.

**Comment by claudiopome** [comment]
Edit 

![image1 (2)](https://user-images.githubusercontent.com/5725682/66389557-f71b4000-e9c8-11e9-96b6-81e88489779d.jpeg)

**Comment by claudiopome** [comment]
Map 
![image2](https://user-images.githubusercontent.com/5725682/66389587-0601f280-e9c9-11e9-979d-d2088c0812d0.jpeg)

![image3](https://user-images.githubusercontent.com/5725682/66389627-1b771c80-e9c9-11e9-8817-b05df4ab2516.jpeg)

**Comment by ziodave** [comment]
Rules:
*[ ] Post Type
*[ ] Taxonomy and Terms

e.g. a Post with Category "software" is mapped to a specific set of mappings.

Mappings:
*[ ] 1 or more Entity Types (e.g. maps to Software Application and Product from the Entity Type taxonomy)
*[ ] schema.org properties to WordPress custom fields and/or ACF fields
*[ ] for each mapping I can apply a transform function (like the ones that we will provide) or a custom function (that can be registered with the mappings, or be applied through WP filters).

**Comment by ziodave** [comment]
Review:

- [ ] generally review styles.
- [ ] review texts.
- [ ] remove the ACF options from the Mappings' screen when ACF isn't available.
- [ ] move the HowTo specific functions to a separate plugin. When moving, you can also preconfigure the mapping.
- [ ] hook the mappings to `wl_entity_jsonld` and `wl_post_jsonld`.
