### ISSUE TITLE
Resource Not Found when Viewing the Linked Data

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#954]
This entity page (https://ussportsbonus.com/guide/valley-forge-casino-resort/) doesn't appear in the structured data and can't be annotated on other articles. When I click to View the Linked Data I get the message of `Resource Not Found`. 

I faced the same issue on another page (https://casinotalk.com/guide/resorts-casino-hotel-atlantic-city/) and I noticed that the issue can be reproduced by filling the Web Site(s) field.

When this is done - the resource is not properly created and therefore the entity cannot be found by the NLP.

[ ] WordPress version: 5.2.3
[ ] WordLift plugin version: 3.22.3

**Comment by ziodave** [comment]
Try putting the following at the top of the wp-config.php file:

```
/**
 * Disable asynchronous push of entities.
 */
putenv('WL_DISABLE_SPARQL_UPDATE_QUERIES_BUFFERING=true' );
```
