### ISSUE TITLE
Structured Data doesn't change when changing the Entity Type

### ISSUE THREAD

**Issue by Doreid** [insideout10/wordlift-plugin#955]
After activating WL Full Entity Support I was able to change the entity type from Place to Airport but the change didn't reflect on the structured data (https://www.flyjetoptions.com/van-nuys-airport/).

[ ] WordPress version: 5.2.3
[ ] WordLift plugin version: 3.22.3

**Comment by ziodave** [comment]
It looks fine to me on the JSON-LD end-point:
https://search.google.com/structured-data/testing-tool/u/1/#url=https%3A%2F%2Fwww.flyjetoptions.com%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dwl_jsonld%26id%3D25333

But I don't see the JSON-LD being called from the Web Page. Maybe it has been disabled?

**Comment by ziodave** [comment]
I suggest to embed the JSON-LD in page (see https://stackoverflow.com/questions/53889789/how-do-i-publish-wordlifts-json-ld-in-the-page-head).
