### ISSUE TITLE
Data not in sync between WP and LOD

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#956]
Please describe the issue here:

Data related to this entity here: https://www.medicalrecords.com/wp-admin/post.php?post=80179&action=edit is not aligned with data in LOD http://data.medicalrecords.com/medicalrecords/page/about_medicalrecords-com.html. 

While the JSON-LD is updated the triple in the graph don't get the update. The information of this entity that is configured on the site as the entity representing the publisher is not published correctly on other articles (see here: https://search.google.com/structured-data/testing-tool/u/0/?hl=it#url=https%3A%2F%2Fwww.medicalrecords.com%2Finsurance%2Fhealth-insurance). 

I am not sure if the two issues are related. 

Please provide additional data about your WordPress install:
[ ] WordPress version: 
[ ] WordLift plugin version:
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
For this client an early requirement was to disable entity push, therefore it is working as expected.
