### ISSUE TITLE
Context cards should be linked to the entities

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#959]
The context cards allow users to have a preview of the content of an entity passing the mouse over the link to the entity in any article or page (and the best cases, the context cards give you a definition which is informative enough). 

Anyway, users can move the mouse from the textual link to the cards and then **most users would try to click on the card to learn more** but cards don't have links. To visit the page of the entity, users are forced to go back to the text of the link and click on it. 

**Adding on the cards the link to the entity pages** by default would make the navigation with cards frictionless. 

[ ] WordLift plugin version: 3.22
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Pass the mouse over the link of an entity 
 - Step 2: Most users would try to click on the card to learn more.

**Comment by cyberandy** [comment]
This might be looked at with #951 - it's important that we provide an immediate way of accessing the link.
