### ISSUE TITLE
Garbage response from API

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#96]
I found that in specific installs sometimes the response from the API is decompressed by WordPress (even if it's not compressed at the source), resulting in garbage.

A way I found to solve is to add the `'decompress'  => false` to the HTTP options:

```php
// Define the basic options for HTTP calls to REDLINK.
define( 'WL_REDLINK_API_HTTP_OPTIONS', serialize( array(
	'timeout'     => 10,
	'redirection' => 5,
	'httpversion' => '1.1',
	'blocking'    => true,
	'cookies'     => array(),
	'sslverify'   => ( 'false' === getenv( 'WL_SSL_VERIFY_ENABLED' )) ? false : true,
    'sslcertificates' => dirname(__FILE__) . '/ssl/ca-bundle.crt',
	'decompress'  => false
) ) );
```

Not sure though if this should land in the code.

**Comment by mcolacino** [comment]
Fixed on 3.0.12
