### ISSUE TITLE
Adding utm tags to track clicks on the Navigator

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#962]
Please describe the issue here:

We shall start tracking on GA when a user clicks on a recommended article/entity from the navigator. We can use UTM tags for this purpose and we need to be able to gather the following: 

- total numbers of clicks generated by the navigator:
      - site-wide
      - for a given article (destination)
      - from a given article (source) 

See here for defining the specs: https://support.google.com/analytics/answer/1033863

Please provide additional data about your WordPress install:
[ ] WordPress version: 
[ ] WordLift plugin version:
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1:
 - Step 2:
 - Step 3:

**Comment by ziodave** [comment]
@cyberandy pls provide the UTM tags.
