### ISSUE TITLE
Incorrect value type "@type" reported in Google Search Console 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#964]
Please describe the issue here:

![image](https://user-images.githubusercontent.com/837037/66812315-f4719b00-ef32-11e9-9dcc-e5aa9ca1433d.png)

The error can be seen here - https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.salzburgerland.com%2Fde%2Fmagazin%2Ftobias-moretti-salzburgs-neuer-jedermann%2F and it seems related to an invalid JSON-LD syntax - fron the JSON-LD playground we read the following:
 
> "@type" value must a string, an array of strings, or an empty object.

WP 5.2.4, WL 3.22.5, WL Entity Redirect 1.1.0-rc1, WordLift for SL Magazin 0.3.0

**Comment by ziodave** [comment]
The problem is due to this being output in the JSON-LD:

![image](https://user-images.githubusercontent.com/11438/66920566-d59f0180-f023-11e9-83b7-579357aafe96.png)


i.e. ` "1": "http://schema.org/LocalBusiness" `

**Comment by ziodave** [comment]
The issue was in the custom integration plugin.
