### ISSUE TITLE
The title "Read more about _name of the entity_" in the faceted search is not working as expected

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#970]
The title "Read more about _name of the entity_" in the faceted search is not working as expected.

This shortcode shows the articles related to an entity in the faceted search, but the text of the articles looks broken. See the screenshot below.  

![faceted-title-broken](https://user-images.githubusercontent.com/24609125/68126440-1e0b5a00-ff14-11e9-9370-7682a1080d30.png)

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.2.4
[ ] WordLift plugin version: 3.22
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Add a faceted search using in the shortcode this property: title="Read more about _name of the entity_"

**Comment by cyberandy** [comment]
This one seems to be a theme-specific issue but it also relates to #381

**Comment by ziodave** [comment]
Related to #381 .
