### ISSUE TITLE
Add support for FAQ markup

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#973]
A Frequently Asked Question (FAQ) page contains a list of questions and answers pertaining to a 
particular topic. Properly marked up FAQ pages may be eligible to have a rich result on Search and Markup Action for the Google Assistant, which can help your site reach the right users. 
Here's an example of an FAQ rich result on Google Search:

![image](https://user-images.githubusercontent.com/837037/68595607-16126380-049a-11ea-91be-364145c3b992.png)

Technical reference is available here: https://developers.google.com/search/docs/data-types/faqpage and a code snippet can be found here https://search.google.com/test/rich-results?utm_campaign=devsite&utm_medium=jsonld&utm_source=faq-page and here https://jasonbarnard.com/q-and-a/musical-instruments/

Now taking into account that:
1.  **all FAQ content must be visible to the user on the source page** and that 
2. the **length of the proposed answer should be between 40 to 50 words** (Jason's example has the answer with 44 words)

We expect to: 

1. let the user highlight text from the editor related to the question and to the answer
2. add a new block in the WordLift widget to group all FAQs in the page
3. provide an indication on the lenght of the answer (this is not explicit in G documentation but it is the result of the experience gathered till now)   

We therefore foresee the following UX:

1. the user highlights the question (or clicks on the text of the question and WL highlights the entire question) 
   - WL tells the user Add "Is pag.." as question? 
2. the user clicks on the Add button in the widget
   - WL adds a new FAQ block (similar to Article metadata or Suggested images) that will display all the FAQs created for that page. For each FAQ WL will show the entire question and a "+" icon (or a color - like yellow) to let the user know what questions don't have yet a corresponding answer    
3. the user highlights the answer (or clicks on the text of the answer and WL highlights all the senteces required to fill up 40-50 words) 
    - WL informs the user that the answer is too long by turning the highlighting to red above the 50 words or to blue below the 50 words
    - WL tells the user Add "Pagination..." as answer?
4. the user clicks on the Add button in the widget
    - WL turns the question under the FAQ block to blu (as if it was a selected entity) 
    - WL adds the structured data to the page in the JSON-LD

![Nov-11-2019 17-05-57](https://user-images.githubusercontent.com/837037/68603449-9049e480-04a8-11ea-830b-dc895ced7182.gif)

**Comment by cyberandy** [comment]
[Sidebar.pdf](https://github.com/insideout10/wordlift-plugin/files/4035498/Sidebar.pdf)

**Comment by cyberandy** [comment]
@ziodave on the UX front do we have all we need here?

**Comment by ziodave** [comment]
yes

**Comment by techgarageblog** [comment]
Maybe its better to find a solution with Yoasr SEO which has a great FAQ Block

**Comment by ziodave** [comment]
AFAIK Yoast SEO FAQ is only for Block Editor.

We’re looking to support Classic Editor as well and provide the ability to mark up content which is already in page (no need to rewrite contents using Block Editor and / or custom blocks).

**Comment by techgarageblog** [comment]
Ok thank you for this information @ziodave. I will open in the next days some Issue for the new Gutenberg Editor with Wordlift. There are many problems ;)

**Comment by ziodave** [comment]
Absolutely, feel free to open an issue here on GitHub or sending an email to support@wordlift.io

Cheers

**Comment by ziodave** [comment]
@naveen17797 some feedback from a test I did today:

- [ ] Add Question / Add Answer aren’t enable even when I select some text, it seems to depend on how you select the text
- [ ] When there is more than a question and I add an answer, the dialog box remains visible while the ajax call is done, giving the perception that I can select another question. the dialog must close as soon as I hit apply
- [ ] In the FAQ list, if I delete an answer also the question is delete. only the answer should be deleted
- [ ] when an answer or question is deleted, the highlighting is not removed in tinymce. the highlighting should be removed
- [ ] in block editor I don’t see the buttons
