### ISSUE TITLE
Iceland Country is missing on the WL countries dropdown list

### ISSUE THREAD

**Issue by EdoardoWordLift** [insideout10/wordlift-plugin#974]
Please describe the issue here:
Iceland Country is missing on the WL countries dropdown list.

Please provide additional data about your WordPress install: 
[ ] WordLift plugin version:3.21.3
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: Go to WL settings
 - Step 2: Click on "country" looking for Iceland on the list
 - Step 3: Iceland is missing

**Comment by ziodave** [comment]
This only affects the Search Rankings feature.

I forwarded the issue to Woorank.
