### ISSUE TITLE
WP taxonomy terms cannot have multiple parents

### ISSUE THREAD

**Issue by pieroit** [insideout10/wordlift-plugin#99]
This is problematic because we have entity types that are child of multiple parents (e.g. LocalBusiness is child of both Place and Organization).

Possible solution:
- When the WL <-> schema mapping is compiled, also compile a data structure hosting the type hierarchy and save it as an option.

**Comment by cyberandy** [comment]
Here we could simply remove the hierarchy from the UI (the user in any cases has to choose one option at the time).

**Comment by mcolacino** [comment]
I close this issue. See #305.
