### ISSUE TITLE
Add Synonym button missing from Pages 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#992]
When transforming a page into an entity we should be able to add synonyms as for any other entity but the button is missing:

![image](https://user-images.githubusercontent.com/837037/71509688-7d3e7880-288c-11ea-87ef-0e47234673f5.png)

This is from https://test.wordlift.it/

**Comment by ziodave** [comment]
I changed the entity type from Article to Person or LocalBusiness and the synonyms showed.
